### PR TITLE
RStrBuf: add r_strbuf_vappendf() and r_strbuf_vsetf()

### PR DESCRIPTION
**Pull request by pelijah**
Lets make code from `r_strbuf_setf()` and `r_strbuf_appendf()` reusable to avoid buggy implementations: https://github.com/radare/radare2/blob/master/libr/asm/p/asm_cris_gnu.c#L67

### CODE REVIEW

**Comment by pelijah** [comment]
It is not my code. I think each `vsnprintf()` requires own `va_list`.

**Comment by ret2libc** [comment]
Yeah I see. I wasn't aware of this thing!

**Comment by pelijah** [comment]
It is just my assumption.

**Comment by ret2libc** [comment]
Apparently it is right ;)

**Pull request merged**
