### PR TITLE
Add scr.wideoff to make offsets and reg values depend on asm.bits ##visual

### PR DESCRIPTION
**Pull request by radare**
TODO:

* [x] honor scr.wideoff in hexdump and disasm

### CODE REVIEW

**Comment by mrmacete** [comment]
lgtm 👍, it can't do harm. apart from r2r tests to adjust i mean.

**Comment by radare** [comment]
we should probably apply this change to the prompt, the offset in disasm, the visual title... and it can become a bit cluttered. Comments on this?

**Comment by XVilka** [comment]
@radare sounds reasonable change in prompt, disasm offset, visual title.

**Comment by radare** [comment]
ive done that change. but im not happy to see that depending on asm.bits. so i  would prefer to h ave a separate variable, which probably depends on asm.bits, because there's no sense in showing 64bit address when working on a 16bit bootloader

**Comment by radare** [comment]
also, maybe we want to have  a single place to generate that offset string.

proposals and ideas are welcome

**Comment by wargio** [comment]
Yes and no. If the profile has a reg with nbits > asm.bits then show nbits

**Pull request merged**
