### PR TITLE
GDB debug for lm32 architecture

### PR DESCRIPTION
**Pull request by zamaudio**
Signed-off-by: Damien Zammit <damien@zamaudio.com>

### CODE REVIEW

**Comment by zamaudio** [comment]
Somehow when debugging, the x86 instruction set is used for mapping to registers, but the lm32 instruction set is used for disassembly... very strange.

**Comment by zamaudio** [comment]
Works now as expected, except PC jumps by wrong endianness with "ds", i get to 04000000 instead of 00000004

**Comment by radare** [comment]
Thanks! merging for now. can you provide a test case for it? which lm32 file to download, how to run qemu? ...

**Comment by zamaudio** [comment]
I'm not 100% certain this will work because I made some changes to qemu... but you can try this: 
`qemu-system-lm32 -L . -bios lm32wtf -s -S` with ` r2 -a lm32 -b 32 -D gdb gdb://127.0.0.1:1234`
The lm32 file can be downloaded here: http://www.zamaudio.com/mbox2/lm32wtf

**Comment by XVilka** [comment]
@zamaudio @radare any changes regarding PC endianess?

**Pull request merged**
