### PR TITLE
Fix #4020 - ROP: Find gadgets from all offsets

### LINKED ISSUE #4020: ROP: Find gadgets from all offsets
If this is a duplicate or already exists, please excuse or redirect me.

Currently, the ROP search command doesn't find gadgets that are "hidden at different offsets" - meaning that if you shift one byte or more, you actually can find the correct opcodes for the gadget as seen here:

`ff` from the `__libc_start_main` call together with `f4` from the `hlt` instruction create a `push esp`, which can't be found by the usual `\R` command.

Proof:

PS: The binary I am analyzing is from UIUCTF 2015, challenge "unoriginal", see [here](https://github.com/ctfs/write-ups-2015/tree/master/uiuctf-2015/pwn/unoriginal)

### PR DESCRIPTION
**Pull request by EasyHard**
Hi, @Maijin @abpolym @crowell, this is my approach to fix #4020 . 

Please feel free to comment and let me know if you have any thoughts about this. Thank you very much.

### CODE REVIEW

**Comment by crowell** [comment]
This looks good. Can you add a test for the example listed in the bug report?

**Comment by EasyHard** [comment]
Sure. No problem.

**Comment by radare** [comment]
lgtm

**Comment by EasyHard** [comment]
hmmm...after a shower I kinda feel this may not work in architectures like arm. Because `i` now may not be aligned. Sorry >_<

**Comment by radare** [comment]
Merged!

**Pull request closed without merging**
