### PR TITLE
Fix #9925, x86.nz was assembling some invalid instructions

### LINKED ISSUE #9925: Wrong opcodes in x86 (inc rax)
I think, in rasm2 this opcodes are wrong:

```
$ rasm2 -a x86 -b 64 -s intel 'inc [rcx]'
48ffc0
$ rasm2 -a x86 -b 64 -s intel 'inc rax'
48ffc0
```

r2 from git:
```
$ r2 -v
radare2 2.6.0-git 17964 @ linux-x86-64 git.2.5.0-90-g56681a52
commit: 56681a52f0615c049c2e16a1b0828f39cf75e1c7 build: 2018-04-18__22:48:37
```

### PR DESCRIPTION
**Pull request by PaoloMonti42**
x86.nz was previously accepting and assembling instructions like
* inc [reg]
* dec [reg]
* mov [reg], imm

Without specifying the size of the destination, they are invalid.

"inc/dec size ptr [reg]" are broken too at the moment, but that will require a much deeper fix for correct encoding.

### CODE REVIEW

**Comment by radare** [comment]
Please rebase

**Comment by PaoloMonti42** [comment]
I fixed the test at log line 1045 in [this](https://github.com/radare/radare2-regressions/pull/1297) PR, but have no idea why the rest is red

**Comment by kazarmy** [comment]
> I fixed the test at log line 1045 in this PR ...

shouldn't the x86_32 test be marked as broken as well?

**Comment by PaoloMonti42** [comment]
Yeah, you're absolutely right! thanks a lot

**Pull request merged**
