### PR TITLE
Fix search.in=io.maps with r2 -m

### PR DESCRIPTION
**Pull request by radare**
This PR comes from the dead https://github.com/radare/radare2/pull/7175 which has been cleanedup and has been proved to be wrong. will add more tests in r2r for later review

### CODE REVIEW

**Comment by radare** [comment]
related https://github.com/radare/radare2/issues/3239

**Comment by radare** [comment]
cc @jroimartin

**Comment by XVilka** [comment]
Works on Linux GCC for Travis, fails on Clang for both Linux and OS X. Interesting. There is a crash of radare2 on searching commands in case of clang.

**Comment by radare** [comment]
Any backtrace?

**Comment by XVilka** [comment]
No, just saw it in the Travis log.

**Comment by radare** [comment]
Maybe worth running in local with valgrind to catch that

**Pull request closed without merging**
