### PR TITLE
PPC pseudo bad parse due missing uppercase letters & PPC emu (due mistake)

### PR DESCRIPTION
**Pull request by wargio**
As in the description, it's now fixed.

i've removed the `signed` word since it's implicit.

### CODE REVIEW

**Comment by wargio** [comment]
for some reasons it also added the ppc_emu files.. :|
Support is not finished

**Comment by radare** [comment]
Can you add tests for this?

**Comment by wargio** [comment]
about what? the emu?

**Comment by radare** [comment]
the pseudo

**Pull request merged**
