### PR TITLE
Demangle functions

### PR DESCRIPTION
**Pull request by inisider**
Add parsing of functions and templates.

Now msvc demang looks fully complete.

### CODE REVIEW

**Comment by XVilka** [comment]
:+1:

**Comment by radare** [comment]
That looks awesome! Thanks

**Comment by inisider** [comment]
U are welcome.

Also look please PR with updated testsuites.

2015-02-18 22:53 GMT+02:00 radare <notifications@github.com>:

> That looks awesome! Thanks
>
>
>
> > On 18 Feb 2015, at 18:46, inisider <notifications@github.com> wrote:
> >
> > Add parsing of functions and templates.
> >
> > Now msvc demang looks fully complete.
> >
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/radare/radare2/pull/2109
> >
> > Commit Summary
> >
> > add parsing og operator name codes
> > add stubs for parsing function and function params
> > reeeemoe uunsed code
> > add initial printing of demangled functions
> > fix some issues according to new testsuit
> > add parsing of types abbreviation
> > add support of abbreabiation of names
> > fix some memory leakage
> > small fix for parsing of storage class code for return
> > add #undef for macro GET_VAR...
> > fix some output for operatorXX()
> > add parsing of templates
> > isolate abbr. name list for templates
> > add MSVC mangling to rabin
> > File Changes
> >
> > M binr/rabin2/rabin2.c (2)
> > M libr/bin/demangle.c (27)
> > M libr/bin/mangling/microsoft_demangle.c (796)
> > M libr/include/r_bin.h (2)
> > Patch Links:
> >
> > https://github.com/radare/radare2/pull/2109.patch
> > https://github.com/radare/radare2/pull/2109.diff
>
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/pull/2109#issuecomment-74945549>.
>



-- 
With best regards,
Aleksei

**Comment by radare** [comment]
Added all the commits except the last one because it conflicts with the support for DLANG. Please reclone and adapt the patch:
```
$ git diff
diff --git a/libr/bin/demangle.c b/libr/bin/demangle.c
index 878f2b8..beaf7d9 100644
--- a/libr/bin/demangle.c
+++ b/libr/bin/demangle.c
@@ -274,6 +274,8 @@ R_API int r_bin_demangle_type (const char *str) {
                return R_BIN_NM_CXX;
        if (!strcmp (str, "dlang"))
                return R_BIN_NM_DLANG;
+       if (!strcmp (str, "msvc"))
+               return R_BIN_NM_MSVC;
        return R_BIN_NM_NONE;
 }
 
diff --git a/libr/include/r_bin.h b/libr/include/r_bin.h
index 668a40b..1cf9b0d 100644
--- a/libr/include/r_bin.h
+++ b/libr/include/r_bin.h
@@ -47,6 +47,7 @@ enum {
        R_BIN_NM_OBJC= 3,
        R_BIN_NM_SWIFT = 4,
        R_BIN_NM_DLANG = 5,
+       R_BIN_NM_MSVC = 6,
        R_BIN_NM_ANY = -1,
 };
 ```

Note that rbin identifies the language depending on the sections and symbols, you should do the same for the new MSVC type. otherwise that will need to be specified by hand.

**Comment by inisider** [comment]
Ok. I will do identify of language.

What do U mean with reclone?
As I understand U fix all conflicts and merge, no?

**Comment by radare** [comment]
Make a new fork or branch from latest r2 master, mainly because your
last patch hasnt been merged because it has been in conflict.

**Pull request closed without merging**
