### PR TITLE
asm.strenc (utf32le)

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
what do you think about an eval var to remove all the non-printable escaped sequences from strings . or just replace them by dots like it was before? it will be less noisy and more readable imho.

**Comment by kazarmy** [comment]
> what do you think about an eval var to remove all the non-printable escaped sequences from strings

Have to define carefully what "non-printable" means.

>  or just replace them by dots like it was before?

Just use `asm.strenc=asciidot`.

**Comment by kazarmy** [comment]
I guess having `utf16ledot` and `utf32ledot` which are basically equivalent to `asciidot` except for the wide chars, would make sense. Or having an `asm.asciidot` eval var instead of `asm.strenc=asciidot`.

**Comment by kazarmy** [comment]
Hmm,

 `asm.asciidot`: Enable a char filter that passes through chars in the range 0x20-0x7e and turns the rest into dots (except some control chars).

I should say "code points" but char is close enough.

**Comment by radare** [comment]
ah cool , thanks

**Pull request merged**
