### PR TITLE
Arcompact delay slot handling

### PR DESCRIPTION
**Pull request by hamishcoleman**
I have some regression test updates for this work too, but it depends on b6d8c627 to check the delay slot analysis

### CODE REVIEW

**Comment by radare** [comment]
Please fix those indentation issues and squash the commits for proper review. The overall patch lgtm but didnt tested

**Comment by hamishcoleman** [comment]
Did you want me to squash the commits in this pull request? (since this would rewrite history, I'm not even sure how github would handle it without actually trying it)

**Comment by radare** [comment]
Its priperly handled. Yep

**Comment by radare** [comment]
Can you add some tests for this? thanks!

**Pull request merged**
