### PR TITLE
Build target armel (not armhf), for legacy armv5-like devices (i.e: parrot airdrone)

### PR DESCRIPTION
**Pull request by brainstorm**
Built with https://github.com/thewtex/cross-compilers, this way:

```
docker run thewtex/cross-compiler-linux-armv5 > ~/bin/dockcross && chmod +x ~/bin/dockcross
dockcross --image thewtex/cross-compiler-linux-armv5 ./configure --with-compiler=armel --host=armel
dockcross make
```

Then it compiles ARMv5 binaries in my Macbook Air:

```
mba-3:radare2 romanvg$ uname -a
Darwin mba-3.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
mba-3:radare2 romanvg$ which rabin2
/usr/local/bin/rabin2

mba-3:radare2 romanvg$ rabin2 -I ./binr/rabin2/rabin2
havecode true
pic      true
canary   false
nx       true
crypto   false
va       true
intrp    /lib/ld-linux.so.3
bintype  elf
class    ELF32
lang     c
arch     arm
bits     32
machine  ARM
os       linux
minopsz  1
maxopsz  16
pcalign  0
subsys   linux
endian   little
stripped false
static   false
linenum  true
lsyms    true
relocs   true
rpath    NONE
binsz    96280
```

Thanks for @radare for the guidance on `mk/armel.mk` ;)

### CODE REVIEW

**Comment by radare** [comment]
Maybe we should copypaste this into the radare2book cc @Maijin

**Comment by Maijin** [comment]
Hum for now I would go for doc/

**Comment by radare** [comment]
thats good too. what about doc/crosscompile?

@braincode, mind to write some words on this?

**Comment by brainstorm** [comment]
Sure, would like to write a small blogpost first, can c&p and/or link to that. Will do!

**Comment by Maijin** [comment]
@brainstorm so basically I can run r2 on parrot ?

**Comment by radare** [comment]
Yep

**Comment by Maijin** [comment]
This seems like a nice tweet to do :D

**Comment by brainstorm** [comment]
Hold on guys, TL;DR: in theory is possible but not in (my own) practice.

The libraries and kernel in the Parrot Airdone v1.0 are too old to have radare running there (I tried). Also, for some obscure reason I forgot about, r2 cannot be compiled statically for ARMv5, so out of luck too.

I basically used the trick in this PR to cross-compile AVRdude instead.

**Comment by radare** [comment]
If you ever try again please paste the error

**Comment by brainstorm** [comment]
Sth like this in the drone:

```
# ./radare2
./radare2: error while loading shared libraries: libutil.so.1: cannot open shared object file: No such file or directory
```

And this happened when trying to compile radare in static for ARMv5 to get rid of lib deps:

```
make[2]: Entering directory '/build/shlr/zip/zlib'
/usr/bin/arm-linux-gnueabi-gcc   -static -static   -fPIC -g -Wall -D__UNIX__=1 -static -fPIC -Wall -I../../libr/include -I../include/   -ldl -pthread -lutil -ldl -pthread -lutil -ldl -pthread -lutil -shared -Wl,-soname,libr_z.so -fPIC -o libr_z.so adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/bin/ld: /usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/lib/libc.a(dl-tsd.o)(.text+0x18): R_ARM_TLS_LE32 relocation not permitted in shared object
/usr/lib/gcc-cross/arm-linux-gnueabi/5/../../../../arm-linux-gnueabi/lib/libc.a(dl-tsd.o): In function `_dl_initial_error_catch_tsd':
(.text+0x18): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
Makefile:70: recipe for target 'libr_z.so' failed
```

Then fiddling further with this:

https://keviniwu.blogspot.se/2010/11/rarmtlsle32-relocation-not-permitted-in.html

Then `./r2` failing in the parrot with a "FATAL: Kernel too old", IIRC (c&p'd from chat logs with @radare).

**Comment by ril3y** [comment]
So radare2 cannot be statically compiled to run on armv5 arch?  Sorry for bringing up and old thread but I have a IoT device that I am working on that I would love to use r2 vs GDB on.

**Comment by brainstorm** [comment]
It should be possible, I just was poking at relatively old libs back then, you might have better luck with this ;)

**Comment by ril3y** [comment]
@brainstorm  Looks like building using uclibc toolchains is a no go since it does not come with the backtrace() function inside of execinfo.h.  Rebuilding a toolchain tonight to test musl see how that goes.

**Comment by radare** [comment]
Just add an ifdef for that uclibc or whatever libc without backtrace you are using. And send a pr

**Pull request merged**
