### PR TITLE
libr: split util in r_util and r_print

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by radare** [comment]
why add a new library? i already removed it in the past

**Comment by ret2libc** [comment]
See the other pr. What if you need something in r_print? You can't actually use it because otherwise you would have a circular dependency. This tries to solve this issue

**Comment by ret2libc** [comment]
Another solution may be to put print.c in r_cons instead of a library on its own... The thing is that r_print_* functions don't really fit in r_util... they are not utilities but important parts of r2 and need to interact with other parts. This is why I'm moving print.c ...

**Comment by radare** [comment]
thats why it was a separate lib, but why do you *need* to split it up again?
is there any technical reason to move that out from util?

**Comment by ret2libc** [comment]
To scroll pages instead of blocks, you need to know what is the first address that is not visible on the screen. And I can know that only when I'm printing (that is in r_print_hexdump). But to know that I need to use r_cons_get_size and r_cons_get_cursor. I can't add r_cons as dependency because otherwise you would have a circular dependency and the build fails.

**Comment by ret2libc** [comment]
Thanks for advices. I'm closing this to open a new PR.

**Pull request closed without merging**
