### PR TITLE
Add P- command to delete projects (currently with Pd)

### LINKED ISSUE #7063: Add P- command to delete projects (currently with Pd)
maybe as an alias, or just remove Pd in favor of the more r2-friendly standard P-

### PR DESCRIPTION
**Pull request by davidpolverari**
Fix #7063.

### CODE REVIEW

**Comment by radare** [comment]
Tests plz

**Comment by Maijin** [comment]
Create test here please @davidpolverari  https://github.com/radare/radare2-regressions/blob/master/t/cmd_project

**Comment by davidpolverari** [comment]
Sorry for not doing this before. I am still getting used to the project. I have just added the tests. What am I supposed to do now?

**Comment by davidpolverari** [comment]
btw, when I said that I added the tests, I meant that I sent a PR to radare2-regressions. I'm still waiting them to be accepted.

**Comment by Maijin** [comment]
Next time paste the link here so it's easier :)

**Comment by davidpolverari** [comment]
Sorry... Next time I will do that :)

**Comment by Maijin** [comment]
No problem

**Pull request merged**
