### PR TITLE
Make up lines even more beautiful

### PR DESCRIPTION
**Pull request by jdz**
Use dashed line from the same Unicode block as other line drawing
characters.  This ensures that they all are present in the same font,
are the same width and align perfectly.

### CODE REVIEW

**Comment by jdz** [comment]
Another option is to use `┊` character.

**Comment by ret2libc** [comment]
I like more what you did in the code. It seems more pleasant.

**Comment by ret2libc** [comment]
please fix the tests. See https://github.com/radare/radare2/blob/master/CONTRIBUTING.md#getting-started .

Also, you can run `cd new ; ./bin/r2r.js -i` to help you fix the tests.

**Comment by radare** [comment]
Screenshots please

**Comment by ret2libc** [comment]
dot-lines

**Comment by ret2libc** [comment]
I prefer the one on the right.

**Comment by jdz** [comment]
Here are some more images using different fonts.

dejavu sans mono book
fira mono
freemono regular
ibm plex mono regular
inconsolata
input mono condensed light
input mono regular
liberation mono regular

**Comment by radare** [comment]
i think this was looking awful in some terminals/fonts. need to rechk

**Comment by ret2libc** [comment]
> about broken tests. imho we shouldnt test utf8 lines

I agree in general, but I don't mind a couple of tests just to be sure we won't revolutionize them by mistake in some PRs.

**Comment by radare** [comment]
Can we have the tests updated pls?

**Comment by jdz** [comment]
This is my first time contributing here, and I've made radare/radare2-regressions#1510.  Or is the pull request wrong (there are no comments there)?

**Comment by jdz** [comment]
I see I've violated the GitHub workflow suggested in contribution guidelines. It also appears it is only possible to change the target of the pull request, not the source (even when the commit is the same).

Sholud we (me) close this PR and open a new one, as per the guidelines?

**Comment by jdz** [comment]
Re-opening pull reqest according to guidelines.

**Pull request closed without merging**
