### PR TITLE
Replace radiff2 -s with Eugene W. Myers' O(ND) diff algorithm (inser…

### PR DESCRIPTION
**Pull request by MaskRay**
…tion/deletion cost=1, no substition)

This is much faster than the original algorithm (substitution is allowed).

http://blog.robertelder.org/diff-algorithm

### CODE REVIEW

**Comment by Maijin** [comment]
Why don't you look at the existing issues https://github.com/radare/radare2/issues/6971 ...

**Comment by radare** [comment]
Uhm, the commit msg suggests both algorithms are supported, but reading the diff seems like you are just replacing the implementation completely. am i missing something?

**Comment by Maijin** [comment]
@radare Nop both algo are still there:

image

**Comment by radare** [comment]
+			"  -s         compute Levenshtein distance (substitution is allowed)\n"
 +			"  -ss        compute text distance (no substitution, using Eugene W. Myers' O(ND) diff algorithm)\n"

?

**Comment by Maijin** [comment]
image

**Comment by MaskRay** [comment]
`-s` for old Levenshtein edit distance https://github.com/radare/radare2/pull/8481
`-ss` for Myers' O(ND) algorithm (much faster)

Bikeshedding whether they should be swapped

**Comment by radare** [comment]
again, you are refering to TWO different algorithsm, and replaced the implementation of the levenstein function with the myers one.

```
+// Eugene W. Myers' O(ND) diff algorithm
 +// Returns edit distance with costs: insertion=1, deletion=1, no substitution
 +R_API bool r_diff_buffers_distance_levenstein
```

i dont see how that would make any difference if its replacing an algorithm that already works with something that we didnt tested and its suposed to support two different algorithms in a single function with missleading name.

just put the myers algorithm in a separate function and keep the old code which was already working and was implementing the levenstein algo properly, check git log and github for previous discussion on this file.

In addition, add tests, and please *focus*, we have travis in red for more than a month, creating new issues, reimplementing stuff that was already correct for something that is untested and theorically faster is not a priority, we can't release, and it's hard to review stuff if we never know if its good or bad when there are no tests for it.

**Comment by Maijin** [comment]
Here are the current META issue for diffing --> https://github.com/radare/radare2/issues/6971 If  you want to help you can tackle every single issue of this :P

**Comment by MaskRay** [comment]
> i dont see how that would make any difference if its replacing an algorithm that already works with something that we didnt tested and its suposed to support two different algorithms in a single function with missleading name.

`-ss` is incorrect

Regarding -ss  r_diff_buffers_distance_levenstein

`radiff2 -ss =(echo -n aaba) =(echo -n babca)`
distance: 3

So it can't be Levenshtein edit distance (insertion/deletion/substitution), otherwise the cost should be 2

`radiff2 -ss =(echo -n a) =(echo -n b)`
distance: 1

So it can't be edit distance (insertion/deletion), otherwise the cost should be 2

So it is neither (insertion/deletion) nor (insertion/deletion/substitution). I think there is something wrong but I haven't read the code carefully. It tries to reduce space to 2*N but apparently made mistakes somewhere. 

These lines look very bad, first 2 and 3 are dubious, second it's unnecessary to update two cells in the inner loop.
```c
-                       // populate the next two entries in v1.
-                       // only really required if this is the last loop.
-                       if (j + 2 > bLen + 3) {
-                               break;
-                       }
-                       v1[j + 1] = smallest;
-                       v1[j + 2] = smallest + 1;
```

**Comment by Maijin** [comment]
Test pls https://github.com/radare/radare2-regressions/blob/master/t.tools/radiff2/radiff2

**Comment by radare** [comment]
See 8315feb1d8c65f3e65368404251f1bb1fa5a6ff6 thats what i was trying to explain

**Comment by MaskRay** [comment]
What `r_diff_buffers_distance_levenstein` (`-ss`) tries to solve is (insertion/deletion/substitution) Levenshtein edit distance

```c
			// The main levenshtein comparison:
			cost = (aBufPtr[i] == bBufPtr[j]) ? 0 : 1;
			smallest = R_MIN ((v1[j] + 1), (v0[j + 1] + 1));
			smallest = R_MIN (smallest, (v0[j] + cost));
```

It tries to reduce the inner loop iterations with `start` and `stop` but it makes mistakes somewhere.

**Pull request closed without merging**
