### PR TITLE
Implement ELF IFUNC/IREL relocations

### PR DESCRIPTION
**Pull request by mheistermann**
When you compile binary statically with a recent glibc+toolchain, some functions, such as strcpy and memmove are turned into IFUNC relocations.
This means instead of having a fixed (or no) relocation to the strcpy/... implementation, instead at runtime (from _libc_start_main), a function is called that returns the actual strcpy/... function pointer depending on the machine.

This adds initial support for that to radare.

I also used the opportunity to refactor elf_specs.h, see the commit message for details.

### CODE REVIEW

**Comment by mheistermann** [comment]
Oh, let me see what's going wrong here...will report back.

**Comment by mheistermann** [comment]
Hrm, I'll investigate why CI is failing...

**Comment by mheistermann** [comment]
Found the root cause of the crash in CI, which are relocation sections whose length is not a multiple of the relocation entry length.
I fixed it properly,
Before this, r2 would just silently skip the last few relocations in such a case - not necessarily the ones causing the problems!

**Comment by radare** [comment]
Woah, very nice PR! Despide the comments that are just cosmetic bits, the overall patch looks good. It will be nice to add some more tests for ELF, but i think the current testsuite already checks many ELF files, even corrupted. I didn't saw any vulnerability in this code, so i guess that it's ok to merge before release.

But it will be good to make a call for fuzzing the ELF once again before release with this patch included.

i'll merge after you fix the changes i have commented.

Thanks!

**Comment by mheistermann** [comment]
Oops, I had forgotten to read the styleguide.
I fixed the issues you pointed out and squashed them into the commits for a nice history.

I turned the assert into eprintf+break, so the error is not silently swallowed.

**Comment by radare** [comment]
This has been merged . Thanks!

**Pull request closed without merging**
