### PR TITLE
Add Base Classes Limit to MSVC RTTI

### PR DESCRIPTION
**Pull request by thestr4ng3r**
Prevents long-running loops for invalid data in rtti structs.
#6851

### CODE REVIEW

**Comment by radare** [comment]
i would prefer to find a better solution than having a user-defined option to limit that thing

**Comment by thestr4ng3r** [comment]
Yeah I agree it's not ideal to expose these internal limits to the user. But `num_base_classes` is read directly from the binary and can be any number. One way would be to stop parsing the base class array when exceeding the respective section, but even then it could happen that it reads all the data from the whole section, which you wouldn't want.
So the only option I see is having a certain limit. If it's not defined by the user it would have to be hard-coded.

**Comment by thestr4ng3r** [comment]
Any suggestion for a better solution?

**Comment by radare** [comment]
i would go for restricting the limit to the section size, and impose a hardcoded limit that we can tweak when testing, i dont think many people will be playing with that limit right now. And the few who do rtti can mess with the code for now. we can find a better solution over time

**Comment by thestr4ng3r** [comment]
Ok, done. I added some checks for invalid addresses that should stop the loop and added a fixed limit of 32.

**Pull request merged**
