### PR TITLE
PE: Add support for parsing TLS

### PR DESCRIPTION
**Pull request by lionaneesh**
Also add TLS callbacks to entrypoints.

### CODE REVIEW

**Comment by lionaneesh** [comment]
I'll add a few samples to radare2 regression in a while.

**Comment by lionaneesh** [comment]
Added a few tests https://github.com/radare/radare2-regressions/pull/331

**Comment by lionaneesh** [comment]
@radare PR is now updated!

**Comment by radare** [comment]
Looks good now! I have changed libr/core/bin.c to show that info in r2 and rabin2. Now, a lot of tests will be broken :D

**Comment by radare** [comment]
(i have merged it)

**Pull request closed without merging**
