### PR TITLE
Fix first parameter position for CLZ asm code

### PR DESCRIPTION
**Pull request by mscherer**
Fix error in 4b74942

Sorry, my manual testing was incomplete and I have hit the "Create pull request" a bit too fast.

### CODE REVIEW

**Comment by mscherer** [comment]
Closing for now, I need more test.

**Comment by Maijin** [comment]
Closing or opening ?

**Comment by mscherer** [comment]
I reopened, I verified it wasn't generating invalid code this time. (turn out that I messed also my 2nd test :/ and the code was correct).

I tested by generating the code and decompiling with rasm2 -d and another disassembler.

**Comment by Maijin** [comment]
ok

**Pull request merged**
