### PR TITLE
Exclude end_addr on getting map by address

### PR DESCRIPTION
**Pull request by josediazfer**

### CODE REVIEW

**Comment by radare** [comment]
Well... thats part of the interval api change .. because we opted use closed intervals to represent ranges. I know its hateful, but we should enhance the interval api and use it consistently across all from/to parts in r2land

**Comment by josediazfer** [comment]
I strongly agree with your comment.Usage Rinterval API avoid duplicated code around the modules using memory maps (like both intervaling and overlapping operations). I could begin to refactoring the debugger part

**Comment by XVilka** [comment]
@josediazfer would be highly appreciated. While fixing yesterday bug I found a w32 debugging code a bit dirty.

**Comment by radare** [comment]
We can fix those by adding a comment to have in mind when changing this. So its ok to merge

**Pull request closed without merging**
