### PR TITLE
Removed some of the asserts in jemallocs internals

### PR DESCRIPTION
**Pull request by Debily**
I tagged the unmodified with `TODO`, one can also grep for them with my name

### CODE REVIEW

**Comment by ret2libc** [comment]
Why are you trying to remove `assert`s? Aren't they considered only when `DEBUG` is defined?

**Comment by Debily** [comment]
In radare2/shlr/heap/README.md : "TODO remove all use of assert".

**Comment by Debily** [comment]
https://github.com/radare/radare2/blob/master/shlr/heap/include/r_jemalloc/internal/assert.h is the special assert header for jemalloc, it does not seem to check for `DEBUG` and neither do any of the other headers

**Comment by Debily** [comment]
https://github.com/radare/radare2/blob/master/shlr/heap/include/r_jemalloc/internal/assert.h is the special assert header for jemalloc, it does not seem to check for `DEBUG` and neither do any of the other headers

**Comment by Debily** [comment]
I should also add that this commit does not remove the debug asserts completely, they will just be used whenever `JEMALLOC_DEBUG` is defined. I've found the debug definition in another header file so it seemed like the best indicator for a debug build to use

**Comment by radare** [comment]
I would not be that cautious

All thise includes are full of unnecessary code for us. We should shrink them as much as possible. If we get a crash then we will fix it. But asserts cant be managed by the user

**Comment by radare** [comment]
can you update the pr by just removing the asserts and not ifdefing everything?

**Comment by radare** [comment]
ping

**Comment by Debily** [comment]
Sure, sorry was away for a whilr

**Comment by XVilka** [comment]
Please also remove those comments:
```
/* TODO: Remove the asserts. */
...
```

**Pull request merged**
