### PR TITLE
Wrote new x86 assembler

### PR DESCRIPTION
**Pull request by aaronpuchert**
This is an attempt to improve the standard `x86.nz` assembler, born out of solving #2014. By eliminating redundancies, this assembler should be more easily understandable and extensible. The main part is a long mnemonic table, which is not yet finished: most 2-byte opcodes are missing, also FPU instructions and some others. However, it should be clear how they could be added to the table.

It is not thoroughly tested, but most instructions should work. And we don't always choose the optimal opcode.

I'm not sure if I modified the configuration files the right way. If there is anything wrong, I would gladly correct it.

### CODE REVIEW

**Comment by radare** [comment]
Cool, just let me share some comments:

* i guess it's still very early state, as long as instructions like "mov eax, 0" are wrongly assembled.
* the android-x86 build was failing because REG_xxx names are defined by android .h files (i have pushed the fix)
* the assembler code should be placed in libr/asm/arch/x86/x86new instead of embedded inside the plugin itself (up2u)

I have merged the code for later review. Would you like to continue the asm->dis->reasm testsuite and make it run properly to verify x86.olly x86.nz and x86.new assemblers?

**Comment by radare** [comment]
That pullreq also broke the mingw32 build because TokenType is defined in windows.h. it's fixed now in git

**Comment by aaronpuchert** [comment]
Yes, `mov eax, 0` is encoded as `mov eax, dword ptr [0]`. This is because the opcode `A1` requires an immediate, but it is written as memory location in the assembly. Didn't think that through. There will be a fix soon.
About the tests: we are talking about [libr/asm/t](https://github.com/radare/radare2/tree/master/libr/asm/t)/{test.cmp|test.nz|test.nz2}? I could make a similar test suite for x86.new and add some more tests.

**Comment by radare** [comment]
Yep. those tests shoulkd be moved to radare2-regressions at some point.
but i think they are better for testing if in there.

Those tests are quite long, and a minor change in the output will break
them all, so we have to be careful about this. also it will be good to
have some large asm tests to verify that rasm2 properly resolves the
labels in jumps and so.

If you want to look for a bug related to the assembler see:

t/rasm2/pa.sh

this was working a while ago, i think @jvoisin will bisect it to find
the offending commit, but it

It basically tests that the assembler can honor flags from r2:

f TEST = 33
pa mov eax, TEST

im aware that replacing such things in the assembly can result in wrong
code, because someone could set a flag named 'eax' and fuck up all that
thing. Maybe we should just use flags that contain a dot in its name
like sym.foo

**Comment by aaronpuchert** [comment]
I would like to do something like [libr/asm/t/test.cmp](https://github.com/radare/radare2/tree/master/libr/asm/t/test.cmp), but this ain't exactly helpful:

```
> libr/asm/t/test.cmp
OLD 3b842408000000 cmp eax, [esp+0x8]
NEW 3b442408 cmp eax, dword [esp + 8]
FAIL

OLD 3b9c2408000000 cmp ebx, [esp+0x8]
NEW 3b5c2408 cmp ebx, dword [esp + 8]
FAIL

OLD 3bb808000000 cmp edi, [eax+0x8]
NEW 3b7808 cmp edi, dword [eax + 8]
FAIL

OLD 3bbe08000000 cmp edi, [esi+0x8]
NEW 3b7e08 cmp edi, dword [esi + 8]
FAIL

OLD 3bbd00050000 cmp edi, [ebp+0x500]
NEW 3bbd00050000 cmp edi, dword [ebp + 0x500]
OK
```

Both assemblers produce correct bytecodes, but x86_new produces even shorter ones. In general it seems like a good idea to let x86_new assemble something, then dissamble it and compare. Two problems: even apart from whitespace, there are many different ways to get the same assembly. For example: `0x100` is the same as `0x00000100` or `256` and `[eax+2*ecx]` the same as `[ecx*2+eax]`. Additionally, we won't find out if the assembler produces optimal and not just correct opcodes.

This is why I would like to write tests along the lines of "`cmp ebx, dword [esp + 8]` should assemble to `3B5C2408`". Hence there should be a list of instructions, for which I compare the produced bytecode against something assembled by hand or coming from a trusted source. This might take some time, but would detect regressions of any kind.

**Comment by radare** [comment]
Another wrong assembly is for "ret"

**Comment by aaronpuchert** [comment]
Found the problem and fixed it. There will be a pull request with some other fixes soon.

**Comment by radare** [comment]
Recently i added mul/div/and/or for 32/64 in .nz, would you like to continue enhacing the .new one?

Also, im thinking about renaming those plugins. Neither .nz or .new seems like a good name to me :p but this may confuse some people, and actually you plugin is loaded before the .nz one (alphabetical order rules) and makes the default assembler making some people to report issues because of missing opcodes.

**Comment by aaronpuchert** [comment]
I noticed the new assembler got selected, but didn't know why. We could rename it to `x86_tab` (or `x86_table`), since it looks up mnemonics in a table. That's a bit more descriptive and comes after `nz` in lexical order. I'd like to do 64-bit support next, but I'm still not sure how: as you pointed out, there are [many things](http://wiki.osdev.org/X86-64_Instruction_Encoding) to consider.

**Comment by radare** [comment]
Ok, that renaming looks fine to me. The way asm plugins are selected by default is a bit lazy. But as long as the user can select a different one its ok to me. Alphabetical order is done by configure-plugins, then those static plugins are loaded in order and the assembler will get the first one in the list if there's none previously selected of the same architecture.

Do you want to do that renaming?

**Pull request closed without merging**
