### PR TITLE
Use op->disp instead of op->ptr for disp of x86 CMP (and ACMP)

### PR DESCRIPTION
**Pull request by kazarmy**
Following #14829.

### CODE REVIEW

**Comment by radare** [comment]
still wip?

**Comment by kazarmy** [comment]
yes, patience is needed, commits welcome

**Comment by kazarmy** [comment]
yay it's green *happy dance* ... ok to merge?

**Comment by kazarmy** [comment]
yay it's green \*happy dance\* ... ok to merge?

**Pull request merged**
