### PR TITLE
Fix segfault on OpenBSD at exit

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by radare** [comment]
Kill(0) causes a segfault? I think this function was checking for <1 befoee to avoid killing all users processes when pid -1

But this was covered in a different place.

**Comment by devnexen** [comment]
Yes the segfault comes down to the private internals of the threads...

**Comment by radare** [comment]
oh nvm its r_th_kill not r_sys_kill. lgtm

**Comment by MaskRay** [comment]
Can you elaborate which syscall, and the arguments, make it SIGSEGV on OpenBSD?

**Pull request merged**
