### PR TITLE
Add msp430 disasm test

### PR DESCRIPTION
**Pull request by Tyilo**

### CODE REVIEW

**Comment by Tyilo** [comment]
Btw the last test fails, but this is probably a bug in the msp430 disassembler.

**Comment by XVilka** [comment]
This belongs to https://github.com/radare/radare2-regressions
Please, send your PR in that repository.
Thanks for the contribution!

**Comment by radare** [comment]
the tests are written for libr/asm/t, until we port those tests to r2r
that pr is fine, but will be good to have that specific case in r2r
asap, its a bug in the disassembler, maybe @montekki can have a look at
it, it should be one or two line patch.

**Comment by Tyilo** [comment]
Well here it is: https://github.com/radare/radare2-regressions/pull/141

**Pull request closed without merging**
