### PR TITLE
cmd_open: Make 'on' use r_io_open_at.

### PR DESCRIPTION
**Pull request by vifino**
condret made me fix this, this PR is a fix related to his talk.

### CODE REVIEW

**Comment by ret2libc** [comment]
Please add a test for `on` command in radare2-regressions repository.

**Comment by radare** [comment]
We should kill rcorefile and riosections

**Comment by radare** [comment]
LGTM but didnt tested

**Comment by radare** [comment]
tested

**Comment by condret** [comment]
I can kill those, but i want something else for having a connetion between binsection and iomaps. I'm thinking about RCoreRegion with 2 map-ids, 1 section-id and maybe some metainfo about those. I think it's reasonable to know which maps belong to which section. If maps only live in io and sections only in bin, core should connect them

**Comment by radare** [comment]
I think just holding associated fds on each rbinobject should be fine. We need this to make projects work too. That was the purpose of rcorefile. But there was nothing related to core.

**Comment by condret** [comment]
I don't think that's a good idea, since bin only needs to have 1 fd. Bin is for parsing, core is a bridge between apis. Also, what about forking in esil, in that case we need multiple esil instances, and core should make sure they all get access to their related maps and files.

**Pull request merged**
