### PR TITLE
fix multifiles for projects

### PR DESCRIPTION
**Pull request by condret**
this needs some discussion, don't discuss style, discuss the concept

### CODE REVIEW

**Comment by radare** [comment]
What about uri based files? ihex:// and dbg://

**Comment by radare** [comment]
one of the problems here is that if we use -p and -d or loading uri-based files

**Comment by condret** [comment]
i undestand why -d is a problem. What is the problem with the uris?

**Comment by radare** [comment]
uris can be anything, and by anything i mean ihex://… requires the target file to exist in the correct place, but stuff like malloc:// will loose the contents and changes as well as winedbg:// and such can have the same problem as -d

**Comment by XVilka** [comment]
Agree with @radare - using URIs is very flexible and can be easily extended with more content schemas in the future.

**Comment by radare** [comment]
i think its time to go forward on this

**Pull request merged**
