### PR TITLE
Meson: remove build_always for custom_targets 

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by xarkes** [comment]
Ah okay, but what's the exact reason to restore it actually?
Because in my opinion, libr_shlr is a bad idea.

**Comment by xarkes** [comment]
Ok sorry just saw the comment in the other PR.

**Comment by ret2libc** [comment]
I think to choose whether `libr_shlr.a` should be built or not, we need to know whether it's needed or not.
I think it's not needed and if it is, it shouldn't, because you should depend on the particular library you need, more than on a conglomerate of random stuff that are put together in a ar archive.

**Comment by xarkes** [comment]
@pelijah Well I wanted to make meson work and that's it. Now that it works, my objectives changed, and I believe the initial idea of `libr_shlr` is bad. Next time shout louder so I don't propose shitty solutions :p

**Pull request merged**
