### PR TITLE
fix Z80 djnz jump target miscalculation

### PR DESCRIPTION
**Pull request by sijskes**

### CODE REVIEW

**Comment by radare** [comment]
Can you add tests for this ?

**Comment by sijskes** [comment]
what format? do you want small asm + bin?

**Comment by radare** [comment]
see the radare2-regressions repo. just extend any z80 test with this

**Comment by sijskes** [comment]
rgr. i will look into it.

**Comment by sijskes** [comment]
@radare i found other inconsistencies with PC relative mode. also 'jr flag,rel' seems off, not always. need to verify my data with databook and testfiles.

**Pull request merged**
