### PR TITLE
arm thumb syscalls use aop.val instead of a register

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
Test case is:
```
e asm.arch=arm
e asm.bits=16
e asm.os=s110
wx 50a102a87cdf002803d0
e emu.str=1
pd 8
```

**Comment by radare** [comment]
r2r test in here https://github.com/radare/radare2-regressions/pull/1449

**Comment by jacobrosenthal** [comment]
I realize you're not done, but this is still broken for all r_syscall_get calls with -1, because -1 assumes 0x80 which you removed (and why I never got my version of this code fully implemented). 

Specifically all syscall flagspace stuff in op.type == R_ANAL_OP_TYPE_SWI libr/core/canal.c needs fixing and all of these
```
| as             show current syscall and arguments
| asc[a] 4       dump syscall info in .asm or .h
| asl close      returns the syscall number for close
| asl 4          returns the name of the syscall number 4
```


```
[0x00018dee]> /as @e:search.in=io.maps.x
0x00018dee sd_ble_gap_device_name_set
0x00018fda sd_softdevice_disable
0x00018fec sd_softdevice_vector_table_base_set
0x0001f3d0 sd_ble_gap_device_name_get
0x00020da8 sd_softdevice_enable
0x0003b216 sd_softdevice_vector_table_base_set
0x0003c47a sd_ble_gap_device_name_get
0x0003d970 sd_softdevice_disable
0x0003d9a8 sd_softdevice_vector_table_base_set
0x0003e19e sd_ble_gap_device_name_set
0x0003ebb2 sd_softdevice_enable
[0x00018dee]> as?
|Usage: as[ljk?] syscall name <-> number utility
| as             show current syscall and arguments
| as 4           show syscall 4 based on asm.os and current regs/mem
| asc[a] 4       dump syscall info in .asm or .h
| asf [k[=[v]]]  list/set/unset pf function signatures (see fcnsign)
| asj            list of syscalls in JSON
| asl            list of syscalls by asm.os and asm.arch
| asl close      returns the syscall number for close
| asl 4          returns the name of the syscall number 4
| ask [query]    perform syscall/ queries
[0x00018de0]> as
0 = application_0 ()
[0x00018de0]> as 0x7c
0 = sd_ble_gap_device_name_set (0x20004aa8, 0x00000140, 0x0000000a)
[0x00018dee]> asca 07xc
Unknown syscall number
[0x00018dee]> asl sd_ble_gap_device_name_set
0
[0x00018dee]> asl 0x7c
Unknown syscall number
[0x00018de0]> ask sd_ble_gap_device_name_set
0x7c,0,3,
[0x00018de0]> 
```

**Comment by jacobrosenthal** [comment]
I found a bin I can share
[BLE_Beacon2.NRF51822_OTA.bin.zip](https://github.com/radare/radare2/files/2316829/BLE_Beacon2.NRF51822_OTA.bin.zip)

This needs to be loaded at 0x00016000

**Comment by radare** [comment]
@jacobrosenthal merged

**Comment by jacobrosenthal** [comment]
Sigh.. literally everything above still broken. How many prs do you want to do this in?

**Comment by jacobrosenthal** [comment]
heh. you didnt even finish removing the 0x80 from the sdb.txt..

**Comment by jacobrosenthal** [comment]
And Im almost entirely sure its not even passing your own test https://github.com/radare/radare2-regressions/blob/master/new/db/esil/syscall#L41

**Comment by radare** [comment]
Perl...

**Comment by radare** [comment]
Its green and merged. So yes it passes

**Comment by radare** [comment]
Sigh? This has been only 1 pr. And nothing is broken. At least i did tests and didnt fuckedup all the code if arch specific crap

Now it can be improved and fixed if needed without having crap in code and being sure we dont break anything. If you have any issue please report a test

No need to do any other pr. Sigh

**Comment by jacobrosenthal** [comment]
https://github.com/radare/radare2-regressions/pull/1462

**Comment by radare** [comment]
> On 27 Aug 2018, at 22:24, Jacob Rosenthal <notifications@github.com> wrote:
> 
> I thin you only look at issues in email or something? Beacuse you have no context every reply. As stated above, which you ignored to merge
> 
> You didnt finish converting 0x80 s in s110-arm-16.sdb.txt

i see that after merge, right
> aae/aaaa doesnt properly find syscalls and put them in syscall
no tests demonstrate this, so pls provide tests
> as
> asc
> asc [num]
> asl [num]
i’ve seen your PR in r2r with failing tests for syscall searching. thanks, thats how we should implement things, writing tests and then improving the code.

**Comment by radare** [comment]
can we stop abusing this issue for this? (not even an issue, its a pr)

**Pull request merged**
