### PR TITLE
Support 16-bit immediate operands in SNES

### PR DESCRIPTION
**Pull request by edsrzf**
Size for immediate operands depends on the value of the M flag
(for register A) or the X flag (for registers X and Y). A register is
8-bit when its respective flag is set and 16-bit when clear.

These flags can be set or unset independently, so this still isn't quite right
for when one flag is set and the other isn't, but it's an improvement. It's
possible to force a particular instruction to decode correctly by using the
`afh` command.

### CODE REVIEW

**Comment by radare** [comment]
Thanks!

**Comment by Maijin** [comment]
@edsrzf Hey, what about adding the .smc format or another SNES file format ?

**Comment by edsrzf** [comment]
Sure, I'm going to look into it. I also have some improvements to the anal plugin coming.

**Comment by Maijin** [comment]
@edsrzf awesome, see https://github.com/radare/radare2/wiki/Implementing-a-new-format and already implemented stuff for some model, it's quite easy to add.

**Pull request closed without merging**
