### PR TITLE
Make buf field private in RBuffer

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by radare** [comment]
static RPrelinkRange *get_prelink_info_range(const ut8 *header_bytes, ut64 length) {
                       ^~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/radare/radare2/libr/..//libr/bin/p/../format/pe/pemixed.c: In function 'r_bin_pemixed_init_native':
/home/travis/build/radare/radare2/libr/..//libr/bin/p/../format/pe/pemixed.c:78:58: error: 'RBuffer {aka struct r_buf_t}' has no member named 'buf'
  if (!(sub_bin_native->b = r_buf_new_with_bytes(pe_bin->b->buf, b_size))) {
                                                          ^~
make[3]: *** [/home/travis/build/radare/radare2/libr/..//libr/bin/p/../format/pe/pemixed.o] Error 1
make[2]: *** [bin] Error 2

**Comment by ret2libc** [comment]
I moved it to 3.5.0 given the huge amount of code i touched/changed. I think it would be safer to wait after release. Also, it is not fully reviewed yet (and some tests do not pass)

**Comment by ret2libc** [comment]
@mrmacete please review the dyldcache changed when you can.

**Comment by mrmacete** [comment]
oh, you changed the dyldcache extractor - i don't know that code too much and i'm not sure it worked properly before (i never use that)

**Comment by ret2libc** [comment]
:D good. @radare ? do you usually use it?

**Comment by radare** [comment]
lgtm!

**Pull request merged**
