### PR TITLE
fixed a huge bug where somehow you could not go back from VV to V and added pdc as a starting point

### PR DESCRIPTION
**Pull request by Vane11ope**
reproduce the bug

go to V! then VV then go back from there to V!, it crashes and now it's fixed. 

additionally, i added '*' command to fire up pdc command on the new panel created.

### CODE REVIEW

**Comment by Maijin** [comment]
Can we have a menu for pdc?

**Comment by Vane11ope** [comment]
@Maijin yup of course, i will that on next PR for sure :)

**Comment by Vane11ope** [comment]
in fact i'm already adding the menu in just now, as a trial. still super slow and buggy but i know it and i will be on fixing them after this PR trust me.
pseudomenu

**Comment by Maijin** [comment]
Great !

**Pull request merged**
