### PR TITLE
backtrace improvements

### PR DESCRIPTION
**Pull request by q6r**
backtrace shows function names, frame # 0 for 32/64 bit are included.

### CODE REVIEW

**Comment by radare** [comment]
Im having really wrong results with that "improvement", i have tested it on 64bits, and stepping from anywhere into a CALL, results in no new stackframe listed. not even after the stackframe is allocated, so im not really happy with that change.

**Comment by radare** [comment]
Would be good to have some testscases for this. feel free to write some tests, copy the stack contents into a malloc:// io, put the bytes in there with 'wx' and then run dbt <virtual-addr>, this should be enough to recover a backtrace from memory. Regstate is also important

**Comment by q6r** [comment]
I agree this does not always work the current approach is to iterate rbp. This will not work when -fomit-frame-pointer. To build something that always work we need DWARF unwind information or exception unwind table which sounds like a lot of code to rewrite where libunwind can be used to support this correctly and much more for many formats,..etc :/

**Comment by radare** [comment]
The stack follows a structure that can be analyzed to extract all the frames firectly from there. No need to analyze code to get this. Unless the stack is corrupted. Lets work on better backtrace after release. Next release will focus on debugger

**Comment by radare** [comment]
Frida supports different backtrace implementation I think we can workout this by doing the same in r2. So you can implement your own backtrace implementation without changing the current behaviour, so we can test with different implementations and decide which one works better for the platform/target you are facing.

**Comment by radare** [comment]
Can you redo the patch to implement this in a different function? i'll do the glue code to select more than one backtrace implementation now.

Thanks

**Comment by radare** [comment]
Merged and squashed

**Pull request closed without merging**
