### PR TITLE
Dotted lines for conditional jumps in graph

### LINKED ISSUE #204: Dotted lines for conditional jumps
1. Should help to recognize ifs/switches
2. Should help to differ them from unconditional jumps
3. Different color on debug mode when jump is taken/not taken

### PR DESCRIPTION
**Pull request by cyanpencil**
Closes #204 

Added new config var: `graph.dotted`, default to False. 

Fixed a bunch of bugs utf8 related in canvas too.

2018-07-24-192635_1066x784_scrot

### CODE REVIEW

**Comment by cyanpencil** [comment]
I've set it as [WIP] cause I want to know if the code can be refactored better... especially this: do I absolutely need to add the `dotted` boolean argument to every call of draw_horizontal_line and draw_vertical_line ? Is there a more elegant way of doing this?

**Comment by XVilka** [comment]
So far looks good. Regarding the `dotted?` checks - you might convert those lines in some macro instead.

**Comment by Maijin** [comment]
Why default to false?

**Comment by radare** [comment]
Why use dotted lines in all lines by default? This makes no sense

**Comment by XVilka** [comment]
@radare who said it is used in all lines? It is only used for conditional jumps.

**Comment by Maijin** [comment]
Yeah it's only for conditional jumps not for everything that's why i don't see why it's disabled by default :S

**Comment by cyanpencil** [comment]
I initially set up this feature to default because I was not sure it looked good enough to by default

Now refactored to use macros to make code a bit cleaner, and set up default of `graph.dotted` to true. 
(But you still have to set `scr.utf8` to true). Is it ok for you @radare ?

**Comment by Maijin** [comment]
Can you do a screenshot of the new one maybe?

**Comment by cyanpencil** [comment]
> Can you do a screenshot of the new one maybe?

I didn't change anything about the rendering, I only refactored code, the result is the same ass the screen I posted before.
The main thing is that "dot" effect changes from font to font; e.g. here's a screen in urxvt using font `Dejavu sans mono`:

image

**Comment by radare** [comment]
I dont see the point on having dotted lines on consitional jumps. Its just useless.

Consitional lines are red and gteen. Uncomditional ones are blue.

The only reason to use dotted lines is for lines that go backward or to symbolize loops.

**Comment by XVilka** [comment]
I don't agree. Not everyone can see colors, moreover it will improve our
users' experience who use Braille screens.

**Comment by Maijin** [comment]
Agree with @XVilka this is great addition

**Comment by Maijin** [comment]
As discussed, can you add dotted lines for lines that go backward or to symbolize loops too?

**Comment by Maijin** [comment]
with a different symbol

**Comment by cyanpencil** [comment]
> As discussed, can you add dotted lines for lines that go backward or to symbolize loops too?

Sure, will do :)

**Comment by radare** [comment]
There was t and f hints before to denote this before. In fact it was showing that t and f along the line which is imho way better than dotted lines to understand what it means

**Pull request merged**
