### PR TITLE
WIP support debug in xnu

### PR DESCRIPTION
**Pull request by alvarofe**
A lot of work remain to be done but I prefer to make a little PR instead of huge one. I fixed the build on ios though I've not tested on a device yet.

### CODE REVIEW

**Comment by radare** [comment]
The commit message is not clear. This commit is just cleaning up some syntax / indentation and refactoring a bit, right? there's no change in the logic of the code

**Comment by alvarofe** [comment]
It also include in RDebug a new field threads to hold the threads, to use it when needed but mostly when I'll implement the step logic (xnu_thread_list now uses dbg->threads, and I want to include as well inside xnu_reg_read and xnu_reg_write). I'll address all the issues that you've commented and more refactoring.

**Comment by radare** [comment]
Not green?

**Comment by alvarofe** [comment]
I created other fixing the conflict

**Pull request closed without merging**
