### PR TITLE
Update anal_x86_cs.c

### LINKED ISSUE #5940: Possible UB at anal_x86_cs.c due return NULL when insufficient memory
At https://github.com/radare/radare2/blob/6b56489eafc6782f0f5de34050b240ebd6abe0a7/libr/anal/p/anal_x86_cs.c#L81function getarg() which can return a NULL, the result strdup() call, or the result of calling r_str_newf(). strdup() can return NULL if insufficient memory

If we analyze r_str_newf() function here is also strdup() function, and even malloc () i.e. if we out of memory, it may well return NULL. However, getarg() function "can" return NULL and not because of lack of memory. For example here:

```
    if (!insn->detail) {
        return NULL;
    }
```

and here:

```
    if (n < 0 || n >= INSOPS) {
        return NULL;
    }
```

Returns NULL from getarg function can be either due to lack of memory, and the "usual way". There is clearly something wrong.

For example, here https://github.com/radare/radare2/blob/6b56489eafc6782f0f5de34050b240ebd6abe0a7/libr/anal/p/anal_x86_cs.c#L656-L662

```
        {
            char *src = getarg (&gop, 1, 0, NULL);
            char *dst = getarg (&gop, 0, 1, NULL);
            esilprintf (op, "%s,%s,>>>,%s", src, dst, dst);
            free (src);
            free (dst);
        }
```

esilprintf () is a wrapper around printf-like functions, and inside does not check the arguments passed to it on a NULL, if getarg() returns NULL you got UB: http://stackoverflow.com/a/11589479/6616147:

> First things first: printf is expecting a valid (i.e. non-NULL) pointer for its %s argument so passing it a NULL is officially undefined. It may print "(null)" or it may delete all files on your hard drive--either is correct behavior as far as ANSI is concerned (at least, that's what Harbison and Steele tells me.)

### PR DESCRIPTION
**Pull request by j123123**
fix #5940 by adding NULL checks before return

### CODE REVIEW

**Comment by radare** [comment]
A library should never abort or exit, so we should handle all null ptrs properly in the callers. also every if should use braces, even the ones nesting a single statement

**Comment by j123123** [comment]
what you think about setjmp/longjmp?

**Comment by radare** [comment]
im totally against that too, for the same reason throwing exceptions sucks hard and crashes after longjmp stuff are hard to debug, and its pretty easy to mess everything with those primitives

**Comment by radare** [comment]
uh?

**Comment by j123123** [comment]
I have some other idea how to fix it. Just to get rid of those ``ret strdup`` and ``ret r_str_newf``. To replace ``ret r_str_newf`` I need something like r_str_newf which act like ``vsnprintf`` function (to write printf-ed stuff into buffer). To replace strdup I just use strcpy. Then I change ``getarg`` function signature, to write ESIL string to pointer, like this
````
static char *getarg(struct Getarg* gop, int n, int set, char *setop, char *out)
````
and write ESIL to ``out``

vdprintf is not standartized in C89/C99 but POSIX.1-2008 have it
>The dprintf() and vdprintf() functions were originally GNU extensions that were later standardized in POSIX.1-2008.

Can I use this approach? Do I need to create new prototype for new function in libr/include/r_util/r_str.h or I can just use ``vsnprintf``?

**Comment by radare** [comment]
obviously nope. r2 is portable and should not contain gnuisms either i dont see why you need all this, you can handle this properly with just a macro that wraps this call for example, or just creating a wrapper function that handles errors properly

**Comment by j123123** [comment]
Oh no, I was wrong
>fprintf(),  printf(), sprintf(), vprintf(), vfprintf(), vsprintf(): POSIX.1-2001, POSIX.1-2008, C89, C99.
vsprintf is here. So, can use it&

And quite frankly, I don't like this approach with allocating small stuff on stack. In radare2 source I see a lot of "return strdup()" and "return r_str_newf"
https://github.com/radare/radare2/search?utf8=✓&q="return+r_str_newf"&type=Code 
https://github.com/radare/radare2/search?utf8=%E2%9C%93&q=%22return+strdup%22&type=Code

I think it is much better to pass things through pointers

**Comment by Maijin** [comment]
vsnprintf is used several time already btw.

**Comment by j123123** [comment]
OK, then check #6055

**Comment by Maijin** [comment]
What's the status on this Pull request ?

**Comment by j123123** [comment]
I think I can close it

**Pull request closed without merging**
