### PR TITLE
adding compile time to PE binaries

### PR DESCRIPTION
**Pull request by gssincla**

### CODE REVIEW

**Comment by radare** [comment]
R2 have code to parse dates, shouldnt we store a human readable form here?

**Comment by gssincla** [comment]
by leaving it in the integer format you avoid a few problems for analysts who want to use r2 for automated analysis:
1) you don't have to parse a text representation back to an integer
2) you don't lock the resulting time into a specific time zone (some compilers seem to use UTC while others seem to use the compiler's local time... so an analysis has to make that call as to what the real time is). Using a string date would require the analyst to do additional work to adjust TZ. 

If a string date is desired, i could always go back and add a second entry like TimeStamp_string with the date parsed to a string in the UTC timezone.

**Comment by radare** [comment]
yep. i would prefer to have two entries, one for humans and another for scripting

i think this way it’s better for everyone :)

also r2 timestamping doesnt supports timezones, it’s in the TODO, and i missed that feature a couple of times, but end up doing the time change by hand when i needed it. Would you want to do this too?

The idea would be to add another config var in `e` to define the timezone. and in case the bin file contains timezone information set it from libr/core/bin.c

**Comment by gssincla** [comment]
added the string timestamp. didnt add timezone. doing a new pullreq

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/921

**Comment by radare** [comment]
Cool! squashed and picked!

**Comment by radare** [comment]
Also, time_t != long. it must be casted at least to avoid a warning.

see my last commit

**Pull request closed without merging**
