### PR TITLE
Add CORS support to http server

### PR DESCRIPTION
**Pull request by pwntester**

### CODE REVIEW

**Comment by radare** [comment]
Maybe we want this cors functionality optional via http.cors bool config value. The rest of fixes lgtm

**Comment by pwntester** [comment]
Ok, Which is the best approach?

1- Create a r_socket_http_CORS_response() and use it instead of r_socket_http_response if http.cors is enabled. This will require us to duplicate all the request handling in rtr.c which seems an overkill

2- Change r_socket_http_response to take an extra CORS boolean argument and add the CORS headers if it is true. We only need to change ALL calls to r_socket_http_response

3- Something easier Im missing xD

**Comment by radare** [comment]
I would add another field in the httpserver struct named cors and just make
the header conditional depending on this var.

**Comment by pwntester** [comment]
I have set http.cors to false by default. It can be tested with:

```
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
</head>
<body>
<script>
$.ajax('http://localhost:9090/cmd/iS').done(function() { alert( "success" ); })
</script>
</body>
</html>
```

**Comment by pwntester** [comment]
btw, what happened with http.public?

**Comment by radare** [comment]
Its now living with http.bind=public

**Comment by radare** [comment]
Thanks! merged

**Pull request closed without merging**
