### PR TITLE
Do not show types/vars comments in the hexadecimal mode view

### LINKED ISSUE #11427: Do not show types/vars comments in the hexadecimal mode view
```
r2 /bin/ls
aaa; s main; VpP
```
then press '|' and type `pd` then press enter.

They do not make any sense in the hexdump mode and can clog the output:
image

### PR DESCRIPTION
**Pull request by sivaramaaa**
Fixes #11427 

comment

### CODE REVIEW

**Comment by radare** [comment]
why not use px instead of pxc instead of making pxc not show comments?

**Comment by sivaramaaa** [comment]
> why not use px instead of pxc instead of making pxc not show comments?

no px doesn't show comment at all , but i need to remove only type related command and keep other comments like section flags etc !

**Before**

sss

**Comment by radare** [comment]
The issue was complaining that comments was overlapping the disasm at the right. So this wont solve the problem.

**Comment by radare** [comment]
Lgtm as an improvement to pxc but i dont think this fixes the problem

**Comment by sivaramaaa** [comment]
> The issue was complaining that comments was overlapping the disasm at the right. So this wont solve the problem.

Ahh now i get it , let me see , what can be done to fix the issue !

**Comment by XVilka** [comment]
Seems there is one failing test @sivaramaaa - `[XX] db/esil/apple iphone-arm-esil pdsf  208`

**Comment by sivaramaaa** [comment]
I am closing this PR right now , it think it's related to panels, so @cyanpencil or @Vane11ope could do a better fix or I could get help from them to fix it !

**Pull request closed without merging**
