### PR TITLE
Fix even more warnings

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by radare** [comment]
why are you including string.h in all those files? this include is already available via r_types.h which is the root include of all r2 stuff. Which warnings have you fixed?

**Comment by jvoisin** [comment]
Because my script went nuts on `str(n)casecmp`, which should be defined in `<string.h>` or maybe `<strings.h>`

**Comment by radare** [comment]
strings.h is not posix, and your script should take in care that those files are not compiled standalone, but included from another .c

**Comment by jvoisin** [comment]
Yup, my bad.

But my manpages is unclear about what to include:

>        The  strcasecmp()  and  strncasecmp()  functions first appeared in 4.4BSD, where they were declared in <string.h>.  Thus, for
       reasons of historical compatibility, the glibc <string.h> header file also declares these functions, if  the  _DEFAULT_SOURCE
       (or, in glibc 2.19 and earlier, _BSD_SOURCE) feature test macro is defined.

**Comment by jvoisin** [comment]
Anyway, this is a shitty PR.

**Pull request closed without merging**
