### PR TITLE
Arm thumb/all opcodes

### PR DESCRIPTION
**Pull request by vdf-git**
supersedes #9802

### CODE REVIEW

**Comment by vdf-git** [comment]
hmm. Still red - however, the appveyor errors seem to be somewhere in core(?)
As for the travis errors, they seem odd: Why should we stop users from coding illegal operations at the assembler step?

**Comment by radare** [comment]
close the other pr if its deprecated

**Comment by radare** [comment]
this one i mean https://github.com/radare/radare2/pull/9802

**Comment by vdf-git** [comment]
Oh right - done. But still, I'm not sure I understand why the checks travis chokes on are there?

**Comment by Maijin** [comment]
You can search here for [XX] https://api.travis-ci.org/v3/job/362464039/log.txt and you'll see what are the changes introduced

**Comment by vdf-git** [comment]
maijin, yes, I know. I just don't understand the point of these particular checks...

**Comment by Maijin** [comment]
What do you not understand in checking if the result of !rasm2 -a arm -b 16 "lsr r15, r5, 2" is correct ?

**Comment by Maijin** [comment]
Well I guess those can probably be killed, I don't know what was their purposes

**Comment by Maijin** [comment]
image
Are you sure for the ESIL ?

**Comment by radare** [comment]
ping, what do with this pr?

**Comment by Maijin** [comment]
Check the ESIL if it's correct or not

**Comment by vdf-git** [comment]
superseded by #9932

**Pull request closed without merging**
