### PR TITLE
Add braces to if, else, for, while ...

### PR DESCRIPTION
**Pull request by nsajko**

### CODE REVIEW

**Comment by nsajko** [comment]
This exposes a bug in codecov, it thinks that code coverage changed while it really could not have changed as far as I understand. That is, codecov probably has a very naive way of counting lines of code.

**Comment by radare** [comment]
which tool did you used to do that? or just patience?

**Comment by nsajko** [comment]
>which tool did you used to do that? or just patience?

clang-tidy

**Comment by ret2libc** [comment]
> This exposes a bug in codecov, it thinks that code coverage changed while it really could not have changed as far as I understand. That is, codecov probably has a very naive way of counting lines of code.

I guess the change derives from the fact that you actually added lines of code. For example:
```
if (rlen > len)	return op->size = 0;
```
becomes
```
if (rlen > len) {
    return op->size = 0;
}
```
So you changed both the total lines and, I guess, also the number of lines that were not hit in some cases. Not saying this is perfectly fine, but I think we can live with this.

**Comment by radare** [comment]
merged 🙈

**Pull request merged**
