### PR TITLE
Run aei before aaft in aaa

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
Maybe do this when not in the debugger? why that specific 'ls' triggers this issue?

**Comment by radare** [comment]
related to https://github.com/radare/radare2/issues/13776

**Comment by radare** [comment]
@Maijin pls review this change. debugger doesnt breaks with this change btw

**Comment by sivaramaaa** [comment]
> debugger doesnt breaks with this change btw

afair aaft is not even enabled on debugger 

aei shouldn't be necessary, but let me check this once I reach home ,

**Comment by radare** [comment]
thanks all yours then

**Comment by Maijin** [comment]
I will follow @sivaramaaa recommendation on this :)

**Comment by radare** [comment]
Waiting for your pr

**Pull request closed without merging**
