### PR TITLE
Fix #5570 , Add dword/qword and stop analyzing PE imports

### LINKED ISSUE #5570: BetterAnal: aa not analyzing imports further (JAYRO_02)
- Stops analyzing forwarded APIs as functions (before it was analyzing the forwarder strings put in the place of the functions as code and could analyze for a long time...sometimes analyzing over 10K instructions)
- Stops analyzing imported functions which would lead to the same outcome as forwarded APIs

anal.c - 

``` C
R_API int r_core_anal_all(RCore *core)

    /* Symbols (Imports are already analyzed by rabin2 on init) */
    if ((list = r_bin_get_symbols (core->bin)) != NULL) {
        r_list_foreach (list, iter, symbol) {
            if (core->cons->breaked)
                break;
            if(symbol->forwarder && (strcmp(symbol->forwarder, "NONE"))) {
                continue;
            }
            if (symbol->type && (!strcmp (symbol->type, "FUNC"))) {
                ut64 addr = r_bin_get_vaddr (core->bin, symbol->paddr,
                    symbol->vaddr);
                if(symbol->name && !strncmp (symbol->name, "imp.", 4)) {
                    r_core_anal_fcn (core, addr, -1,
                    R_ANAL_FCN_TYPE_IMP, 0);
                }
                else {
                    r_core_anal_fcn (core, addr, -1,
                    R_ANAL_FCN_TYPE_NULL, 0);
                }
            }
        }
    }

    /* Set fcn type to R_ANAL_FCN_TYPE_SYM for symbols */
    r_list_foreach (core->anal->fcns, iter, fcni) {
        if (core->cons->breaked)
            break;
        fcn_callconv (core, fcni);
        if (fcni->type != R_ANAL_FCN_TYPE_IMP && (!strncmp (fcni->name, "sym.", 4) || !strncmp (fcni->name, "main", 4))) {
            fcni->type = R_ANAL_FCN_TYPE_SYM;
        }
    }

static int core_anal_fcn(RCore *core, ut64 at, ut64 from, int reftype, int depth) {
    int has_next = reftype == R_ANAL_FCN_TYPE_IMP ? false : r_config_get_i (core->config, "anal.hasnext");


    if(reftype == R_ANAL_FCN_TYPE_IMP) {
        fcn->type = R_ANAL_FCN_TYPE_IMP;
        char *cpu_type = core->anal->cpu;
        if(cpu_type) {
            if(!strcmp (cpu_type, "x86")) {
                if(core->anal->bits == 32) {
                    r_anal_fcn_set_size (fcn, 4);
                }
                else if(core->anal->bits == 64) {
                    r_anal_fcn_set_size (fcn, 8);
                }
            }
        }
    }
    else {
        r_anal_fcn_set_size (fcn, 0);
    }

    if(reftype == R_ANAL_FCN_TYPE_IMP) {
        fcnlen = R_ANAL_RET_END;
    }
    else {
        fcnlen = r_anal_fcn (core->anal, fcn, at+delta, buf, buflen, reftype);
    }
```

### PR DESCRIPTION
**Pull request by sivaramaaa**
Fixes issue #5570 and these regression : 

[ radare/radare2-regressions@8ab8a95](https://github.com/radare/radare2-regressions/commit/8ab8a95841713e9646f450cea9fbb272e6874caa)

[radare/radare2-regressions@5e7f739](https://github.com/radare/radare2-regressions/commit/5e7f739a9fb73ac4c3dd98ccab280b8d5fea5ec6)

### CODE REVIEW

**Comment by Maijin** [comment]
no red, interesting, this needs a test for the analysis, will you be able to add one @sivaramaaa ?

**Comment by Maijin** [comment]
Yep tests are fixed, Good job !

**Comment by sivaramaaa** [comment]
Also added a test to verify this PR stop analyzing PE imports !!

**Comment by Maijin** [comment]
Well now you merged the test, you need to merge this one otherwise it will be red :/

**Pull request merged**
