### PR TITLE
Anal patches

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by radare** [comment]
This PR is wrong. cant be merged or cherrypicked. github warns about this. can you redo it after properly rebasing the changes against master?

**Comment by radare** [comment]
The PR should only contain those two commits:
```
@dmtch	Split function if overlaps, do not split inner functions	ef3884b
 @dmtch	Jump tables analysis	 ae918bb
```

The other two are already in master. Please redo the PR with only these two commits (you can push -f in your branch and the PR will be updated).

Please address the comments above.

thanks!

**Comment by dmtch** [comment]
I'll do it tomorrow, thanks.

**Comment by radare** [comment]
also, from what i’ve seen this jmptable analysis is just for 64bit programs.

and i guess that this will be only available for x86.

as long as this is an experimental code i would make it only available after enabling
a config var like `e anal.jmptable` or something like this, and set it to true when we
can confirm it works in all binaries/compilers and architectures.

How do you asume the boundaries and type of those pointer tables? because some of them are relative, others are absolute, some of 16bit , etc..

**Comment by dmtch** [comment]
This approach is suitable for x86 (32/64), msvc in general, as it is needed for my work. Also I'll think about how to do it for gcc (x86/64). Other architectures and compilers are very specific, e.g. arm (in sample that I have in this moment) - there is a separate function that follow branches from parameters. I'll make config variable for my case, ok?

**Comment by radare** [comment]
yes please, and don’t enable it by default, as long as there are many other config vars for the current analysis and we are slowly testing and enabling them to avoid regressions and unexpected issues.

thanks!

**Comment by radare** [comment]
see https://github.com/radare/radare2/issues/3238 <https://github.com/radare/radare2/issues/3238> and https://github.com/radare/radare2/issues/3201 <https://github.com/radare/radare2/issues/3201>

**Comment by radare** [comment]
jmptables aka switch tables was only implemented in java, using the _ex methods that are only used by the java. this stuff is not really tested, and will probably require some more work to get a proper design for this.

My idea was to think in a fully arch/os/compiler-independent analysis for switch tables, using esil emulation to detect the ranges of input values and boundaries of the jmp table to determine all the possible output destinations. But this is far from “simple”, and doing a specific case for each compiler like ida does is tedious, boring and totally uninteresting approach, but useful in short term.

Also, the way we show this jmp tables information in the code analysis graph and such is also important because a tiny issue on this can result in a totally messed up graph, but we are missing many points by identifying each computed jmp destination as a new function instead of a subroutine associated to a switch table.

**Comment by dmtch** [comment]
> My idea was to think in a fully arch/os/compiler-independent analysis for switch tables, using esil emulation to detect the ranges of input values and boundaries of the jmp table to determine all the possible output destinations
Unfortunately, I've not enough time for this interesting research now :(

I inspected several samples of x86/64 executables from different compilers (msvc, gcc, delphi, borland c++, fpc). There are two common cases of jumptables-branching code:
1. direct jump like "jmp [tbl + ind * sz]"
2. indirect jumps:
2.1. absolute addresses: "mov r1, tbl [ind * sz] ; jmp r1"
2.2. relative addresses: "lea r1, tbl ; *** ; mov r2, [r1 + ind * sz] ; add r2, r1 ; jmp r2"
I need this to work... May be you know more cases related to this architectures?
Thank you for help!

**Comment by dmtch** [comment]
> 2.1. absolute addresses: "mov r1, tbl [ind * sz] ; jmp r1"
Also there is one thing like this:
mov r1, some_func
...
call r1
Does radare recognise this call?

**Comment by radare** [comment]
R2 recognizes this call if you set asm.emu

**Comment by radare** [comment]
dont worry, just send a pr with that option diasbled by default, so nothing will break and you can use it and we have time after release to do proper research for all platforms

**Comment by radare** [comment]
Cant merge those commits, please rebase and adapt them for master

**Comment by radare** [comment]
also, ihave fixed all tests, so the testsuite is now green again.

**Comment by dmtch** [comment]
Thank you!

**Comment by dmtch** [comment]
What is wrong with tests?

**Comment by Maijin** [comment]
@dmtch not related to your PR

**Comment by radare** [comment]
yeah im aware of my java regression gotta fix and review this now :) thx

**Comment by Maijin** [comment]
See also https://github.com/radare/radare2/issues/3234 ; related

**Comment by radare** [comment]
Merged! thanks!

**Pull request closed without merging**
