### PR TITLE
moved yxml.c

### PR DESCRIPTION
**Pull request by ninostephen**
Moved yxml.c from /libr/bin/format/xnu/ to /shlr/yxml/
also copied /libr/bin/fomat/xnu/yxml.h to /shlr/yxml/

### CODE REVIEW

**Comment by Maijin** [comment]
Why do rename the file .com ? That's a C file, did you verify that the files that are using this library still build? It seems not: https://travis-ci.org/radare/radare2/jobs/504308089#L591

**Comment by ninostephen** [comment]
i just noticed that i screwed up the path. instead of /yxml/yxml.h I accidentally name it as /yxml/yxml/yxml.h

And the .com extension... i didn't see any any .com files. I just checked it. It's .c

**Comment by radare** [comment]
wtf

**Comment by Maijin** [comment]
Yeah wtf. Closing

**Pull request closed without merging**
