### PR TITLE
more work in PE loader

### PR DESCRIPTION
**Pull request by alvarofe**

### CODE REVIEW

**Comment by alvarofe** [comment]
@radare to speed up loading a file with a huge number of section i've added a check to ensure that sz != 0 since r_io_section_add ignores those section latter on but `rabin2 -PS` take those into account doing some test to fail should i revert that?

**Comment by radare** [comment]
if sz == 0 and vsz == 0, it shoudlnt be loaded, but if vsz > 0 then this must be simulatd with virtual mallocs or so

**Comment by alvarofe** [comment]
Doing the check for sz=0 and vsz=0 doesn't improve the load time for 65535 section since all sections has a valid vsz size, so should i add the hack back to not waste time when testing?

**Comment by Maijin** [comment]
As you can notice in the tests, looks like the slowness has disappear anyway.

**Pull request closed without merging**
