### PR TITLE
Vane11ope/panels

### PR DESCRIPTION
**Pull request by Vane11ope**
just a starting point of calling graph as one of panels. 

now is super rough yet, it's like "just calling".

therefore lots and lots more improvements coming including the better algorithm for drawing things and making all the modes function beautifully.

### CODE REVIEW

**Comment by radare** [comment]
not sure if your PR is breaking or not. please can you squash all your commits and rebase that on top of master?

im also wondering if your changes conflict with @cyanpencil ones

**Comment by radare** [comment]
(doesnt seems to conflict)

**Comment by Vane11ope** [comment]
i merged master into this before sending PR. also i checked cyanpencil's PR too beforehand so guess not breaking any but let me double check

**Comment by radare** [comment]
merge != squash != rebase :P

**Pull request closed without merging**
