### PR TITLE
Handle bad sections in PE - #4945

### PR DESCRIPTION
**Pull request by alvarofe**
There is still room for improvements or more trick to take into account but is the first attempt. #2471 #4945 #2885

### CODE REVIEW

**Comment by oddcoder** [comment]
cool

**Comment by Maijin** [comment]
those are failing https://github.com/dmtch/radare2-regressions/blob/master/t.anal/x86/fcnbbs

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
please rebase to make travis happy

**Pull request closed without merging**
