### PR TITLE
Fix address range bug of memory snapshot

### PR DESCRIPTION
**Pull request by RKX1209**
addr should be in [snap->addr, snap->addr_end) ?

### CODE REVIEW

**Comment by radare** [comment]
Better use the BETWEEN macro

**Comment by RKX1209** [comment]
OK. I'll send patch v2

**Comment by Maijin** [comment]
Why do you close the PR? Just update it :P

**Comment by RKX1209** [comment]
Oops, sorry. I didn't know updating function of PR.
But I've sent new PR #7029 
Please see this new one.

**Comment by Maijin** [comment]
Next time please update it.

**Comment by RKX1209** [comment]
Sure!

**Comment by alvarofe** [comment]
for update a PR just git push to your branch. If you did squash just push -f

**Pull request closed without merging**
