### PR TITLE
added free (a2) in case X86_INS_IMUL

### PR DESCRIPTION
**Pull request by j123123**

### CODE REVIEW

**Comment by j123123** [comment]
And maybe it's better to use some stack-allocation stuff (like alloca() or variable-length arrays) ?

**Comment by radare** [comment]
alloca is bad idea because it doesnt controls the left stack size and can crash without being able to control that. bad practices

**Comment by j123123** [comment]
looks like my fix is wrong, you have
```
  			if (a2) {
 				// TODO update flags & handle signedness
 				esilprintf (op, "%s,%s,*,%s,=", a2, a1, a0);
 				free (a2);
  			} else {
```
here.

**Comment by j123123** [comment]
@radare 
>alloca is bad idea because it doesnt controls the left stack size

but in function  getarg at https://github.com/radare/radare2/blob/6b56489eafc6782f0f5de34050b240ebd6abe0a7/libr/anal/p/anal_x86_cs.c#L103 you using ``strdup()`` which theoretically can return ``NULL``
so if ``char *a0 = getarg (&gop, 0, 0, NULL);`` return NULL because lack of memory, then ``free(NULL)`` happens

**Comment by jjdredd** [comment]
what's wrong with free(NULL)?

**Comment by radare** [comment]
nothing

**Comment by j123123** [comment]
wrong not free(NULL) itself. Wrong that it doesn't check if memory allocation failed because lack of memory and NULL appears
assume we have NULL at a0 because lack of memory. Then this happens;
```
 				} else {
 					esilprintf (op, "%s,%s,*=", a0, "rax");
 				}
```
and it crashes

**Pull request closed without merging**
