### PR TITLE
Rowrite

### PR DESCRIPTION
**Pull request by qsantos**

### CODE REVIEW

**Comment by condret** [comment]
can't u use a makro for r_core_file_readonly ?

**Comment by qsantos** [comment]
Yes, but would not it be cleaner to use a proper function?

**Comment by qsantos** [comment]
Apparently, the bit R_IO_WRITE_ of desc->flags is not automatically set for "malloc://%d". The solution is either to let `__open()` from `io/p/io_malloc.c` set this bit automatically (it can makes sense since this is just a region of memory), or add the "-w" flags to commands (if we still want to allow read-only in these situations).

**Comment by radare** [comment]
cc @condret

**Comment by radare** [comment]
Can you cleanup and close this issue and the other with the same name? otherwise its hard to review

**Comment by radare** [comment]
When you can't write in a specific offset it means that:

* the section doesnt allows to write
* the backend file was opened as readonly
* there's no iocache layer on top
* there are no overlapped sections with write perms in there
* etc

The thing is that you can't check if you can write on a specific address by just checking if the file was opened as readwrite or not

**Pull request closed without merging**
