### PR TITLE
get [1][2] jumps for panels and fixed some unstable behaviors

### PR DESCRIPTION
**Pull request by Vane11ope**

### CODE REVIEW

**Comment by Vane11ope** [comment]
@Maijin done

**Comment by Vane11ope** [comment]
@maijin also, heard radare2book will be printed out next week so can i update radare2book with the help message like this PR one goes already?

**Comment by Maijin** [comment]
@XVilka can probably give a better opinion on this

**Comment by XVilka** [comment]
@Vane11ope of course.

**Pull request merged**
