### PR TITLE
Add a way to compare claimed CRC (in header) of PE files with the actual CRC (computed)

### PR DESCRIPTION
**Pull request by lionaneesh**
Ref: #921. I tested a few PEs, it works fine. Checked against the ground truth from pefile (https://github.com/erocarrera/pefile).

### CODE REVIEW

**Comment by radare** [comment]
Update the manpage too.

**Comment by radare** [comment]
this info is also available for signed mach0 binaries and DEX files. which is currently stored in SDB, not exposed to the bininfo thing

**Comment by lionaneesh** [comment]
Tests are added here: https://github.com/radare/radare2-regressions/pull/330. Consistent with pefile's results.

**Comment by lionaneesh** [comment]
@radare Manpage of radare2? Its just an info command right now.

**Comment by lionaneesh** [comment]
I suppose we need to add this to rabin2. Which flag should I set? -C and -c are used.

**Comment by radare** [comment]
The manpage is in `man/rabin.1`. But yeah, -c and -C are taken already, so the `iC` command is not the way to go. What do you think about just putting this info inside the `RBinInfo`?

**Comment by radare** [comment]
Modify libr/core/bin.c to display this info

**Comment by radare** [comment]
maybe we can add another field specifying which algorithm is used to compute the hash.. or which command must be run to recalculate it

**Comment by radare** [comment]
This `fix-checksum` operation should be usable from `rabin2 -O`. i'll fill a separate issue for that

**Comment by radare** [comment]
https://github.com/radare/radare2/issues/4298

**Comment by lionaneesh** [comment]
@radare  updated!

**Comment by radare** [comment]
Merged! I have pushed a change to break more tests with the info displayed, we need to find better names for those fields.

Thanks!

**Pull request closed without merging**
