### PR TITLE
Adding afAj for json format

### PR DESCRIPTION
**Pull request by oddcoder**
and fixing typo in the afA output

### CODE REVIEW

**Comment by oddcoder** [comment]
https://github.com/radare/radare2-regressions/pull/368
tests are here

**Comment by radare** [comment]
missing spaces around parenthesis

**Comment by radare** [comment]
two unnecessary newlines

**Comment by radare** [comment]
fixed, squashed and merged. also, use oneliner commits, or the git log review is more tedious

**Comment by oddcoder** [comment]
@radare you are telling me you did't use the online github :O ?

**Comment by radare** [comment]
I do everything from the shell. I dont trust guis

**Pull request closed without merging**
