### PR TITLE
Update !? help #5554

### PR DESCRIPTION
**Pull request by tjemg**
This commit hopefully fixes this issue.

### CODE REVIEW

**Comment by radare** [comment]
dont reuse branches, dont merge on them. please redo the pr to just include the commit that matters

**Comment by radare** [comment]
Also, the help message is not updated at all by this commit

**Comment by tjemg** [comment]
maybe I did not understand the issue with 5554... I thought that when typing ?!?, the message as described should appear... which I tested with this commit.
also, I am not sure how to fix this pr, since my master branch already contains the merge. maybe I need to issue another pr?

**Comment by radare** [comment]
?! != !?

**Comment by radare** [comment]
Thisi s what was suposed to be done to fix the issue 220a0b46bd76c8f897e028f60a253fa1da65d916 i have merged your pr because it makes sense to help dyslexic people to use r2.

**Pull request merged**
