### PR TITLE
Enhanced elf bin

### PR DESCRIPTION
**Pull request by alvarofe**
This PR is to enhance a little bit ELF. However is needed to add more boundaries checks. In the following days along with fuzzing, I will try to add more checkings to fix these issues.

Also if there is some feature that you will like to add tell me and we can kill two birds with one stone

### CODE REVIEW

**Comment by Maijin** [comment]
@alvarofe You can find some very fuzzed binaries that are crashing the radare2 currently in radare2-regression bins/fuzzed. You can run the fuzzed testsuite using `make format.others`.

Enjoy

**Comment by alvarofe** [comment]
Thanks @Maijin :)

**Comment by radare** [comment]
Merged, indeed, we have several regressions and crashes exposed by those bins. Also by coverity, @alvarofe do you have access to it? anyway, the current coverity interface sucks hard. im very slow and its impossible to get a list of issues from a specific directory, etc. it would be great if we could download all the results and make our own interface to browse them.

**Comment by alvarofe** [comment]
I have access to coverity, although I have not used it yet.

**Pull request closed without merging**
