### PR TITLE
Add err lib function to osx and linux

### PR DESCRIPTION
**Pull request by ret2libc**
Is there a way to specify varargs?
Because the signature of `err` is: `void err(int eval, const char *fmt, ...)`

### CODE REVIEW

**Comment by Maijin** [comment]
@oddcoder

**Comment by Maijin** [comment]
This is wrong it should be done here https://github.com/radare/radare2/blob/master/libr/anal/d/types and adding corresponding call convention i.e https://github.com/radare/radare2/blob/master/libr/anal/d/types-x86-linux-64

**Comment by ret2libc** [comment]
I see ;) Thanks!

**Comment by ret2libc** [comment]
Ok, updated :)

**Comment by Maijin** [comment]
Still missing the .cc

**Pull request merged**
