### PR TITLE
rahash2 learns -c parameter

### PR DESCRIPTION
**Pull request by stanciuadrian**
-c is allowed when BASE64 (d)ecoding is not performed and when a single hash is computed

### CODE REVIEW

**Comment by radare** [comment]
Update the manpage

**Comment by radare** [comment]
also, indent with tabs, not spaces.

**Comment by stanciuadrian** [comment]
I tried to blend in the existing indentation. Will re-indent the whole file with tabs.

**Comment by radare** [comment]
Merged! thanks i have fixed the test too

**Pull request closed without merging**
