### PR TITLE
Fix #14202 - Add support to '\d', '\w', etc. in regex

### LINKED ISSUE #14202: Regex search seems broken
i mean, the regex work.. but why \d is considered 'd' and not a number? :D

```
[0x00000000]> "/e /\d\d\d\d\d\d\d\d/i"
Searching 16 bytes in [0x0-0x2b1400]
hits: 1
0x001bbabd hit3_0 .#dddddddd\u00e2\u00ff\u00ff\u00ffmddddddd;\.
[0x00000000]>
```

Screenshot 2019-05-31 at 17 33 38

### PR DESCRIPTION
**Pull request by GustavoLCR**
Fix #14202
I followed coding the style of regcomp.c, should I change?

### CODE REVIEW

**Comment by radare** [comment]
lgtm, about changing indentation rules. better in a different PR

**Comment by radare** [comment]
can  you add tests?

**Comment by GustavoLCR** [comment]
> can you add tests?

ok

**Comment by GustavoLCR** [comment]
https://github.com/radare/radare2-regressions/pull/1933

**Comment by radare** [comment]
thanks!!

**Pull request merged**
