### PR TITLE
Remove old fcnstore, Use anal->fcn_tree in r_anal_get_fcn_at()

### PR DESCRIPTION
**Pull request by thestr4ng3r**
r_anal_get_fcn_in() already used fcn_tree, but r_anal_get_fcn_at() did not.

For the case I described in #9702, this reduces the time for `aaa` from about 35 seconds to 23 seconds. According to callgrind, r_anal_get_fcn_at() took 10.70% of all executed instructions before and 0.23% after this change.

### CODE REVIEW

**Comment by radare** [comment]
3 XX because of crashes

**Comment by thestr4ng3r** [comment]
Yes, I am working on it.

**Comment by radare** [comment]
👍

**Comment by thestr4ng3r** [comment]
The tree corrupts in some cases when the max_addr changes, but it is not propagated in the tree. I am also seeing some places where fcn->addr is changed without updating the tree. I will fix these things.

However in the future, one always has to keep the tree in mind when changing fcn->addr and fcn->_size. It would be useful to have some kind of assertions or maybe a r2 command to check if the tree is valid in r2r. Otherwise these bugs will be hard to catch.

**Comment by thestr4ng3r** [comment]
Ok, the places I mentioned where fcn->addr is changed were actually ok, because the function hasn't been added to anal yet in these cases.

But the cases where the size is changed were not. I added an RAnal * parameter to `r_anal_fcn_set_size()` and `r_anal_fcn_resize()` that can be NULL if the function hasn't been added to anal yet and must be the respective anal otherwise.

**Comment by thestr4ng3r** [comment]
By the way I also added a function `_fcn_tree_print_dot()` that prints the function tree in graphviz dot and marks nodes and edges in red if an invariant is violated.

**Comment by radare** [comment]
<3

**Pull request merged**
