### PR TITLE
Fix #9579

### LINKED ISSUE #9579: to does not load char* member correctly
char* structure member are not displayed.

Here is a complete example:
```
r2 -b 32 -
 -- It's the year of desktop on radare2
[0x00000000]> wv 4; wz r2 @ 4
[0x00000000]> px 7
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  0400 0000 7232 00                        ....r2.
[0x00000000]> cat /tmp/test.h
typedef struct test {
  char* name;
} test_t;
[0x00000000]> to /tmp/test.h 
[0x00000000]> ts test
pf z name
[0x00000000]> tp test
 name : 0x00000000 = .
```
It seems that the type should be `s` instead of `z`.

### Work environment

```
r2 -version
radare2 2.4.0-git 17578 @ linux-x86-64 git.2.2.0-660-g067ae7030
commit: 067ae7030d6c65810cb8d66e5d15c6f7926d00c5 build: 2018-03-04__16:04:34
```
### Expected behavior

The string `r2` should be displayed.

### Possible fix

```--- a/libr/anal/d/types.sdb.txt
+++ b/libr/anal/d/types.sdb.txt
@@ -34,7 +34,7 @@ type.char=c
 type.char.size=8
 
 char *=type
-type.char *=z
+type.char *=s
 
 uint8_t=type
 type.uint8_t=b
```

Here is the output after patching and rebuilding the sdb:
```
r2 -b 32 -
 -- There's no way you could crash radare2. No. Way.
[0x00000000]> wv 4; wz r2 @ 4
[0x00000000]> to /tmp/test.h 
[0x00000000]> ts test
pf s name
[0x00000000]> tp test
 name : 0x00000000 = 0x00000000 -> 0x00000004 r2
```

### PR DESCRIPTION
**Pull request by guedou**
This PR fixes #9579

### CODE REVIEW

**Comment by lowlyw** [comment]
s/S is an issue, 32 vs 64 bits

**Comment by lowlyw** [comment]
please test both ways

**Comment by guedou** [comment]
How should I fix this issue?

**Comment by radare** [comment]
lgtm

**Comment by radare** [comment]
works for 32bit only so maybe the way to go would be to go would be *z... but i think we can detect if its widechar or utf8, ascii, etc

see
```
|  *       next char is pointer (honors asm.bits)
|  z       \0 terminated string
|  Z       \0 terminated wide string
|  s       32bit pointer to string (4 bytes)
|  S       64bit pointer to string (8 bytes)
```

**Comment by radare** [comment]
screen shot 2018-03-05 at 00 23 34

**Comment by radare** [comment]
the funyy thing is that * doesnt seems to be broken

**Comment by radare** [comment]
so pf have no way to follow pointers depending on asm.bits :?

**Comment by radare** [comment]
Filled an issue here https://github.com/radare/radare2/issues/9584

**Comment by kazarmy** [comment]
I think char * needs to stay type `z` until pf gets an immediate-value variant, otherwise there's no direct way to pf values/args stored in registers.

**Pull request merged**
