### PR TITLE
mesonbuild: Using radare2 as subproject

### PR DESCRIPTION
**Pull request by pelijah**
Allow using radare2 as subproject from meson projects.

### CODE REVIEW

**Comment by xarkes** [comment]
Something is strange with the dynamic build, it finishes the build and then tries to restart the build like 3/4 times.

**Comment by pelijah** [comment]
Yep, ninja fails at installing step on my machine too...

**Comment by pelijah** [comment]
Still don't know why ninja starts failing on my branch and works fine on master.

**Comment by xarkes** [comment]
Lgtm

**Pull request merged**
