### PR TITLE
Remove r_io_buffer*

### PR DESCRIPTION
**Pull request by MaskRay**
There are already r_io_cache* (r_io_t::cachemode) and r_io_desc_cache* (r_io_t::__cache). There is no place for this extra cache layer.

### CODE REVIEW

**Comment by MaskRay** [comment]
I expected you would have some objection. `io.buffer` is very weird in that it can be read (`r_io_*read`) but cannot be written (no `r_io_*write` uses it). It will be written through.

**Comment by radare** [comment]
io.buffer is weird because concept comes from r1 and siol didnt get updated for this, siol have p and v caches, but no generic layered global cache like io.buffer does. and this was done to optimize slow io backends like remote gdb machines and such.

**Comment by MaskRay** [comment]
It supports just one segment and dig through the history and only find one ancient issue (https://github.com/radare/radare2/issues/3808)  referring to it

> I've tried using the options io.buffer.from=0x1ffab000; io.buffer.to=0x1ffabf00; io.buffer=true and io.cache=true, however they didn't seem to reduce the number of redundant reads at all.

This, at present, stands in the way to do proper refactoring of the IO layer.

**Comment by MaskRay** [comment]
Oh another referral https://github.com/radare/radare2/issues/2738 it is apparent it makes people confused.

**Comment by radare** [comment]
Ok lets go forwars and break things to get proper io cache design here. We can add a map named cache with the contents read from the other underlaying maps. This can be handled from core. But ideally io should have a stack of those maps. Being able to delete them or repriorize them. This seems like better solution for iobuffer with siol in mind.

So at the end the needed pieces to get this to work are already in io. But i would like to have this cache concept inside io to manage that stuff outside core

**Comment by MaskRay** [comment]
@condret said there is `libr/include/sdb/dict.h` for `ut64` keys. But it cannot handle 0 keys (`#define MHTNO 0`)

**Comment by radare** [comment]
Dict was an experiment. Ret2libc is totally against it. Dunno about your opinion. Imho it works and its faster than ht in many situations. But again it was an experiment and didnt tried to used

**Pull request merged**
