### PR TITLE
Bug-fixes for gdb read/write mem

### PR DESCRIPTION
**Pull request by SrimantaBarua**
@vifino I've added the `PFMT64d` -> `PFMT64x` from your changes, if it's okay with you, since I see you haven't made the PR yet. Would help solve a few bugs.

### CODE REVIEW

**Comment by radare** [comment]
Lol. So basically all memreads beyond address 0 were wrong before?

**Comment by SrimantaBarua** [comment]
The sizes of memreads were wrong, address was okay. And that's why it was causing errors on gdbservers with max packet size < (2048 * 1.6) bytes, because sometimes it was sending a too big a packet

**Comment by radare** [comment]
Aaah! Nice one

**Comment by vifino** [comment]
@SrimantaBarua Aww, now I am a bit salty that you get the fix merged for that :P

**Comment by SrimantaBarua** [comment]
@vifino Yeah sorry, I didn't know when you were going to send the PR, and this was going to solve bugs we've had for the last week, so wanted to get this done earlier.

**Pull request merged**
