### PR TITLE
Fix #7911 added resources extraction in rabin2

### LINKED ISSUE #7911: Resources extraction in rabin2

### PR DESCRIPTION
**Pull request by plutec**
I use the -U parameters to be the closer free letter in the word.

### CODE REVIEW

**Comment by radare** [comment]
Why not reuse the -x associated with fatbins? And do that in case its not a fatbin?

**Comment by plutec** [comment]
I don't understand what you propose with -x. Do you mean -xU ?

**Comment by Maijin** [comment]
-O sounds more logic imho

**Comment by Maijin** [comment]
Ah it's only for display ok then whatever.

**Comment by radare** [comment]
Rabin2 have the -x flag that extract all sub-bins. On windows this would be supported at aome point. Basically an exe have different sub executables inside. The dos, win31, win9x, and .net code to show error messages basically.

So the suggestion that fits better is probably -O like alvaro said because there are subcommands of -O that dump prts of the bin. Not necessarily complete executables like -x does

**Comment by Maijin** [comment]
Yeah although this was only for display which is != extraction

**Comment by plutec** [comment]
Yes, it's only to display, use the extrated by r2_core

**Comment by Maijin** [comment]
ok then -U probably the best for display 👍  -O to be used for extraction

**Comment by plutec** [comment]
Which is the difference for extraction and for displaying for you?
Extraction is when there are one or more bins inside a fatbin, and you "extract" the bins and the resources from them.
Display is when you have a bin and "display" the resources of that, is this right?

**Comment by Maijin** [comment]
No display is same as `iR` whereas extraction is extracting the ressources selected and dumping it on the filesystem just like -O allows you to dump sections for example

**Comment by plutec** [comment]
Ahh ok, I understand! Thanks!
So, anything else pending in this PR?

**Comment by radare** [comment]
Aah ok

**Comment by radare** [comment]
Uhm maybe we can make -x work for extracting and check if -U is used to extract the resources.. the same can be done with -xS to extract all sections in separate files or -xs for the symbols, etc

**Comment by plutec** [comment]
Good, i'll try during the day

**Comment by plutec** [comment]
I checked the code and -xU run as expected:
```
$ rabin2 -xU file.dll 
Resource 0
	name: 1
	timestamp: Wed Dec 31 23:00:00 1969
	paddr: 0x00098038
	size: 256
	type: UNKNOWN
	language: LANG_ENGLISH
Resource 1
	name: 1
	timestamp: Wed Dec 31 23:00:00 1969
	paddr: 0x00075568
	size: 138.7K
	type: UNKNOWN
	language: LANG_ENGLISH
Resource 2
	name: 102
	timestamp: Wed Dec 31 23:00:00 1969
	paddr: 0x00075508
	size: 92
	type: RCDATA
	language: LANG_ENGLISH
Resource 3
	name: 1
	timestamp: Wed Dec 31 23:00:00 1969
	paddr: 0x00075160
	size: 936
	type: VERSION
	language: LANG_ENGLISH
```
I think the code is well done and if you use -x (set the flag) and any other subcommand (-U, -s, -S) works in the same way:
```
case 'x': set_action (R_BIN_REQ_EXTRACT); break;
```

**Pull request merged**
