### PR TITLE
Haiku port (partial)

### PR DESCRIPTION
**Pull request by mmuman**
Some fixes for Haiku (gcc2)

While we can compile stuff with gcc4, we still use gcc2 for the base system, so it makes sense to try and build with it anyway (although there are still some other issues to fix).

Mostly C89.

### CODE REVIEW

**Comment by radare** [comment]
Please squash them into a single commit. Do you have plans to add support for the debugger too?

**Comment by mmuman** [comment]
All the C89 you mean? I did a commit per file on purpose but well 😀

**Comment by mmuman** [comment]
Don't know yet for the debugger

**Comment by radare** [comment]
Ive been checking out the haiku gdb patches and doesnt seems hard. Its not ptrace friendly, but all the code is there and its a reasonable work.

**Comment by mmuman** [comment]
I've started porting Valgrind which also wants ptrace(). Either I'll have to write a glue to our current debugger interface, or implement one of the existing ptrace API on top of it.

**Comment by XVilka** [comment]
Defining variables in place is very useful, imho, you've said you can use gcc-4 for building for Haiku. Why to stuck with very outdated format, at least since the radare2 is not in the base system?

**Comment by radare** [comment]
Looks good both commits, thanks! i have also updated sdb, no need to send another pr in there

**Comment by mmuman** [comment]
Ah ok, was about to do it. Thanks.
Not sure what to do about js0n.c though, it's probably going to be very messy if I start to touch it:
```
src/json/js0n.c:26: duplicate array index in initializer
src/json/js0n.c:26: (near initialization for `gostruct')
```
Looks like gcc2 doesn't like it at all. I'm not sure it's worth trying to build with gcc2, would r2 handle gcc2-built executables anyway even when built with gcc4 (C++ mangling and other ABI differences)?

**Comment by radare** [comment]
Yeah js0n have some kind of black magic that makes the code kinda simple. And this change will make it more complicated. I have already though on this several times but never found a reason to support older compilers here. 

I think defining vars at the begining of a stack frame makes sense and helps to build code in a more modular or functional way.

But im not sure about things like this. We can probably make a js0n-c89.c and include it from js0n.c if needed. If at some point we find a way to make this cleaner it can be good for comparing and will fix the issue but im not a big fan of having dupped code. Also, i guess code will also perform worst, not sure about compiler optimizations here

**Pull request closed without merging**
