### PR TITLE
New relsub fix

### PR DESCRIPTION
**Pull request by Svenito**
Contains changes from the reverted commit but without the segfaults

### CODE REVIEW

**Comment by radare** [comment]
damn travis :[

**Comment by Svenito** [comment]
Is it still running? Wtf?

**Comment by radare** [comment]
I have cancelled many jobs to free resources in their side.. but yep its still running

**Comment by radare** [comment]
Well in fact it has started to run 3 min ago

**Comment by radare** [comment]
travis was happy about that <3 awesome contrib thanks!

**Pull request merged**
