### PR TITLE
Merge meson scripts

### PR DESCRIPTION
**Pull request by pelijah**
Just merged meson.py, meson_sdb.py, meson_extra.py scripts together with minimal changes

### CODE REVIEW

**Comment by xarkes** [comment]
Cool thanks

**Comment by pelijah** [comment]
@xarkes Well it was really stupid idea to remove sys/meson_sdb.py without checking its dependencies. So now meson build via make is broken. I am very sorry. How can I fix my mistake? Will it be better to submit new PR with restored meson_sdb.py?

**Comment by xarkes** [comment]
Don't worry about meson + Makefile there is no need to keep it.
In the end if you want to build using meson (whatever OS you use) we just want to use the python script, no extra files

**Comment by pelijah** [comment]
btw what do you think about #9143?

**Comment by xarkes** [comment]
Yeah looks good but I didn't look why Appveyor is red, probably unrelated, if so I can merge

**Pull request merged**
