### PR TITLE
Output 'delay' field in aoj command (and fix 'failcycles')

### PR DESCRIPTION
**Pull request by sapir**

### CODE REVIEW

**Comment by sapir** [comment]
how do I update the tests to fix the Travis build?

**Comment by alvarofe** [comment]
send a PR to [regression](https://github.com/radare/radare2-regressions)

**Comment by radare** [comment]
Thanks!

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://dcbmuzaffarnagar.com/written.php?0meu>

 

lukas-runas@gmx.de

**Pull request closed without merging**
