### PR TITLE
Fix for incorrect pc after breakpoint, in x86 gdb

### PR DESCRIPTION
**Pull request by SrimantaBarua**

### CODE REVIEW

**Comment by SrimantaBarua** [comment]
Don't merge yet, this causes issues with continue after hitting breakpoint

**Comment by SrimantaBarua** [comment]
Updated. Using the `swbreak+` option is what gdb does. But it won't work here because r2 internally checks if `bp address == pc - sizeof(bp)`. In `swbreak+` the target updates pc to point to the bp address. So r2 didn't know bp was being hit.

Currently this sets the stop reason as `R_DEBUG_REASON_BREAKPOINT` every time signal 5 is received. Is this wrong? But something like Qemu gdbserver does not provide any extra information other than the signal and thread id, so there it would have to be breakpoint.

**Comment by SrimantaBarua** [comment]
Works for simavr too, so I don't think this affects other archs. If you're okay with the signal 5 == breakpoint thing ^ for now, then I think this can be merged.

**Comment by radare** [comment]
looks good, we can use signal5 for now, but will be good to not use the same message that other events can generate, i'm merging now

**Comment by SrimantaBarua** [comment]
The logic for other events for signal 5 is implemented in `shlr/gdb/`, but we don't support them yet. So will add that to `debug/` when we support them

**Pull request merged**
