### PR TITLE
Add r_anal_op_partial() to optimize analysis

### PR DESCRIPTION
**Pull request by thestr4ng3r**
The idea is to skip esil generation when not needed at all. With only these small changes, I was able to get the time for `aaa` (most time taken in `aac` in this case) for a relatively big dll I have from about 40 seconds to 35 seconds.
Better name suggestions for `r_anal_op_partial()` are welcome :)

### CODE REVIEW

**Comment by XVilka** [comment]
```
var int local_14h @ rbp-0x14
-arg int local_10h @ rbp-0x10
-arg int local_8h @ rbp-0x8
+var int local_10h @ rbp-0x10
+var int local_8h @ rbp-0x8
[  ]  1  xtensa_var: xtensa stackframe             
[XX]
```
Not sure though how this is related.

**Comment by thestr4ng3r** [comment]
I have no idea to be honest. Actually I can't even run that test successfully with master locally:
```
[florian@florian-desktop radare2-regressions]$ ./t.anal/others_anal/xtensa_var
[XX]  1  xtensa_var: xtensa stackframe             

Regression: ./t.anal/others_anal/xtensa_var
Command:  /home/florian/bin/radare2 -e scr.color=0 -N -q -i /tmp/r2-regressions//xtensa_var-ZZI0l4/rad   malloc://512 > /tmp/r2-regressions//xtensa_var-ZZI0l4/out 2> /tmp/r2-regressions//xtensa_var-ZZI0l4/err
File: malloc://512
Script: e asm.arch=xtensa
e asm.bits=32
wx 12c1f0d91140d382c9213d0d093101f5ebc00000cd028c820c034d0d0112e4c0000008312d0cd811c82112c1100df0
af
afvs

Diff: --- /tmp/r2-regressions//xtensa_var-ZZI0l4/exp	2018-03-15 12:26:59.098338066 +0000
+++ /tmp/r2-regressions//xtensa_var-ZZI0l4/out	2018-03-15 12:26:59.098338066 +0000
@@ -1,3 +0,0 @@
-var int local_4h @ a1+0x4
-var int local_8h @ a1+0x8
-var int local_ch @ a1+0xc
```

**Comment by radare** [comment]
the function argument/local variable detection is wrong in many cases, so not sure if those tests are right, because in real use cases i found many places where its wrong

**Comment by thestr4ng3r** [comment]
But that still does not explain why my changes change the behaviour. Let me investigate a bit...

**Comment by radare** [comment]
the idea i had in mind to do this was to pass a mask to the anal_op function to specify which fields are you interested in. mainly opex, esil and ->src|dst are the slower ones

**Comment by thestr4ng3r** [comment]
I added the additional function to not change the signature of r_anal_op() since it is used in so many places. But if you are ok with that, I would change it the way you said and add a bitmask. I would prefer that solution as well.

**Comment by thestr4ng3r** [comment]
Don't merge yet if travis gets green, I want to try adding the bitmask.

**Comment by thestr4ng3r** [comment]
Ok now r_anal_op() has the mask parameter. However anal->decode is still used to tell plugins whether to generate esil. Now it would be nicer to also pass that as the mask parameter to the plugins, however then the signature for RAnalOpCallback would have to be changed, every single plugin has to be adapted and all plugins outside of r2 will be broken.
What do you think @radare? Break and refactor things or use it as it is now?

**Comment by radare** [comment]
The change looks good, despite breaking api compat. But i'm a big fan of this, because it makes easier to spot people stuck in the past.

**Pull request merged**
