### PR TITLE
Fixes #14534: Ignore non-printable and non json chars

### LINKED ISSUE #14534: pj is not json wtf
```
$ r2 /bin/ls
[0x1000011e8]> pj
UH��AWAVAUATSH��
[0x1000011e8]> pj
UH��AWAVAUATSH��
[0x1000011e8]> pj?
Usage: pj[..] [size]
| pj    print current block as indented JSON
| pj.   print as indented JSON from 0 to the current offset
| pj..  print JSON path from 0 to the current offset
[0x1000011e8]> pj.
Cannot read
[0x1000011e8]> pj..
[0x1000011e8]>
```

### PR DESCRIPTION
**Pull request by deepakchethan**
After change:

Screen Shot 2019-08-23 at 10 09 21 AM

### CODE REVIEW

**Comment by radare** [comment]
Lgtm but its red

**Comment by radare** [comment]
i think its because of the newlines

```
[35m-}[39m
[35m[39m[32m+}[39m
```

**Comment by radare** [comment]
missing newline?

**Comment by deepakchethan** [comment]
It's Green !!!

**Comment by radare** [comment]
💚

**Pull request merged**
