### PR TITLE
Save breakpoints on project save. Related issue: #2409.

### PR DESCRIPTION
**Pull request by lyuts**

### CODE REVIEW

**Comment by radare** [comment]
This brings some issues:

* is the binary PIE
* is the system doing ASLR?
* is the breakpoint placed in program segment?
* it is in heap?
* is a breakpoint placed in code from the future? (dlopen...)
* it is places in a executable region?
* is an execute breakpoint? (or read, or write)...
* it is a hardware or software breakpoint?

I would suggest a change on the approach by making that dumped list of breakpoints using some known bases like the base address of the module where it is set, by making them relative. But as you see by the list before the current approach only works on very marginal cases, where the executable is not PIE (very rare nowadays on modern systems)

**Comment by XVilka** [comment]
@radare anyway you need to think of these before the starting to implement storing them as a SDB.

**Comment by lyuts** [comment]
@radare, good points, missed them entirely. Now i'm not ok with the proposed behavior as it is not always correct. Sounds like it would take a big effort to make it work, e.g. just the case with dlopen is not obvious.

**Comment by radare** [comment]
Maybe we should close this pullreq

**Comment by radare** [comment]
One possible solution would be to expose a base flag name in all the db* output something like i recently added in f*. see the output of "f*base". but for breakpoints we have to assume that every breakpoint can be on a different library which can have a different base address on each run

**Comment by radare** [comment]
Im closing this pullreq because it is wrongly solved and should be tracked in the issue

**Pull request closed without merging**
