### PR TITLE
setting default non zero values for window row and column size

### PR DESCRIPTION
**Pull request by 8tab**
fixes a segfault while debugging under cgdb.

### CODE REVIEW

**Comment by radare** [comment]
Thanks!

**Comment by radare** [comment]
where this segfault was happening? maybe it will be good to fix this too

**Comment by 8tab** [comment]
it was a segfault in chop_prompt. My patch fixes this issue, but I see the if condition is wrong, so I can submit another patch for this. BTW, I see you closed this PR without merging it. Is it intended?

**Comment by radare** [comment]
It has been merged, just not using the github ui for it a202b0c4cb83750242a2a15193381c39df2ba539

**Comment by 8tab** [comment]
ok, thanks for explanation.

**Pull request closed without merging**
