### PR TITLE
Pdb downloader issue

### PR DESCRIPTION
**Pull request by inisider**
Done this issue https://github.com/radare/radare2/issues/1909

### CODE REVIEW

**Comment by radare** [comment]
Merged! can you add some tests for this?

**Comment by inisider** [comment]
Cool. Do U have some ideas how to do this? Or just get some library from
System32 and test wit it? And how to test case when PDB_SERVER and
PDB_AGENT variables are not defaults?

**Comment by radare** [comment]
Iirc pdbserver was already tested. But not sure how should we test user agent without a custom serverside php. For the extract flag .. It can be checked like we do with the current test but swap the flag to test if it obeys it.

**Comment by inisider** [comment]
iirc pdbserver was tested just using microsoft server. what to do with case
when this is not microsoft server...

вт, 26 мая 2015 г. в 14:47, radare <notifications@github.com>:

> Iirc pdbserver was already tested. But not sure how should we test user
> agent without a custom serverside php. For the extract flag .. It can be
> checked like we do with the current test but swap the flag to test if it
> obeys it.
>
>
>

**Comment by radare** [comment]
this will require some serverside mangling which is out of the scope of
the issue.. so i vote for not testing it :)

**Pull request closed without merging**
