### PR TITLE
Analyze symboly of type of STATIC

### PR DESCRIPTION
**Pull request by sivaramaaa**
### Before 

beff

### After 

afl

### CODE REVIEW

**Comment by sivaramaaa** [comment]
Expecting it to be super **RED**

**Comment by radare** [comment]
this red looks green

**Comment by sivaramaaa** [comment]
Yeah :)

**Comment by XVilka** [comment]
Pull request is green,
Pancake is happy,
The output is nifty,
Merge to be seen.

**Comment by radare** [comment]
haiku <3

**Pull request merged**
