### PR TITLE
implemented delay slot in esil_step

### PR DESCRIPTION
**Pull request by mrmacete**
+ the delayed instruction is executed first
+ and then flow continues normally

### CODE REVIEW

**Comment by mrmacete** [comment]
This is an attempt to fix the currently broken implementation of delay slot emulation in esil_step.

With this patch i managed to run successfully part of complex MIPS code ripped from a crackme, i wrote the corresponding tests accordingly.

The disadvantages of this approach are:
- order of instruction is changed
- instructions with a delay slot (e.g. branches) need two aes steps to complete
- i feel it is mostly a hack, it may need to be discussed more

**Comment by radare** [comment]
As long as delayed execution is happening under the hood and producing exceptions in weird manners depending on the next instruction i think its ok to push this change for now.

We should probably keep that double step in there and store the delayed state to perform the emulation of the next instruction and throw a exception in case of invalid insteuction in there if necessary. 

This will be fine for correct code,. But the stepping should be handled in anal instead of core.cmd, we should start writing some tests using the esil api in a higher level form to share this code between core and debug.esil allowing others to perform this kind of emulation without the r2 shell, just using the api.

**Comment by mrmacete** [comment]
just changed the code to use the already present "goto repeat" way to perform the delayed step. This permits to:
- handle properly the invalid instructions in the delay slot (added a test for this)
- use a single 'aes' to emulate branches

i agree this should be somehow moved to the anal-side, but at which level? by merging ESIL into a single statement? but how can anal_op have this capability? if i understand correctly, it belongs to a higher level... moreover merging ESIL is not so straightforward (for example ho to deal with BREAK instructions?)

**Comment by radare** [comment]
merged!

**Comment by radare** [comment]
Can you check how unicorn handles the delay slot when stepping?

**Comment by mrmacete** [comment]
ok, i'm checking

**Comment by mrmacete** [comment]
i've to analyze it deeper, but what really catches the eye is this comment:

```
/* Execute a branch and its delay slot as a single instruction.
           This is what GDB expects and is consistent with what the
           hardware does (e.g. if a delay slot instruction faults, the
           reported PC is the PC of the branch).  */
```

at line 19315 of [this file](https://github.com/unicorn-engine/unicorn/blob/master/qemu/target-mips/translate.c)

**Comment by mrmacete** [comment]
if i'm understanding well, the process seems:

- there's a branch instruction, figure out the target address and store it in the current context/state
- if the branch requires a delay slot, don't actually perform the jump and set the delay slot flag
- perform the delay slot instruction as nothing happened
- it was a delay slot (i.e. the delay slot flag is set)? let's perform the actual jump to the stored target and clear off

every branch instruction raises an exception if it is found inside a delay slot

**Comment by mrmacete** [comment]
translating this to r2-land, some "execution state" must be informed of delay slots, it could be the *anal* context which knows delay slots, but presently it isn't execution-aware - or it could be the *esil* context which has an execution state but it's unaware of delay slots...

**Comment by mrmacete** [comment]
Or... Use special internal registers declared in the profile and doing this in pure ESIL... Not sure how but it's a tempting thought...

**Comment by radare** [comment]
maybe we can use a virtual register to define this state

**Comment by mrmacete** [comment]
yeah, they could be 2 registers, say:
- BT = branch target
- DS = delay slot

In this way, the ESIL for an unconditional branch with delay slot can be:

```
TARGET_ADDR,BT,=,1,DS,=
```

instead, a classic branch can remain what it is now and still works:

```
TARGET_ADDR,PC,=
```

or switch to the branch target way but without setting the delay slot register

```
TARGET_ADDR,BT,=
```

The step algorithm can be something like:

- check the DS register
- if it's a delay slot (DS!=0):
    - if the instruction isn't allowed here, exception (this check can be done in ESIL too)
    - else, save DS in a temp state and clear DS register
- emulate instruction at PC
- PC=BT (do the branch) if:
    - BT is set (how to know it? check with zero? this disallows branching to zero... another register? meh...)
    - and ( DS was set before instruction emulation - we're executing the delay slot
        - or the just emulated instruction did not set DS )
- after performing the branch, BT is cleared / destroyed

This assumes the delay slot count to be 1 or 0, if out there exist archs with more than one instruction in delay slots, it can be accomplished treating DS as a counter...

**Comment by radare** [comment]
As long as runtime logic depends on it maybe it will be better to make those registers internal to esil. prefixed with %. This way the pc change will happen when:

if %ds > 0 {
  %ds--;
  if %ds {
    if PC {
       TRAP;
    }
  } else {
    PC=%bt;
  }
}

This code will go into the esil step procedure, and the logic will be the same for all archs with delay slot. So we dont have to modify every regprofile.

**Comment by mrmacete** [comment]
ok i may try this tonight, ok?

**Comment by radare** [comment]
Ok!

**Comment by mrmacete** [comment]
it seems to work, for sure it needs review: https://github.com/radare/radare2/pull/3809

**Pull request closed without merging**
