### PR TITLE
fix android arm build and update integration of kernel map

### PR DESCRIPTION
**Pull request by P4N74**
fix broken compilation due to io_r2k.c for all android build.
I will separate windows and linux in two different files.

### CODE REVIEW

**Comment by radare** [comment]
This is wrong. Dont ever use sizet. Because if you have an arm64 kernel and the r2 is compiled for arm will work. In r2land we use to always use ut64 for everything to avoid that problem

**Comment by P4N74** [comment]
@radare I am actually looking for something like I did earlier for [this](https://github.com/radare/radare2/pull/6265/files#diff-88e9929db8acdc2983780de75bfca054R249)
Earlier it was as shown below, which was later changed to what is currently in the code and I squashed the two commits.
```
#if __x86_64__ || __arm64__ || __aarch64__
typedef ut64 ul;
#elif __i386__ || __arm__
typdef ut32 ul;
#endif
```

**Comment by radare** [comment]
Dont do tjat. Just use ut64 everywhere . Doing what you propose is the same as using sizet

**Comment by radare** [comment]
Merging to get the android build fixed

**Pull request merged**
