### PR TITLE
Temp rasm2 lib loading fix

### PR DESCRIPTION
**Pull request by Lukas-Dresel**
So i made a preliminary fix for issue #4495 simply for 0.10.2, will be fixed better once i tackled issue #4513. Also adjusted rasm2's load order to match core/libs.c
Adjusted library loading by all the r*2 tools to work the same way as the core. Again, will be fixed better.

### CODE REVIEW

**Comment by Lukas-Dresel** [comment]
Don't merge this yet please

**Comment by Lukas-Dresel** [comment]
Last changes aren't yet confirmed stable

**Comment by Lukas-Dresel** [comment]
Done. Should be good now. Can be merged.

**Comment by Lukas-Dresel** [comment]
NOW i'm done ;)

**Comment by radare** [comment]
Merged! thanks!

**Pull request closed without merging**
