### PR TITLE
add aes-cbc encryption to rahash2

### PR DESCRIPTION
**Pull request by P4N74**
Add AES-CBC mode and fix AES-ECB .  Support for getting IV is added with `-I` option in rahash2.

### CODE REVIEW

**Comment by radare** [comment]
Thanks!

**Comment by radare** [comment]
Oops. there are some warnings, can you fix them?
```
rahash2.c:301:38: warning: passing 'const char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
    if (iv && !r_crypto_set_iv (cry, iv, ivlen)) {
                                     ^~
/Users/pancake/prg/radare2/libr/..//libr/include/r_crypto.h:56:95: note: passing argument to parameter 'iv' here
__attribute__((visibility("default"))) int r_crypto_set_iv(RCrypto *cry, const unsigned char *iv, int ivlen);
                                                                                              ^
rahash2.c:473:6: warning: assigning to 'char *' from 'unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
  iv = (unsigned char*)malloc (strlen (ivseed) + 128);
     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rahash2.c:478:35: warning: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
   ivlen = r_hex_str2bin (ivseed, iv);
                                  ^~
/Users/pancake/prg/radare2/libr/..//libr/include/r_util.h:603:89: note: passing argument to parameter 'out' here
__attribute__((visibility("default"))) int r_hex_str2bin(const char *in, unsigned char *out);
                                                                                        ^
3 warnings generated.
```

**Comment by P4N74** [comment]
Yes I will work it out.

**Comment by P4N74** [comment]
@radare should I update this pr or create new?

**Comment by radare** [comment]
Create a new one. Feel free to fix other indentation and warnings out there

**Pull request closed without merging**
