### PR TITLE
Fix syntax choice for asm_x86_as

### PR DESCRIPTION
**Pull request by Tyilo**

### CODE REVIEW

**Comment by Maijin** [comment]
It's tested and it works on both OSX CLANG and Linux GCC https://travis-ci.org/radare/radare2/jobs/95618795#L1202

**Comment by Tyilo** [comment]
I still have a problem with this. The default syntax for me is intel, while for the test servers and Maijin it is att.

That is this doesn't work for me:
```
rasm2 -a x86.as -b 64 'movq %rdx, %rax'
```

but this does:
```
rasm2 -a x86.as -b 64 'mov rax, rdx'
```

**Comment by radare** [comment]
You can speicfy the syntax . See rasm2 -h but it should be the same by default everywhere

**Comment by radare** [comment]
```

**Comment by radare** [comment]
that works fine for me after applying your patch

**Comment by radare** [comment]
Thanks!

**Pull request closed without merging**
