### PR TITLE
Disable function autonaming to avoid confusions ##anal

### PR DESCRIPTION
**Pull request by radare**
screenshot 2019-02-14 at 04 12 08

### CODE REVIEW

**Comment by radare** [comment]
10 XX

**Comment by ITAYC0HEN** [comment]
I think it is better not to detect "jmp thunk table" functions and remove "aan". We should prioritize fixing this though. 
As a compromise, we can only apply "anal.autoname" only if:
1. Binary is PE
2. function of size < 10.
3. The referenced flag is "sym.imp."

In these cases, the functions are probably jmp thunks

**Comment by Maijin** [comment]
In elf the elements are marked accordingly as dword or qword

**Comment by ITAYC0HEN** [comment]
What do you mean? And what it. Implies about the solution? I thought that plt got detection in r2 is good

**Comment by radare** [comment]
Feel free to improve aan with your suggestions. But the idea of this pr is to decide if we want it enabled or not by default

**Comment by ITAYC0HEN** [comment]
I vote for disable.

**Comment by radare** [comment]
♿️

**Comment by ret2libc** [comment]
I'm fine with disabling it. It's not like it's that useful usually... it just gets the name of the first called function.

**Comment by Maijin** [comment]
@ret2libc in the case I mentionned, the renaming is mandatory if you want to be able to understand something.

**Comment by Maijin** [comment]
I have added other tools comparison in the issue, only binja is doing as bad as without aan.

**Comment by radare** [comment]
It is very useful actually if u check the failing tests its important for windows binaries which use to have wrappers of wrappers of functions as well as for crackmes where methods get meaningful names related tonthe strings they contain.

**Comment by radare** [comment]
Imho i would keep it enabled for now and wait for next release to do any change on this

**Comment by ITAYC0HEN** [comment]
in my opinion, having something like this is worse than nothing:

image

**Comment by radare** [comment]
i think we should make it an int and make it configurable to choose the level of autonaming rules to use. 0 for disable, 1 for direct trampolines, 2 for more stuff, ...

**Comment by ITAYC0HEN** [comment]
can be merged now.

**Comment by radare** [comment]
did you updated the tests?

**Comment by radare** [comment]
no  wait after release? XD

**Pull request merged**
