### PR TITLE
Initial implementation of the dri command - inverse debug registers ##debug

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by XVilka** [comment]
What is the purpose of this command?

**Comment by radare** [comment]
already explained it, shared a video and showed several use cases for when this is useful in the core channel

**Comment by radare** [comment]
https://twitter.com/trufae/status/1098619641809854464 <https://twitter.com/trufae/status/1098619641809854464>

**Comment by XVilka** [comment]
Thanks for the example.

**Pull request merged**
