### PR TITLE
[WIP] Add support for Windows Minidump (mdmp) files

### PR DESCRIPTION
**Pull request by davispuh**
This adds support for [Windows Minidump (mdmp) files](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680369.aspx). They can easly be created manually with Task Manager and also some applications generate them on crash. There aren't any real documentation about this format.

I worked on this more than a year ago but got carried away and thus never really finished it. It's still on my TODO list, but I don't know when I'll have time to work on it so anyway I'm just putting it up here. It compiles but I don't know if it still works on current radare and I don't remember how far I got and how much there's left to be implemented.

### CODE REVIEW

**Comment by davispuh** [comment]
FYI: I remembered about this because Microsoft just published PDB header file [microsoft-pdb](/Microsoft/microsoft-pdb)

**Comment by Maijin** [comment]
@davispuh See the CLANG/OSX doesn't build https://travis-ci.org/radare/radare2/jobs/88485386

**Comment by Maijin** [comment]
@davispuh Feel free to open an issue here with stuff like `* [ ]` :
To keep trace of what is remaining to do if some people want to contribute on this and for you to keep trace.
* [ ]

**Comment by radare** [comment]
I fixed the build. im gonna merge this now, but it needs some reviews. Can we have a testcase in r2r repo to verify that everything works and doesnt breaks in the future?

It is great to have such kind of contribs :) we’ll take care your code, so it will not be abandoned here.

thanks!

**Comment by radare** [comment]
Thanks! merged!

**Comment by radare** [comment]
I've updated the code for the latest r2 and fixed windows build. You can see the changes here: 0648cea3e5d85a088e079cade59f404bbf5f2119 we'll need some testcases, so we need some minidump bins for testing and write tests for them.

**Comment by davispuh** [comment]
wow, I really didn't expect for this to be merged... Cool :+1:

**Comment by radare** [comment]
Welcome to r2land, a place where things happen quickly :)

**Pull request closed without merging**
