### PR TITLE
core/graph: improve nodes layout

### PR DESCRIPTION
**Pull request by ret2libc**
It seems to me this patch places nodes a in slightly better way.
If somebody can test and confirm, it would be great!

### CODE REVIEW

**Comment by ret2libc** [comment]
```
r2 -c "agn title1 body1;agn title2 body2;age title1 title2;agn title3 body3;age title1 title3;agn title4 body4;age title2 title4;age title3 title4;agg" -
```
This is an example of a different layout.

**Comment by ret2libc** [comment]
```
r2 -c "agn title1 body1;agn title2 body2;age title1 title2;agn title3 body3;age title1 title3;agn title4 body4;age title2 title4;age title3 title4;agn title5 b;agn title6 b;age title3 title6;age title4 title5;age title6 title5;agg" -
```
Also this.

**Comment by radare** [comment]
before:
screen shot 2015-07-22 at 22 50 03

after:
screen shot 2015-07-22 at 23 33 35

**Comment by radare** [comment]
What about adding a config var to toggle between those two layouts? both look good depending on the case, not sure which one will be more readable in all situations, and having both is better for testing

**Comment by ret2libc** [comment]
I think it's ok, even if it would make the code a little bit harder to maintain. For some time we can keep both, but I would prefer to keep only one layout before release.

**Comment by jvoisin** [comment]
I prefer the second one

**Comment by radare** [comment]
👍

**Comment by crowell** [comment]
the new one looks great :100:

**Comment by XVilka** [comment]
I like the second too.

**Comment by hteso** [comment]
+1 to the second one

**Comment by radare** [comment]
I prefer the first one because is smaller and lines are easier to follow (less corners in edges), also, the second layout is problematic when graphs are big because it doesnt centers it properly. Just add a graph.newlayout or something like this var and i'll merge

**Comment by ret2libc** [comment]
I don't think it's just a matter of number of corners in edges. We are used to IDA graphs and they also have this kind of corners. It makes the comprehension easier because it puts the parent node in a central position compared to the children. Moreover, if a function has a code that is not "symmetric" you can't have a perfect graph that is centered (of course we can improve a lot the current layout to avoid having graph too large)

Anyway, I will add the var for the moment, but I'd really like to remove it asap. I don't want to have two different layouts to maintain, debug, issues, etc. We should have one layout that works well for most of the functions. We will evaluate later ;)

**Comment by radare** [comment]
im not used to IDA graphs because i really detest its user interface and licensing rules, and the few times i used IDA graphs i find them really useless mainly because moving nodes doesnt realign edges, it can’t be managed by the keyboard, etc. i hate having to scroll to understand something.

So i’m talking from my experience with graphs to correlate information used in forensic tools. Where it is important to have it compact layouts for readability, where a single execution path can be followed linearly.

there’s already a var to specify two different layouts in branch lines in disasm too, so it doesnt hurts to me to have this. i prefer a compact layout :P

**Comment by ret2libc** [comment]
We can have more compact graphs by reducing the distance between nodes like this:
distance jpg
old

The thing in this PR is that I think it's easier to understand having all parent nodes as close as possible to their children. You shouldn't have one child very close and another one far.

(btw, do you think it's better this reduced distance between nodes?)

**Comment by radare** [comment]
yep that looks better!

**Pull request closed without merging**
