### PR TITLE
Speedup nearest flag lookup by using skiplist.

### PR DESCRIPTION
**Pull request by karliss**
I measured the change in time for open + "aa" on the content of my /usr/bin/[a-f]* . Time for most of the executables taking more than 0.5s improved or didn't become worse.

[times.csv.txt](https://github.com/radare/radare2/files/1136856/times.csv.txt)
plot

### CODE REVIEW

**Comment by radare** [comment]
on windows linkage fails:

```
libr/search -L/c/projects/radare2-shvdd/libr/cons -lr_util -lr_reg -lr_syscall -lr_search -lr_cons    /c/projects/radare2-shvdd/libr/..//shlr/java/libr_java.lib     /c/projects/radare2-shvdd/libr/../shlr/capstone/libcapstone.a  -L/c/projects/radare2-shvdd/libr/util -L/c/projects/radare2-shvdd/libr/reg -L/c/projects/radare2-shvdd/libr/syscall -L/c/projects/radare2-shvdd/libr/search -L/c/projects/radare2-shvdd/libr/cons -lr_util -lr_reg -lr_syscall -lr_search -lr_cons    /c/projects/radare2-shvdd/libr/..//shlr/java/libr_java.lib  "
sign.o: In function `getRealRef':
c:\projects\radare2-shvdd\libr\anal/sign.c:15: undefined reference to `r_flag_get_list'
collect2.exe: error: ld returned 1 exit status
make[3]: *** [libr_anal.dll] Error 1
make[3]: Leaving directory `/c/projects/radare2-shvdd/libr/anal'
make[2]: *** [anal] Error 2
make[2]: Leaving directory `/c/projects/radare2-shvdd/libr'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/c/projects/radare2-shvdd/libr'

```

**Comment by radare** [comment]
looks good for linux/mac, but windows build is broken can you pls fix that?

**Comment by karliss** [comment]
I am already working on it.

**Comment by karliss** [comment]
Link dependency structure before last commit.
dep

**Comment by radare** [comment]
In order to avoid this dependency you can just extend the RFlagBind structure

**Comment by radare** [comment]
ping

**Comment by karliss** [comment]
I will setup a windows dev environment later today so that i can test it without spamming CI. 

What is the point of hiding explicit module dependencies using function pointers? There is already tool for assigning function pointers between modules, it is called linker. The dependency is already there. r_anal seems to be using r_flag extensively. Why not link it properly?

**Comment by radare** [comment]
> On 11 Jul 2017, at 08:46, karliss <notifications@github.com> wrote:
> 
> I will setup a windows dev environment later today so that i can test it without spamming CI.
> 
no need for that. we are late in releae already

> What is the point of hiding explicit module dependencies using function pointers? There is already tool for assigning function pointers between modules, it is called linker. The dependency is already there. r_anal seems to be using r_flag extensively. Why not link it properly?
> 
> 
the point is to avoid an extra dependency lib. yes this is done via the bind functions, core is in charge of calling that, no the dependency is not there because it uses rflagbind, so theres no need to depend on rflag

**Comment by radare** [comment]
also, its not clear to me why replacing a hashtable with a skiplist is gonna make it faster because hashtables are O(1) and skilplists are Log(n), moving for 1.7 for proper review

**Comment by karliss** [comment]
If used as dictionary skiplist doesn't automatically help but it allows more interesting queries. In this case the trick was in `r_flag_get_at` which  iterates through all the flags to find one closest to specified address. For skiplists it's the same as regular operations.  I haven't looked for it yet but I wouldn't be suprised to find could which would benefit from fast iteration over flags in  address range.

In addition the old code for offset->flag hasmap used strings of length log(n) as keys.

Feel free to review carefully. It would be easy to make difficult to notice bugs by not reporting some of the flags.

**Comment by radare** [comment]
yeah there are several places to optimize r2, this was one of them :)

i’ll check as soon as I can, busy with release now

**Comment by radare** [comment]
I can confirm the performance boost. for example, disassembling 6000 DEX instructions now takes 1.85s instead of 2.3s. And flags are built before anal, so its not that tragic to add this dependency.

**Comment by radare** [comment]
Thanks! and sorry for the delay. I was busy and didnt had much time to review

**Pull request merged**
