### PR TITLE
MIPS esil small fixes, this will unbreak esil/mips regressions

### PR DESCRIPTION
**Pull request by mrmacete**
+ fixed "sub" operands order
+ fixed "add" typo (was implemented using "-" instead of "+")

### CODE REVIEW

**Comment by radare** [comment]
i dont think this is correct.

sub v0, v1, v2 must be `v1,v2,-,v0,=` and your patch is removing sub and swaping the order of the parametrs. see also the example wtih `ae 1,4,-` (will must return 3 instead of -3)

**Comment by mrmacete** [comment]
yeah but... as far as i understand `sub v0, v1, v2` means, in pseudo-C, `v0 = v1 - v2`, therefore, if `ae 1,4,-` correctly computes to `3` the correct esil for the above is `v2,v1,-,v0,=` what am i missing?

**Comment by mrmacete** [comment]
oh, and actually it isn't removing sub, it's just collapsing in the same implementation of "SUBU" which is correct, apart from the overflow trap which is still missing

**Comment by radare** [comment]
omg thats right http://web.cse.ohio-state.edu/~crawfis/cse675-02/Slides/MIPS%20Instruction%20Set.pdf

**Comment by radare** [comment]
nooooeeeees . this is not right. i have verified it with the MARS emulator. 

`sub t0, t1, t2` is `t0=t1-t2` aka `t2,t1,-,t0,=`. so your fixes are wrong. please send PR reverting the behaviour and fixing the tests.

You can also verify this with qemu. the documentation is confusing because it swaps the bits

**Comment by radare** [comment]
see https://github.com/radare/radare2/pull/4918

**Comment by radare** [comment]
you can also test http://rivoire.cs.sonoma.edu/cs351/wemips/

**Comment by mrmacete** [comment]
sorry, i'm puzzled: my fix is exactly doing`t2,t1,-,t0,=`

**Comment by radare** [comment]
try it yourself 

http://rivoire.cs.sonoma.edu/cs351/wemips/

**Comment by radare** [comment]
nope. your change was doing t1,t2,-,t0,= ... it was right before..

**Comment by mrmacete** [comment]
maybe you're looking at the "add", because the "sub" is:

```
case MIPS_INS_FSUB:
	case MIPS_INS_SUB:
	case MIPS_INS_SUBU:
	case MIPS_INS_DSUB:
	case MIPS_INS_DSUBU:
		PROTECT_ZERO () {
			r_strbuf_appendf(&op->esil, "%s,%s,-,%s,=",
				ARG (2), ARG (1), ARG (0));
		}
		break;
```

**Comment by radare** [comment]
uhm nvm :)

**Pull request merged**
