### PR TITLE
core/config: rename var to enable/disable breakpoint mark before disasm

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by radare** [comment]
this var hides the '*' from the cursor, not just the breakpoint, maybe another name would be better

**Comment by radare** [comment]
what about asm.bpcur?

**Comment by ret2libc** [comment]
I actually like asm.indicators more, but also asm.bpcur is ok.

**Comment by radare** [comment]
Asm.marks ?

**Comment by radare** [comment]
Also. Which other marks do you think matters to add? Trace information?

**Comment by ret2libc** [comment]
asm.marks is good! 
Well, I think it can be used to mark the EIP in case we don't want to use "rip:" but just a "=>".
Also, it can be used to mark the start/end of a region of the file that you want to search (like when you use / and search.from/search.to).

**Pull request closed without merging**
