### PR TITLE
bye viz.js, hello joint.js

### PR DESCRIPTION
**Pull request by pwntester**
Now graph is draggable and render should be faster
Also added minimap

### CODE REVIEW

**Comment by crowell** [comment]
hm... I don't see any arrows, cant tell the difference between blocks too. image

**Comment by crowell** [comment]
also, minimap is in the wrong place in chrome, is in the top right in firefox, but top left in chrome.

**Comment by pwntester** [comment]
Thanks for taking a look at it. I have no idea what can be wrong since it works on FF and Chrome on my machine. Do you get any errors inthe JS console?
Can you try setting the alt background color to something lighter than background_color?
ec gui.alt_background rgb:c0c0c0

**Comment by pwntester** [comment]
Added position persistance and the posibility to mark BBs in red (clicking the BB header)

**Comment by pwntester** [comment]
I wont add zoom, since the SVG can be easily escaled but the HTML on top of it not.

**Comment by crowell** [comment]
I think it was mostly I felt lost with the colors like they were.  I think that the default background should probably be changed to c0c0c0 or something :-)

**Comment by pwntester** [comment]
Cool, so is it working ok for you on botth FF and Chrome?

It should look something like this: http://i.imgur.com/amcZGQu.png

**Comment by crowell** [comment]
yep, looking good :+1:

**Comment by pwntester** [comment]
there is a bug in the ansi to rgb function. `ec` shows alt_background is gray by default, but `ecj` shows [0,0,0]. Will fix and add on this same PR

**Comment by radare** [comment]
will wait for that change to merge.

Thanks!

sorry for late review, im very busy irl lately. will be back soon :)

**Comment by pwntester** [comment]
It turned out that there is no bug in the unrgb function, actually, plain ansi colors are incorrectly mapped. For example in the default palette, `other`, `input` and `mov` are set to `Color_WHITE` in `pal.c` however they are displayed gray in `ec` and `ecj` returns `(127,127,127)` which is a shade of gray. It seems there is no gray in the plain ansi palette, so I guess this is ok.

**Comment by crowell** [comment]
adding comments seems broken on the new graph view.

On Wed, Jan 7, 2015 at 12:33 PM, Alvaro <notifications@github.com> wrote:

> It turned out that there is no bug in the unrgb function, actually, plain
> ansi colors are incorrectly mapped. For example in the default palette,
> other, input and mov are set to Color_WHITE in pal.c however they are
> displayed gray in ec and ecj returns (127,127,127) which is a shade of
> gray. It seems there is no gray in the plain ansi palette, so I guess this
> is ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/pull/1939#issuecomment-69058457>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by pwntester** [comment]
Thanks for the testing. hmm, its working for me in both enyo and panel views using context menu and shorttcut. Can you give me more details on how to reproduce it?

**Comment by crowell** [comment]
closed and reopened r2, things are working again...

**Comment by crowell** [comment]
The issue seems to be in some functions where the basic blocks are not connected with arrows, i'll find one in my /bin/ls and share it

**Comment by crowell** [comment]
look at https://paste.kde.org/pmtmsqrqt/0jifhr/raw
go to `0x466` all of the basic blocks are drawn on top of each other.

**Comment by pwntester** [comment]
Fixed! ;) the problem was that r2 sends edges with no end and joint.js chokes on them. Im adding an empty vertex as graphviz does showing the address. these offsets normally land in the middle of a BB with a JMP xref. r2 should split the BB there

**Comment by crowell** [comment]
looks great now!

the bb issue is related to this one #1904

**Comment by radare** [comment]
The small view should be attached to top right/bottom or so. also i think that a mixed view of graph + disasm would be great, we can do that using the two panel mode. also clicking on the offset address doesnt seeks there (onlly if its an argument from a call or so). 

i had a glitch in the first run, but im not able to reproduce it again. it looks better now, so im pushing it. 

thanks!

**Pull request closed without merging**
