### PR TITLE
Align fcn name cmts

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
Can u fix all the broken tests to make travis green again?

**Comment by kazarmy** [comment]
Yes. Fixed the test in commit radare/radare2-regressions@a3ef1b9fd6c01122bedd257ccb64dda80f46f720 of radare/radare2-regressions#825.

**Comment by radare** [comment]
Nope there are more tests broken in master because of your prs.

**Comment by radare** [comment]
nvm :D i jus tchkd last travis. the pending test is urelted 

thanks!

**Pull request merged**
