### PR TITLE
fix libr/parse/code.c variable type.

### PR DESCRIPTION
**Pull request by SajjadPourali**

### CODE REVIEW

**Comment by radare** [comment]
This is wrong

**Comment by SajjadPourali** [comment]
please check these lines :
shlr/tcc/tccgen.c:202: int tcc_sym_push(char* typename, int typesize, int meta)
libr/parse/code.c:36: const char *typename = k;
libr/parse/code.c:49: char *subtype = sdb_get (anal->sdb_types, query, 0);
libr/parse/code.c:64: tcc_sym_push (subtype, 0, btype);
libr/parse/code.c:71: tcc_sym_push(typename, typesize, btype);
```
code.c:71:16: warning: passing 'const char *' to parameter of type 'char *'
      discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                tcc_sym_push(typename, typesize, btype);
                             ^~~~~~~~
/Users/sajjad/Desktop/radare/libr/..//shlr/tcc/tccgen.c:202:24: note: passing
      argument to parameter 'typename' here
int tcc_sym_push(char* typename, int typesize, int meta)

```

**Comment by SajjadPourali** [comment]
or it is possible converting all `char *` to `const char *` in this section.
```
diff -ur radare2/libr/parse/code.c radare/libr/parse/code.c
--- radare2/libr/parse/code.c	2017-06-08 16:11:04.000000000 +0430
+++ radare/libr/parse/code.c	2017-06-10 10:58:46.000000000 +0430
@@ -46,7 +46,7 @@
 					break;
 				}
 				query = sdb_fmt (-1, "struct.%s.%s", k, name);
-				char *subtype = sdb_get (anal->sdb_types, query, 0);
+				const char *subtype = (const char*) sdb_get (anal->sdb_types, query, 0);
 				if (!subtype) {
 					break;
 				}
@@ -63,7 +63,7 @@
 					btype = sdb_num_get (anal->sdb_types, query, 0);
 					tcc_sym_push (subtype, 0, btype);
 				}
-				free (subtype);
+				free ((char *)subtype);
 				ptr = next;
 			} while (next);
 			free (members);
diff -ur radare2/shlr/tcc/tccgen.c radare/shlr/tcc/tccgen.c
--- radare2/shlr/tcc/tccgen.c	2017-06-08 16:11:04.000000000 +0430
+++ radare/shlr/tcc/tccgen.c	2017-06-10 10:58:18.000000000 +0430
@@ -199,7 +199,7 @@
 
 // TODO: Add better way to store the meta information
 // about the pushed type
-int tcc_sym_push(char* typename, int typesize, int meta)
+int tcc_sym_push(const char* typename, int typesize, int meta)
 {
 	CType *new_type;
```

**Comment by radare** [comment]
You cant cast a restricted type to an unrestricted one. The warning must be fixed but hiding it with a cast is just asking for trouble

**Pull request closed without merging**
