### PR TITLE
Menu

### PR DESCRIPTION
**Pull request by alvarofe**
Added plugins into menu though there is room for improvement since i show all of them instead to categorize into anal,asm....

### CODE REVIEW

**Comment by radare** [comment]
You must get this list from plugins.def.cfg. Also plugins are tristate: static, shared or not compiled at all

**Comment by alvarofe** [comment]
I got all the plugin from there i created other file instead to parse the plugin.def.cfg. Basically the user choose which plugin want to be static (then i dump those plugin into plugin.cfg inside STATIC=""), the remaining is offer as shared (dump those plugin into plugin.cfg inside SHARED="") and those that neither static nor shared is not compiled. Maybe dialog offer a list with different states and get all of them at once

**Comment by radare** [comment]
dont create files that need to be maintained twice.. it is better to just parse the def.cfg everytime you want to get the list of plugins

**Comment by radare** [comment]
Fixed and merged

**Pull request closed without merging**
