### PR TITLE
some small changes in objc parser

### PR DESCRIPTION
**Pull request by inisider**
- add R_API for public function
- remove usage of strcpy

### CODE REVIEW

**Comment by ret2libc** [comment]
What's the advantage of using strncpy instead of strcpy in that case?

**Comment by radare** [comment]
Many analysis frameworks report strcpy as a vuln. So its always better to keep away from it. Didnt looked that specific case

**Comment by ret2libc** [comment]
Len should be the length of the destination operand not the strlen of the source IMO. Also in this case the dest has already a size of srclen +1 so I don't see the point of strncpy + zeroing last char

**Comment by alvarofe** [comment]
it should be strlen from the destination buffer not the source. `strncpy  (dst, src, strlen (dst) -1)`. It's a good practice zeroed the last characters to avoid future issues, since all the c-string function read until '\0' is found and this issue has caused oob in the past. However I've not read the code and perhaps is not necessary in this case

**Comment by radare** [comment]
@ret2libc wtf, strlen with strncpy is totally wrong. this patch is not correct. please @inisider fix that thing :)

**Comment by inisider** [comment]
@radare what is wrong?

**Comment by ret2libc** [comment]
@inisider I think in this case strncpy doesn't really improve over strcpy. Moreover, you can just use strdup instead of the strlen + malloc + strcpy/memcpy.

**Comment by inisider** [comment]
@ret2libc ty.

**Comment by radare** [comment]
lgtm

**Pull request closed without merging**
