### PR TITLE
Web-UI Types panel

### PR DESCRIPTION
**Pull request by monokles**
image

Adds a types panel to the web UI that allows you to view and add/remove types

Some notes:
-Underlying 't' command has some quirks that might result in odd behaviour* with funcs or enums
-Can't load from header files through JS because of browser sandboxing (won't resolve actual file path), a possible workaround would be to create our own file browser through ajax/r2

*e.g. "t- <structname>" removes entire struct but "t- <enum>" or "t- <func>" only remove the "<name>=<func/enum>" entry in sdb and not their child variables.

### CODE REVIEW

**Comment by radare** [comment]
We should probably implement some JSON `t` subcommands in order to implement the web interface without having to parse text.

**Comment by jvoisin** [comment]
This looks _fucking_ awesome!

**Comment by radare** [comment]
also, to avoid input problems maybe we need a command under `t` to accept a base64 encoded string as argument

**Comment by radare** [comment]
i can merge this after some testing, but i would like `t` to have such features to make it more interactable from r2pipe and the web

**Comment by radare** [comment]
I have merged those commits, please rework again from master in order to support this.

also the '[-]' buttons are too far from the type that its hard to say which entry it will remove, and a title="" can be useful to understand what is going to do.

**Comment by pwntester** [comment]
Really cool, thanks!

**Pull request closed without merging**
