### PR TITLE
 Handle Zero Length Hashes #2784 and  rahash2 escape chars in -E #2783

### PR DESCRIPTION
**Pull request by jjdredd**
Handle Zero Length Hashes #2784 and rahash2 escape chars in -E #2783

### CODE REVIEW

**Comment by radare** [comment]
Why in -E? Wasnt suposed to be  in -s?

**Comment by jjdredd** [comment]
how do you make difference between raw strings and escaped?
`echo` has an option for both (`-e`)

**Comment by jjdredd** [comment]
ok we have time to think about this later

**Comment by jjdredd** [comment]
sorry I definetely need a break, will fix later

**Comment by radare** [comment]
Not sure if we want to differenciate this..

**Comment by radare** [comment]
You need a fix, so go break later

**Pull request closed without merging**
