### PR TITLE
Add ELF Identification fields to elf64 pfo

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by kazarmy** [comment]
Based on ELF64 header info at https://docs.oracle.com/cd/E19683-01/816-1386/6m7qcoblh/index.html.

**Comment by Maijin** [comment]
don't forget to update the hardcoded -nn values too https://github.com/radare/radare2/blob/master/libr/bin/format/elf/elf.c#L144 etc.

**Comment by kazarmy** [comment]
ok will do in next pr

**Comment by radare** [comment]
-nn must die

**Comment by kazarmy** [comment]
> don't forget to update the hardcoded -nn values too https://github.com/radare/radare2/blob/master/libr/bin/format/elf/elf.c#L144 etc.

well I'm not sure what -nn does but running the code above isn't one of them

**Comment by kazarmy** [comment]
oh i see -nn calls rabin2

**Pull request merged**
