### PR TITLE
Add ELF Identification fields to elf32 pfo

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by kazarmy** [comment]
Based on ELF spec at http://refspecs.linuxbase.org/elf/elf.pdf.

**Comment by radare** [comment]
i added support for .h files in this directory. maybe those are more readable. but yeah thats the way to go :) i have a pad where i described all the ideas i have related about header parsing and types, structs... if you are in the mood i can share it with you and we can discuss some plans for 3.5

**Comment by kazarmy** [comment]
is it this one? https://hackmd.io/3IvnIkxfSM6WNyeYLbESrA

**Comment by radare** [comment]
yup

**Pull request merged**
