### PR TITLE
 Handle Zero Length Hashes #2784

### PR DESCRIPTION
**Pull request by jjdredd**

### CODE REVIEW

**Comment by alvarofe** [comment]
Appveyor is green o_O

**Comment by jjdredd** [comment]
@alvarofe yeah, but is it fixed or is it "fixed"?

**Comment by jjdredd** [comment]
lol, what happened?

**Comment by alvarofe** [comment]
It was so wonderful to be real jeje

**Comment by radare** [comment]
we should take care of appveyor some day :p

**Comment by jjdredd** [comment]
hm, I need to fix this.

**Pull request closed without merging**
