### PR TITLE
rax2 fix overflow

### PR DESCRIPTION
**Pull request by kriw**
I realized malloc size is not enough.

### CODE REVIEW

**Comment by radare** [comment]
can you please add tests for the testuite?

**Comment by radare** [comment]
also, i think this code should work fine with RPrint = NULL; so you dont need to create an instance of it and safe some lines

**Comment by kriw** [comment]
r_print_hex_from_bin (p, str) uses p->cb_printf(...), so I think it needs to create an instance.
If NULL is passed instead of an instance of RPrint, it cause Segmentation fault.

**Comment by radare** [comment]
I thibk other functions in rprint use printf when the rprint instance is null

**Comment by kriw** [comment]
I have fixed, but I could not see the other functions use printf when rprint instance is null.
The others does return early if the instance is null. Should it also be fixed?

**Comment by radare** [comment]
Hexdump works without rprint or at least it should. I think its a nice api to be used without having to instantiate anything so i would go for yes. Unless that creates lot of unnecessary boilerplate

**Pull request merged**
