### PR TITLE
Don't display fd output for unselected flagspaces.

### PR DESCRIPTION
**Pull request by sapir**

### CODE REVIEW

**Comment by radare** [comment]
This patch is not correct, because the `r_flag_get_at` will always return 1 flag, if there's more than one flag in the same offset it will not show any flag in `fd`. See this test:

```
NAME='no flags'
CMDS='fs jeje
f hidden
fs jojo
f visible
fd
f
'
EXPECT='visible
0x00000000 1 visible
'
run_test
```

**Comment by radare** [comment]
ping

**Comment by sapir** [comment]
pong, sorry
should I add a 'space' parameter to r_flag_get_at?

**Comment by radare** [comment]
selected space is already in RFlag, the problem is that we should just iterate and get the ones that are in this flagspace instead of stopping at first offset in case the flag matches

**Comment by radare** [comment]
This commit looks better, but this conditional should only happend from `fd`. Otherwise the output of `pd` and any other command using the flags api will not show them.

Maybe we can add a new field in the RFlag struct to specify if this mode is set or not maybe name it `(bool space_strict)`? This var must be set before doing the `fd` and unset after it.

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
I just finished the change and pushed in master. 

Thanks!

**Pull request closed without merging**
