### PR TITLE
Fix 12474

### PR DESCRIPTION
**Pull request by AdamVanScyoc**
This doesn't appear to be failling any of the rabin2 tests in the radare2 regressions test suite, but I apologize if there are any issues that I missed.

### CODE REVIEW

**Comment by radare** [comment]
screenshot 2019-01-05 at 00 00 22

**Comment by radare** [comment]
Why closed?

**Comment by AdamVanScyoc** [comment]
I deleted this branch in an attempt to start from scratch and fix the failing tests. Still working on it.

Do the tests that are failing normally get run as part of the radare2-regressions? I having trouble replicating them.

**Comment by Maijin** [comment]
rebase and relaunch test but the test on the screenshot here^ were part of your branch/PR.

**Comment by AdamVanScyoc** [comment]
This is going to take me a little while to figure out as school is starting back up. This issue is not blocking anything, is it?

**Pull request closed without merging**
