### PR TITLE
Fix fcnlines on flags on the same offset as fcns

### LINKED ISSUE #10708: Don't show function lines over flag names outside of the function
See from the merged PR from @Vane11ope - lines with flags like `; --main`, `; --section_end..text`, etc are covered with function lines, but in fact, they should not - they are not exactly a part of the function and also
ruins the beauty of function lines:
image

### PR DESCRIPTION
**Pull request by cyanpencil**
Fix #10708 

Also a bit of refactoring and removing unused code inside disasm.c

### CODE REVIEW

**Comment by cyanpencil** [comment]
There are some broken tests like this:
```
-|           ;-- main:
-|           ;-- $a:
+            ;-- main:
+            ;-- $a:
 / (fcn) sym.main 44
 |           ; var int local_ch @ fp-0xc
 |           ; var int local_8h @ fp-0x8
```
will fix them tonight/tomorrow morning

**Comment by radare** [comment]
but i think it looks better this way (without moving the flags)

**Comment by cyanpencil** [comment]
Ok, added r2r pr: https://github.com/radare/radare2-regressions/pull/1470

> also, what do you think about changing the way flags are showed in disasm. instead of having ; — just use name : like normal asm labels

Could be an idea, I must say that I am now used to the ;-- notation, but maybe using : is better, makes them easier to distinguish from normal comments, especially for beginners. If you want I'll open an issue about this, for discussing it better with the community, with the [question] tag

**Comment by radare** [comment]
Yep sgtm

**Pull request merged**
