### PR TITLE
Fix some issues related to comments alignment ##disasm

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
im short in time, maybe @kazarmy or @GustavoLCR can have a look at this pr. i think the only issue to fix is just an extra space before the ';' in some situations.

after:

Screenshot 2019-06-19 at 14 57 02
Screenshot 2019-06-19 at 14 57 20

before:

Screenshot 2019-06-19 at 14 58 32
Screenshot 2019-06-19 at 14 58 52

**Comment by kazarmy** [comment]
Why is this better? Aren't the comments using more vertical space?

**Comment by radare** [comment]
Cause now MOV comments and others are aligned properly instead to be aligned to the left. The only thing is that short comments were stacked in one line and now they are using multiple lines, whichis somewhat more readable imho, if you are on a small terminal and u set asm.cmt.right=0 it looks better than before too

**Comment by radare** [comment]
this looks like wrongly aligned

```
[31m[XX][39m db/formats/elf/symbols [33mspecial ARM symbols with dot[39m  102

$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i /tmp/tmp-16361uiT1i6Tpqotp ../bins/elf/special-sym-with-dot.bin
pd 5 @ 0x464

             ;-- main:
             0x00000464      80b5           push {r7, lr}
             0x00000466      6f46           mov r7, sp
             0x00000468      82b0           sub sp, 8
             0x0000046a      69ec1623       stcl p3, c2, [sb], -0x58
[35m-            0x0000046e      0548           ldr r0, [0x00000484]        ; [0x484:4]=28 ; 1156[39m
[35m[39m[32m+            0x0000046e      0548           ldr r0, [0x00000484]; [0x484:4]=28 ; 1156[39m
[32m[39m
```

**Comment by kazarmy** [comment]
should be fixed by 2b738f5104b69896dffebc1266a6a8cfbf0f6010

**Comment by radare** [comment]
I think the current 26 XX should be updated, did you looked at them? thanks!

**Comment by kazarmy** [comment]
Yes.
blank_line_before
Don't think that blank line was intended.

**Comment by radare** [comment]
right, not ready to merge

**Comment by radare** [comment]
21 XX now

**Comment by radare** [comment]
and all those 21 XX look good to me now :)) any complain? i will update the tests and merge this after dinner if everyone is fine with this change.

thanks for this tedious work!

**Comment by radare** [comment]
its also improving pds output when more than one comment is in the line btw

**Comment by kazarmy** [comment]
> thanks for this tedious work!

nah it was fun ... sorry not much time to hunt down everything

**Comment by radare** [comment]
Yeah i fixed 2 more issues after merging and im fighting this pdJ one still

**Pull request merged**
