### PR TITLE
A panel will be allocated for each help msg when it is called ##panels

### PR DESCRIPTION
**Pull request by Vane11ope**
I personally love this feature. 

people, including me, can use panels mode with the help msg being active all the time if they call it, and they can of course kill it anytime like any other panel.

### CODE REVIEW

**Comment by radare** [comment]
wheres's the gif? :D

**Comment by XVilka** [comment]
Better a WebP, since it is supported everywhere now, and without 256 colors
restriction.

**Comment by radare** [comment]
Or mp4, wat...webp is now in mozilla too?

**Comment by XVilka** [comment]
Yes

**Pull request merged**
