### PR TITLE
support arbitrary number of matches in cons/less, refactor (resolved merge conflict)

### PR DESCRIPTION
**Pull request by jjdredd**

### CODE REVIEW

**Comment by jjdredd** [comment]
guiz, travis is ill

**Comment by Maijin** [comment]
@jjdredd just slow

**Comment by jjdredd** [comment]
there's definitely something wrong with him
>  ran for 1 hr 14 min 58 sec

https://travis-ci.org/radare/radare2/builds/65256508

**Comment by jjdredd** [comment]
lol, looks like this has been going on for a month at least, never noticed

**Comment by radare** [comment]
I can't merge thiose commits. please create a new pulreq and put your changes on top in a single commit

**Pull request closed without merging**
