### PR TITLE
ie: set hvaddr of elf entry0 to baddr + 0x18

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
whats the point on having hvaddr and hpaddr? i mean... the haddr was implicitly physical only because headers are not suposed to be mapped in memory when loaded. so they will not have vaddr, and if they do it will be baddr+haddr.

**Comment by kazarmy** [comment]
the motivation for this was the removal of baddr from the `iee` list since it's the same for every `iee` entry ... then i realized that somebody might be using the baddr value to calculate the hvaddr like you mentioned (baddr+haddr) ... even though baddr is available in `iI`, it would be slower to look it up there compared to having it directly in the `iee` output (denormalization argument) ... thus this pr so that i can replace baddr with hvaddr (eventually).

but this does feel like going around in circles ... revert back hpaddr to haddr?

**Comment by radare** [comment]
what about having some kind of Value struct that holds p, v for size and address? i know this is gonna need a lot of changes. but maybe we need a better way to represent this

**Comment by kazarmy** [comment]
> what about having some kind of Value struct that holds p, v for size and address?

hmm, size of what?

anyway, i'm closing this pr since it apparently isn't going anywhere ... i'll revert hvaddr back to haddr for program entries soon

**Pull request closed without merging**
