### PR TITLE
libr/cons: Fix EOT handling

### PR DESCRIPTION
**Pull request by nsajko**

### CODE REVIEW

**Comment by nsajko** [comment]
Are there any test failures that seem related to this change?

**Comment by radare** [comment]
i think this check was to avoid infinite loops when EOF happens

**Comment by radare** [comment]
yeah the XX are unrelated

**Comment by ret2libc** [comment]
I can't really say what are the full implications of this change, but... from testing it seems to work fine and fix the issue I had with `^D`. @radare do you happen to remember when the infinite recursion could happen?

**Comment by nsajko** [comment]
By the way, the removed code was probably always incorrect because it evaluated `errno` without checking that `read` returned -1.

**Comment by ret2libc** [comment]
@radare can we merge this? Do you have concerns? To me, it seems it fixes a bug. 

```
^D still doesn't work though. If you do radare2 /bin/ls,you resize the screen and then you go back to normal mode, if you press CTRL+D it doesn't quit radare2.
```

**Comment by radare** [comment]
Did some tests and seems to work fine

**Pull request merged**
