### PR TITLE
Fix #7008 alignment in Vx

### LINKED ISSUE #7008: Vx read garbage showing invalid
Test file in r2r `bins/pe/appenddata.exe`.

https://asciinema.org/a/694b1w2erjlbm8j9zd35tnvay

You can see how when using Vx is not reading the right content though seeking is correct.

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by xarkes** [comment]
It should fix [this issue](https://github.com/radare/radare2/issues/7008)

**Comment by radare** [comment]
This is on purpose to show some context to the disasm of the refs otherwise its a bit useless at least for my use cases

Which is the problem you are having for this?

**Comment by xarkes** [comment]
This is the output:
[](https://asciinema.org/a/694b1w2erjlbm8j9zd35tnvay)
And this is what should be shown:
[](https://asciinema.org/a/5u2j8dx2skinek0sngypgt1al)
In the first case the shown disassembly is wrong because it is not aligned correctly.

**Comment by alvarofe** [comment]
Merged. Thanks

**Comment by radare** [comment]
Noes! We should this properly instead of removing the delta. We should use so-8 or something like that maybe @o:-8?

**Comment by alvarofe** [comment]
It produces invalid and such since as I talked yesterday with @skuater is not fully perfect. I'd rather see the right offset than just invalids due to alignments.

Using this for example does not work for the case we have in hands.

```
r_core_cmdf (core, "s @ 0x%08"PFMT64x"; so-8", refi->addr);
dis = r_core_cmd_strf (core,  "pd $r-4; 2s-", refi->addr);

```

so what about to fix so-x? visual mode even fails when scrolling upwards with this binary

https://asciinema.org/a/338e7p71ufze1o1o2lov6kfs1

btw `@o:-8`?? from the help

```
@o:fd               temporary switch to another fd
```

did i miss something?

**Comment by Maijin** [comment]
@radare meant `@i:`

**Comment by Maijin** [comment]
We can reopen an issue if necessary but as an easy enhacement

**Comment by alvarofe** [comment]
```
[0x00401000]> pd 1
               ; section 0 va=0x00401000 pa=0x00000200 sz=512 vsz=4096 rwx=m--wx sect_0
            ;-- section.sect_0:
┌ (fcn) entry0 23
│              ; " * appended data."
│           0x00401000      6818104000     push 0x401018
[0x00401000]> pd 4 @i:-8
            0x00400fe0      ff             invalid
            0x00400fe1      ff             invalid
            0x00400fe2      ff             invalid
            0x00400fe3      ff             invalid
```
I would create an issue for to enhance this

**Pull request closed without merging**
