### PR TITLE
Move _section_chk_dup to cbin.c

### PR DESCRIPTION
**Pull request by MaskRay**
The second step to bring 65536sect back

The first is https://github.com/radare/radare2/pull/8344

### CODE REVIEW

**Comment by alvarofe** [comment]
What about instead of sdb use ht or sdbht? At the end is what sdb use underneath but is less overkill imho

**Comment by MaskRay** [comment]
Changed to `ht_new`.

**Comment by condret** [comment]
can we do this check in the bin-api pls, when binsections get created?

**Comment by radare** [comment]
This was the idea of sdbization of rbin. But first fix travis

**Pull request merged**
