### PR TITLE
Add dij command and expose dbg->reason in there

### PR DESCRIPTION
**Pull request by earada**
Issue #2849

### CODE REVIEW

**Comment by radare** [comment]
Dbg reason should be a struct. An int is not enough to represent all the info we need there.

**Comment by earada** [comment]
Which fields are also saved in dbg right now? Could you provide a "dij" output example?

**Comment by radare** [comment]
see https://pad.nopcode.org/p/tLM4P3CsEx <https://pad.nopcode.org/p/tLM4P3CsEx> to follow the discussion on this topic

**Comment by radare** [comment]
murged. i'll work on the rdebugreason struct and json when i have some time. this was fine to put in master

**Pull request closed without merging**
