### PR TITLE
Emulate menu is added ##panels

### PR DESCRIPTION
**Pull request by Vane11ope**
Since it was not that convenient enough for me.

### CODE REVIEW

**Comment by Vane11ope** [comment]
lol i will fix this tonight

**Comment by radare** [comment]
9078
9079       "C:\projects\radare2-shvdd\build\radare2.sln" (default target) (1) ->
9080       "C:\projects\radare2-shvdd\build\libr\core\f105261@@r_core@sta.vcxproj" (default target) (39) ->
9081       (ClCompile target) -> 
9082         c:\projects\radare2-shvdd\libr\core\panels.c(2551): error C2143: syntax error: missing ';' before '.' [C:\projects\radare2-shvdd\build\libr\core\f105261@@r_core@sta.vcxproj]
9083         c:\projects\radare2-shvdd\libr\core\panels.c(2553): error C2224: left of '.S_addr' must have struct/union type [C:\projects\radare2-shvdd\build\libr\core\f105261@@r_core@sta.vcxproj]
9084         c:\projects\radare2-shvdd\libr\core\panels.c(2557): error C2224: left of '.S_addr' must have struct/union type [C:\projects\radare2-shvdd\build\libr\core\f105261@@r_core@sta.vcxproj]
9085
9086    544 Warning(s)
9087    3 Error(s)
9088
9089Time Elapsed 00:07:46.54
9090

**Comment by radare** [comment]
Red for windows

**Comment by Vane11ope** [comment]
yup cool

**Comment by Vane11ope** [comment]
This LGTM red isnt mine btw, it seems

**Comment by XVilka** [comment]
LGTM.

**Pull request merged**
