### PR TITLE
Make jump and call instruction pc relative

### PR DESCRIPTION
**Pull request by Rot127**
The problem was discussed here: https://github.com/radare/radare2/issues/12352

### CODE REVIEW

**Comment by XVilka** [comment]
Do not merge! Since it should be fixed in the script first.

**Comment by radare** [comment]
Which script

**Comment by XVilka** [comment]
It is all autogenerated code.

**Comment by radare** [comment]
Ouch

**Comment by Rot127** [comment]
The script is fixed (https://github.com/radareorg/r2hexagon/pull/1).
Luckily you forced me to update it. My search & replace skills seem to be not that good and I missed some lines.

Besides that:
The script generates different indices in hexagon_disas.c unrelated to this issue. It would be interesting to know if there has been changes to the script after the initial commit of the hexagon plug-in.

**Comment by Rot127** [comment]
Please do not merge! Although the immediates are signed, the jumps won't lead to a previous address. Try to fix it today or tomorrow.

**Comment by XVilka** [comment]
@Rot127 can you please craft a couple tests for Hexagon in https://github.com/radare/radare2-regressions for these jumps/calls?

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
No need for ping, I will merge (and regenerate the files) once it is properly checked. Please don't do it without me, thanks.

**Comment by radare** [comment]
All yours 👍

**Comment by XVilka** [comment]
@Rot127 I noticed there is a difference between actual C files and generated if you run `importer.py`. Please rebase, add more tests and synchronize the generated C files with presented in this pull request.

**Comment by Rot127** [comment]
@Xvilka Sorry, it's the first time I am using git and obviously I need to work more carefully. Thank you for your patience!

**Comment by Rot127** [comment]
Jesus, next time I learn to handle the tools before I do something.

**Comment by XVilka** [comment]
uhh, can you please do a clean rebase and do a force push? shouldn't be hard since there will be no conflicts.

**Comment by Rot127** [comment]
Maybe I should think about to become a lumberjack. Or a baker... Something without git.
Anyway, lets leave it closed and open a new one. Is this fine?

**Comment by XVilka** [comment]
Sure, feel free to close and create as many as you want.

**Comment by XVilka** [comment]
Please don't forget to send pull request first to https://github.com/radareorg/r2hexagon, because python-generated and C files there are different too.

**Pull request closed without merging**
