### PR TITLE
Add codespell script and try to fix spelling everywhere

### PR DESCRIPTION
**Pull request by XVilka**
Added a script to run [codespell](https://github.com/codespell-project/codespell), some r2land dictionary to whitelist some words. Also tried to fix the spelling everywhere. Please be sure that there were no false positives before merging.

### CODE REVIEW

**Comment by XVilka** [comment]
No, I already spotted some false positives. Will update later.

**Comment by radare** [comment]
ok

**Comment by radare** [comment]
pls finish this pr

**Comment by trufae** [comment]
can you finish this pr in < 1 week

**Comment by XVilka** [comment]
I thought about it - it tries to correct too many valid names, codespell should check only comments, but it can't. Lets abandon this one, moving to 9999 milestone, until codespell or any other tool implements proper spellcheck for the code: https://github.com/codespell-project/codespell/issues/1147

**Comment by XVilka** [comment]
Nevermind, lets do it by smaller chunks.

**Pull request merged**
