### PR TITLE
__WALL for waitpid does not exist on OpenBSD (probably same thing wit…

### PR DESCRIPTION
**Pull request by nevun**
…h other BSDs)

Ugly ifdef but better an ugly diff than just complaining it does not compile.

### CODE REVIEW

**Comment by nevun** [comment]
and after this there is procfs_pid_slurp() in debug_native.c which does not exist. The major rewrite turned debug_native.c into a APPLE/LINUX or gtfo ?

**Comment by radare** [comment]
i dont think -_WALL is suposed to be any standard thing at all, so its probably another linuxism introduced by @jduck

what about #if __linux__ and else the WAIT_ANY?

@jduck whats the difference between WAIT_ANY and __WALL?

**Comment by nevun** [comment]
flipping the ifdef would probably be better.. btw macOS also has waitpid (and the WAIT_ANY option)..

Last revision compiling on OpenBSD was revision db8414d1861068ae78e7a21fce20570afcba4b4c﻿ (2016-06-16).

**Comment by trufae** [comment]
yeah confirmed, wall is an ugly linuxism. the thing is that:

WAIT_ANY is -1
__WALL is 0x4000000

so, in theory WAIT_ANY should be enough for all platforms, no need to go for this, because waitpid handles a bitfield here

**Comment by jduck** [comment]
@nevun Thanks for your help on this. I wish your original fix (or a proper inversion of it) had landed instead of this untested crap @radare put in. :-/

I apologize for breaking *bsd but there are no tests and I don't even have a proper test machine for BSD currently. Do you have any interest in helping to make the Linux/OSX debugger tests run on OpenBSD??

**Comment by nevun** [comment]
@jduck I am interested in getting the debugger to work on OpenBSD and I have started to look into it. The problem is not only in radare2 though: on OpenBSD we need this commit first to be able to even fetch the memory map of a process as non-root:
https://marc.info/?l=openbsd-tech&m=146714613725520&w=2

**Comment by radare** [comment]
Bear ij mind that this is a regression.radsre and r2 supported debugging on open, net and free from the very beginning.

**Comment by nevun** [comment]
Yes, and if I comment out some linuxism it actually compiles and I can run a debug session. Will submit a pull-request later.

**Comment by trufae** [comment]
cool! thanks

**Comment by jduck** [comment]
Looking forward to your PR! I'm surprised debugging on OpenBSD is that broken currently hehe. Anyway, even if root is required that's fine.

**Pull request closed without merging**
