### PR TITLE
Add Windows Crypto API types ##anal

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by pelijah** [comment]
What the heck!? r2r hates me.

**Comment by Maijin** [comment]
rebase on top of master maybe?

**Comment by pelijah** [comment]
Already tried.

**Comment by pelijah** [comment]
Meh

**Comment by radare** [comment]
Did you rebased? The travis output seems very wrong

**Comment by pelijah** [comment]
Hooray!

**Pull request merged**
