### PR TITLE
Minor documentation update.

### PR DESCRIPTION
**Pull request by r0nk**
Minor documentation update, telling developers where to go in order to generate static libraries.

### CODE REVIEW

**Comment by radare** [comment]
Also, this is very important and should be explained carefully in the doc/static or DEVELOPERS file which makes static linking something dangerous. (already knew, but always good to remind people about how licenses work)

http://stackoverflow.com/questions/10130143/gpl-lgpl-and-static-linking

**Comment by radare** [comment]
Also this stackoverflow page explains the legal case of using it via r2pipe 

http://stackoverflow.com/questions/1394623/can-i-dynamically-call-a-lgpl-gpl-software-in-my-closed-source-application

**Comment by r0nk** [comment]
Alright, I've modified it a bit more, now it sends people to doc/static, and doc/static goes a bit more in depth. The documentation should probably have a bit more to it, but unfortunately I'm still learning how it works, so I can't really add more to it yet.

**Comment by radare** [comment]
I have pushed some more changes and squashed your commits. it's now in master

thanks

**Comment by radare** [comment]
In short, you can safely dynamically link to the r2 libraries which are licensed under LGPL (see the --without-gpl configure flag to ensure no GPL code is compiled in there), if you link to GPL code, you'll be forced to opensource your program that uses it.

Statically linking a propietary program against LGPL is also problematic in the sense that LGPL will force you to opensource the code that is linked statically against r2 libraries.

The reason of this is to avoid /tivoization/, this is, we are giving the users the freedom to change the version or patch any part of the r2 libraries and therefor upgrade/fix issues that are happening in the closed source program. With static linking that will require much more work.

**Pull request closed without merging**
