### PR TITLE
Hide fcn name if fcn type shown

### PR DESCRIPTION
**Pull request by kazarmy**
Also, `r_anal_type_func_guess` was generating false positives so I reduced its aggressiveness.

### CODE REVIEW

**Comment by kazarmy** [comment]
I've just looked at https://asciinema.org/a/5gk0wfzxih3t4qehfue3qt7yn (from https://twitter.com/Maijin212/status/850033842077528065). Clearly, more work is needed (e.g. more than one guess) so closing for now.

@Maijin Is 6272A9D472DCA823D02B0AC02EFCAE6F the same binary as the one at https://www.hybrid-analysis.com/sample/af21e945735599fb69b08d73928489c9547eb97961730e51713400d653f1519d?environmentId=100?

**Comment by kazarmy** [comment]
Could close forever depending on whether this is a good idea or not.

**Comment by Maijin** [comment]
Yeah that's this one you want it ?

**Comment by kazarmy** [comment]
I want to try downloading it myself first ... thanks!

**Pull request closed without merging**
