### PR TITLE
Allow asm.highlight color change thru ec line_highlight

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
red?

**Comment by kazarmy** [comment]
AppVeyor is green now .. XX on Travis unrelated

**Comment by kazarmy** [comment]
everything's green now :smiley:

**Comment by radare** [comment]
As a comment i would say that this varname looks too long for me. And we should update the themes to use it

**Comment by kazarmy** [comment]
> As a comment i would say that this varname looks too long for me. ...

`wordhl` and `linehl`?

**Comment by radare** [comment]
Yeah

**Pull request merged**
