### PR TITLE
wtf?! i sent refactored code just yesterday and someone got that back? please. 

### PR DESCRIPTION
**Pull request by Vane11ope**
the API isn't even used anywhere else. please. i deleted this just yesterday. seriously.

### CODE REVIEW

**Comment by radare** [comment]
Wtf? Nobody toyched this except you

**Comment by Vane11ope** [comment]
no. see commit log

**Comment by Vane11ope** [comment]
https://github.com/Vane11ope/radare2/commit/16d72de010fde7488e2f8c736c55e284ad4b07f0#diff-d2539ef3ef5e298a85c83ca0047b18e8

here you go

**Comment by Vane11ope** [comment]
seems so and sorry i was kinda offensive. it happens. anyway this can be merged and i wanna move on

**Pull request merged**
