### PR TITLE
Fix 32bit->64bit zero extension upon MOV (x86_64)

### PR DESCRIPTION
**Pull request by XVilka**
Remove converting EAX to RAX in getarg, and do that instead in a MOV command itself

### CODE REVIEW

**Comment by radare** [comment]
show me your tests

**Comment by Maijin** [comment]
image
image

**Comment by radare** [comment]
this hackaround should be fixed in capstone i guess

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
Well, may be.

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
can we close this?

**Comment by XVilka** [comment]
Yes, I'll open a bug instead.

**Pull request closed without merging**
