### PR TITLE
Wide crc hashes

### PR DESCRIPTION
**Pull request by vertur**
- Added support for 64-bit CRC hashing (explicit typing removed).
- Added more CRC hashing presets (partially disabled due to low space in algo bitset).
- Fixed issues with mismatched types (int vs ut32 vs ut64) in hashing routines.

### CODE REVIEW

**Comment by radare** [comment]
Im afraid to introduce over 9000 variants of the same checksums just with different names,, maybe we should support 2 level of specifications to select algo and variant

**Comment by vertur** [comment]
That is nice idea, but it requires reworking hashing API.
To reduce the active number of presets (and checksums) I use conditional inclusion of presets. Probably I need disable (or temporary cut) all R_HAVE_CRCXX_EXTRA except CRC15, because my primary goal was to have CRC64.

**Comment by radare** [comment]
ok, i'll merge this and then refactor the r_hash api to have TYPE and SUBTYPE specifications.

**Comment by radare** [comment]
Would you like to contribute on that? https://github.com/radare/radare2/issues/9148

i filled the issue so we can discuss the design changes to achieve this.

thanks!

**Pull request merged**
