### PR TITLE
convert negative fp numbers to hex

### PR DESCRIPTION
**Pull request by glslang**
Simple change to allow for negative floating point numbers in rax2. An example is rax2 -121.875f to return Fxc2f3c000.

### CODE REVIEW

**Comment by radare** [comment]
Can you make a pullreq in the regressions repo with some tests for this new behaviour? Thanks!

**Comment by glslang** [comment]
Many thanks for the comments. I'm using the vimrc in the doc folder so hopefully the indent is better although I didn't find an exact example in the source code for the case break when an open curly brace exists. 

I didn't add the preprocessing above because sizeof cannot be used by the preprocessor and there isn't an assert at compile time in a header immediately usable by rax2.

**Comment by radare** [comment]
This can be done with an static assert, which can be done in c++ with templates. And in c you can trick the compiler to prouce invalid expressions that fail at compile time.

For example:

Void foo[sizeof(float)==4?0:-1];

Another option would be to memcpy the float into an ut32 to ensure those limits

**Comment by glslang** [comment]
added the usual switch trick to prevent warnings of unused variables and so on.

**Comment by radare** [comment]
Maybe we can expose this switch trick in r_util.h or r_types.h under R_STATIC_ASSERT or so? It can be useful in other places too

**Comment by glslang** [comment]
Added to r_util.

**Comment by radare** [comment]
Thanks! looks good now

**Pull request closed without merging**
