### PR TITLE
WIP: travis ptrace

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by radare** [comment]
RM LOVE

**Comment by ret2libc** [comment]
there are many errors... sometimes it's not able to open the binary for debugging :/ but it definitely seems travis supports ptrace!! yeahh

**Comment by radare** [comment]
ptrace all the things!!11

**Comment by Maijin** [comment]
What was the fix ?

**Comment by ret2libc** [comment]
Maijin, there was no fix. It seems to just work.
But there is some work to do because some binaries/tests seem to work, others instead fail because radare2 says it cannot open those files for writing :/

I have no time to investigate soon, though. So i'm currently closing this.

**Pull request closed without merging**
