### PR TITLE
Add spp to r2 for rasm2 [FIX #6103]

### LINKED ISSUE #6103: Add .include directive for rasm2

### PR DESCRIPTION
**Pull request by Svenito**
File input for rasm2 is passed through spp to support .include directives. #6103

* Add spp project to shlr folder
* Adds sync rule to shlr Makefile
* Pass slurped file data through spp before parsing with rasm
* Update utils Makefile to link in spp

### CODE REVIEW

**Comment by radare** [comment]
I have merged the prs of spp, do u need to update the pr after that?

**Comment by Svenito** [comment]
The r2 pr was waiting for the SPP PR. In theory all should be good to go
now. I built rasm against the master of SPP.

**Comment by radare** [comment]
build is broken ../../shlr/spp/spp.c:4:20: fatal error: config.h: No such file or directory

travis is unhappy

**Comment by Svenito** [comment]
Will buy Travis a beer and try to make him happy again

**Comment by radare** [comment]
pls fix asap

**Comment by Maijin** [comment]
@Svenito you will have to pay one for appveyor too, this breaks windows build

**Comment by Svenito** [comment]
Understood. Should get time tonight

**Comment by radare** [comment]
linux builds doesnt finish and osx one have 3 broken tests. https://s3.amazonaws.com/archive.travis-ci.org/jobs/184846953/log.txt

can you squash the commits and rebase them on top of master?

**Pull request merged**
