### PR TITLE
Fixing assembly of inc/dec

### PR DESCRIPTION
**Pull request by PaoloMonti42**
Working on a final fix that makes the assembler work for all cases.

### CODE REVIEW

**Comment by PaoloMonti42** [comment]
First commit should fix an issue of the parsing function where you have 2 registers in a single operand.
Since there is only one "extended" field per operand, it should not be overwritten at the second call to parseReg

**Comment by PaoloMonti42** [comment]
Last commit should be fixing everything, I will add more tests and remove the WIP if it's green

**Comment by radare** [comment]
seems like it's red after merging your PRs in r2r and r2 :?

**Comment by PaoloMonti42** [comment]
Yeah, but the PR itself is green. How can it happen?

**Pull request merged**
