### PR TITLE
Meson: Added sdb building/installation rules

### PR DESCRIPTION
**Pull request by pelijah**
\+ installation rules for doc, man and some other data

Patch for Cutter:
```diff
diff --git a/meson.py b/meson.py
index 2febe33..6298364 100644
--- a/meson.py
+++ b/meson.py
@@ -71,10 +71,9 @@ def win_dist(args):
     log.debug('Deploying Qt5')
     subprocess.call(['windeployqt', '--release', os.path.join(dist, 'Cutter.exe')])
     log.debug('Deploying libr2')
-    r2_meson_mod.win_dist_libr2(DIST=dist)
+    r2_meson_mod.win_dist_libr2(DIST=dist, BUILDDIR=os.path.join(build, 'subprojects', 'radare2'))

 def build(args):
-    r2_meson_mod.prepare_capstone()
     cutter_builddir = os.path.join(ROOT, args.dir)
     if not args.webengine:
         VARS['QT'].remove('WebEngineWidgets')
@@ -91,7 +90,6 @@ def build(args):
         r2_meson_mod.meson(os.path.join(ROOT, 'src'), cutter_builddir,
                            prefix=cutter_builddir, backend=args.backend,
                            release=True, shared=False, options=defines)
-    r2_meson_mod.build_sdb(args.backend, release=True)
     log.info('Building cutter')
     if args.backend == 'ninja':
         r2_meson_mod.ninja(cutter_builddir)

```

### CODE REVIEW

**Comment by xarkes** [comment]
Red :(

**Comment by pelijah** [comment]
Ok it was not good idea to remove vs_dedup() function.

**Comment by radare** [comment]
ok to merge @xarkes ?

**Comment by xarkes** [comment]
Yes lgtm

**Pull request merged**
