### PR TITLE
commented out the help message which does not work functionally just yet that I would like to get back in future.

### PR DESCRIPTION
**Pull request by Vane11ope**

### CODE REVIEW

**Comment by Maijin** [comment]
Huh? the . is important feature it should be fixed, not hidden

**Comment by Vane11ope** [comment]
ok

**Comment by Vane11ope** [comment]
@Maijin done

**Comment by Maijin** [comment]
Can you fix the r2book PR too ?

**Comment by Vane11ope** [comment]
@majin do you think ive not done it? :) haha of course ive done it and merged already

**Comment by Vane11ope** [comment]
@Maijin https://github.com/radare/radare2book/pull/127

**Comment by Maijin** [comment]
perfect thanks

**Pull request merged**
