### PR TITLE
Do not output highlighted text when saving projects

### PR DESCRIPTION
**Pull request by jroimartin**

### CODE REVIEW

**Comment by radare** [comment]
hahahaha. good one! thanks

**Comment by hummypkg** [comment]
I actually liked that being saved as part of the project :(

**Comment by radare** [comment]
this was producing wrong project files. you are right, now the highlighted value is not saved :/ maybe nibble can find a better solution to this. probably disabling the value in RCons itself instead of changing the rcore settings.

**Comment by jroimartin** [comment]
@hummypkg fixed in #5008 :)

**Pull request merged**
