### PR TITLE
Add a `bool` argument `do_skyline` to `r_io_map_{add,new}`

### PR DESCRIPTION
**Pull request by MaskRay**
We can do some precomputation when the map structure changes (add/delete/remap/...).

### CODE REVIEW

**Comment by MaskRay** [comment]
So the time-consuming `r_io_map_calculate_skyline` does not need to be recalculated again and again in the RBin loading process.

**Comment by Maijin** [comment]
https://travis-ci.org/radare/radare2/jobs/268981989 doesn't build.

**Comment by alvarofe** [comment]
IMHO I wouldn't add a bool, i would hide this behind rio when adding and removing maps change a boolean within RIO and when the skyline is needed make the calculation.

_Sent from my Xiaomi MI 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MaskRay** [comment]
@alvarofe postponing calculation of skyline would be unacceptable if https://github.com/radare/radare2/pull/8279#issuecomment-325170198 was taken.
Because the `for (addr = from; addr < to; ...) {}` code needs access to the skyline. It seems uglier to me if a check is added before the loop. 

In the code, I do not use `r_io_al_read_at` but `r_io_read_at` that dealing with one specific map

**Comment by MaskRay** [comment]
When  address space wraparound + gaps between maps are concerned, the call sites of `r_io_read_at`  (`cmd_search.c` `canal.c` ...) and the loop `for (addr = from; addr < to; addr += len)` can be replaced with a macro that defines the following structure

```c++
  auto *map_skylines_end = map_skylines + sizeof(map_skylines)/sizeof(*map_skylines);
  // Found the first map whose `to` > addr
  // upper_bound is an optimization
  //RIOMap **it = upper_bound(shadowmap_begin, shadowmap_end, from, cmp_by_to);
  auto *it = map_skylines;

  ut64 addr = from, total_len = to - from;
  while (it != map_skylines_end) {
    if (it->to-1 <= addr) {
      it++;
      continue;
    }
    if (addr < it->from) {
      // [addr, it->from) is a gap
      if (total_len <= it->from - from) break;
      addr = it->from;
    }
    ut64 len = R_MIN(R_MIN(to - addr, it->to - addr), sizeof buf);
    st64 ret = r_io_read_at(io, addr, buf, len);
    // Assume `int r_io_read_at` is used. bool will not differ much
    if (ret < 0) handle_error;

    // Do your work on [addr, addr+ret) with [buf, buf+ret)
    printf("%" PRIx64 " - %" PRIx64 "\n", addr, addr+ret);

    if (ret < len || (addr += ret) == to) break;
    if (!addr) it = map_skylines;
  }
```

**Comment by alvarofe** [comment]
Is crashing all over the places

**Comment by MaskRay** [comment]
@alvarofe I'm innocent. It is just because the test ran at a bad patch caused by others.

**Comment by alvarofe** [comment]
someone fucked up rbtree test

**Comment by alvarofe** [comment]
Once the rbtree is fixed we can gauge this PR so we can track XX tests

**Comment by MaskRay** [comment]
rbteee is not used in this PR..........

I think it is good now

**Comment by alvarofe** [comment]
i know, it was if travis fail some XX can be hidden for that failure

**Pull request merged**
