### PR TITLE
Fix #2937

### LINKED ISSUE #2937: Fix V810 COVs
```
*** CID 1311669:    (CONSTANT_EXPRESSION_RESULT)
/libr/anal/p/anal_v810.c: 129 in v810_op()
123     			break;
124     		case V810_RETI:
125     			op->type = R_ANAL_OP_TYPE_RET;
126     			break;
127     		case V810_JAL:
128     			destaddr = ((word1 & 0x3FF) << 16) | word2;
   CID 1311669:    (CONSTANT_EXPRESSION_RESULT)
   "destaddr & 0x2000000" is always 0 regardless of the values of its operands. This occurs as the logical operand of if.
129     			if (destaddr & 0x2000000)
130     				destaddrs = destaddr | 0xFC000000;
131     			else
132     				destaddrs = destaddr;
133     
134     			op->jump = addr + destaddrs;
/libr/anal/p/anal_v810.c: 140 in v810_op()
134     			op->jump = addr + destaddrs;
135     			op->fail = addr + 4;
136     			op->type = R_ANAL_OP_TYPE_CALL;
137     			break;
138     		case V810_JR:
139     			destaddr = ((word1 & 0x3FF) << 16) | word2;
   CID 1311669:    (CONSTANT_EXPRESSION_RESULT)
   "destaddr & 0x2000000" is always 0 regardless of the values of its operands. This occurs as the logical operand of if.
140     			if (destaddr & 0x2000000)
141     				destaddrs = destaddr | 0xFC000000;
142     			else
143     				destaddrs = destaddr;
144     
145     			op->jump = addr + destaddrs;
```

### PR DESCRIPTION
**Pull request by mrdanielps**

### CODE REVIEW

**Comment by radare** [comment]
This is wrong. you are initializing those variables as 16bit , so they are half filled with trash

**Comment by mrdanielps** [comment]
Yeah, sorry about that, it should be fixed now.

**Comment by radare** [comment]
Nope. see:
```
        r_mem_copyendian((ut8*)&word1, buf, 2, LIL_ENDIAN);
        r_mem_copyendian((ut8*)&word2, buf + 2, 2, LIL_ENDIAN);
```

**Comment by mrdanielps** [comment]
I assume that's what you meant, right?

BTW, the tests aren't up to date: https://github.com/radare/radare2-regressions/pull/201

**Comment by radare** [comment]
Nope. The memcopyendian function is copying 2 bytes. And ut32 is 4. So even aftter this change, the patch is wrong. I would suggest doing the bit shifting by hand; Instead of using memcpyendian.

**Comment by mrdanielps** [comment]
But word1 and word2 are ut16. destaddr and destaddrs should be 32 bit because the jump displacement can be up to 26 bits. Am I missing something?
Maybe I should rename the variables to make it more clear.

**Comment by radare** [comment]
you changed word1 and word2 to ut32

https://github.com/mrdanielps/radare2/commit/d7b0cd34638dc0d0a1d14787affce6ba2b4215e9 <https://github.com/mrdanielps/radare2/commit/d7b0cd34638dc0d0a1d14787affce6ba2b4215e9>

**Comment by mrdanielps** [comment]
I changed destaddr and destaddrs:
```diff
-	ut16 destaddr;
-	st16 destaddrs;
+	ut32 destaddr;
+	st32 destaddrs;
 	ut16 word1, word2;
```

**Comment by radare** [comment]
Oh sorry, that looks goodl. thanks :)

**Pull request closed without merging**
