### PR TITLE
fix asm.bbline #3739

### PR DESCRIPTION
**Pull request by ret2libc**
The BasicBlock is a concept you can have only with analysis info. This ensure that the displayed result is correct.

### CODE REVIEW

**Comment by ret2libc** [comment]
yep it is. there was no need to re-do the utf8 thing, because ds->refline2 is already utf8 friendly. You can see here https://github.com/radare/radare2/blob/master/libr/anal/reflines.c#L413 that it's transformed for utf8

**Comment by radare** [comment]
Fair enough :)

**Comment by ret2libc** [comment]
just to be clear, this means that with this patch, asm.bbline will not work without doing analysis before. This is because IMO the concept of basicblock has no sense if there are no functions.

**Comment by radare** [comment]
yep, agree for consistency

**Pull request closed without merging**
