### PR TITLE
Add support for x86-32 gcc "mov r,[r*s+d];jmp r" jumptables

### PR DESCRIPTION
**Pull request by radare**
Thanks @rlaemmert for providing test case

- This PR also improves the analysis of MOV instructions on X86
- And extends output of 'ao' to show ireg, scale, ...

### CODE REVIEW

**Comment by radare** [comment]
please @rlaemmert review/fix the tests and add a test for your `calc` binary if can be shared

**Comment by radare** [comment]
to write the test do the following:

```
$ r2 -e anal.jmptbl=true -s 0x08049203 -caf /tmp/calc.file
```

and then `f~?switch.` != 0 and `f~?case.` != 0

**Comment by ret2libc** [comment]
I'm going to try this tonight/tomorrow and provide feedback! That's definitely something I'm interested in :)

**Comment by radare** [comment]
I have rebased the PR, cc @rlaemmert

**Comment by ret2libc** [comment]
do we have a testcase for this in r2r?

**Comment by radare** [comment]
tired of watiing. i did the test that i described here and im fixing the tests. will hopefully merge today

**Comment by radare** [comment]
should be green now, cleaning up printfs. took me 11 minutes..

**Comment by radare** [comment]
r2r test is here https://github.com/radare/radare2-regressions/pull/1353

**Pull request merged**
