### PR TITLE
x86.cs: Fix POPA{LW} esil

### PR DESCRIPTION
**Pull request by zamaudio**
Signed-off-by: Damien Zammit <damien@zamaudio.com>

### CODE REVIEW

**Comment by radare** [comment]
Please @rlaemmert review

**Comment by radare** [comment]
i think its not fixed, just handled somehow. but i guess thats better than nothing

**Comment by rlaemmert** [comment]
Yea totally agree, the first commit related to POPA corrects the stackptr as there needs to be
decremented 8 times regsize and also it removes POPCNT from this case. Thats correct as it has nothing to do with POPA opcodes. The second commit adds the missing PUSHF versions, but the case is still wrong. Anyway we should separate the PUSHF cases from the PUSH one, because PUSH<F> pushs the eflags.

**Comment by radare** [comment]
any update on this?

**Comment by zamaudio** [comment]
Can you merge just the POPA{LW} commit, as it is still an improvement.  The second one doesn't really help much at all. Would that be accurate @rlaemmert ?

**Comment by radare** [comment]
ok, but bear in  mind to fix them at some point :) as we know this is not solving the problem, just enhancing the current situation a bit :P

**Comment by zamaudio** [comment]
I was under the impression there was nothing wrong with the POPA{LW} instructions, apart from the bug with the stack pointer... so it fixes it totally.  But the second patch is half baked.

**Comment by rlaemmert** [comment]
You could merge both  because the second one doesnt change anything. Pushf is still not done for esil.

**Pull request merged**
