### PR TITLE
Try anal.jmptbl=true

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by Maijin** [comment]
Only 2 XX that's really not bad

**Comment by radare** [comment]
Can u check which are those tests that fail and why. Also test moar with bins u know and use pls

**Comment by Maijin** [comment]
It's tested against all the fuzz + all the other existing "aaa" tests which is a LOT already ^_^, at least against segfault.

XX tests one is main function being bigger which i think is expected and the other is local. flag being counted 12 instead of 11 which seems to be coherent too

**Comment by radare** [comment]
So it seems to me that is something good to enable by default. What do you think?

**Comment by Maijin** [comment]
sounds good to me indeed :)

**Comment by XVilka** [comment]
Agree for enabling it by default.

**Pull request merged**
