### PR TITLE
AVR output ports comments/annotations

### PR DESCRIPTION
**Pull request by brainstorm**
This will ease the reading of AVR ports via automatic comments on `in` and `out` :D

skarmavbild 2016-06-30 kl 19 58 10

### CODE REVIEW

**Comment by radare** [comment]
what about rebasing and NEVER merging in a pullreq branch?

**Comment by brainstorm** [comment]
Couple of things:

1) Is it possible to remove/overwrite the generic "store register to I/O location?" comment.
2) Yes, will rebase and cleanup later when it's good, please spare my life pancake ;)

**Comment by brainstorm** [comment]
And while we are at it, putting the interrupt vector table:

skarmavbild 2016-06-30 kl 21 30 18

Where it belongs in radare? :)

skarmavbild 2016-06-30 kl 21 31 44

**Comment by radare** [comment]
merged!

**Pull request closed without merging**
