### PR TITLE
Fix escaping of \u

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
we dont want to escape \u, because its like escaping \x or so.. your patch will make \u0011 to be \\u0011 which is wrong because the \u0011 is a valid escape sequence

**Comment by kazarmy** [comment]
The patch fixes #7674. As for Unicode strings in general, there should be a config var and analysis hints stating whether a string is Latin-1, UTF-8, UTF-16LE etc. This if I'm not mistaken is a GSoC/RSoC microtask.

**Comment by kazarmy** [comment]
Should I close this PR?

**Comment by radare** [comment]
Wait i need to chk to decide first. Enotime

**Comment by kazarmy** [comment]
A new flag, maybe `asm.nonwidestrenc`, is perhaps in order here but my time after hours is currently disrupted and is expected to remain so for another 2-3 weeks, so the flag probably won't arrive anytime soon.

**Comment by kazarmy** [comment]
Hmm `asm.charstrenc` is a better name.

**Comment by radare** [comment]
ETOOLONG

**Comment by kazarmy** [comment]
Yes the `str` can be dropped. So there should be `asm.charenc`, `asm.wcharenc` and `asm.forceenc` flags.

**Comment by radare** [comment]
what about asm.strenc ? and why do we want to force the encoding? which use case cant be catched in the current loop?

**Comment by kazarmy** [comment]
Currently there are 2 possible encodings for flag and anal string output (and hopefully other string output in the near future) that depend on [whether the string's 2nd byte is 0](https://github.com/radare/radare2/blob/0b4eb1740c723996c3843791faec2fc7b1a620fe/libr/core/disasm.c#L2624):

- If the 2nd byte is 0, the string is assumed to be a wide string and an almost-UTF-16, little endian encoding is used. Almost because UTF-16 surrogate pairs are not supported.
- Otherwise, the Latin-1 encoding is used (with \x escape sequences).

> and why do we want to force the encoding? which use case cant be catched in the current loop?

Loop? The above algorithm doesn't work for a wide string where the second byte isn't 0, e.g. "╟╥╥╢" which is \u255f\u2565\u2565\u2562. So there is a need to force the encoding here.

> what about asm.strenc ?

That single var can be made to work, with probably the following semantics:

- If its value is `guess`, then it's the status quo i.e. UTF-16, little endian for wide strings as defined above and Latin-1 for other strings.
- If its value is an encoding e.g. `utf-8`, then all strings including wide strings are forced to that encoding.

**Comment by radare** [comment]
im adding support for utf32, i can merge that now , but it will be good to handle utf32 strings too like this

**Comment by radare** [comment]
but im afraid that if this pr is passing green is because we are missing tests

**Comment by kazarmy** [comment]
> ... but it will be good to handle utf32 strings too like this
>
> ... we are missing tests

Need to figure out how the code works first though.

**Comment by kazarmy** [comment]
Closing since superseded by #7849.

**Pull request closed without merging**
