### PR TITLE
#2061 add simple json style output to radiff2

### PR DESCRIPTION
**Pull request by kairenken**
This pull request adds a simple json-based output to radiff2.
See this example:
````bash
$ radiff2 -j bgrep bgrep.2
{ "offset":"0x000008e2" , "from":"31ed5e89e1" , "to":"9066890408" }
{ "offset":"0x00000937" , "from":"74" , "to":"90" }
````

radare-style output:
````bash
$ radiff2 -r bgrep bgrep.2
wx 9066890408 @ 0x000008e2
wx 90 @ 0x00000937
````

nomal output:
````bash
$ radiff2 bgrep bgrep.2
0x000008e2 31ed5e89e1 => 9066890408 0x000008e2
0x00000937 74 => 90 0x00000937
````

### CODE REVIEW

**Comment by radare** [comment]
Will merge when the json spec discussion is finished. Anybody wants to share some comments on here?

**Comment by radare** [comment]
This task is similar to this one, if you want to check it out while we decide the proper format for this json.

https://github.com/radare/radare2/issues/1594

**Comment by radare** [comment]
Discussion pad: https://pad.nopcode.org/p/gZCYlT8hsA

**Comment by radare** [comment]
Related https://github.com/radare/radare2/issues/1778

**Comment by kairenken** [comment]
Added some more commits to fullfill https://pad.nopcode.org/p/gZCYlT8hsA more.

**Comment by radare** [comment]
I can see different issues here:

* offset field must be numbers (in base 10) and not strings.
* from/to fields always contain a space at the end.

**Comment by radare** [comment]
No need to define an extra enum for NORMAL,JSON,RADARE, just use single char like 'j', 'r' and 0

**Comment by radare** [comment]
Add spaces between the function name and the parenthesis, like the rest of the code.

You can make a global var to store the type of output, .. but as long as you are passing an integer as void*, it would be better to just wrap all the global variables inside a struct and pass the pointer as the void*user.

**Comment by radare** [comment]
The handle_sha256 callback is mixing printf and r_cons_newline(). which are incompatible. you should use one or the other, but not mix them. as long as radiff2 is a cmdline too. you dont need the internal buffering/filtering that rcons provides, so just make a printf ("\n");

**Comment by radare** [comment]
The JSON definition looks good to me, so just fix those issues and i'll merge :) thanks!

**Comment by kairenken** [comment]
````shell
$ cp radiff2 radiff2.foo
1 files ( 72,0 KiB) copied in 0,0 seconds ( 37,3 MiB/s).
$ r2 -w radiff2.foo
 -- Emulate the base address of a file with e file.baddr.
[0x00401130]> wx 90
[0x00401130]> quit
$ ./radiff2 -j radiff2 radiff2.foo 
{"files":[{"filename":"radiff2", "size":61753, "sha256":"558cc8aeccfd2ed4085377a5e6ffc8558d4a608e2f00e1895614ba4d40035e51"},
{"filename":"radiff2.foo", "size":61753, "sha256":"8d65859357fdac0f1ead52fbe92bd47b26352fa63dbd0853fb3d3e17694806ea"}],
"changes":[{"offset":4400,"from":"31", "to":"90"}]}
$ ./radiff2 -r radiff2 radiff2.foo 
wx 90 @ 0x00001130
$ ./radiff2 radiff2 radiff2.foo 
0x00001130 31 => 90 0x00001130
````

I've fixed your issues for the layout the code issues itself too.

**Comment by radare** [comment]
Cool! thanks!

**Pull request closed without merging**
