### PR TITLE
Fix #3955

### LINKED ISSUE #3955: `afl` columnize output format
Usually, if you list all functions in a binary, you'll get this (Example: [BSides Vancouver www challenge](https://github.com/ctfs/write-ups-2015/tree/master/bsides-vancouver-ctf-2015/ownable/www)):

```bash
[0x08048650]> afl 
0x08048650  34  1  entry0
0x08048610  16  2  sym.imp.__libc_start_main
0x080487b7  483  7  sym.main
0x08048680  43  4  sym.deregister_tm_clones
0x080486b0  56  4  sym.register_tm_clones
0x080486f0  30  3  sym.__do_global_dtors_aux
0x08048710  44  4  sym.frame_dummy
0x080489a0  5  1  sym.__libc_csu_fini
0x08048a0a  4  1  sym.__i686.get_pc_thunk.bx
0x0804873c  123  3  sym.copybuf
0x08048620  16  2  sym.imp.strncpy
0x080485b0  16  2  sym.imp.strcpy
0x08048550  16  2  sym.imp.strcmp
0x080485c0  16  2  sym.imp.puts
0x080485e0  16  2  sym.imp.exit
0x08048a10  23  1  sym._fini
0x080489b0  90  4  sym.__libc_csu_init
0x08048518  38  3  sym._init
0x080485d0  16  2  loc.imp.__gmon_start__
0x08048560  16  2  sym.imp.read
0x08048570  16  2  sym.imp.printf
0x08048580  16  2  sym.imp.fflush
0x08048590  16  2  sym.imp.fgets
0x080485a0  16  2  sym.imp.time
0x080485f0  16  2  sym.imp.open
0x08048600  16  2  sym.imp.srand
0x08048630  16  2  sym.imp.rand
0x08048640  16  2  sym.imp.close
```

I always have to pipe it to `column -t` to get a prettier output:

```bash
[0x08048650]> afl | column -t
0x08048650  34   1  entry0
0x08048610  16   2  sym.imp.__libc_start_main
0x080487b7  483  7  sym.main
0x08048680  43   4  sym.deregister_tm_clones
0x080486b0  56   4  sym.register_tm_clones
0x080486f0  30   3  sym.__do_global_dtors_aux
0x08048710  44   4  sym.frame_dummy
0x080489a0  5    1  sym.__libc_csu_fini
0x08048a0a  4    1  sym.__i686.get_pc_thunk.bx
0x0804873c  123  3  sym.copybuf
0x08048620  16   2  sym.imp.strncpy
0x080485b0  16   2  sym.imp.strcpy
0x08048550  16   2  sym.imp.strcmp
0x080485c0  16   2  sym.imp.puts
0x080485e0  16   2  sym.imp.exit
0x08048a10  23   1  sym._fini
0x080489b0  90   4  sym.__libc_csu_init
0x08048518  38   3  sym._init
0x080485d0  16   2  loc.imp.__gmon_start__
0x08048560  16   2  sym.imp.read
0x08048570  16   2  sym.imp.printf
0x08048580  16   2  sym.imp.fflush
0x08048590  16   2  sym.imp.fgets
0x080485a0  16   2  sym.imp.time
0x080485f0  16   2  sym.imp.open
0x08048600  16   2  sym.imp.srand
0x08048630  16   2  sym.imp.rand
0x08048640  16   2  sym.imp.close
```

Can this be per default :)?

### PR DESCRIPTION
**Pull request by d3bug3r**

### CODE REVIEW

**Comment by Maijin** [comment]
Can you correct the tests and add a Pull requests on radare2-regressions repository ? See https://s3.amazonaws.com/archive.travis-ci.org/jobs/118483339/log.txt
ctrl+f on [XX]

**Comment by radare** [comment]
lgtm but please fix the testsuite

**Comment by radare** [comment]
ping?

**Comment by radare** [comment]
Tired of waiting. merged. please @Maijin fix the testsuite after this

**Comment by Maijin** [comment]
done

**Comment by Maijin** [comment]
restarted

**Pull request closed without merging**
