### PR TITLE
Upstream patches from pkgsrc/devel/radare2

### PR DESCRIPTION
**Pull request by sevan**
Switch to using egrep instead of non-portable "grep -e".
Add support for SunOS.

### CODE REVIEW

**Comment by XVilka** [comment]
For the configure part - please fix configure.acr and/or acr itself, since
it's auto-generated.

**Comment by sevan** [comment]
thanks for the heads up, pushed a new commit to add that

**Comment by radare** [comment]
the configure thing goes to the acr repo

egrep is not available everywhere...this will break other targets like
termux..

**Comment by sevan** [comment]
will raise a pull request later in the acr repo.
re egrep, what's the best way to proceed? test if egrep is present & use that else use grep -e?

**Comment by radare** [comment]
this is probably the sanest way to make it portable.but .. is -e already necessary in this case? maybe we can just drop that and will work equally. can you confirm?

**Comment by sevan** [comment]
I tested running the find commands from libr/Makefile, manually after a succesful build on OS X, NetBSD & Debian.
It appears that `grep -e` doesn't actually work in this scenario, in that the end result is no files are found. As apposed to with `egrep` instead.
e.g.
` find * -type f | egrep  '\.a$$' | grep -v fs/p 
                                                               
shlr/tcc/libr_tcc.a

shlr/wind/libr_wind.a

shlr/bochs/lib/libbochs.a

shlr/sdb/src/libsdb.a

shlr/grub/libgrubfs.a

shlr/gdb/lib/libgdbr.a

shlr/zip/zlib/libr_z.a

shlr/zip/librz.a

shlr/zip/zip/libr_zip.a

shlr/capstone/libcapstone.a

shlr/java/libr_java.a

shlr/qnx/lib/libqnxr.a`

**Comment by radare** [comment]
that $$ is only necessary from make. you can use $ in the shell

**Comment by radare** [comment]
also. its unnecessary to use grep here. find already have support for this:
```
find . -iname *.a
```

can you rework this change and test on SunOS ?

**Comment by sevan** [comment]
Done

**Comment by radare** [comment]
Can you please send the PR to https://github.com/radare/acr/pulls instead of r2?

**Pull request merged**
