### PR TITLE
update pr

### PR DESCRIPTION
**Pull request by JohnDoe1234123**
https://github.com/radare/radare2/commit/8208f42fa2b6821081c5a48fda716622a7776f3e

### CODE REVIEW

**Comment by JohnDoe1234123** [comment]
please ignore https://github.com/JohnDoe1234123/radare2/commit/d15bccf6496c07b2bf47160f0276b21775dbe90b

**Comment by radare** [comment]
See 1fc7dd4cf68091cf01feaec224b2504e02e258ab

**Comment by JohnDoe1234123** [comment]
@radare I wanted to discuss the issue first.

**Comment by radare** [comment]
oh, i missunderstood then. the approach im trying to follow in r2 is that it is a library, and a library should never crash, exit or break your program. so the rule here is, no asserts, no exit, no segfaults :)

i have reproduced some sitautions where r2 cant allocate more memory and it keeps stable as the shell is still there and some actions can be still performed, but at least is not dying unexpectedly

**Pull request closed without merging**
