### PR TITLE
add end of string metadata for better navigation in Visual mode

### PR DESCRIPTION
**Pull request by lowlyw**

### CODE REVIEW

**Comment by radare** [comment]
it's true that scroll works better with this change merged but there are some things that worry me:

* string_end should not be a type of metadata.
* the scrolling problem over metas is not just a string problem, same happens with hexdump data or structs. and must support scrolling in the middle of it, not just by the end. so we probably need an rbtree instead of sdb to store that or use sdb in a better way
* scroll works fine by scrolling up from the end of a string, not in the middle or few bytes after
* string_end metas are deleted/updated when string length changes or its removed?

**Comment by lowlyw** [comment]
> string_end should not be a type of metadata.

sure, i agree 100%,  metadata should be a range, and that's not currently the case, but i'm not willing to rewrite the metadata without planning :\

> the scrolling problem over metas is not just a string problem, same happens with hexdump data or structs. and must support scrolling in the middle of it, not just by the end. so we probably need an rbtree instead of sdb to store that or use sdb in a better way

👍 agree 100%

> scroll works fine by scrolling up from the end of a string, not in the middle or few bytes after

the goal of this patch is to make it so you don't end up in the middle :P again, metadata needs rearch entirely, but this is a decent stopgap imo

> string_end metas are deleted/updated when string length changes or its removed?

yes, on `r_meta_del` we have 

```diff
 +	if (type == R_META_TYPE_STRING) {
 +		r_meta_del (a, R_META_TYPE_STRING_END, addr + size, size);
 +	}
```

**Comment by radare** [comment]
Then we should redesign meta using the rbtree that is right now used for fcns in anal

**Comment by radare** [comment]
so, what do you think about closing it and plan the proper fix?

**Comment by lowlyw** [comment]
let's do that then!

**Pull request closed without merging**
