### PR TITLE
Add to Docker Hub as an automated build

### PR DESCRIPTION
**Pull request by Manouchehri**
I would do this myself if I could, but it needs to be done by someone who's listed as a ~~collaborator on the repository~~ member of the radare GitHub organization or owner.

To enable automated builds on each push, all that has to be done is create an account at [Docker Hub](https://hub.docker.com), pick automated build and point it towards radare2's master branch.

(The soft link isn't necessary if you point the Dockerfile location to `/doc/`.)

2015-10-10-21 07 52-screenshot

### CODE REVIEW

**Comment by Manouchehri** [comment]
Here's the automated build I have on my account right now.

https://hub.docker.com/r/manouchehri/radare2/

The issue with that one is that I have to manually update my fork of radare2 for the automated build to be triggered.

**Comment by Maijin** [comment]
Kewl :+1:

**Comment by Maijin** [comment]
So basically we have already an organization on this website called "radare", member are xvilka and myself. But I can't add radare2 repo to the automated build. It's up to @radare to:
1) Create an account on docker hub 
2) ask me or xvilka___ to be in radare organization of docker hub
3) Link the github account
4) Create -> Create automated builds

**Comment by Manouchehri** [comment]
After checking with @Maijin, it seems that it has to be done by @radare, as the collaborators aren't in a GitHub organization.

screenshot 2015-10-11 at 09 35 47

screenshot 2015-10-11 at 09 40 43

**Comment by Maijin** [comment]
Yes, So basically we have already an organization on this website called "radare", member are xvilka and myself. But I can't add radare2 repo to the automated build. It's up to @radare to:
1) Create an account on docker hub 
2) ask me or @XVilka to be in radare organization of docker hub
3) Link the github account
4) Create -> Create automated builds

**Comment by radare** [comment]
Created account, organization, moved the dockerfile to root and trying to setup the webhook now

**Comment by Maijin** [comment]
Now

**Comment by Maijin** [comment]
Now waiting for the build to success

**Comment by Manouchehri** [comment]
@Maijin: Not quite.

One slight issue, `/doc/Dockerfile` was moved to `/Dockerfile` in c048d775ca8449970c3a108c876c81736e8741b1, but my instructions of setting the `build_path` to `/doc` were used. Just set the Dockerfile location back to `/` and you'll be good.

**Comment by Manouchehri** [comment]
2015-10-12-16 30 51-screenshot

**Comment by Maijin** [comment]
@Manouchehri yep, it's on-going, we'll see tomorrow

**Comment by Maijin** [comment]
It's super slow ;)

**Comment by Manouchehri** [comment]
So the next build is already set to point to /?

Docker rate limits to avoid projects like radare2 from submitting a hundred
builds a day. ;P

**Comment by Maijin** [comment]
@Manouchehri yes is setted to / but is super super slow :/

**Comment by Manouchehri** [comment]
Haha yeah, I tend to pull Docker images once a day. I'll check on it
tomorrow. =)

Thanks guys!

**Comment by crowell** [comment]
Is this worth having if it is this so slow?

**Comment by Manouchehri** [comment]
Sure, why not? It's already set up, there's nothing else that needs to be
done since it's an automated build.

If you don't use Docker, then it's not worth using. For those of us who do,
it's fine to have a build that's a few hours out of date.

**Comment by Maijin** [comment]
@Manouchehri https://hub.docker.com/r/radare/radare2 but I don't get why is not working ? Maybe not yet completed ?

**Comment by Maijin** [comment]
@crowell is very useful ;)

**Comment by Manouchehri** [comment]
It only gets trigger on a push and I believe there's some rate limiting.
Tomorrow afternoon it should be working.

**Comment by Maijin** [comment]
ok but there are progress ;)

**Comment by Manouchehri** [comment]
The build finished a few seconds ago, try it now.

**Comment by Maijin** [comment]
yep, doing it now

**Comment by Maijin** [comment]
@Manouchehri the dockerfile will probably need to be enhanced

**Comment by Manouchehri** [comment]
Yeah, that's work for later. Just getting it listed was the first step. =)

**Comment by Maijin** [comment]
@Manouchehri It works ;)

**Comment by Manouchehri** [comment]
@crowell It isn't as slow as I initially thought, there's already several builds from today. Each one takes slightly under 20 minutes.

https://hub.docker.com/r/radare/radare2/builds/

**Pull request closed without merging**
