### PR TITLE
env.sh: fix "cannot open radare20" issue.

### PR DESCRIPTION
**Pull request by ret2libc**
The last parameter wasn't correctly passed.

### CODE REVIEW

**Comment by radare** [comment]
Please, check if the last commit in master fixes this issue

**Comment by ret2libc** [comment]
This should be posix compatible and it should definitely solve the issue.
As written in the commit "The error is caused because if you try to evaluate the 10th parameter,
$10 is evaluate just as $1 + '0'. To make it work, we can use ${10}"

**Comment by radare** [comment]
I would prefer not to depend on jot or seq, can you send a pr for the current master?

**Comment by ret2libc** [comment]
Done!

**Comment by radare** [comment]
Merged. Thanks!

**Pull request closed without merging**
