### PR TITLE
Added checks in elf.c and mach0.c

### PR DESCRIPTION
**Pull request by alvarofe**
With these littles changes the elf fuzzed tests are passed though is needed a more thoroughly analysis to study more edge-cases and fuzzing with afl or try with other files. These days I will continue working on it.

The only that remain really broken are the java fuzzed files.

### CODE REVIEW

**Comment by Maijin** [comment]
@alvarofe It doesn't pass the travis see the errors:

    /home/travis/build/radare/radare2/libr/..//libr/bin/p/../format/elf/elf.c:81:2: error: stray ‘\302’ in program
    /home/travis/build/radare/radare2/libr/..//libr/bin/p/../format/elf/elf.c:81:2: error: stray ‘\240’ in program
    make[3]: *** [/home/travis/build/radare/radare2/libr/..//libr/bin/p/../format/elf/elf.o] Error 1
    make[2]: *** [bin] Error 2
    make[1]: *** [all] Error 2
    make: *** [all] Error 2

**Comment by alvarofe** [comment]
uppss :S I will check at night now gtg

**Comment by alvarofe** [comment]
It is failing in the binary tiny.elf but with readelf I get the following
```
alvaro_fe@macbook 21:03  greadelf -S tiny.elf
readelf: Error: tiny.elf: Falló al leer el encabezado del fichero
```
And in a linux machine
```
readelf -S tiny.elf
readelf: Error: tiny.elf: Failed to read file header
```

**Comment by radare** [comment]
as long as tinyelfs are valid elfs for the system linker they must be loaded properly. im aware that ida, gnu and other crappy tools fail to load them. but r2 must keep being happy with those kind of files.

**Comment by XVilka** [comment]
I'm not sure we need these checks, since linux ld.so doesn't care about them. Because not the only tinyelfs are our target, but also some malicious malformed ELFs. r2 loading code should be bulletproof, but still need to be able to open whatever is possible. Please consider that.

**Comment by alvarofe** [comment]
If we need to allow malformed and tiny elfs to load in r2, that checks must be eliminated because don't concern with security at all, that is true. I have to add check in those case where can produce seg fault or dangerous things like for example an offset that is greater than the bin size or an index greater than the strtab size.

**Comment by XVilka** [comment]
LGTM

**Comment by XVilka** [comment]
@radare what do you think of this refined patch?

**Comment by radare** [comment]
Merged yesterday O:)

**Pull request closed without merging**
