### PR TITLE
Added additional default value of dir.prefix on Windows

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by radare** [comment]
Why this api doesnt return char*?

Wouldnt be better to put this inside r_sys_prefix. Making the R2_PREFIX to be ignored

**Comment by pelijah** [comment]
> Wouldnt be better to put this inside r_sys_prefix. Making the R2_PREFIX to be ignored

But r_core_config_init calls r_sys_prefix with non-NULL argument making any r_sys_prefix default value useless.

**Comment by radare** [comment]
let's merge this for now, because the line above doing a getenv is also wrong and it should be using the r_sys_prefix() api

**Comment by radare** [comment]
Yep that must be changed too

**Pull request merged**
