### PR TITLE
avoid aap if it's debug

### PR DESCRIPTION
**Pull request by Vane11ope**

### CODE REVIEW

**Comment by radare** [comment]
I think we should change search.in and anal.in the cfg.debug changes

**Comment by Vane11ope** [comment]
agreed. this fix is like super temporal solution anyway, just to avoid r2 -dAA /bin/ls to not loop infinitely. looked into code and there should be better and proper fix for this.

**Comment by radare** [comment]
Yes i know. But i would prefer to have the proper fix. Because using io.maps ranges in the debugger is kind of a pain.. in fact we should be able yo detect when io.maps.x is used and this range covers the whole 64bit address space show a warning and return an empty range instead to avoid such undesired events to happen

**Comment by radare** [comment]
fixed in https://github.com/radare/radare2/pull/13957

**Comment by radare** [comment]
fixed now

**Pull request closed without merging**
