### PR TITLE
Use r_str_escape for ASCII anal addr strings

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
I think this introduces some false positive strings

**Comment by kazarmy** [comment]
Can't see the Travis log on my slow connection, but I haven't relaxed any
conditions for string printing (in fact, I've tightened them).

**Comment by radare** [comment]
I dont think we should consider strings <4 length with non printable bytes. Maybe adding utf32 support introduced those, but will be good to enhance those checks

**Comment by kazarmy** [comment]
> I think this introduces some false positive strings

Just realized that r2r has `make alltargets` and found the failing "iphone-arm-esil pdsf" t.esil/apple test. I do know that the test output depends on the presence or absence of a `r_str_filter (msg, 0);` which is likely because its absence changes the string's length. Probably would need to consider an `\xhh` escape sequence as 1 char in pdsf but don't have time to do it right now.

**Comment by kazarmy** [comment]
Should be ok now. `pdsf` should have more tests.

**Pull request merged**
