### PR TITLE
Fix #14046 - Don't use ansi with aaa notifications if no ansicon

### LINKED ISSUE #14046: Dont use ansi on eprintf outside unix systems
though that was fixed

Screenshot 2019-05-13 at 11 34 35

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
but windows si unhappy with `print.c.obj : error LNK2019: unresolved external symbol r_cons_singleton referenced in function r_print_rowlog
1199`

**Comment by kazarmy** [comment]
Oh f0a1e4d80ee696d966ce86079fbc53df62a38cfe

**Comment by radare** [comment]
?

**Comment by kazarmy** [comment]
nvm

**Pull request merged**
