### PR TITLE
Disable -t and deobfuscate -n variable

### PR DESCRIPTION
**Pull request by thestr4ng3r**
#12996

### CODE REVIEW

**Comment by radare** [comment]
Why disable -t instead of making it work with tasks?

**Comment by thestr4ng3r** [comment]
I don't have the time to do it right now since it requires a lot of refactoring, so I would like to disable it for now because it is completely broken anyway.

**Comment by radare** [comment]
add a warning message at least

**Comment by thestr4ng3r** [comment]
You mean a warning if you do -t while it is disabled?

**Comment by radare** [comment]
yes

**Comment by radare** [comment]
do that and i'll merge, but i dnt see much problem in just calling r_core_cmdf(core, "& aa"); shouldnt be hard to do and should work

**Comment by thestr4ng3r** [comment]
No it's not that easy. -t should also load bin info in the background and there are other things between that and analysis. Also analysis is still not completely safe to run in tasks nevertheless, even if it works in practice.

**Comment by radare** [comment]
opening the bin info can be "& oba;e io.va=1"

**Comment by thestr4ng3r** [comment]
Yes, but there is more stuff in between and I don't won't to do any code duplication.

**Pull request merged**
