### PR TITLE
Fix #1545

### LINKED ISSUE #1545: af*/afj should be deprecated and use to afi*/afij
What should `af*` and `afj` do?
Should we kill them?

### PR DESCRIPTION
**Pull request by alvarofe**
`af*` ---> `afi*`
`afj` ---> `aflj`.

### CODE REVIEW

**Comment by alvarofe** [comment]
I didn't test if I was broken some test upps. I'll wait to the output of travis to see

**Comment by radare** [comment]
Travis is reporting some tests totally unrelated to your changes :?

**Comment by alvarofe** [comment]
Yes. I don't know why. However the latest commits were failing equally on the same test. But the newer commit has passed the test :S  
captura de pantalla 2015-04-19 a las 1 13 12

**Comment by XVilka** [comment]
@alvarofe just ignore it, it is completely unrelated to your PR. It is safe to merge. :+1:

**Comment by Maijin** [comment]
@alvarofe  @XVilka see, it's green ;)

**Pull request closed without merging**
