### PR TITLE
resolving #2620 [webui] if a basic block ending is a jump to its parent, both edges are superposed

### PR DESCRIPTION
**Pull request by grandemk**
this pull request separate the edges when they are superposed.

### CODE REVIEW

**Comment by crowell** [comment]
is appveyor just broken?

**Comment by grandemk** [comment]
I'm not sure of what is happening here, I just made some change in disasm.js from enyo, this shouldn't break any makefile things right ?

**Comment by Maijin** [comment]
@grandemk @crowell Appveyor is WIP, your PR pass the travis/test-suite so it's fine :+1: . @XVilka ping

**Comment by radare** [comment]
Merged!

**Comment by zlowram** [comment]
@grandemk should this fix apply also on the /p webui?

**Comment by grandemk** [comment]
I worked with the webui that spawn with the =h command, I'm not familiar with the other webui. 

The code was in enyo but the url of the webui is http://localhost:9090/p/ so I'm a bit confused ^^". I search for configuration var representing the webui, there is a http.ui=p. 

So how can I test the other webui ? The fix is related to the graph lib used in enyo.

**Comment by Maijin** [comment]
@grandemk go in  http://localhost:9090/ And you can select the webUI there

**Comment by grandemk** [comment]
Yes thanks ^^ I can't believe I didn't try that  So I only used /p, but changed code in enyo for that... I am now confused++

**Comment by grandemk** [comment]
@zlowram ok so this fix apply to /p.
/enyo use /graph to display the graphs, so this fix is not used.
I believe the code I changed is in enyo because it is planned to use it in enyo as well. @Maijin True ?

**Comment by zlowram** [comment]
@grandemk I was asking you this, because it does not appear to be fixed. I'm using a very simple hello world, a for loop, and the edges still look overlapped: 
screen shot 2015-06-07 at 01 33 10

**Comment by grandemk** [comment]
@zlowram try to move the block a little bit further, if the vertices I introduce for the deviation are set inside the block, I do nothing because else jointjs becomes crazy.

**Comment by grandemk** [comment]
You should get something like this:
la

**Comment by zlowram** [comment]
I can't get it to look like this, no matter how I move the basic block. Could it be possible that you're only taking into account the case where the jump is true (green)? Here's the code I used to reproduce the bug:
```
#include<stdio.h>

int main (int argc, char **argv) {
	for (int i = 0; i < 5; i++) {
		printf("%d\n", i);
	}
}
```

**Comment by grandemk** [comment]
Ok I will try this and get back to you. The color shouldn't change anything as I work directly on the links between blocks.

**Comment by grandemk** [comment]
I just checked out a repository, here is what I get after sys/install.sh:
screen

**Comment by zlowram** [comment]
I now did the same, purge the current install, clone the repo and sys/install. It seems I had a mess with the symlinks and were pointing to another cloned instance.

Now works as expected, my fault!

BTW, good job! :+1:

**Comment by grandemk** [comment]
Thanks :)

2015-06-08 14:15 GMT+02:00 zlowram <notifications@github.com>:

**Pull request closed without merging**
