### PR TITLE
Fix #4965. Add support for luhn searching and hashing.	

### LINKED ISSUE #4965: Add support for luhn searching and hashing
https://en.m.wikipedia.org/wiki/Luhn_algorithm

### PR DESCRIPTION
**Pull request by m1ghtym0**

### CODE REVIEW

**Comment by Maijin** [comment]
Add a test here https://github.com/radare/radare2-regressions/blob/master/t.tools/rahash2/rahash2

Then post the PR link here ;)

**Comment by radare** [comment]
Use a different branch and rebase on master. There are unrelated commits here

**Comment by m1ghtym0** [comment]
https://github.com/radare/radare2-regressions/pull/494

**Comment by m1ghtym0** [comment]
I forgot to switch the branch, in order to operate on the new one, i will open a new pr.

**Pull request closed without merging**
