### PR TITLE
fix for bbs alignment

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by Maijin** [comment]
Check the travis, Segfault detected

**Comment by dmtch** [comment]
I got it.

**Comment by radare** [comment]
not passing the testsuite, pls send pr if needed in r2r

**Comment by Maijin** [comment]
@dmtch still Segfaulting see https://travis-ci.org/radare/radare2/jobs/96283080#L252 for example

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
build with `sys/asan.sh` and run the segfault tests

**Comment by radare** [comment]
Please provide at least one test case to demonstrates the fixes you did.. we should evaluate the old and new changes. maybe they can be squashed.

**Comment by radare** [comment]
i have found that your changes break some kind of analysis, see the t/cmd_pd and t.anal/x86/jmp* tests .. the thing is that with jmptbl=false if you found a "jmp rax" it shouldnt break the function at there unless there's a previous jmp that skips that one. otherwise we get functions with invalid instructions or just wrong boundaries because its skipping that jmp

**Comment by dmtch** [comment]
It was very unsafe to delete a function during other function analysis. I need a bit time to think.

**Comment by radare** [comment]
The problem im talking about its in current master, didnt applied your patches yet.

**Comment by radare** [comment]
We should write much more code analysis tests and verify every analysis option as true, false and default

**Comment by dmtch** [comment]
I dropped those segfault-causes commits and rebased these normal.
I'll also test my other options, thanks.

**Comment by radare** [comment]
yeah logical and is fine too, lets wait for travis

**Comment by radare** [comment]
The last AVR search test doesnt passes because it doesnt cuts the function when it founds the RET

**Comment by radare** [comment]
i have marked it as broken and pushed all those commits.
thanks! can you look at this avr-search-broken test? thanks!

**Comment by dmtch** [comment]
Okay, I'll check it.

**Comment by dmtch** [comment]
https://github.com/radare/radare2/blob/master/libr/anal/p/anal_avr.c#L274
It's very strange that jmp is interpreted as R_ANAL_OP_TYPE_CJMP. What do you think?

**Comment by radare** [comment]
probably a bug in that code. i should read the avr cpu specs to see why this is wrong or right :)

**Comment by Darkkey** [comment]
@dmtch What's the difference (in terms or r2 analyzer) between R_ANAL_OP_TYPE_CJMP and R_ANAL_OP_TYPE_JMP?

**Comment by Maijin** [comment]
@Darkkey 

* CJMP https://github.com/radare/radare2/blob/master/libr/anal/op.c#L237
* JMP https://github.com/radare/radare2/blob/master/libr/anal/op.c#L247

**Comment by radare** [comment]
CJMP is conditional, JMP is not

**Comment by Darkkey** [comment]
Ah, than it's surely an error in AVR anal, could you change it to JMP? Thank you!

**Comment by Darkkey** [comment]
Nevermind, it seems to be more complicated case, I will look into it on the next week.

**Pull request closed without merging**
