### PR TITLE
Refs

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by radare** [comment]
not passing the tests

**Comment by dmtch** [comment]
I don't understand test "[  ]  1  x86_win:"
aaa
afi @ sub.kernel32.dll_ExitProcess_b2d ~ name
Function name is strange.

**Comment by Maijin** [comment]
The function is autorenamed thanks to aaa and the offset b2d corresponds to the offset of where the function is located

**Comment by dmtch** [comment]
This test is failed not for my patches.

**Comment by radare** [comment]
Please, focus on fixing the regression your patches introduce instead of pushing more additions in this branch, otherwise it makes it harder to review

**Comment by radare** [comment]
The reason why this test fails is because your patches break afna command. which is one of the post-analysis commands that is run by `aaa`. The `afna` command basically analyses the calls performed by a function that have no name `fcn.` prefix, and renames it to `sub.` +  something meaningful that is realted to the calls it does and its unique.

Here's a screenshot with and without your changes:

screen shot 2015-11-25 at 15 32 33

**Comment by radare** [comment]
We should probably improve the afna command and add more tests for it. Maybe this PR is a good place for that :)

**Comment by dmtch** [comment]
Thank you for explaination, I found my flaw.

**Comment by radare** [comment]
Awesome!

**Comment by radare** [comment]
LGTM :+1: 

thanks!

**Comment by dmtch** [comment]
Thanks :)

**Pull request closed without merging**
