### PR TITLE
Use letters instead of numbers for `ahi` bases

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by radare** [comment]
Please dont break current numeric input

**Comment by jvoisin** [comment]
But it's confusing as hell: I'm quite sure that we don't want to encourage users to use it, `2` for strings, `1` for binary, …

**Comment by radare** [comment]
DO IT

**Comment by Maijin** [comment]
@jvoisin as discussed don't forget help of `Vd`, `ah` and `ahi?`

**Comment by radare** [comment]
And add tests too

**Comment by radare** [comment]
Indentation is completelly wrong

**Comment by radare** [comment]
Change the " 10" for " [base]" and update the help message to explain letters and numbers

**Comment by radare** [comment]
Also, commands in comments in the switch case must be like `// "ahi"` this is useful for greping

**Comment by radare** [comment]
Fixed, squashed and merged!

**Pull request closed without merging**
