### PR TITLE
Add support to show comments and function name in axt

### PR DESCRIPTION
**Pull request by as0ler**
Enhance axt output · Issue #3843

### CODE REVIEW

**Comment by radare** [comment]
Use tabs to indent your code

**Comment by radare** [comment]
Wrong commit message `Addedupport`??

**Comment by radare** [comment]
Can you write some tests for this thing?

**Comment by Maijin** [comment]
I'll add more yes for comment and fcnname

**Comment by radare** [comment]
Fixed tests, your vimrc is fuckedup. i have used sys/indent.sh to fix the indentation, but the changes are hard to review. But looks good so far. thanks!

**Pull request closed without merging**
