### PR TITLE
rax2 support ternary values

### PR DESCRIPTION
**Pull request by kriw**
This is related to the issue #750 
Add these two commands,
```
ternary ->  int           ;  rax2 1010dt
ternary ->  hex           ;  rax2 212t
```

### CODE REVIEW

**Comment by kriw** [comment]
I thought it would be more readable than comparing e.g. `str[i] == 'd' && str[i+1] == 't'`.
And It can not be used switch comparing more than two characters like "dt"

**Comment by kriw** [comment]
I can revert these unnecessary changes.

**Comment by kriw** [comment]
Same to https://github.com/radare/radare2/pull/8818/commits/df173c9b38fd66ef0c640fb8460389fd89a16012 ?

**Comment by radare** [comment]
ill merge that way. at the end the str thing is just in rax2, not rnum, so its not really a performance issue. for the next time, please dont merge master, just rebase or dont do anything, otherwise the diff and the commit log is completely messed up

**Comment by radare** [comment]
also if you commit like this: "Fix #numberofissuhere" the issue will be closed automatically when merged

**Comment by kriw** [comment]
OK, thank you for your comments.

**Pull request merged**
