### PR TITLE
Cleanup meson files

### PR DESCRIPTION
**Pull request by pelijah**
- Using common codestyle

- Linking libs (libr2sdb, libr2zip, ...) without using "*.extract_all_objects()"

- Removed useless include directories

### CODE REVIEW

**Comment by xarkes** [comment]
Common codestyle?
`item : value` seems uglier than `item: value` (as in Yaml)

**Comment by pelijah** [comment]
It is style from mesonbuild docs/examples. But I can change it as well as indentation style.

**Comment by xarkes** [comment]
Ok well if meson suggests this style keep it.

**Comment by pelijah** [comment]
To be honest they don't suggest it.

**Comment by pelijah** [comment]
Well it is not "standard" but they use it in most manuals http://mesonbuild.com/Manual.html

**Comment by xarkes** [comment]
I think they don't suggest anything (http://mesonbuild.com/Qt5-module.html see here it is not uniformized).
So imho it's cleaner if you keep using `this: type` rather than `this : type`:
Otherwise, lgtm.

**Comment by pelijah** [comment]
https://github.com/radare/radare2/pull/9178#issuecomment-366554180
I added this "feature".

**Comment by xarkes** [comment]
Yep cool thanks!

**Pull request merged**
