### PR TITLE
Revert "Revert "Change `dr=` output""

### PR DESCRIPTION
**Pull request by radare**
This reverts commit 79087fbb2f00b318d32cbd72fb14d69ca133d176.

### CODE REVIEW

**Comment by radare** [comment]
@skuater wanna review this? im not completely happy with this change, and im afraid that changing register profiles can break something, but the proposal was interesting

**Comment by XVilka** [comment]
Should be this closed?

**Comment by radare** [comment]
was suposed to be reviewed during the debugger overhaul that will do when i am able to spend some time with it

**Comment by radare** [comment]
Closing as not mergeable after the last refactoring in debugger code

**Pull request closed without merging**
