### PR TITLE
Handle Zero Length Hashes #2784 rahash2 escape chars in -E #2783

### PR DESCRIPTION
**Pull request by jjdredd**

### CODE REVIEW

**Comment by jjdredd** [comment]
should fail bc of the help, see test patch in the regressions repo

**Comment by radare** [comment]
I'm still not sure if we really want a nonescaped string in -s

**Comment by jjdredd** [comment]
multihash? you mean when multiple algos are supplied with `-a` option?
I can remove `-E` option making `-s` behave like `-E` is now

**Comment by jjdredd** [comment]
see comment in my repo

**Comment by radare** [comment]
ive reverted the pr in r2r to get travis happy again

**Comment by jjdredd** [comment]
what what were you saying about hashing? I think I'm starting and finishing hash properly (line 92)

**Comment by radare** [comment]
Confirmed,. its wrong. the begin/end must be done outside the internal function, because it's used for incremental hashing. and this will break hashing huge files like hard disks. And also making it slower. the only part of the patch that matters is the len<1 one

**Comment by radare** [comment]
Another bug in this patch is that the resulting ranges for the 0 length string is 0:-1 instead of 0:0:
```
$  rahash2 -s ''
0x00000000-0xffffffffffffffff sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
This conflicts with he meaning of being an inclusive offset. aka `[]` instead of `[)` like it was before... this is a conceptual bug. and im not quite happy with any of the solutions unless we change that range to be from:+length

**Comment by jjdredd** [comment]
ok, I'll write a new patch.

**Pull request closed without merging**
