### PR TITLE
Support of little thread debug function

### PR DESCRIPTION
**Pull request by devnexen**
With little example use.

### CODE REVIEW

**Comment by radare** [comment]
lgtm, my only worry is portability, but we may discover that soon or late before the release i guess :D

**Comment by unixfreaxjp** [comment]
This caused errors in multiple FreeBSD compilers. The compilation is halt, no easy workaround, can not compile new builds due this error. These errors occurred during testing in 4 servers with is having recent updated FreeBSD ports on 64 and 32 bit architectures. For screenshot error messages during compilation can be viewed in https://twitter.com/malwaremustd1e/status/1107774696395669504
Errors is pointing to `libr/util/thread.c` codes that leads to inconsistency coding on `pthread_getname_np` and `pthread_get_name_np`, though out the BSD OS defection `ifdef` used.

Affected #FreeBSD users is advised to rollback to any commit before this commit  https://github.com/radare/radare2/commit/209427308dc342842076d0dcc823fb3d1b3645a4 until the problem is resolved. Or rollback related codes in `libr/include/r_th.h` ,  `libr/main/radare2.c` and `libr/util/thread.c`
For example, I am using this commit as rollback version: https://github.com/radare/radare2/commit/a404c7706366689f089cd30ea9d6cd4bde2560f5

**Comment by unixfreaxjp** [comment]
@radare you should add ` libr/include/r_th.h` on the impacted file list.

**Comment by unixfreaxjp** [comment]
Some versions of BSD 10 kernels that doesn't have/use `pthread_getname_np` and `pthread_get_name_np`, and you can not expect that radare2 FreeBSD users use box in generic way, so many of services and admins here are using production box and still using `/usr/include/pthread_np.h`  as pr pasted below. 
This matter is a forcing users to use specific build and abandons olders `pthread_np.h` in kernel. I suggest to revoke this commit, or avoiding using `/usr/include/pthread_np.h` for the purpose. Or else, radare2 is limited to specific versions on OS and please write those down. in details.

Some `/usr/include/pthread_np.h` snips:

```asm
   :
/*
 * Non-POSIX thread function prototype definitions:
 */
__BEGIN_DECLS
int pthread_attr_setcreatesuspend_np(pthread_attr_t *);
int pthread_attr_get_np(pthread_t, pthread_attr_t *);
int pthread_attr_getaffinity_np(const pthread_attr_t *, size_t, cpuset_t *);
int pthread_attr_setaffinity_np(pthread_attr_t *, size_t, const cpuset_t *);
int pthread_getaffinity_np(pthread_t, size_t, cpuset_t *);
int pthread_getthreadid_np(void);
int pthread_main_np(void);
int pthread_multi_np(void);
int pthread_mutexattr_getkind_np(pthread_mutexattr_t);
int pthread_mutexattr_setkind_np(pthread_mutexattr_t *, int);
void pthread_resume_all_np(void);
int pthread_resume_np(pthread_t);
void pthread_set_name_np(pthread_t, const char *);
int pthread_mutex_getspinloops_np(pthread_mutex_t *mutex, int *count);
int pthread_mutex_setspinloops_np(pthread_mutex_t *mutex, int count);
int pthread_mutex_getyieldloops_np(pthread_mutex_t *mutex, int *count);
int pthread_mutex_setyieldloops_np(pthread_mutex_t *mutex, int count);
int pthread_mutex_isowned_np(pthread_mutex_t *mutex);
int pthread_setaffinity_np(pthread_t, size_t, const cpuset_t *);
int pthread_single_np(void);
void pthread_suspend_all_np(void);
int pthread_suspend_np(pthread_t);
int pthread_switch_add_np(pthread_switch_routine_t);
int pthread_switch_delete_np(pthread_switch_routine_t);
int pthread_timedjoin_np(pthread_t, void **, const struct timespec *);
__END_DECLS
```

and 

```asm
     :
/*
 * Non-POSIX thread function prototype definitions:
 */
__BEGIN_DECLS
int pthread_attr_setcreatesuspend_np(pthread_attr_t *);
int pthread_attr_get_np(pthread_t, pthread_attr_t *);
int pthread_attr_getaffinity_np(const pthread_attr_t *, size_t, cpuset_t *);
int pthread_attr_setaffinity_np(pthread_attr_t *, size_t, const cpuset_t *);
int pthread_getaffinity_np(pthread_t, size_t, cpuset_t *);
int pthread_getthreadid_np(void);
int pthread_main_np(void);
int pthread_multi_np(void);
int pthread_mutexattr_getkind_np(pthread_mutexattr_t);
int pthread_mutexattr_setkind_np(pthread_mutexattr_t *, int);
void pthread_resume_all_np(void);
int pthread_resume_np(pthread_t);
void pthread_set_name_np(pthread_t, const char *);
int pthread_mutex_getspinloops_np(pthread_mutex_t *mutex, int *count);
int pthread_mutex_setspinloops_np(pthread_mutex_t *mutex, int count);
int pthread_mutex_getyieldloops_np(pthread_mutex_t *mutex, int *count);
int pthread_mutex_setyieldloops_np(pthread_mutex_t *mutex, int count);
int pthread_mutex_isowned_np(pthread_mutex_t *mutex);
int pthread_setaffinity_np(pthread_t, size_t, const cpuset_t *);
int pthread_single_np(void);
void pthread_suspend_all_np(void);
int pthread_suspend_np(pthread_t);
int pthread_switch_add_np(pthread_switch_routine_t);
int pthread_switch_delete_np(pthread_switch_routine_t);
int pthread_timedjoin_np(pthread_t, void **, const struct timespec *);
__END_DECLS

#endif
```

**Comment by unixfreaxjp** [comment]
To avoid portability conflict in FreeBSD from several versions, please minimize the using `/usr/include/` system library functions from the for radare2 codes. The beauty of radare2 is its portability quality on native codes that makes r2 can run in any platforms and compilers. 

This commit is YET another example how much trouble can occur on usage of system's library that older systems are not supporting/using them.

**Comment by radare** [comment]
Should be fixed now, those issues are expected to happen in git, and most of them can be fixed in just one line, dont panic.

until we get freebsd (and other OS) support in CI we wont be able to catch that stuff during the development cycle of r2.

Let me explain that, because maybe it wasnt clear for everyone:

* R2 makes a new release every 6 weeks
* First week after the release focuses on merging/fixing issues reported by users, if anything happens I do a minor release to address that
* The following 4 weeks are used to introduce new features, breaking changes, heavy refactorings, experiments...
* The last week before the release we focus on fixing bugs, testing, improving stability, cleaning code, ..

This week is the last week of the 4 that allow us to introduce new stuff and break things, you can always revert the specific commit (use git blame + grep to find out which commit touched that specific line) and then (git revert <commit>) to fix the issue if you really need r2 to work on that platform. But again, until we get CI working on those platforms we cant ensure that every commit we merge makes everyone happy until the last week before the release, where, (at least me, spend time building on all my machines (mips, ppc, x86-32, arm, ..)

Feel free to push travis or setup a CI system (just cron+sys/install.sh) should be enough , because cron sends a mail in case of failure, so we will get notified when any commit breaks something and address that before its too late.

in additioni, if you use git in production, and you are afraid of git pull and having broken builds use make install instead of make symstall to copy the executables in $PREFIIX instead of symlinkinig them, this way you will always have a working r2 installed (or keep multiple copies of r2 in your home, and rotate git pull when the git one works)

**Comment by unixfreaxjp** [comment]
Thank you for adding the FreeBSD version recognition below:
```c
elif (__FreeBSD__ &&  __FreeBSD_version >= 1200000) || __DragonFly__ /* (snipped)
```
..merged in https://github.com/radare/radare2/pull/13428/commits/d28b6b7af647c1aea0408958ae21f7a06885cb6e

The test-build has no error anymore, now going to the production.
```asm
radare2 3.4.0-git 21221 @ freebsd-x86-64 git.3.3.0-198-g59cfc2bb3
commit: 59cfc2bb3f3eda9f86d7615e12db801f07bf1d47 build: 2019-03-19__11:41:08

radare2 3.4.0-git 21446 @ freebsd-x86-32 git.3.3.0-198-g59cfc2b
commit: 59cfc2bb3f3eda9f86d7615e12db801f07bf1d47 build: 2019-03-19__20:40:53
```
This issue in FreeBSD https://github.com/radare/radare2/pull/13343 is solved.

**Pull request merged**
