### PR TITLE
(webui) infinite scroll in /p

### PR DESCRIPTION
**Pull request by pwntester**
for beta testing

### CODE REVIEW

**Comment by radare** [comment]
This change seems to be quite catastrophic for Firefox (no context menu, and broken graph). also when scrolling the selected offset is lost and the scroll makes a jump that makes you loss the track of the code because it needs to scroll up a bit

**Comment by pwntester** [comment]
Will review the lack of context menu and broken graph.
As for the lost selected offset, this is something we have to accept if we want infinite scrolling since we cannot keep all instructions so we have to discard the ones far from current view point. Its easy to return to the last offset using the history stack though

**Comment by pwntester** [comment]
Ok, found and fixed the bug for context menu and broken graph
now,what should we do with selected address. We should select an address but if user selected address goes offview, should we select the closest address to the user selected one?

**Comment by radare** [comment]
if it goes out it should seek there, but the scrolling gaps must be fixed, one solution for forward scrolling would be to not remove the previous disassembled code to keep scroll position, otherwise we should recalculate the offset of each address, maybe with # a hrefs, but this will do it a little slower.

**Comment by radare** [comment]
Doesnt seems to work, it easily gets into an infinite loop (scrolling down) and hang (scrolling up) because buffer is smaller than screen and there's no scroll.

**Comment by pwntester** [comment]
Cannot reproduce, even with r2 - but has added a check to verify if div is scrollable or not

**Comment by radare** [comment]
Merged. while it still needs some work

**Pull request closed without merging**
