### PR TITLE
Add SIB addressing support to nz compiler [Fix #3644]

### LINKED ISSUE #3644: The x86 handmade assembler (x86.nz) can not handle SIB addressing
Currently the x86.nz assembler plugin can not assemble instructions where scale-index-base addressing is used. Example:

```
[0x00 radare2]$ echo 'mov eax, dword [eax*4+0x1337]' | rasm2 -a x86.nz -
8b4037
```

The same with x86.nasm:

```
[0x00 radare2]$ echo 'mov eax, dword [eax*4+0x1337]' | rasm2 -a x86.nasm -
8b048537130000
```

### PR DESCRIPTION
**Pull request by Svenito**
Add support for SIB addressing as per issue #3644

Added regressions tests for these cases via PR radare/radare2-regressions#396

### CODE REVIEW

**Comment by ret2libc** [comment]
It looks good to me.

**Comment by ret2libc** [comment]
Please squash the last four commits into a single one, since they are all about the same thing. I'll merge it then.

**Comment by radare** [comment]
Thanks!

**Comment by radare** [comment]
github can squash too :3

**Comment by ret2libc** [comment]
But not only some commits :P

**Comment by Svenito** [comment]
squished the last 4 into one

**Comment by radare** [comment]
? it was merged 1h ago, no need to squash anything now

**Pull request merged**
