### PR TITLE
anal_mips_cs: fixed wrong order of operands in ESIL

### PR DESCRIPTION
**Pull request by mrmacete**
when a memory reference had a negative offset, the ESIL subtraction was inverted

### CODE REVIEW

**Comment by radare** [comment]
Please, remove that branch and do not pull from master in a branch you are pullreq

**Comment by radare** [comment]
(i have merged)

**Comment by mrmacete** [comment]
ok, so the correct way to keep in sync is to remove the forked repo and recreate it at before each pull request?

**Comment by radare** [comment]
No. Just create a nrw branch from master. The idea is:

* you have a fork of the repo
* when you wanna send a pr:
  - git checkout master
  - git pull https://...
  - git checkout -b newbranch
* do your stuff here
* git push 
* create the pullreq from the website using that branch as base and target the naster of my repo

**Comment by mrmacete** [comment]
oh, thanks, got it.

**Pull request closed without merging**
