### PR TITLE
fix #6332

### LINKED ISSUE #6332: pd removing part of the opcode string
Some Dalvik opcodes are being truncate by pd command. Check the following examples:

```
r2 radare2-regressions/bins/dex/HelloWorld.dex
```
```
[0x0000025c]> ao
address: 0x25c
opcode: sget-object v0, Ljava/lang/System;
prefix: 0
id: 98
bytes: 62000400
refptr: 0
size: 4
type: load
stack: null
family: cpu
[0x0000025c]> pd 1
            ;-- entry0:
            ;-- LHello.method.main([Ljava/lang/String;)V:
            0x0000025c      62000400       sget-object v0
[0x0000025c]>
```
Another example:
```
[0x0000025c]> s 0x0000026a
[0x0000026a]> pd 1
            0x0000026a      22000100       new-instance v0
[0x0000026a]> ao
address: 0x26a
opcode: new-instance v0, LHello;
prefix: 0
id: 34
bytes: 22000100
ptr: 0x000000f0
refptr: 0
size: 4
type: new
stack: null
family: cpu
[0x0000026a]>
```

### PR DESCRIPTION
**Pull request by h4ng3r**
This ugly hack for Dalvik is chopping some opcodes. Colors are not working for Dalvik, so I decided to comment this hack. Maybe we should move colorize code to plugins.

### CODE REVIEW

**Comment by radare** [comment]
Can u add a test for r2r?

**Comment by alvarofe** [comment]
Commenting that out breaks other stuffs, doesn't it?

**Comment by h4ng3r** [comment]
@alvarofe travis is green now ;)
@radare test case:
```
r2 -qc "pi 1; ao~sget" radare2-regressions/bins/dex/HelloWorld.dex
sget-object v0
opcode: sget-object v0, Ljava/lang/System;
```
As you can see pi 1 cuts the opcode after the first ",".

I think that fixing colors is not simple... I'll need to understand them first. But fixing the chop seems more important than fixing colors, which I'll do it someday.

**Comment by radare** [comment]
Bug confirmed, tried to fix but seems like a little mess. requires a deeper look to fix. thanks for the test! can you or @Maijin put that test in r2r?

thanks!

**Comment by h4ng3r** [comment]
@radare I'll put the test in r2r in 1hour. Thanks

**Pull request merged**
