### PR TITLE
Add mz bin plugin

### PR DESCRIPTION
**Pull request by Nodepad**

### CODE REVIEW

**Comment by Maijin** [comment]
@Nodepad No worries if Travis is happy that means your PR pass the testsuite, AppveyorCI is still WIP

**Comment by radare** [comment]
Machine is wrong. Mz bins run on 286 too

**Comment by radare** [comment]
The btree patch is unrelated, right?

**Comment by radare** [comment]
Oh i see how is it used. I would preferilky use sdb only. But the overall patch looks good to me. Can you submit some case uses fot sdb?
Thanks!

**Comment by Nodepad** [comment]
I've copied machine from pe plugin. MZ can run on hardware starting from 8086. Should machine be "8086"?
I don't know how to use sdb. I've just added it like in pe plugin.

**Comment by radare** [comment]
Merged! thanks!

**Pull request closed without merging**
