### PR TITLE
Nix forced echo on breakpoint commands (#7724)

### PR DESCRIPTION
**Pull request by puxlit**
This isn't a complete excision of `scr.echo`; it just removes the bit responsible for #7724.

I gather regression tests are desirable?

### CODE REVIEW

**Comment by radare** [comment]
ah i think that eco was forced to have realtime feedback on the output of the commands, otherwise ?e foo will not work until the process gets back to the prompt

**Comment by puxlit** [comment]
Are there reasons for why we can't call `r_cons_flush` in `r_core_debug_breakpoint_hit` instead?

**Comment by radare** [comment]
it will flush everything that happened before executing the command, so maybe we need to grab the previous output , clear the buffer, run the command, flush the output and bring back the buffer, so we dont loss stuff

**Comment by puxlit** [comment]
Ah, gotcha.

**Comment by puxlit** [comment]
```
[0x7fff98834f46]> db sym._setCallback
[0x7fff98834f46]> dbte sym._setCallback
[0x7fff98834f46]> "dbc sym._setCallback ? `dr?rax`"
[0x7fff98834f46]> ?e we should only see this just before the prompt returns;dc
hit tracepoint at: 10de6ca60
4 0x4 04 4 0000:0004 4 "\x04" 00000100 4.0 4.000000f 4.000000
hit tracepoint at: 10de6ca60
5 0x5 05 5 0000:0005 5 "\x05" 00000101 5.0 5.000000f 5.000000
hit tracepoint at: 10de6ca60
6 0x6 06 6 0000:0006 6 "\x06" 00000110 6.0 6.000000f 6.000000
hit tracepoint at: 10de6ca60
7 0x7 07 7 0000:0007 7 "\a" 00000111 7.0 7.000000f 7.000000

==> Process finished

we should only see this just before the prompt returns
[0x10de6ca61]>
```

**Comment by radare** [comment]
ok to merge now?

**Comment by radare** [comment]
looks like it does

**Pull request merged**
