### PR TITLE
Some memory leak fixes

### PR DESCRIPTION
**Pull request by dequis**
A few hours of work yesterday. Pull requesting since i'm not doing much progress on this stuff today.

Just dealing with the simplest use case mentioned in #1222, filtering to definite leaks only.

    valgrind --leak-check=full --show-leak-kinds=definite r2 =true

Before:

    definitely lost: 64,328 bytes in 672 blocks

After:

    definitely lost: 62,440 bytes in 600 blocks

### CODE REVIEW

**Comment by radare** [comment]
The  purge -> free change in rreg is wrong. its producing a crash when using the debugger, merged the other two

**Comment by dequis** [comment]
Ouch. That wasn't caught by the test suite.

...does test suite even cover *anything* debugger related?

**Comment by Maijin** [comment]
@dequis yes but it's not cover by the TravisCI but by the JenkinsCI, you should also run it by yourself before pushing code or PR; https://github.com/radare/radare2-regressions/tree/master/t.archos <- Debugger tests

**Comment by radare** [comment]
yes. there are debugger related test cases. but iirc those only run in jenkins. not travis. and i reproduced the issue on osx. maybe is ok on linux, didnt tried. but that was the reason i was using purge instead of freee. to avoid freeing the stored pointers because they are freed somewhere else iirc.

**Comment by dequis** [comment]
Okay. `t.archos` isn't running in linux because the makefile expects `$(shell uname)-$(shell uname -m)` (`Linux-x86_64`) and the directory is called just `Linux`

```
[dx@bolsa radare/r2-regressions/t.archos]$ ls -l
total 4
drwxr-xr-x 1 dx users  62 May  6 21:43 Darwin-x86_64
drwxr-xr-x 1 dx users 138 Aug 29 02:55 Linux
-rw-r--r-- 1 dx users 111 Aug 30 18:44 Makefile

[dx@bolsa radare/r2-regressions/t.archos]$ make
[ -d "Linux-x86_64" ] && ( cd .. && sh run_tests.sh t.archos/Linux-x86_64 )
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
```

(removed the `@` and `|| true` so that it wouldn't fail silently)

**Comment by radare** [comment]
type sh run_tests.sh t.archos

**Comment by dequis** [comment]
Moving this to a ticket in the regressions repo: https://github.com/radare/radare2-regressions/issues/217

**Pull request closed without merging**
