### PR TITLE
adding initial support for PIC18C diassem.

### PR DESCRIPTION
**Pull request by oddcoder**
I tried to add initial support to pic18cxx instruction set which is 16bit mcu
to the best :)

### CODE REVIEW

**Comment by oddcoder** [comment]
I think I fixed all these notes and that if(1) !!

**Comment by oddcoder** [comment]
I have added some test cases in radare-regression for the pic18c

**Comment by radare** [comment]
OMG do not ever git pull from master in a pr :__ im fixing the conflicts by hand

**Comment by radare** [comment]
Merged!

**Pull request closed without merging**
