### PR TITLE
corrected minor spelling and grammar mistakes

### PR DESCRIPTION
**Pull request by NaveenBoggarapu**
I have corrected some minor spelling and grammar mistakes.

PS: This is mainly to understand the technicality about how to commit and create pull request.

### CODE REVIEW

**Comment by NaveenBoggarapu** [comment]
All the changes done are in the comments part, how did it AppVeyor build failed?

**Comment by radare** [comment]
You are welcome, but I think this commit can contain more stuff  in here. the sentence itself looks a bit wrong to me, what about:

```
- When the above conditions are satisfied, feel free to submit an issue,
+ When the above conditions are satisfied, you should be ready to describe the issue,
```

But i guess there will be more places to fix this thing. i would like to merge this patch, but in a more wide way, not just for 2 little fixes.

**Comment by radare** [comment]
The PR is correct, but not the username of your commit. configure your git properly plz:
```
Author: Naveen Boggarapu <NaveenBoggarapu@users.noreply.github.com>
```

**Comment by NaveenBoggarapu** [comment]
What is PR?

User name is correct, Do you mean my mail id?

**Comment by Maijin** [comment]
PR == Pull Request
See this https://help.github.com/articles/setting-your-email-in-git/

**Comment by NaveenBoggarapu** [comment]
Ok, Should I be submitting a new pull request after changing user name and recommitting?
Or is there a procedure to do it?

**Comment by radare** [comment]
Just squash and push -f

**Comment by NaveenBoggarapu** [comment]
I have also added a fix for an issue I have encountered.

**Comment by radare** [comment]
still wrong

**Comment by NaveenBoggarapu** [comment]
Did it again, please check it once.

This is the configuration made on my machine.

```
naveen@naveen:~/Workspace/radare2$ git config --global user.email
NaveenBoggarapu@users.noreply.github.com
naveen@naveen:~/Workspace/radare2$ git config --global user.name
NaveenBoggarapu

```

Sorry for the trouble, this is my first pull request.

**Comment by radare** [comment]
this is not a valid email address

**Comment by radare** [comment]
anyway, can you submit more grammar fixes/misstakes? i would prefer to merge PRs with more content than just 2 nazi-grammar lines.

**Comment by NaveenBoggarapu** [comment]
This is mainly to check the pull request.
I am currently working on fixing this issue #4482. I have this issue encountered while using radiff2.

**Comment by NaveenBoggarapu** [comment]
Corrected my mail id.

**Comment by NaveenBoggarapu** [comment]
Added fix to some memory leaks

**Comment by radare** [comment]
do not *EVER* merge in a branch

**Comment by radare** [comment]
squash and rebase the changes on master instead of merging branches

**Comment by NaveenBoggarapu** [comment]
rebased.

**Comment by radare** [comment]
merged now! thanks!

**Pull request closed without merging**
