### PR TITLE
Fix default case detection in jump table analysis

### PR DESCRIPTION
**Pull request by io12**

### CODE REVIEW

**Comment by radare** [comment]
the change looks reasonable

**Comment by XVilka** [comment]
Travis is red though.

**Comment by io12** [comment]
Travis fails with most new PRs from the looks of it. I don't think it is related to my patch.

**Comment by XVilka** [comment]
Can you please rebase it?

**Comment by io12** [comment]
Okay, I just rebased now.

**Comment by XVilka** [comment]
There are many failed tests after that, like:
```
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i /tmp/tmp-153545usXHK7AEiof.tmp /home/travis/build/radare/radare2/radare2-regressions/bins/jmptbl/test_clang_5.0_32.out
aaa
f~switch
f~case.
 0x080483fd 1 switch.0x080483fd
 0x0804840d 1 case.0x80483fd.0
 0x08048404 1 case.0x80483fd.1
 0x08048404 1 case.0x80483fd.2
 0x08048404 1 case.0x80483fd.3
 0x08048416 1 case.0x80483fd.4
-0x0804841f 1 case.0x80483fd.5
-0x08048428 1 case.0x80483fd.6
-0x08048431 1 case.0x80483fd.7
-0x0804843a 1 case.0x80483fd.8
-0x08048431 1 case.0x80483fd.9
-0x08048443 1 case.0x80483fd.10
-0x0804844c 1 case.0x80483fd.11
-0x08048455 1 case.0x80483fd.12
 0x08048431 1 case.default.0x8048431
-
EXPECT64=MHgwODA0ODNmZCAxIHN3aXRjaC4weDA4MDQ4M2ZkCjB4MDgwNDg0MGQgMSBjYXNlLjB4ODA0ODNmZC4wCjB4MDgwNDg0MDQgMSBjYXNlLjB4ODA0ODNmZC4xCjB4MDgwNDg0MDQgMSBjYXNlLjB4ODA0ODNmZC4yCjB4MDgwNDg0MDQgMSBjYXNlLjB4ODA0ODNmZC4zCjB4MDgwNDg0MTYgMSBjYXNlLjB4ODA0ODNmZC40CjB4MDgwNDg0MzEgMSBjYXNlLmRlZmF1bHQuMHg4MDQ4NDMxCg==
[XX] db/anal/x86 clang_5.0_64 switch/case flags  208
```
Feel free to check Travis logs

**Comment by radare** [comment]
please rebase and take care of those regressions

**Comment by XVilka** [comment]
@io12 ping?

**Comment by io12** [comment]
Sorry I don't have time to fix this right now.

**Comment by ret2libc** [comment]
Also @io12 could you provide a test in r2r or a binary that shows the wrong behaviour in current master and how your patch fixes it? It would help a lot, thanks!

**Comment by ret2libc** [comment]
As of right now, the patch seems wrong. I'm looking at the test `[XX] db/anal/x86 clang_5.0_64 switch/case flags  192` and the cases that are removed shouldn't be.

**Comment by io12** [comment]
The patch fixes detection of the `default` case with `aaaa` in `sym.phase_3` in the CMU binary bomb.
[bomb.zip](https://github.com/radare/radare2/files/2246258/bomb.zip)

**Comment by ret2libc** [comment]
@io12 This was definitely very useful to detect the problem! See PR https://github.com/radare/radare2/pull/10879 for the proper fix. Unfortunately RAnalOp.type is a mix of different values, so you can't just do `&`, but you have first to mask it with the proper mask and then use the usual `=`, `!=`, etc.

Can we add bomb binary to our test suite in https://github.com/radare/radare2-regressions? So we can prevent regressions. Are you willing to do a PR in radare2-regressions to include the binary and add a test to check the correct switch tables are detected? :)

**Comment by io12** [comment]
Yes I can do that, but first there's the issue where the cases are detected as individual functions with `aa`, which prevents them from being displayed as cases.

**Pull request closed without merging**
