### PR TITLE
Store Anal Classes list in own Namespace ##anal ##classes

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by radare** [comment]
can you access it via the `k`  command?

**Comment by thestr4ng3r** [comment]
It's in sdb, so yes of course. Or what do you mean?

**Comment by radare** [comment]
its nested inside another sdb referenced from the root one?

**Comment by thestr4ng3r** [comment]
The classes list is in `anal/classes` (for every class `ClassName=c`), the attrs are in `anal/classes/attrs`.

**Comment by radare** [comment]
dont use more than one ##tag

**Pull request merged**
