### PR TITLE
Pava is back

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by Maijin** [comment]
@condret ^

**Comment by radare** [comment]
i want to improve pava more before merging, ill try to find some time before the release and show clear examples about its usecases

**Comment by xarkes** [comment]
What's the purpose of pava?
Wasn't it removed because it was useless?

**Comment by radare** [comment]
no, it was removed because condret didnt understood the purpose and because it was depending on rbin sections which will be deprecated and the option to enable it was inside r-io, which wasnt the right place

**Comment by radare** [comment]
the purpose is to have a way to view the virtual address specified by the rbin headers when disassembling physical addresses, this is how IDA, HIEW and many other tools work, basically because that’s the only way to have a linear view of the executable and being able to modify header data structures without depending on having them mapped in memory.

**Comment by xarkes** [comment]
Ah ok, that's clearer, thanks!

**Comment by radare** [comment]
i just rebased

**Pull request merged**
