### PR TITLE
Add NOOK

### PR DESCRIPTION
**Pull request by Maijin**

### CODE REVIEW

**Comment by radare** [comment]
THANK YOU

**Comment by ret2libc** [comment]
@Maijin also add that to travis-extract-var please, otherwise it's not passed to docker

**Comment by radare** [comment]
ok to merge for me

**Comment by radare** [comment]
no need to wait for travis

**Comment by ret2libc** [comment]
No, change is useless I believe. NOOK is already set in travis-script

**Comment by ret2libc** [comment]
Not necessary, NOOK is already in https://github.com/radare/radare2/blob/master/travis-script#L28.

**Pull request closed without merging**
