### PR TITLE
fixes #5418

### LINKED ISSUE #5418: Linux coredump warning
Is [it](https://github.com/radare/radare2/blob/master/libr/debug/p/native/linux/linux_coredump.c#L627) a good idea to overrun a buffer ([def here](https://github.com/radare/radare2/blob/master/libr/bin/format/elf/glibc_elf.h#L89))?

```c
// definition
typedef struct
{
  unsigned char	e_ident[EI_NIDENT];	/* Magic number and other info */
  Elf64_Half	e_type;			/* Object file type */

//..

// weird overrun
	/* buffer overrun here */
	h->e_ident[EI_NIDENT] = EI_NIDENT;
	h->e_type = ET_CORE;
```

### PR DESCRIPTION
**Pull request by l4l**

### CODE REVIEW

**Comment by radare** [comment]
uhm.. i dont think think this is correct fix cc @leberus can you review it?

**Comment by l4l** [comment]
Well, I've checked man & some random elfs at my system. Looks fine

**Comment by radare** [comment]
Btw, for consistency is better to start all commit messages in uppercase. Also, using Fix instead of fixes and making hhe message a bit more descriptive to not need to read the diff or access github to understand whats going on

**Comment by l4l** [comment]
Ok, i'll bear that in mind

**Comment by leberus** [comment]
Thanks for fixing that!
Btw, I managed to get an arm board, so next week I expect to be able to
port the code to ARM platform.

El dia 30/07/2016 7:05 PM, "Eugene" <notifications@github.com> va escriure:

**Comment by radare** [comment]
Cool :)

**Pull request merged**
