### PR TITLE
Modified fn command to rename flag

### PR DESCRIPTION
**Pull request by xarkes**
I copy pasted the code from vmenus.c and removed every input prompt so now you can rename from the command line.

### CODE REVIEW

**Comment by radare** [comment]
thats what afn does. flags are not functions, dont mix concepts

**Comment by xarkes** [comment]
Well then what is the alternative for Vdn without using V?

**Comment by radare** [comment]
I think visual does fn and afn. But didnt checked the code. Maybe afn should do fn automatically?

**Comment by radare** [comment]
We should do this in a separate command under 'a'. we decided to use the `an`. please update the PR with this change

**Pull request merged**
