### PR TITLE
Set the core offset right and update the panels correctly when scrolling disassembly##panels

### PR DESCRIPTION
**Pull request by Vane11ope**
Removed the "refresh" parameter from Panel so that all the panels will be refreshed all the time. 
The core offset was not set right in some places, now they are fixed.
Some fixes and refactoring are additional.

### CODE REVIEW

**Comment by radare** [comment]
Isnt this making it slow ?

**Comment by Vane11ope** [comment]
@radare not critically but i might have second thought. im getting it back wait.

**Comment by Vane11ope** [comment]
@radare done. this is better. please edit the commit message like the title of this PR which i edited when you squash and merge. thank you :)

**Comment by Vane11ope** [comment]
oh thought i messed up but actually master was red.

**Comment by radare** [comment]
appveyour build is unhappy

**Comment by radare** [comment]
please rebase master is green

**Pull request merged**
