### PR TITLE
[WIP] Meson: enable Propeller and Java

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by XVilka** [comment]
Looks a bit hackish. But still does the job.

**Comment by pelijah** [comment]
But java test still fails...

**Comment by pelijah** [comment]
So java tests not fail now?

**Comment by xarkes** [comment]
No, they fail.

**Comment by pelijah** [comment]
Hmm ok. Maybe it requires updating list of anal pugins in libr/meson.build? I want to add commit with this changes but PR was already merged.

**Comment by xarkes** [comment]
Yes it's missing here, make another PR.

**Pull request merged**
