### PR TITLE
libr/parse: add another view for function variable/arguments

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by XVilka** [comment]
May be show the type of the variable in the comments too (or wherever you think it's better)? Sometimes it's helpful without scrolling back and forth.

**Comment by ret2libc** [comment]
BTW, new tests at https://github.com/radare/radare2-regressions/pull/755 . 

This is the format with `asm.varsub_only=true` (default):
```
; var int local_40h @ rsp+0x40
mov rax, qword [local_40h]
```
while this is the one with `asm.varsub_only=false`:
```
; var int local_40h = 0x40
mov rax, qword [rsp + local_40h]
```

**Comment by ret2libc** [comment]
@XVilka I think that's for another PR. Also I'm not sure right now of a good solution for that problem... I *don't want* to add yet another comment, there are already too many.

**Comment by Maijin** [comment]
Well this  var int local_40h = 0x40 remain false btw, because if you do `afvd local_40h` it will not be 0x40.

**Pull request merged**
