### PR TITLE
small msp430 improvements

### PR DESCRIPTION
**Pull request by BenGardiner**
see also https://github.com/radare/radare2-regressions/pull/1574

### CODE REVIEW

**Comment by radare** [comment]
if you use the same branch name in r2 and r2r, travis will run your fork and be green ( i guess)

**Comment by Maijin** [comment]
My bad I merged the PR in r2r however the last travis was showing that your PR did not fix the issue see XX] in the log.

If you see a FX then it means it's fixed

**Comment by BenGardiner** [comment]
> if you use the same branch name in r2 and r2r, travis will run your fork and be green ( i guess)

there's a branch of the same name in my r2r fork right now which fixes tests. do I need to kick anything?

**Comment by radare** [comment]
i've pressed the button. lets wait for travis

**Pull request merged**
