### PR TITLE
A bit more documentation on ESIL (for AVR) does not hurt

### PR DESCRIPTION
**Pull request by brainstorm**
Just a bit more practical docs for ESIL so that newbies like e are not completely lost when approaching this ;)

### CODE REVIEW

**Comment by Maijin** [comment]
Please also update https://github.com/radare/radare2book/blob/master/esil.md

**Comment by Maijin** [comment]
Also your fix break build on windows => https://ci.appveyor.com/project/radare/radare2-shvdd/build/0.10.3.6918#L2993 Please fix

**Comment by brainstorm** [comment]
Wouldn't it make sense to get rid of one of the documentation(s)? @radare ??

**Comment by radare** [comment]
well doc/* is installed in system, the other requires interwebs access.. so i think its ok to have dup here, but maybe is the book who should rip the doc from the src

**Comment by brainstorm** [comment]
What about moving/substituting all doc/* for all the *.md's. They are still
pretty readable in plaintext and docs could be autogenerated :)

**Comment by radare** [comment]
autogenerated from source?

**Comment by brainstorm** [comment]
I mean sth like this: https://readthedocs.org/

or this actually:

https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

**Pull request merged**
