### PR TITLE
Kill msvc2

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by XVilka** [comment]
You forgot https://github.com/radare/radare2/blob/master/meson.build#L107

**Comment by radare** [comment]
```
$ git grep include/msvc
libr/include/r_getopt.h:* libr/include/msvc/getopt.h
meson.build:  platform_inc += ['libr/include/msvc']
sys/msvc.sh:INC_DIR=$(cygpath -aw $(pwd)/libr/include/msvc)
```

**Comment by radare** [comment]
why is cygpath in there? wasnt that removed from master?

**Comment by radare** [comment]
Screenshot 2019-03-18 at 13 16 37

**Comment by XVilka** [comment]
So shouldn't be merged then?

**Comment by radare** [comment]
not yet, still fixing appveyour

**Comment by XVilka** [comment]
```
       "C:\projects\radare2-shvdd\build\radare2.sln" (default target) (1) ->
       "C:\projects\radare2-shvdd\build\shlr\cafa177@@r2qnx@sta.vcxproj" (default target) (9) ->
       (ClCompile target) -> 
         c:\projects\radare2-shvdd\shlr\qnx\include\packet.h(6): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\projects\radare2-shvdd\build\shlr\cafa177@@r2qnx@sta.vcxproj]
       "C:\projects\radare2-shvdd\build\radare2.sln" (default target) (1) ->
       "C:\projects\radare2-shvdd\build\shlr\cafa177@@r2zip@sta.vcxproj" (default target) (14) ->
         c:\projects\radare2-shvdd\shlr\zip\zip\zip_close.c(46): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\projects\radare2-shvdd\build\shlr\cafa177@@r2zip@sta.vcxproj]
       "C:\projects\radare2-shvdd\build\radare2.sln" (default target) (1) ->
       "C:\projects\radare2-shvdd\build\libr\util\dc150f5@@r_util@sta.vcxproj" (default target) (18) ->
         c:\projects\radare2-shvdd\libr\util\calc.c(15): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\projects\radare2-shvdd\build\libr\util\dc150f5@@r_util@sta.vcxproj]
    172 Warning(s)
    3 Error(s)
Time Elapsed 00:01:36.22
[r2-meson][ERROR]
```

**Comment by radare** [comment]
Soon

**Comment by radare** [comment]
Screenshot 2019-03-19 at 12 48 46

**Pull request merged**
