### PR TITLE
Fix: useless pnote pointer and small fix within has_map_anonymous_con…

### PR DESCRIPTION
**Pull request by leberus**
Small fixup within has_map_anonymous_content (typo error) and delete pnote pointed

### CODE REVIEW

**Comment by radare** [comment]
thanks! im gonna adapt and merge your patch after mine.

**Comment by radare** [comment]
merged!

**Comment by radare** [comment]
this var was not useless. this patch introduced new bugs. i have fixed this in my commit after yours. please test stuff before sending prs

**Comment by leberus** [comment]
Oh yes, soz, I didn't think about it. Was to point the var at the start again.

**Pull request closed without merging**
