### PR TITLE
Fixes ELF Segfault

### PR DESCRIPTION
**Pull request by ninjahacker**
This addresses issue #2321 . The solution may not be acceptable, or it may be interesting to use for other similar situations. We don't know ahead of time if the fields in the ELF header are correct or bogus. This ignores them and checks whether a pointer is in mmap'd addressable memory by catching a segfault signal if it is sent. We can exit gracefully if caught. Some info in r2 is still weird when the ELF header is fake, but at least it doesn't crash.

### CODE REVIEW

**Comment by crowell** [comment]
can you do this on a new branch sync'd with master?

**Comment by ninjahacker** [comment]
I thought that would be automatic. I don't think I understand pulling and syncing.

**Comment by ninjahacker** [comment]
Okay, I think it is up to date.

**Comment by radare** [comment]
Please rebabse the commits into a single squashed one on a new clean branch. Do not ever do merges os sync with master in pullrequed branches

**Comment by radare** [comment]
ping

**Comment by ninjahacker** [comment]
I understand rejecting the pull. I wasn't sure if the fix would be allowed, but I believe this issue is still open. I'm reading up on git. I'm a newbie using it. It's very confusing compared to svn. Should pull requests be in a separate branch?

**Comment by radare** [comment]
Yes, each pullreq must be done in a different branch in your forked repository. Never git pull from my repo in those branches, just commit your changes in there. Can you still reproduce the elf crash? because i already fixed it today. can you confirm?

**Comment by ninjahacker** [comment]
No, sorry. You are correct. It is fixed. I didn't realize you submitted a patch for this.

**Pull request closed without merging**
