### PR TITLE
Show string cmt even if \t, \r or \n at start

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
If you print tabs the visual and graph will break

**Comment by kazarmy** [comment]
A tab is not printable by the [definition of IS_PRINTABLE](https://github.com/kazarmy/radare2/blob/401d36af959fabca6552464b56183173ca8a7c73/libr/include/r_util/r_str_util.h#L11). So:

- If `strlen (msg) != 1` then the tab is processed by `r_str_filter` and [gets turned into a dot](https://github.com/kazarmy/radare2/blob/401d36af959fabca6552464b56183173ca8a7c73/libr/util/str.c#L1590-L1591).
- If `strlen (msg) == 1` then the tab is processed by [line 2773 of disasm.c](https://github.com/kazarmy/radare2/blob/401d36af959fabca6552464b56183173ca8a7c73/libr/core/disasm.c#L2773) and [gets turned into the escape sequence `\x09`](https://github.com/kazarmy/radare2/blob/401d36af959fabca6552464b56183173ca8a7c73/libr/core/disasm.c#L2770-L2773). Line 2773 will be executed due to the `if` statement at [line 2761](https://github.com/kazarmy/radare2/blob/401d36af959fabca6552464b56183173ca8a7c73/libr/core/disasm.c#L2761).

Despite the inconsistency, an actual tab will not be printed either way and thus the visual and graph won't break.

**Comment by radare** [comment]
Can we have a test?

**Comment by kazarmy** [comment]
Yes. See radare/radare2-regressions#815.

**Pull request merged**
