### PR TITLE
improvements of asm.pseudo for x86 (jmp,test,cmp,etc..)

### PR DESCRIPTION
**Pull request by wargio**
Fixes https://github.com/radare/radare2/issues/7581

### CODE REVIEW

**Comment by wargio** [comment]
```
│           0x0044e30c      39356c0a4900   var = dword [0x490a6c] - esi ; [0x1d:4]=0
│       ┌─< 0x0044e312      0f85b0000000   if (var != jne) goto 0x44e3c8
│       │   0x0044e318      6800080000     push 0x800
│       │   0x0044e31d      56             push esi
│       │   0x0044e31e      683c944600     push 0x46943c
│       │   0x0044e323      ff1538424600   dword [sym.imp.KERNEL32.dll_LoadLibraryExW] () ; 0x464238 ; "R\xaa\b"
│       │   0x0044e329      8bf8           edi = eax
│       │   0x0044e32b      85ff           var = edi & edi
│      ┌──< 0x0044e32d      7526           if (var != jne) goto 0x44e355
│      ││   0x0044e32f      ff1514414600   dword [sym.imp.KERNEL32.dll_GetLastError] () ; 0x464114
│      ││   0x0044e335      83f857         var = eax - 0x57      ; 'W' ; 'W' ; "ram cannot be run in DOS mode....$"
│     ┌───< 0x0044e338      0f856a010000   if (var != jne) goto 0x44e4a8
│     │││   0x0044e33e      56             push esi

```

**Comment by radare** [comment]
What about using if (var) or if (!val) in here? At least for jne and je would work

**Comment by wargio** [comment]
ok, easy to commit it. give me 30 secs

**Comment by wargio** [comment]
```
│           0x0044e30c      39356c0a4900   var = dword [0x490a6c] - esi ; [0x1d:4]=0
│       ┌─< 0x0044e312      0f85b0000000   if (var != 0) goto 0x44e3c8
│       │   0x0044e318      6800080000     push 0x800
│       │   0x0044e31d      56             push esi
│       │   0x0044e31e      683c944600     push 0x46943c
│       │   0x0044e323      ff1538424600   dword [sym.imp.KERNEL32.dll_LoadLibraryExW] () ; 0x464238 ; "R\xaa\b"
│       │   0x0044e329      8bf8           edi = eax
│       │   0x0044e32b      85ff           var = edi & edi
│      ┌──< 0x0044e32d      7526           if (var != 0) goto 0x44e355
│      ││   0x0044e32f      ff1514414600   dword [sym.imp.KERNEL32.dll_GetLastError] () ; 0x464114
│      ││   0x0044e335      83f857         var = eax - 0x57      ; 'W' ; 'W' ; "ram cannot be run in DOS mode....$"
│     ┌───< 0x0044e338      0f856a010000   if (var != 0) goto 0x44e4a8
│     │││   0x0044e33e      56             push esi
```

**Comment by radare** [comment]
yeah much better :)

**Comment by jeaye** [comment]
This doesn't quite work (with either Intel or AT&T syntax) in some cases, since it doesn't set `var = XXX` before the condition. Here's a snippet of r2's `main` disassembled:

```text
[0x00000000 0% 180 /home/jeaye/bin/r2]> pd $r @ fcn.00000000                                                                            
/ (fcn) fcn.00000000 2                                                                                                                  
|   fcn.00000000 ();                                                                                                                    
\           0x00000000      2321           esp &= dword [rcx]                                                                           
            0x00000002      2f                                                                                                          
            0x00000003      62                                                                                                          
            0x00000004      696e2f73680a.  ebp *= dword [rsi + 0x2f]                                                                    
            0x0000000b      686f6d652f     push 0x2f656d6f                                                                              
            0x00000010      6a65           push 0x65                   ; 'e' ; 'e' ; 101                                                
            0x00000012      61                                         ; 'e' ; 0x65 ; 'e' ; 101                                         
        ,=< 0x00000013      7965           jns 0x7a                    ;[1]                                                             
        |   0x00000015      2f                                                                                                          
       ,==< 0x00000016      7072           jo 0x8a                     ;[2]                                                             
       ||   0x00000018      6f             outsd dx,dword [rsi]                                                                         
       ||   0x00000019      6a65           push 0x65                   ; 'e' ; 'e' ; 101                                                
       ||   0x0000001b      6374732f       rsi = dword [rbx + rsi*2 + 0x2f] ; [0x2f:4]=0x6d6f682f ; '/' ; 47                            
      ,===< 0x0000001f      7261           if (((unsigned) var) < 0) goto 0x82 ;[3]                                                     
      |||   0x00000021      64                                                                                                          
      |||   0x00000022      61                                                                                                          
     ,====< 0x00000023      7265           if (((unsigned) var) < 0) goto 0x8a ;[2]                                                     
     ||||   0x00000025      322f           ch ^= byte [rdi]                                                                             
     ||||   0x00000027      656e           outsb dx,byte gs:[rsi]                                                                       
    ,=====< 0x00000029      762e           if (((unsigned) var) <= 0) goto 0x59 ;[4]                                                    
   ,======< 0x0000002b      7368           jae 0x95                    ;[5]                                                             
   ||||||   0x0000002d      2027           byte [rdi] &= ah   
```

Notice I get `rsi = XXX` before the `if`, but not `var`. With `e asm.syntax = att`, it's worse:

```text
[0x00000000 0% 180 /home/jeaye/bin/r2]> pd $r @ fcn.00000000                                                                            
/ (fcn) fcn.00000000 2                                                                                                                  
|   fcn.00000000 ();                                                                                                                    
\           0x00000000      2321           andl (%rcx),%esp                                                                             
            0x00000002      2f                                                                                                          
            0x00000003      62                                                                                                          
            0x00000004      696e2f73680a.  imull $0x2f0a6873,0x2f(%rsi),%ebp                                                            
            0x0000000b      686f6d652f     pushq $0x2f656d6f                                                                            
            0x00000010      6a65           pushq $0x65                 ; 'e' ; 'e' ; 101                                                
            0x00000012      61                                         ; 'e' ; 0x65 ; 'e' ; 101                                         
        ,=< 0x00000013      7965           jns 0x7a                    ;[1]                                                             
        |   0x00000015      2f                                                                                                          
       ,==< 0x00000016      7072           jo 0x8a                     ;[2]                                                             
       ||   0x00000018      6f             outsl (%rsi),%dx                                                                             
       ||   0x00000019      6a65           pushq $0x65                 ; 'e' ; 'e' ; 101                                                
       ||   0x0000001b      6374732f       movslq 0x2f(%rbx,%rsi,2), %rsi  ; [0x2f:4]=0x6d6f682f ; '/' ; 47                             
      ,===< 0x0000001f      7261           if (((unsigned) var) < 0) goto 0x82 ;[3]                                                     
      |||   0x00000021      64                                                                                                          
      |||   0x00000022      61                                                                                                          
     ,====< 0x00000023      7265           if (((unsigned) var) < 0) goto 0x8a ;[2]                                                     
     ||||   0x00000025      322f           xorb (%rdi),%ch                                                                              
     ||||   0x00000027      656e           outsb %gs:(%rsi),%dx                                                                         
    ,=====< 0x00000029      762e           if (((unsigned) var) <= 0) goto 0x59 ;[4]                                                    
   ,======< 0x0000002b      7368           jae 0x95                    ;[5]                                                             
   ||||||   0x0000002d      2027           andb %ah,(%rdi)  
```

Is this intended?

**Comment by wargio** [comment]
Probably we should add some code to change it to something else for at&t

**Comment by radare** [comment]
Meh i would just go forcig intel syntax for pdc temporarily

**Comment by wargio** [comment]
i think the problem here isn't pdc, but pseudo itself. that pseudo is intel only, not AT&T

**Comment by radare** [comment]
I know, but i dont see any benefit in dupping the work for at&t when intel is more close to pseudo

**Pull request merged**
