### PR TITLE
Fix capstone symbols visibility

### PR DESCRIPTION
**Pull request by kamou**
related to issue #7515

### CODE REVIEW

**Comment by kamou** [comment]
dunno why, just removing the attribute won't help, I had to explicitly set the attribute as hidden

**Comment by radare** [comment]
i think what this patch is doing is making the build of the shared lib of capstone with hidden symbols, so its an empty dylib, im not sure why this should fix the issue...

**Comment by kamou** [comment]
I know, it is quiet weird, but without this, capstone symbols end up in the relocation section `.rela.plt`
but maybe that's because we're linking against capstone and their header explicitly sets the default visibility ?
another weird thing is that just removing the attribute won't help. I need to explicitly set it to hidden for the symbols to get removed from libr_anal and libr_asm relocation sections...

**Comment by kamou** [comment]
I can try to have a deeper look at it next week

**Pull request merged**
