### PR TITLE
Fix #2188

### LINKED ISSUE #2188: List local/args in proper order
Alphabetically sort them.

First list args, and then locals

Probably needs to implement `sdb_array_sort()` in [sdb]( https://github.com/radare/sdb ).

### PR DESCRIPTION
**Pull request by alvarofe**
In order to work the sdb repository must be updated first. 

I checked the regressions to see if I was breaking something but the unique test that was expecting to receive arguments and variable list was the cmd_pdf_dwarf but It is already broken.

### CODE REVIEW

**Comment by radare** [comment]
You must order variables by its delta, not by its name. by default the given names are in correct order, but if you change the name of a variable this will break the order of <args>/<locals>

**Comment by alvarofe** [comment]
I'm ordering by its delta.

The cmp function is checking the delta

```c
static var_comparator(char *a , char *b ){
	//sorted by delta
	return atoi(a+2) < atoi(b+2);
}
```

Before the fix.

```
[0x100000d30]> pd 1@main
╒ (fcn) entry0 382
│          ; var int local_1      @ rbp-0x8
│          ; var int local_130_4  @ rbp-0x414
│          ; var int local_131    @ rbp-0x418
│          ; var int local_132    @ rbp-0x420
│          ; var int local_-9     @ rbp-0x48
│          ; var int local_130    @ rbp-0x410
│          ; var int local_133_4  @ rbp-0x42c
│          ; var int local_135    @ rbp-0x438
│          ; var int local_135_4  @ rbp-0x43c
│          ; var int local_136    @ rbp-0x440
│          ; var int local_136_4  @ rbp-0x444
│          ; var int local_137    @ rbp-0x448
│          ; var int local_132_4  @ rbp-0x424
│          ; var int local_137_4  @ rbp-0x44c
│          ; var int local_138    @ rbp-0x450
│          ; var int local_133    @ rbp-0x428
│          ; arg int arg_0_2      @ rbp+0x2
│          ;-- main:
│          ;-- entry0:
│          ;-- entry0:
│          0x100000d30    55           push rbp
```

After

```
[0x100000d30]> pd 1@main
╒ (fcn) entry0 382
│          ; arg int arg_0_2      @ rbp+0x2
│          ; var int local_1      @ rbp-0x8
│          ; var int local_-9     @ rbp-0x48
│          ; var int local_130    @ rbp-0x410
│          ; var int local_130_4  @ rbp-0x414
│          ; var int local_131    @ rbp-0x418
│          ; var int local_132    @ rbp-0x420
│          ; var int local_132_4  @ rbp-0x424
│          ; var int local_133    @ rbp-0x428
│          ; var int local_133_4  @ rbp-0x42c
│          ; var int local_135    @ rbp-0x438
│          ; var int local_135_4  @ rbp-0x43c
│          ; var int local_136    @ rbp-0x440
│          ; var int local_136_4  @ rbp-0x444
│          ; var int local_137    @ rbp-0x448
│          ; var int local_137_4  @ rbp-0x44c
│          ; var int local_138    @ rbp-0x450
│          ;-- main:
│          ;-- entry0:
│          ;-- entry0:
│          0x100000d30    55           push rbp
```

**Comment by alvarofe** [comment]
If I rename the variable  the order follows the same

```
[0x100000d30]> afvn local_130 local_1
[0x100000d30]> pd 1@main
╒ (fcn) entry0 382
│          ; arg int arg_0_2      @ rbp+0x2
│          ; var int local_1      @ rbp-0x8
│          ; var int local_-9     @ rbp-0x48
│          ; var int local_1      @ rbp-0x410
│          ; var int local_130_4  @ rbp-0x414
│          ; var int local_131    @ rbp-0x418
│          ; var int local_132    @ rbp-0x420
│          ; var int local_132_4  @ rbp-0x424
│          ; var int local_133    @ rbp-0x428
│          ; var int local_133_4  @ rbp-0x42c
│          ; var int local_135    @ rbp-0x438
│          ; var int local_135_4  @ rbp-0x43c
│          ; var int local_136    @ rbp-0x440
│          ; var int local_136_4  @ rbp-0x444
│          ; var int local_137    @ rbp-0x448
│          ; var int local_137_4  @ rbp-0x44c
│          ; var int local_138    @ rbp-0x450
│          ;-- main:
│          ;-- entry0:
│          ;-- entry0:
│          0x100000d30    55           push rbp
```

**Comment by radare** [comment]
Thanks! that new patch looks good!

**Pull request closed without merging**
