### PR TITLE
Show call hints and propagate types for indirect calls to imp symbols

### PR DESCRIPTION
**Pull request by pelijah**
Before:
изображение

After:
изображение

### CODE REVIEW

**Comment by radare** [comment]
add a config var disabled by default, s travis will be green and users will have the choice

**Comment by Maijin** [comment]
This must be default, it's already default for all the other cases

**Comment by Maijin** [comment]
And there is already an eval for that it's called asm.calls

**Comment by Maijin** [comment]
And I can fix the 3 travis tests

**Comment by XVilka** [comment]
Agree it should be on default. But maybe we should think about how to shorten the output. You can see that function name duplicated here, along with the argument name, I think it is possible to rework the output without this redundancy.

**Comment by Maijin** [comment]
We can do that in a separate PR

**Comment by XVilka** [comment]
LGTM then

**Comment by radare** [comment]
no. if you do this in a separate pr you have to update all the tests and we dont even want this by default. at least i dont

**Comment by Maijin** [comment]
It's 3 tests.

**Comment by radare** [comment]
if thats honoring asm.calls its fine i guess to merge if the tests got fixed

**Comment by Maijin** [comment]
Before I fix and merge there are warnings that needs to be fixed @pelijah:

```
anal_tp.c:549:42: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
                                                fcn_name = r_type_func_guess (TDB, full_name);
                                                                                   ^~~~~~~~~
/Users/maijin/Documents/Projects/radare2/libr/include/r_util/r_ctypes.h:42:63: note: passing argument to parameter 'func_name' here
R_API R_OWN char *r_type_func_guess(Sdb *TDB, R_NONNULL char *func_name);
                                                              ^
disasm.c:4462:46: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        } else if (!(name = r_type_func_guess (TDB, full_name))) {
                                                    ^~~~~~~~~
/Users/maijin/Documents/Projects/radare2/libr/include/r_util/r_ctypes.h:42:63: note: passing argument to parameter 'func_name' here
R_API R_OWN char *r_type_func_guess(Sdb *TDB, R_NONNULL char *func_name);
```

**Comment by radare** [comment]
and the r2r pr is in...?

**Comment by radare** [comment]
cc @Maijin

**Comment by Maijin** [comment]
Yep r2r fixed and pushed here 👍

**Comment by radare** [comment]
We will have to rebase maxbb again then

**Comment by Maijin** [comment]
sad

**Pull request merged**
