### PR TITLE
Fixes #13713: vr rotates between JMP, CALL and DATA reference hints

### LINKED ISSUE #13713: vr should rotate between JMP, CALL and DATA reference hints
right now it's "calls and jumps" or "data refs"

### PR DESCRIPTION
**Pull request by deepakchethan**
### jmp hints
Screen Shot 2019-04-15 at 11 43 35 PM

### call hints
Screen Shot 2019-04-15 at 11 43 47 PM

### LEA hints
Screen Shot 2019-04-15 at 11 43 57 PM

### CODE REVIEW

**Comment by radare** [comment]
Call hints should be the ones by default. by reading the code i have the feeling that it is the JMP ones now. Can you confirm/correct this? the rest of the PR looks great.

Thanks!

**Comment by radare** [comment]
the testsuite confirms my theory :) default hint sare jmp and should be calls
Screenshot 2019-04-15 at 22 27 13

**Comment by deepakchethan** [comment]
> default call instead of jmp

Yes sir, I changed to call and the tests are passing locally.

**Comment by radare** [comment]
Uhm for some reason the graph in the test have no hints, which looks good to me. But wonder why it changed. I’ll test and update the test if good

**Comment by radare** [comment]
thanks

**Pull request merged**
