### PR TITLE
Consistent naming of flags

### LINKED ISSUE #2599: aetr regression
Happened in https://github.com/radare/radare2/commit/24a27ecfcb180156c68840ab2a4c6563fe29ee79 for t.esil/cmd_aetr
```
[BR]  8  cmd_aetr: flags

Command:  /usr/bin/radare2 -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_aetr-rad.MttIhb   malloc://1024 > /tmp/r2-regressions//cmd_aetr-out.8xLJFD 2> /tmp/r2-regressions//cmd_aetr-err.co0WZt
File: malloc://1024
Script: aetr 0,0x2147a8,rip,+,[8],==,%z,zf,=,%b64,cf,=,%p,pf,=,%s,sf,=
Diff: --- /tmp/r2-regressions//cmd_aetr-exp.8hiIup	2015-05-21 02:07:55.000000000 +0200
+++ /tmp/r2-regressions//cmd_aetr-out.8xLJFD	2015-05-21 02:07:55.000000000 +0200
@@ -29,8 +29,8 @@
 0005.0e:      XOR      V_26:32 ,      V_20:32 ,      V_27:32
 0005.0f:      AND       0x1:32 ,      V_27:32 ,      V_28:32
 0005.10:      NOT      V_28:32 ,              ,      V_29:32
-0005.11:       OR      V_29:32 ,         0:01 ,      V_30:01
-0005.12:      STR      V_30:01 ,              ,      R_pf:01
+0005.11:       OR      V_29:32 ,         0:00 ,      V_30:00
+0005.12:      STR      V_30:00 ,              ,        pf
 0006.00:      SHL       0x1:32 ,      0x3f:32 ,      V_31:32
 0006.01:      AND      V_04:01 ,      V_31:32 ,      V_32:32
 0006.02:      SHR      V_32:32 ,      0x3f:32 ,      V_33:32
```

### PR DESCRIPTION
**Pull request by sushant94**
Closes #2599 

* Replace pf by flag_p in 64 and esil strings
* Replace af -> flag_a, if -> flag_i, tf -> flag_t, df -> flag_d

### CODE REVIEW

**Comment by radare** [comment]
This patch breaks esil because all esil backends generate code to use the short names for the flag registers.

**Comment by sushant94** [comment]
In that case, they must be changes to flag_* form too or we must revert back to the older shorter names as before.
What do you suggest?

**Comment by radare** [comment]
Not sure, that will produce longer evil expressions, but we want them to be consistent, and im not sure if we can have enough single-letter register names to cover all the x86 flags

**Comment by radare** [comment]
I would suggest going for the shorter form. I was asking for feedback from other people too.

**Comment by jvoisin** [comment]
I like the long names, they are more clear.

**Comment by jpenalbae** [comment]
Personally I like short names.

Also this would require patching all the esil backends to use the longer names...

**Comment by radare** [comment]
I would go for the short ones. can you send a pullreq with that fix so we can evaluate both options?

**Comment by radare** [comment]
Mnemonics win

**Pull request closed without merging**
