### PR TITLE
Rax2 refactoring

### PR DESCRIPTION
**Pull request by grigory-rechistov**
This is a simple set of patches meant to be my first attempt to contribute to radare2 code base.
1. I refactored rax2 code to get rid of magic numbers associated with command-line options.
2. Made rax2 behave more Unis-way in its error reporting. I must say it is far from perfect, as it is unclear what can be considered an error and what is not.
3. Updated rax2 manpage to mention all supported options.

### CODE REVIEW

**Comment by radare** [comment]
Indentation is wrong, use always tabs.

**Comment by radare** [comment]
pleas squash them all into a single commit

**Comment by radare** [comment]
Indentaiton fixed, squashed and merged. thanks!

**Comment by radare** [comment]
This refactoring is breaking 4 tests https://travis-ci.org/radare/radare2/jobs/75012232

**Comment by radare** [comment]
ive reverted the merge. please fix the indentation with spaces in the usage function, squash all your commits into a single one, and fix it to allow the tests to pass fine

**Comment by grigory-rechistov** [comment]
Thanks for the review, I will find out what's wrong with test and will resubmit.

**Pull request closed without merging**
