### PR TITLE
Detect binaries compilers with sanitizers

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by ret2libc** [comment]
Cool! Shall we print that info somewhere too?

**Comment by devnexen** [comment]
rabin2 does.

**Comment by ret2libc** [comment]
Ok!

**Comment by ret2libc** [comment]
Ok I think you should do a PR on radare2-regressions as well to adjust all the new output and maybe also add a new binary which has sanitizers to check if it works

**Comment by ret2libc** [comment]
Please do use the same name in the branch on radare2-regressions, so that we can test both your r2 changes and r2r ones together.

https://github.com/radare/radare2/blob/master/CONTRIBUTING.md#getting-started

**Comment by devnexen** [comment]
Done ... forgot this little detail :-)

**Pull request merged**
