### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by alvarofe**
Let see what travis says. In order to pass the test I pushed on regression a PR to reflect a little change in r_print_fill

### CODE REVIEW

**Comment by radare** [comment]
Fix the b24b325, the last patch doesnt fixes it properly

**Comment by alvarofe** [comment]
`Fix regression in cmd_p_equal` fixs that but the regression repository must be updated with the PR I sent.

**Comment by alvarofe** [comment]
Let's see if this pass the test ;)

**Comment by radare** [comment]
It does :)

**Pull request closed without merging**
