### PR TITLE
fix mem lost in pal detected with valgrind

### PR DESCRIPTION
**Pull request by alvarofe**

### CODE REVIEW

**Comment by radare** [comment]
if this is not called how can it fix a memleak?

**Comment by alvarofe** [comment]
I wanted to say memory that is not freed sorry

**Comment by radare** [comment]
its not even freed in your patch. it must be called from r_cons_free()

**Comment by alvarofe** [comment]
Sure? because valgrind was happy now :S . Why inside r_cons_free?

```
R_API RCons *r_cons_free () {
     I.refcnt--;
     if (I.refcnt != 0)
         return NULL;
     if (I.line) {
         r_line_free ();
         I.line = NULL;
     }
     if (I.buffer) {
         free (I.buffer);
         I.buffer = NULL;
     }
     return NULL;
 }
```

**Comment by radare** [comment]
This must be called after the first return NULL, also, use R_FREE() instead of free() or just set the pointer to NULL after freeing it to avoid possible doublefrees

**Comment by radare** [comment]
i dont see how valgrind can be happy with dead code. am i missing something? is this function ever called?

**Comment by alvarofe** [comment]
The output was
```
==1786==
==1786== HEAP SUMMARY:
==1786==     in use at exit: 170,705 bytes in 2,034 blocks
==1786==   total heap usage: 67,254 allocs, 65,220 frees, 139,666,466 bytes allocated
==1786==
==1786== 6 bytes in 1 blocks are definitely lost in loss record 1 of 199
==1786==    at 0x10007050B: malloc (in /usr/local/Cellar/valgrind/HEAD/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==1786==    by 0x1013DCF86: strdup (in /usr/lib/system/libsystem_c.dylib)
==1786==    by 0x1001DE807: r_cons_pal_init (pal.c:56)
==1786==    by 0x1001D3E4F: r_cons_new (cons.c:215)
==1786==    by 0x1000785A8: r_core_init (core.c:831)
==1786==    by 0x100001B91: main (in /usr/bin/r2)
==1786==
==1786== 6 bytes in 1 blocks are definitely lost in loss record 2 of 199
==1786==    at 0x10007050B: malloc (in /usr/local/Cellar/valgrind/HEAD/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==1786==    by 0x1013DCF86: strdup (in /usr/lib/system/libsystem_c.dylib)
==1786==    by 0x1001DE81E: r_cons_pal_init (pal.c:57)
==1786==    by 0x1001D3E4F: r_cons_new (cons.c:215)
==1786==    by 0x1000785A8: r_core_init (core.c:831)
==1786==    by 0x100001B91: main (in /usr/bin/r2)
==1786==
==1786== 6 bytes in 1 blocks are definitely lost in loss record 3 of 199
==1786==    at 0x10007050B: malloc (in /usr/local/Cellar/valgrind/HEAD/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==1786==    by 0x1013DCF86: strdup (in /usr/lib/system/libsystem_c.dylib)
==1786==    by 0x1001DE84C: r_cons_pal_init (pal.c:59)
==1786==    by 0x1001D3E4F: r_cons_new (cons.c:215)
==1786==    by 0x1000785A8: r_core_init (core.c:831)
==1786==    by 0x100001B91: main (in /usr/bin/r2)
==1786==
==1786== 6 bytes in 1 blocks are definitely lost in loss record 4 of 199
==1786==    at 0x10007050B: malloc (in /usr/local/Cellar/valgrind/HEAD/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==1786==    by 0x1013DCF86: strdup (in /usr/lib/system/libsystem_c.dylib)
==1786==    by 0x1001DE863: r_cons_pal_init (pal.c:60)
==1786==    by 0x1001D3E4F: r_cons_new (cons.c:215)
==1786==    by 0x1000785A8: r_core_init (core.c:831)
==1786==    by 0x100001B91: main (in /usr/bin/r2)

.....
```

After the patch the memory was freed and valgrind doesn't show nothing. I will check more thoroughly and change what you are saying

**Comment by radare** [comment]
Wheres ur function called?

**Comment by alvarofe** [comment]
in `r_core_fini` to free everything and now I wrote it in `r_cons_free` when the refcount reach 0 as you said me.

**Comment by radare** [comment]
Then remove that call from core. That freeing must be done from cons. Also, can you confirm that the previous buffer is freed when setting new values?

Also, try with oc command that creates multiple instances of rcore if that thing is not breaking it

**Comment by alvarofe** [comment]
My function `r_cons_pal_free` now is called from `r_cons_free` and this one is called from `r_core_fini` if I had not said enough clear.

I will check that two things  ;)

**Comment by radare** [comment]
Cool thanks!

**Comment by radare** [comment]
Thanks!

**Pull request closed without merging**
