### PR TITLE
Issue #1530

### PR DESCRIPTION
**Pull request by alvarofe**
This would be the initial implementation of 'psj' let me know if there is some issue or if you want add something more ;)

### CODE REVIEW

**Comment by jjdredd** [comment]
cd4afc8 doesn't really have to be a seperate commit.
what's wrong with indentation? misconfigured emacs? :)

**Comment by alvarofe** [comment]
I use vim. I've just seen the doc/vim I will try to follow the same indentation and configuration :)
I reverted the commit to only reflect the psj command.

**Comment by alvarofe** [comment]
The indentation of the switch I don't know why is there, because in vim and SourceTree is at the same level that the above r_cons_printf

**Comment by radare** [comment]
*use tabs*

**Comment by radare** [comment]
Thanks!

**Pull request closed without merging**
