### PR TITLE
Add PYC file format plugin

### PR DESCRIPTION
**Pull request by c0riolis**
Issue #4228

### CODE REVIEW

**Comment by radare** [comment]
Thanks!

**Comment by radare** [comment]
the makefile is wrong and it doesntc ompiles, but im fixing it

**Comment by radare** [comment]
I fixed the build but:

* no disassembler commited yet
* some warnings are displayed when loading it


```
prop:prg pancake$ r2 hello.pyc
Undefined type in get_object (0)
Undefined type in get_object (64)
Undefined type in get_object (0)
Undefined type in get_object (0)
Undefined type in get_object (47)
Undefined type in get_object (48)
Undefined type in get_object (64)
Undefined type in get_object (1)
Undefined type in get_object (0)
 -- Jingle sploits, jingle sploits, ropchain all the way.
[0x00000008]>
```

**Comment by c0riolis** [comment]
@radare As stated in the radare2-extra PR, only the sections listing and entrypoints are handled. This is because before disassembling you have to deserialize the file, which contains python objects, ie, you have recode a whole marshal module. Right now the plugin handles basic marshaled objects deserializing which is enough to list sections for basic python byte-compiled files, but warns you when it doesn't handle the type you are trying to unmarshal, causing the warnings you had at loading.

Implementation of missing types as well as disassembly will come later, but as the actual features required some code (about 1300 lines of change), and is working for simple files, I thought that a PR was adapted.

**Comment by radare** [comment]
Yep thats good. Just clarifying m what's missing. Thanks

**Pull request closed without merging**
