### PR TITLE
a bunch of the configs of disassembly are supported in the menu ##panels

### PR DESCRIPTION
**Pull request by Vane11ope**

### CODE REVIEW

**Comment by Vane11ope** [comment]
GIFrecord_2019-06-22_201652

like this

**Comment by Vane11ope** [comment]
lol i am fixing this

**Comment by radare** [comment]
fixing wat, waiting for it to merge

**Comment by Vane11ope** [comment]
tests were failing.

**Comment by radare** [comment]
tests are failing in master too

**Comment by Vane11ope** [comment]
lmao ok

**Comment by radare** [comment]
well. its red because it doesnt build at all

```
/home/travis/build/radare/radare2/libr/..//libr/anal/p/../..//asm/arch/tms320/c55x_plus/hashvector.c:97:25: warning: 'ins_hash' defined but not used [-Wunused-variable]
 static HASHCODE_ENTRY_T ins_hash[] = {
                         ^~~~~~~~
panels.c: In function '__initPanelsMenu':
panels.c:3591:4: error: too few arguments to function '__addMenu'
    __addMenu (core, parent, menus_Emulate[i], __esil_init_cb);
    ^~~~~~~~~
panels.c:3386:6: note: declared here
 void __addMenu(RCore *core, const char *parent, const char *base_name, RPanelsMenuCallback cb, RPanelsMenuGetName get_name_cb) {
      ^~~~~~~~~
panels.c:3593:4: error: too few arguments to function '__addMenu'
    __addMenu (core, parent, menus_Emulate[i], __esil_step_to_cb);
    ^~~~~~~~~
panels.c:3386:6: note: declared here
 void __addMenu(RCore *core, const char *parent, const char *base_name, RPanelsMenuCallback cb, RPanelsMenuGetName get_name_cb) {
      ^~~~~~~~~
panels.c:3595:4: error: too few arguments to function '__addMenu'
    __addMenu (core, parent, menus_Emulate[i], __esil_step_range_cb);
    ^~~~~~~~~
panels.c:3386:6: note: declared here
 void __addMenu(RCore *core, const char *parent, const char *base_name, RPanelsMenuCallback cb, RPanelsMenuGetName get_name_cb) {
      ^~~~~~~~~
make[3]: *** [panels.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```
pls :P

**Comment by Vane11ope** [comment]
DONE

**Pull request merged**
