### PR TITLE
Change CONTRIBUTING.md tab width to 4

### PR DESCRIPTION
**Pull request by itheof**
To be consistent with suggested editor config in ./doc

### CODE REVIEW

**Comment by radare** [comment]
Why merged. This was siposed to be a discussion. And we ve been using 8 chars for 12 years. Why merge without discussion first? I dont like this change

**Comment by XVilka** [comment]
@radare because it was different with the other doc, inconsistent. Can be easily changed back to but also changed in that other doc.

**Comment by XVilka** [comment]
@radare it is your config after all: https://github.com/radare/radare2/blob/master/doc/vim#L8

**Comment by ret2libc** [comment]
I don't like this change either actually... Tab has been 8 chars for a long time AFAIK

**Comment by Maijin** [comment]
Open a new issue please, digging/posting to the graveyard is always a bad idea.

**Pull request merged**
