### PR TITLE
Fix xtensa conditional jump for bbxi.

### PR DESCRIPTION
**Pull request by ieei**

### CODE REVIEW

**Comment by ieei** [comment]
Notice how `blt` instruction shows a line going down to `0x102` instead of going to `0x02` as it should.
This patch/pull request fixes this issue!

```
r2 -a xtensa -

[0x00000000]> wx 3a8868037813690568237915783362650232c31072650352c5108723e437640c68037813
[0x00000000]> pd 14
/ (fcn) fcn.00000000 513
|           0x00000000      3a88           add.n a8, a8, a3
|           0x00000002      6803           l32i.n a6, a3, 0
|           0x00000004      7813           l32i.n a7, a3, 4
|           0x00000006      6905           s32i.n a6, a5, 0
|           0x00000008      6823           l32i.n a6, a3, 8
|           0x0000000a      7915           s32i.n a7, a5, 4
|           0x0000000c      7833           l32i.n a7, a3, 12
|           0x0000000e      626502         s32i a6, a5, 8
|           0x00000011      32c310         addi a3, a3, 16
|           0x00000014      726503         s32i a7, a5, 12
|           0x00000017      52c510         addi a5, a5, 16
|       ,=< 0x0000001a      8723e4         blt a3, a8, 0x00000002
|      ,==< 0x0000001d      37640c         bbci a4, 3, 0x0000002d
|      ||   0x00000020      6803           l32i.n a6, a3, 0
[0x00000000]> s 0x1a
[0x0000001a]> ao
address: 0x1a
opcode: blt a3, a8, 0x00000002
prefix: 0
bytes: 8723e4
val: 0x00000000
ptr: 0x00000000
refptr: 0
size: 3
type: cjmp
type2: null
jump: 0x00000102
fail: 0x0000001d
stack: null
cond: 1
family: cpu
[0x0000001a]>
```

**Comment by radare** [comment]
Thanks! i have added a test case for this. merged!

**Comment by ieei** [comment]
Thanks! I'm kind of new to radare, so thanks for showing me how to add test cases. I'll try to contribute a bit more on the xtensa anal plugin, as there are still some issues I see.

**Comment by Maijin** [comment]
@ieei See the test PR https://github.com/radare/radare2-regressions/commit/9acf23e83dcd7465988ef63dc97af89ba3d766e2

**Comment by ieei** [comment]
@Maijin Yes, that was what I was referring to!

**Comment by radare** [comment]
Cool!

**Pull request closed without merging**
