### PR TITLE
Initial e pdb.symstore support (#8323)

### PR DESCRIPTION
**Pull request by riverar**
## New features
- core: `e pdb.symstore` added and defaults to `R2_HOMEDIR R_SYS_DIR "pdb"` (e.g. `C:\Users\Rafael\.config\radare2\pdb`, `~/.config/radare2/pdb`).
- rabin2: Added `RABIN2_SYMSTORE` env for overriding the paths above (e.g. via `-PP`)
 
## Potential breaking change
- Symbols will no longer be downloaded to the current input file directory, potentially breaking any code looking for downloaded .pdbs in the same directory as input files. [(code)](https://github.com/radare/radare2/compare/master...riverar:pdbdir?expand=1#diff-edacfa47d9cc092782716363f0ae7a60L63)
  - This does **not** affect the _loading_ of PDBs from the input directory, just in case the user has private symbols they wish to use. [(code)](https://github.com/radare/radare2/compare/master...riverar:pdbdir?expand=1#diff-3b6a666e5020b5146abd0a7ab217cb42R589)

### CODE REVIEW

**Comment by radare** [comment]
lgtm, @xarkes any comment?

**Comment by xarkes** [comment]
no lgtm

**Comment by XVilka** [comment]
@xarkes "no lgtm" or "no, lgtm"?

**Comment by xarkes** [comment]
Haha sorry I should have merged to make this more clear. No comments, it looks good to me :)

**Pull request merged**
