### PR TITLE
add .version to all plugins

### PR DESCRIPTION
**Pull request by neuschaefer**

### CODE REVIEW

**Comment by radare** [comment]
Omg we have tons of plugins 😱

**Comment by neuschaefer** [comment]
> Omg we have tons of plugins 😱

Yeah, around 150 :)

**Comment by neuschaefer** [comment]
Why is AppVeyor failing? :(

**Comment by jvoisin** [comment]
Because AppVeyor is broken, and should be deactivated :/
@XVilka ^

**Comment by radare** [comment]
Merged. Thanks!, appveyour should be fixed... i dont know WHY it fails to find sdb, because is compiled fine.. lets open an issue to fix this thing

**Pull request closed without merging**
