### PR TITLE
Improve build of libr.a and libr.dylib, fix and improve sys/ios-sdk.sh

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by xarkes** [comment]
@pelijah Can you take a quick look about the linking issues for msvc?
```
[868/1096] Linking target libr/anal/r_anal.dll.
FAILED: libr/anal/r_anal.dll 
link @libr/anal/r_anal.dll.rsp
   Creating library libr/anal\\r_anal.lib and object libr/anal\\r_anal.exp
p_anal_arm_gnu.c.obj : error LNK2019: unresolved external symbol arm_disasm_one_insn referenced in function op_thumb
p_anal_arm_gnu.c.obj : error LNK2019: unresolved external symbol arm_set_pc referenced in function arm_op32
p_anal_arm_gnu.c.obj : error LNK2019: unresolved external symbol arm_set_input_buffer referenced in function arm_op32
p_anal_arm_gnu.c.obj : error LNK2019: unresolved external symbol arm_set_thumb referenced in function arm_op32
p_anal_arm_gnu.c.obj : error LNK2019: unresolved external symbol arm_free referenced in function arm_op32
p_anal_arm_gnu.c.obj : error LNK2019: unresolved external symbol arm_new referenced in function arm_op32
p_anal_cr16.c.obj : error LNK2019: unresolved external symbol cr16_decode_command referenced in function cr16_op
p_anal_ebc.c.obj : error LNK2019: unresolved external symbol ebc_decode_command referenced in function ebc_op
p_anal_h8300.c.obj : error LNK2019: unresolved external symbol h8300_decode_command referenced in function h8300_op
p_anal_msp430.c.obj : error LNK2019: unresolved external symbol msp430_decode_command referenced in function msp430_op
p_anal_ppc_cs.c.obj : error LNK2019: unresolved external symbol vle_init referenced in function analop_vle
p_anal_ppc_cs.c.obj : error LNK2019: unresolved external symbol vle_next referenced in function analop_vle
p_anal_ppc_cs.c.obj : error LNK2019: unresolved external symbol vle_free referenced in function analop_vle
p_anal_propeller.c.obj : error LNK2019: unresolved external symbol propeller_decode_command referenced in function propeller_op
p_anal_tms320.c.obj : error LNK2019: unresolved external symbol tms320_dasm referenced in function tms320_c55x_op
p_anal_tms320.c.obj : error LNK2019: unresolved external symbol tms320_dasm_init referenced in function tms320_init
p_anal_tms320.c.obj : error LNK2019: unresolved external symbol tms320_dasm_fini referenced in function tms320_fini
p_anal_tms320_c55x_plus.c.obj : error LNK2019: unresolved external symbol get_ins_len referenced in function tms320_c55x_plus_op
p_anal_v810.c.obj : error LNK2019: unresolved external symbol v810_decode_command referenced in function v810_op
p_anal_v850.c.obj : error LNK2019: unresolved external symbol v850_decode_command referenced in function v850_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_insnbuf_size referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_insnbuf_alloc referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_insnbuf_from_chars referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_isa_init referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_format_decode referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_format_num_slots referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_format_get_slot referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_opcode_decode referenced in function xtensa_op
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_operand_get_field referenced in function analop_esil
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_operand_regfile referenced in function analop_esil
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol xtensa_regfile_shortname referenced in function analop_esil
p_anal_xtensa.c.obj : error LNK2019: unresolved external symbol __imp_xtensa_default_isa referenced in function xtensa_op
libr/anal/r_anal.dll : fatal error LNK1120: 32 unresolved externals
```

**Comment by pelijah** [comment]
Look here:
https://github.com/radare/radare2/blob/master/libr/anal/p/arm_gnu.mk#L2

In meson we just link whole `libr_asm` which doesn't export `arm_disasm_one_insn ` and other symbols. To fix this we have to rework all `meson.build` files.

**Comment by xarkes** [comment]
Ah :(

**Comment by pelijah** [comment]
Actually we can directly add some source files from libr_asm to libr_anal. It is easier way but meson files will become dirtier.

**Comment by xarkes** [comment]
You mean put some C file in both `libr/asm/meson.build` and `libr/anal/meson.build`?
Wouldn't that fail at some point?

**Comment by pelijah** [comment]
Already present in https://github.com/radare/radare2/blob/master/libr/anal/meson.build#L85

**Comment by xarkes** [comment]
Ok so we should do the same I think

**Comment by pelijah** [comment]
I think it would be better to refactor it.

**Comment by pelijah** [comment]
But it requires more time.

**Comment by xarkes** [comment]
Yes you're right it's better but it takes more time :D If you can handle this, then great! Otherwise we can just put those file in there and it will compile. Dirty but it works. Up to you I think.
Or we can do something dirty now to merge the PR, and refactor later.

**Comment by radare** [comment]
I prefer a quick fix to merge this and continue improving this. Also there are things to be done in the makefiles but i prefer to merge asap

**Comment by radare** [comment]
squashed and rebased. fixed on linux, waiting for travis, but i guess ill merge and then go for the meson pr

**Comment by xarkes** [comment]
Yes, imho it's going to produce too many libraries for nothing...
I think it's better to duplicate a few `.c` files in the main `meson.build` files, rather than linking libraries with one unique file as you did there: https://github.com/radare/radare2/pull/10046/files#diff-5269591bdb9304be0c928ca6f2b70b74R15
No?

**Comment by pelijah** [comment]
Well then revert my commit.

**Comment by radare** [comment]
why the hell is travis not running the testsuite?

**Comment by radare** [comment]
@pelijah i have reverted your pr, so it doesnt builds with meson

**Comment by radare** [comment]
screen shot 2018-05-09 at 18 53 47

also, meson build is failing hard

**Comment by pelijah** [comment]
Patch for meson:

```diff
--- a/libr/anal/meson.build
+++ b/libr/anal/meson.build
@@ -83,6 +83,26 @@ files = [
   'arch/hexagon/hexagon_anal.c',
   '../asm/arch/hexagon/hexagon.c',
   '../asm/arch/hexagon/hexagon_disas.c',
+  '../asm/arch/arm/winedbg/be_arm.c',
+  '../asm/arch/cr16/cr16_disas.c',
+  '../asm/arch/ebc/ebc_disas.c',
+  '../asm/arch/h8300/h8300_disas.c',
+  '../asm/arch/msp430/msp430_disas.c',
+  '../asm/arch/ppc/libvle/vle.c',
+  '../asm/arch/propeller/propeller_disas.c',
+  '../asm/arch/tms320/tms320_dasm.c',
+  '../asm/arch/tms320/c55x_plus/ins.c',
+  '../asm/arch/tms320/c55x_plus/c55plus.c',
+  '../asm/arch/tms320/c55x_plus/c55plus_decode.c',
+  '../asm/arch/tms320/c55x_plus/decode_funcs.c',
+  '../asm/arch/tms320/c55x_plus/hashtable.c',
+  '../asm/arch/tms320/c55x_plus/utils.c',
+  '../asm/arch/v810/v810_disas.c',
+  '../asm/arch/v850/v850_disas.c',
+  '../asm/arch/xtensa/gnu/xtensa-dis.c',
+  '../asm/arch/xtensa/gnu/elf32-xtensa.c',
+  '../asm/arch/xtensa/gnu/xtensa-isa.c',
+  '../asm/arch/xtensa/gnu/xtensa-modules.c'
 ]

 r_anal = library('r_anal', files,
```

**Comment by xarkes** [comment]
Thank you pelijah.

**Comment by radare** [comment]
Thank u!!

**Pull request merged**
