### PR TITLE
Basic analysis for z80

### PR DESCRIPTION
**Pull request by kolen**
Trying to make z80 analysis work. It was in almost stub state, at least now it detects conditional and unconditional jumps and returns.

I'm not sure if it works correctly, I need to get used to analysis in Radare.

What can I do to improve it further? Will esil be used by analyzer or it's intended only to be human-readable? Are all fields such as ``stackop``, ``ptr`` and op types such as ``R_ANAL_OP_TYPE_DIV`` useful or they're superseded by esil?

### CODE REVIEW

**Comment by radare** [comment]
Can you share any test case for that af+pdf=err?

**Comment by radare** [comment]
Can we have some tests for z80?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/3287

**Comment by radare** [comment]
Thanks ! merged

**Pull request closed without merging**
