### PR TITLE
meson: don't compile inclusion-only .c files

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by ret2libc** [comment]
I think you need to rebase.

**Comment by MaskRay** [comment]
Rebased

**Comment by ret2libc** [comment]
Random question: what is the problem with leaving them in the `files` list?

**Comment by MaskRay** [comment]
They got compiled unnecessarily and triggered `-Wunused-function` warnings because of those unused `static` functions.

**Pull request merged**
