### PR TITLE
Fix #2490

### LINKED ISSUE #2490: vterm PE with asan not fixed
sys/asan.sh
sh run_tests.sh t.formats/pe

### PR DESCRIPTION
**Pull request by alvarofe**

### CODE REVIEW

**Comment by radare** [comment]
test failing because of debug printf

**Comment by alvarofe** [comment]
From master I was getting the following, so I didn't remove the eprintf. Let see what Travis says now.

```
alvaro_fe@macbook 22:22 ~/Projects/Reverse/radare2/r2-regressions/bins/pdb rabin2 -PP user32.dll                                                                                [master] git:r2-regressions
sh: cabextract: command not found
Missing cabextract
PDB "user32.pdb" download failed

alvaro_fe@macbook 22:24 ~/Projects/Reverse/radare2/r2-regressions/bins/pdb rabin2 -PP user32.dll                                                                                [master] git:r2-regressions
sh: cabextract: command not found
Missing cabextract
PDB "user32.pdb" download failed
alvaro_fe@macbook 22:25 ~/Projects/Reverse/radare2/r2-regressions/bins/pdb r2 -v                                                                                                [master] git:r2-regressions
radare2 0.9.9-git 7819 @ darwin-little-x86-64 git.0.9.8-1449-g08c859d
commit: 08c859d18cb6f49547f40584a649201a6712c5de build: 2015-05-05
```

**Comment by Maijin** [comment]
@alvarofe 

`sh: cabextract: command not found` You need to install this to get the test passing correctly on your machine then ;)

**Comment by alvarofe** [comment]
OMG!!!!! I need to sleep more jejeje thanks @Maijin : )

**Comment by radare** [comment]
@Maijin what about making this test conditional, depending if cabextract is installed? 
```
type cabextract
if [ $? = 0 ]; then
...
run_test
fi
```

**Comment by radare** [comment]
Thanks!

**Comment by Maijin** [comment]
@radare done

**Pull request closed without merging**
