### PR TITLE
Add anal_var_delete

### PR DESCRIPTION
**Pull request by psie**

### CODE REVIEW

**Comment by radare** [comment]
The commit message looks wrong

**Comment by psie** [comment]
Sorry, what should it be then? 
"Write missing code for removing variables"?
"Implement variables removing"?

**Comment by XVilka** [comment]
Merged thanks!
Next time please use different branch, rather than 'master'.

**Comment by radare** [comment]
Maybe just 'fix ...' Because the function was already there and it got broken after the rewrite to sdb.

But thats fine :) thanks for the contrib!

**Pull request closed without merging**
