### PR TITLE
Update fortunes.fun

### PR DESCRIPTION
**Pull request by zonkzonk**

### CODE REVIEW

**Comment by radare** [comment]
Can be offensive, more than fun. Probably best not to merge :)

**Comment by crowell** [comment]
also, spelling

**Comment by jjdredd** [comment]
> Can be offensive, more than fun.

why?

**Comment by radare** [comment]
Ok. Its more abstract joke than i thought

**Comment by zonkzonk** [comment]
wat. it's a compliment! 11

**Pull request closed without merging**
