### PR TITLE
Meson: enable Propeller and Java

### PR DESCRIPTION
**Pull request by XVilka**
To fix https://github.com/radare/radare2/issues/8950

### CODE REVIEW

**Comment by radare** [comment]
Wat du

**Comment by XVilka** [comment]
wait. dynamic linking issues should be fixed first

**Comment by xarkes** [comment]
ping?

**Comment by XVilka** [comment]
There are still unresolved errors:
```
liblibr2java.a(java_class.c.obj) : error LNK2005: r_bin_java_extract_all_bin_type_values already defined in r_asm.lib(r_asm.dll)
liblibr2java.a(java_class.c.obj) : error LNK2005: r_bin_java_extract_type_values already defined in r_asm.lib(r_asm.dll)
liblibr2java.a(java_class.c.obj) : error LNK2005: r_bin_java_get_bin_obj_list_thru_obj already defined in r_asm.lib(r_asm.dll)
liblibr2java.a(java_class.c.obj) : error LNK2005: r_bin_java_get_method_code_attribute already defined in r_asm.lib(r_asm.dll)
liblibr2java.a(java_class.c.obj) : error LNK2005: r_bin_java_get_method_code_offset already defined in r_asm.lib(r_asm.dll)
liblibr2java.a(java_class.c.obj) : error LNK2005: r_bin_java_get_method_code_size already defined in r_asm.lib(r_asm.dll)
liblibr2java.a(java_class.c.obj) : error LNK2005: r_bin_java_get_methods_list already defined in r_asm.lib(r_asm.dll)
   Creating library libr/anal\\r_anal.lib and object libr/anal\\r_anal.exp
p_anal_propeller.c.obj : error LNK2019: unresolved external symbol propeller_decode_command referenced in function propeller_op
libr/anal/r_anal.dll : fatal error LNK1120: 1 unresolved externals
```

**Comment by radare** [comment]
I did a libr_shlr.a to ease the static linking maybe meson can do the same

**Comment by xarkes** [comment]
Ah yes that'd be interesting cc @pelijah

**Comment by pelijah** [comment]
I don't think that this solution helps us. This problem is due to R_API macro.

**Comment by xarkes** [comment]
Anyway maybe it's interesting to follow what the Makefiles do and build lib_shlr.a with meson too (less confusing if every build system follow the same rules)

**Comment by pelijah** [comment]
> Anyway maybe it's interesting to follow what the Makefiles do and build lib_shlr.a with meson too (less confusing if every build system follow the same rules)

We can create array `libr_shlr` with all shlr libs and pass it to other bins/libs `link_with : [libr_shlr, r_util, r_core ...]`. It's the easiest way.

**Comment by pelijah** [comment]
We can use linker's /FORCE:MULTIPE option https://github.com/pelijah/radare2/commit/c605973e7bbfcf3c639b4a3ed7e782f7b22ffbec

**Comment by xarkes** [comment]
@XVilka Could you rebase and use @pelijah's commit above? It should be green then.

**Comment by XVilka** [comment]
Closing in favor of https://github.com/radare/radare2/pull/9639

**Pull request closed without merging**
