### PR TITLE
Fix 2369 - move bits and endian from core to bin info

### PR DESCRIPTION
**Pull request by alvarofe**
This fix the issue. I've made also a PR in the regression repository to reflect this change.

### CODE REVIEW

**Comment by Maijin** [comment]
@alvarofe related have you seen that appending j is output json? And that if you for example use iI on PE you get half of the infos ? (no compiled date, no binsz, ...), even worse for iIq

**Comment by alvarofe** [comment]
I only limited to strip duplicated fields and move some from core to bin and vice versa. It's true that the json output differ from the normal but that was in that way before I touched the code. I could change it in order that the two outputs be equal. 

In the case of 'iq' the code is the following

```
if ((mode & R_CORE_BIN_SIMPLE)) {
		r_cons_printf ("arch %s\n", info->arch);
		r_cons_printf ("bits %d\n", info->bits);
		r_cons_printf ("os %s\n", info->os);
		r_cons_printf ("endian %s\n", info->big_endian? "big": "little");

```

binsz is the same as size in core when the ouput is json.

```
pic      false
canary   false
nx       false
crypto   false
va       true
root     pe
class    PE32
arch     x86
bits     32
machine  i386
os       windows
subsys   Windows CUI
endian   little
strip    true
static   false
linenum  false
lsyms    false
relocs   false
binsz    1024
compiled Thu Jan  1 00:00:00 1970
----
{
   "bin" : {
      "machine" : "i386",
      "nx" : false,
      "bits" : 32,
      "type" : "pe",
      "os" : "windows",
      "endian" : "little",
      "canary" : false,
      "stripped" : true,
      "class" : "PE32",
      "arch" : "x86",
      "crypto" : false,
      "va" : true,
      "syms" : false,
      "linenums" : false,
      "static" : false,
      "pic" : false,
      "relocs" : false,
      "lang" : ""
   },
   "core" : {
      "mode" : "r--",
      "file" : "normal.exe",
      "fd" : 6,
      "format" : "pe",
      "type" : "EXEC (Executable file)",
      "block" : 256,
      "size" : 1024
   }
}

```

Also as @radare pointed the other day, I might integrate inside bin info the output from "fs", I think that's what he said.

**Comment by Maijin** [comment]
@alvarofe having same output in json and normal view seems would be awesome :+1: and much more logic

**Comment by radare** [comment]
also, bear in mind that all those changes affect the webui :)

but its good to make a cleanup on that topic

**Comment by alvarofe** [comment]
I understand that I have permission to proceed ;) Also before to merge pwntester if I am not wrong can change the code to reflect this change. If it is not very complicated I will try to do it myself

**Pull request closed without merging**
