### PR TITLE
[PPC] added more standard special purpose registers to pseudo

### PR DESCRIPTION
**Pull request by wargio**
* MQ
* XER
* RTCU
* RTCL
* LR
* CTR
* DSISR
* DAR
* DEC
* SDR1
* SRR0
* SRR1
* VRSAVE
* TBRL
* TBRU
* SPRG0
* SPRG1
* SPRG2
* SPRG3
* EAR
* TBL
* TBU
* PVR
* SPEFSCR
* IBAT0U
* IBAT0L
* IBAT1U
* IBAT1L
* IBAT2U
* IBAT2L
* IBAT3U
* IBAT3L
* DBAT0U
* DBAT0L
* DBAT1U
* DBAT1L
* DBAT2U
* DBAT2L
* DBAT3U
* DBAT3L
* UMMCR0
* UMMCR1
* UPMC1
* UPMC2
* USIA
* UPMC3
* UPMC4
* MMCR0
* PMC1
* PMC2
* SIA
* MMCR1
* PMC3
* PMC4
* SDA
* DMISS
* DCMP
* HASH1
* HASH2
* IMISS
* ICMP
* RPA
* IABR
* DABR
* ICTC
* THRM1
* THRM2
* THRM3
* PIR

### CODE REVIEW

**Comment by radare** [comment]
fuck, it was ppc, hate that -f restriction

**Comment by wargio** [comment]
something wrong happened?

**Comment by radare** [comment]
I just misstyped when correcting the commit message. Please try to use proper error messages next time. But it was my fault

**Comment by wargio** [comment]
Ok, sorry.

**Pull request merged**
