### PR TITLE
check for macos as well as darwin

### PR DESCRIPTION
**Pull request by jacobrosenthal**
I think this should be looking for macos as well as darwin for modern mac binaries. But someone who understand the code path should weigh in, Im just searching through the source looking for usages of darwin and macos

### CODE REVIEW

**Comment by radare** [comment]
Add an isXNU() function and add tvos, watchos and ios to the list of oses to check here

**Comment by jacobrosenthal** [comment]
Hows this

**Comment by jacobrosenthal** [comment]
I dont know anything about syscalls on the 'xnu' family. Which of these xnu platforms should we be checking for here? https://github.com/radare/radare2/blob/master/libr/syscall/syscall.c#L86 use

**Comment by jacobrosenthal** [comment]
@pancake what about here  https://github.com/radare/radare2/blob/master/libr/syscall/syscall.c#L86 I want to remove the osx check, its not useful, and it seems like maybe that needs a tvos, ios, watchos as well

**Pull request merged**
