### PR TITLE
Added AES-128/192/256 with ECB mode to rahash2

### PR DESCRIPTION
**Pull request by l4l**
#4254 related

There is still some work for IV-family mode AESes like CBC/CFB/OFB

### CODE REVIEW

**Comment by radare** [comment]
Fix the linking https://travis-ci.org/radare/radare2/jobs/117952682

**Comment by l4l** [comment]
That's really strange. I can't reproduce it with clang/gcc and [this piece](https://github.com/radare/radare2/pull/4402/files#diff-efaa26a6fe5685c6635f1c741cf5651aR67) of code link properly.
Any ideas?

**Comment by Maijin** [comment]
Cross-link r2r https://github.com/radare/radare2-regressions/pull/344

**Comment by radare** [comment]
You can reproduce it on mac or mingw or android static builds.

There are scripts in sys /for all this stuff

The thing is that linux linker is quite lazy and solves this dependency at runtime while pther systems require explicit compile time linkage

**Comment by radare** [comment]
Use tabs, not spaces

**Comment by radare** [comment]
Anyway, i did the fixes and squashed your commits.

Thanks! :D

**Pull request closed without merging**
