### PR TITLE
[gdb] Removed debug eprintf from gdb code

### PR DESCRIPTION
**Pull request by wargio**
just commented some (useless?) code.

### CODE REVIEW

**Comment by gaming-hacker** [comment]
since when does commenting out printf lines cause builds to fail?

**Comment by Maijin** [comment]
@gaming-hacker unrelated

**Comment by radare** [comment]
and build doesnt fails at all

**Comment by gaming-hacker** [comment]
isn't that what red x next to the hash code means, build failed? 
i have my own fork and want to cherry pick this  but wanted to know why the failure.

screen shot 2018-01-18 at 16 52 56

**Comment by Maijin** [comment]
No that can also mean the tests are failings, for travis at least.

**Comment by radare** [comment]
Ill fix asap been busy all day. The redness is just because a typo in the magicpath

**Pull request merged**
