### PR TITLE
Moved segments from iS/'rabin2 -S' to iSS/'rabin2 -SS'

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by ret2libc** [comment]
Actually I'm not really sure we want this. I think that except for ELF, `iS` just shows the sections and that's what should be available IMHO. Segments, which are what the loader loads in memory, should be just handled by the IO library.

If we really want to see both segments and sections, I suggest we use a separate command, otherwise it becomes confusing having everything in a single command as it is now, because it's hard to know which ones are segments and which are not.

**Comment by Maijin** [comment]
I agree on that, iS should show only the sections, segments should be dealt by a command in `o` something

**Comment by radare** [comment]
as long as we are short in letters, we can use -SS for segments in rabin2

**Comment by ret2libc** [comment]
BTW, related to this split of sections and segments, there's this issue I created some time ago https://github.com/radare/radare2/issues/9625

**Comment by kazarmy** [comment]
I actually prefer a command like `iSg` -- no need for a loader or mapper to tell you what the segments (aka program header entries) are.

**Comment by ret2libc** [comment]
I agree with @kazarmy you don't need a loader or anything else to list segments. It's still another binary information, just I wouldn't mix them with sections.

**Comment by kazarmy** [comment]
ok to merge? Will do json/commands/simple output later. TTS support appears broken but the support is generally inconsistent anyway.

Internally still faking segments as sections for expediency's sake.

**Comment by Maijin** [comment]
@kazarmy need to remove segments from iSj too

**Comment by kazarmy** [comment]
> @kazarmy need to remove segments from iSj too

#10308 does do the above

**Pull request merged**
