### PR TITLE
Implement pfc normalized types and values ##print

### PR DESCRIPTION
**Pull request by oxcabe**
Please review. Suggestions are appreciated :p

### CODE REVIEW

**Comment by oxcabe** [comment]
PS: Travis will go red since output changed. I have to update (and add new) tests for pfc.

**Comment by radare** [comment]
update the testss and rebase this pr to make travis run again

**Comment by radare** [comment]
there are 86 XX, not gonna merge this until you rebase , the broken tests are not suposed to be broken

**Comment by XVilka** [comment]
@oxcabe see my comment - don't remove float/double/void *.

**Comment by oxcabe** [comment]
Yeah, it looks like I broke a lot of things. I'm working on this atm.

float / double will be back too.

**Pull request merged**
