### PR TITLE
fix for functions analyzer

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by Maijin** [comment]
Some tests are failing with this, you should give a look at travisCI (note that the AVR one are currently XX as well due to 04cd1250c2b6c771effed162ea56c058def07dd2 not your PR)

**Comment by dmtch** [comment]
I think that everything is alright with this test ("-A guess-number-riscv64" - s sym.main; pdf). Program's output has changed a bit, but it's more relative now.
Before:
0x00010178    ef00c01f       jal ra, sym.printf             ; sym.__libc_init_array+0xe4
After:
0x00010178    ef00c01f       jal ra, sym.printf
Because __libc_init_array+0xe4 is just printf function begin. And the same with other references at sym.main.

**Comment by dmtch** [comment]
Ok!

**Comment by radare** [comment]
ping? :)

**Comment by dmtch** [comment]
Pong :) I'm ready, normal commits in anal_patches branch.

**Comment by radare** [comment]
i don't see any PR

**Pull request closed without merging**
