### PR TITLE
added buggy fortunes

### PR DESCRIPTION
**Pull request by stefan2904**
such fortunes, much fun, wow.

### CODE REVIEW

**Comment by radare** [comment]
the last one sounds offensive to me

**Comment by kaydoubleu** [comment]
Eve in the context of Alice & Bob ;)

**Comment by radare** [comment]
with context makes more sense

**Comment by stefan2904** [comment]
Yes, that's right, its a mashup of Google's "don't be eviland crypto's Alice & Bob universe. Sorry for the confusion.

**Pull request closed without merging**
