### PR TITLE
saving/retireving functions stack in project file

### PR DESCRIPTION
**Pull request by oddcoder**

### CODE REVIEW

**Comment by Maijin** [comment]
@oddcoder I don't see anything tied with projects. Did you forget to add something in project.c ?

**Comment by oddcoder** [comment]
not really project.c dumps the output of bunch of functions into project files, one of them is `afl*`
since stack frame fits into `afl*` I added it to the output of `afl*`, so it will be dumped into project file

**Comment by Maijin** [comment]
ok

**Comment by radare** [comment]
i think having sdb baked projects is important, but also keeping plaintext script is too, so i would like to add an option or a command to have both ways of doing that in case someone wants to just pipe a script from a session to another to transfer the state. even if that’s slower.

**Comment by XVilka** [comment]
I agree with @radare - both are quite useful.

**Pull request merged**
