### PR TITLE
Always bracket indirect addr operand (except LEA)

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
We can check lea by the string so the analop shouldnt be necessary. Not sure why the brackets went away for the other use cases.. well i think it was as a shortened reloc representation

**Comment by XVilka** [comment]
Please rebase, since I merged AppVeyor fix

**Comment by kazarmy** [comment]
> We can check lea by the string so the analop shouldnt be necessary.

Ok 22a6fbaaf0be090f5be1994f2a97d8b37ebb26aa

> Please rebase, since I merged AppVeyor fix

Done

**Comment by radare** [comment]
LGtm now. Merge!

**Comment by kazarmy** [comment]
sorry wrong terms used ... fortunately a rose by any other name is still a rose

**Pull request merged**
