### PR TITLE
Fix spurious relocs

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by codido** [comment]
This looks much better, but I still see some spurious relocations in other files. For instance, in the attached file (base64: [acct.o.txt](https://github.com/radare/radare2/files/172134/acct.o.txt)), is there really a relocation at offset 0xb5 (test eax, eax)?

**Comment by radare** [comment]
any comments on this @alvarofe ?

**Comment by alvarofe** [comment]
i will look at this but it has to wait. closing by now

**Comment by radare** [comment]
why closing?

**Comment by radare** [comment]
@alvarofe can we close this? you are working on a more detailes fix, right?

**Pull request closed without merging**
