### PR TITLE
Time to say goodbye to r_json

### PR DESCRIPTION
**Pull request by Vane11ope**
It's been quite a journey but now is good time to say goodbye to r_json once and for all.

### CODE REVIEW

**Comment by radare** [comment]
Woah was not dxpecting this :)) killing duped apis is always good news

**Comment by radare** [comment]
@wargio feels sad to remove such working code, what about moving it into its own separate repository for being reused by other people?

**Comment by XVilka** [comment]
It is git - in case of emergency you can always break a glass and do git
checkout older revision.

**Comment by Maijin** [comment]
+ the syntax for using r_json is awful with those: free(XXX(JSON(XXX(YYY)

image

**Pull request merged**
