### PR TITLE
added ood <args>

### PR DESCRIPTION
**Pull request by alvarofe**
I'm working in dbg.args so don't close the issue #3359

https://asciinema.org/a/6p4xorquj7j9nb1o2t7zh9fy7

### CODE REVIEW

**Comment by jvoisin** [comment]
Why are you running it with `sudo` ?!

**Comment by alvarofe** [comment]
because then to debug I need sudo

**Comment by radare** [comment]
Because signing in osx is a pain

**Comment by radare** [comment]
You can sign r2 with ur own cert, see doc/osx for instructions

**Comment by alvarofe** [comment]
I have one but i prefer sudo that sign every time I compile

**Comment by alvarofe** [comment]
Anyone with windows can test ?

ttps://asciinema.org/a/bwn0t9ni9wdz4y4wbq9y7n957

**Comment by radare** [comment]
waiting for the final fix to merge. thanks!

**Comment by radare** [comment]
Confirmed! Works as expected.

Thanks!

**Pull request closed without merging**
