### PR TITLE
fix issue #4342

### PR DESCRIPTION
**Pull request by P4N74**
`imj` outputs as:

```
[Memory]

[{"name":"RAM                 ", "size":2048, "address":0, "flags":"-rwx"},
{"name":" RAM_MIRROR_2       ", "size":2048, "address":4096, "flags":"-rwx"},
{"name":" RAM_MIRROR_3       ", "size":2048, "address":6144, "flags":"-rwx"},
{"name":"PPU_REG             ", "size":8, "address":8192, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_1   ", "size":8, "address":8200, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_2   ", "size":8, "address":8208, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_3   ", "size":8, "address":8216, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_4   ", "size":8, "address":8224, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_5   ", "size":8, "address":8232, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_6   ", "size":8, "address":8240, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_7   ", "size":8, "address":8248, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_8   ", "size":8, "address":8256, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_9   ", "size":8, "address":8264, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_10  ", "size":8, "address":8272, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_11  ", "size":8, "address":8280, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_12  ", "size":8, "address":8288, "flags":"-rwx"},
{"name":" PPU_REG_MIRROR_13  ", "size":8, "address":8296, "flags":"-rwx"},
.
.
.
.
{"name":" PPU_REG_MIRROR_1023", "size":8, "address":16376, "flags":"-rwx"},
{"name":"APU_AND_IOREGS      ", "size":32, "address":16384, "flags":"-rwx"},
{"name":"SRAM                ", "size":8192, "address":24576, "flags":"-rwx"},
]
```

### CODE REVIEW

**Comment by crowell** [comment]
does a json parser throw away the extra spaces? i think we dont want those.

eg should be

`{"name":"SRAM", "size":8192, "address":24576, "flags":"-rwx"}`
instead of
`{"name":"SRAM                ", "size":8192, "address":24576, "flags":"-rwx"}`

**Comment by P4N74** [comment]
@crowell ok, i will do that...also, I will be working on the same branch for `imq` support.

**Comment by Maijin** [comment]
last comma before `]` is wrong also

**Comment by P4N74** [comment]
@crowell @Maijin i have resolved the previous issues now and also implemented `imq`.

**Comment by P4N74** [comment]
tests for `imq` and `imj`: https://github.com/radare/radare2-regressions/pull/362

**Comment by radare** [comment]
Use tabs, not spaces

**Comment by radare** [comment]
the commit conflicts with master so it cant be merged

**Comment by radare** [comment]
also, do not put any newline in the JSON, or extra spaces, its not suposed to be read by humans, but a parser and its important to be as much compact as possible and newlines are noisy here... and problematic by some parsers

**Comment by P4N74** [comment]
@radare is the commit conflict a major problem?

**Comment by radare** [comment]
Yes, you must rebase your branch on top of latest master

**Comment by radare** [comment]
Try with | json_pp or ~{}

**Comment by P4N74** [comment]
@radare now. I am not sure if the way I did is correct. I just fetched from upstream (radare/radare2.git) and rebased on top of upstream/master.

**Comment by radare** [comment]
The commits are completely messed up. I have squashed cherry-picked and fixed all the merge conflicts... if you rebase -i @~X and squash them into a single commit you will be able to rebase that commit much easily. but in normal usage, you shouldnt be running `git pull` on a branch of yours unless you know there are important changes in master for your pr.

thanks

**Pull request closed without merging**
