### PR TITLE
anal/fcn: do not use raw type, but first mask it with TYPE_MASK

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by XVilka** [comment]
@sivaramaaa please check this one

**Comment by ret2libc** [comment]
This is just a reimplementation of https://github.com/radare/radare2/pull/10686.
It should be alright, since the op.type value may be composed of multiple pieces (e.g. it can indicate whether there are registers or not). So before using `==` or `!=`, we should mask the value.

**Comment by sivaramaaa** [comment]
lgtm :+1:

**Comment by radare** [comment]
Yeah! Merge please

**Pull request merged**
