### PR TITLE
Initial databases

### PR DESCRIPTION
**Pull request by oddcoder**
Removing useless databases
Adding windows types
Fixing seg fault

### CODE REVIEW

**Comment by Maijin** [comment]
That is probably breaking an important feature that should be merged with yours : e asm.emu =true ; e asm.emuwrite

**Comment by Maijin** [comment]
see [33m[  ]  3  emu: [0mWindows Function EMU LoadStringA
and [33m[  ]  2  emu: [0mWindows Function EMU printf

**Comment by oddcoder** [comment]
restored those deleted sdbs

**Comment by Maijin** [comment]
Well better would be to fix this and make this old stuff use your new engine.

**Comment by oddcoder** [comment]
ofc I will do that but I thought of getting used stuff back as quick fix

**Pull request merged**
