### PR TITLE
Changed aeis to aeim in ESIL help to match code

### PR DESCRIPTION
**Pull request by zlowram**
Keeped "aeis" as an alias for compatibility.

### CODE REVIEW

**Comment by radare** [comment]
I don't see the point of having two commands that do the same. We already discussed this, and `aeis` should not reinitialize the memory if it was already initialized. Also, we should need a command to uninitialize that state. Would you work on that?

**Comment by zlowram** [comment]
Ok, I'll do it. Regarding the uninitialization, isn't `aeim-` already doing it?

**Comment by radare** [comment]
Yeah.. So i think that aeim only initializes once.. At least the memory.. Maybe it resets the registers.. My idea for aeis was just to initialize it if it was not there

**Comment by radare** [comment]
ping?

**Comment by radare** [comment]
im not going to wait much more to close this bug...

**Comment by radare** [comment]
Thanks!

**Pull request closed without merging**
