### PR TITLE
Add aeaj

### PR DESCRIPTION
**Pull request by Soly**
See #6366.

I did some minor refactoring since there was some repeated code. 

I'd like to amend this PR to also address the `aeaf` issue mentioned in #6366 but I'm not sure what the issue means.

### CODE REVIEW

**Comment by radare** [comment]
Can we have some tests for this? thanks!

**Comment by Soly** [comment]
For all the `aea` commands? 
Would these go in `t` or `t.anal`?

**Comment by Maijin** [comment]
t.esil

**Comment by Maijin** [comment]
And for aeaj add it in t/cmd_json too

**Pull request merged**
