### PR TITLE
Add r_reg_{get,set}_value_by_role and fix "aef" because "PC" is not available on every arch

### PR DESCRIPTION
**Pull request by MaskRay**
…vailable on every arch

### CODE REVIEW

**Comment by MaskRay** [comment]
Next plan is to refactor

```c
				const char *pc = r_reg_get_name (core->anal->reg, R_REG_NAME_PC);
				if (r_reg_getv (core->anal->reg, pc) == 0LL) {
```

and `SP` `BP` to use `by_role` versions.

**Comment by radare** [comment]
PC is an alias register name and it must exist in all archs

**Comment by MaskRay** [comment]
@radare  There are "pc" and "PC", the older code did work on x86.

**Comment by radare** [comment]
pc is a registername and PC is the alias, all eegisters are lowercase, all regroles are uppercase

**Comment by MaskRay** [comment]
Before the change, some function in `reg.c/value.c` complained the argument was `NULL` because `strcmp` did not find a register named `PC`. nvm

**Pull request merged**
