### PR TITLE
Renamed sdb models to .sdb.txt

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by Maijin** [comment]
image

**Comment by radare** [comment]
fix the build without meson

**Comment by xarkes** [comment]
lgtm

**Comment by kuh3h3** [comment]
but meson on windows vs2017 pre 3 can`t produce sdb files. yesterday it works well.

**Comment by kuh3h3** [comment]
handling messages there, but no sdb files  made.

C:\Users\kuh3h\Downloads\Compressed\radare2>sys\meson_sdb.py
The Meson build system
Version: 0.42.0
Source dir: C:\Users\kuh3h\Downloads\Compressed\radare2\shlr\sdb
Build dir: C:\Users\kuh3h\Downloads\Compressed\radare2\build_sdb
Build type: native build
Project name: sdb
Native C compiler: cl (msvc 19.11.25507.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Build targets in project: 2
ninja: Entering directory `build_sdb'
[9/24] Compiling C object sdb@sta/src_num.c.obj.
c:\users\kuh3h\downloads\compressed\radare2\shlr\sdb\src\num.c(34): warning C4146: unary minus operator applied to unsigned type, result still unsigned
[11/24] Compiling C object sdb@sta/src_json_js0n.c.obj.
TODO: json not implemented for this platform
[12/24] Compiling C object sdb@sta/src_cdb_make.c.obj.
c:\users\kuh3h\downloads\compressed\radare2\shlr\sdb\src\cdb_make.c(24): warning C4273: '_aligned_free': inconsistent dll linkage
c:\program files (x86)\windows kits\10\include\10.0.15063.0\ucrt\corecrt_malloc.h(144): note: see previous definition of '_aligned_free'
[14/24] Compiling C object sdb@sta/src_json.c.obj.
TODO: json not implemented for this platform
[20/24] Compiling C object sdb@sta/src_util.c.obj.
gettimeofday: Windows support is ugly here
[21/24] Compiling C object sdb@sta/src_sdb.c.obj.
c:\users\kuh3h\downloads\compressed\radare2\shlr\sdb\src\sdb.c(1126): warning C4090: 'function': different 'const' qualifiers
c:\users\kuh3h\downloads\compressed\radare2\shlr\sdb\src\sdb.c(1166): warning C4090: 'function': different 'const' qualifiers
[22/24] Linking static target libsdb.a.
src_json.c.obj : warning LNK4006: js0n already defined in src_json_js0n.c.obj; second definition ignored
[24/24] Linking target sdb.exe.
Generating sdb files.
Looking up C:\Users\kuh3h\Downloads\Compressed\radare2\libr\cons\d, C:\Users\kuh3h\Downloads\Compressed\radare2\libr\bin\d, C:\Users\kuh3h\Downloads\Compressed\radare2\libr\asm\d, C:\Users\kuh3h\Downloads\Compressed\radare2\libr\syscall\d, C:\Users\kuh3h\Downloads\Compressed\radare2\libr\magic\d, C:\Users\kuh3h\Downloads\Compressed\radare2\libr\anal\d
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\cons\d directory...
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\bin\d directory...
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\bin\d\dll directory...
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\asm\d directory...
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\syscall\d directory...
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\magic\d directory...
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\magic\d\default directory...
Handling C:\Users\kuh3h\Downloads\Compressed\radare2\libr\anal\d directory...
Done

**Comment by xarkes** [comment]
Yes I know I'll push a fix in a few hours ;)

**Pull request merged**
