### PR TITLE
Compile in release mode when testing

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by Maijin** [comment]
wow check the codecov

**Comment by ret2libc** [comment]
@Maijin what about codecov?

**Comment by Maijin** [comment]
Just interesting to see the huge change

**Comment by ret2libc** [comment]
Mmm maybe it's better to run with -O0/debug symbols when using covscan

**Comment by ret2libc** [comment]
This is not useful at all... Closing.

**Pull request closed without merging**
