### PR TITLE
Refactor evars asm.lines.*

### PR DESCRIPTION
**Pull request by wargio**
Related to issue #9798

```
asm.linesout > asm.lines.out
asm.linesright > asm.lines.right
asm.lineswide > asm.lines.wide
asm.lineswidth > asm.lines.width
```

### CODE REVIEW

**Comment by radare** [comment]
Conflict and red

**Comment by wargio** [comment]
fixed

**Comment by wargio** [comment]
Tests are broken. Today I'll patch them and send pr

**Comment by radare** [comment]
pls update the tests, and it says there are cornflakes here. will merge when grin

**Comment by Maijin** [comment]
shlr/www/enyo/disassembler_old.js need change in the radare2-webui repository then

**Comment by wargio** [comment]
Ok

**Comment by wargio** [comment]
@radare merge?

**Comment by radare** [comment]
its red

**Comment by radare** [comment]
im blindly merging because i think its a "race condition"

**Pull request merged**
