### PR TITLE
dcu: show error msg if debugger is dead

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by xarkes** [comment]
Are you sure `is_debugger` is enough to tell the debugger is running?
cc @fcasal

**Comment by radare** [comment]
what if the debugger plugin is debug.esil? or debug.io? we should probably clarify what debug mode is actually, and make clear when you debug or emulate, and when you transplant a process from one backend to another. btw why's that red :?

**Comment by kazarmy** [comment]
closing this since on second thought, the consequences aren't really catastrophic (just do `ood` and repeat the `dcu` command) and the error reporting should be done by code that is deeper in the function

**Comment by kazarmy** [comment]
on third thought, it should be ok to show an error message if the debugger is dead

**Pull request merged**
