### PR TITLE
Added Windows webserver instructions

### PR DESCRIPTION
**Pull request by JanWerder**

### CODE REVIEW

**Comment by radare** [comment]
I have the feeling that the current readme is too long, the command in linux and windows is the same, only the admin privs differ, so i would unify the command and add the notes related to windows right below the generic description.

r2 is a symlink to radare2, and there's no need to append the .exe. Anyone used to read documentation can share his 5cents on this?

**Comment by XVilka** [comment]
@radare may be add a request for an admin rights in the windows radare2? In the manifest https://msdn.microsoft.com/en-us/library/bb756929.aspx

**Comment by crowell** [comment]
why are admin rights even needed when starting the web server. the port
chosen should not require any elevated privs.

we should try to make it not require admin as a lot of people would not be
comfortable running r2 as admin/root.

On Mon, Apr 27, 2015 at 1:06 PM, Anton Kochkov <notifications@github.com>
wrote:

> @radare <https://github.com/radare> may be add a request for an admin
> rights in the windows radare2? In the manifest
> https://msdn.microsoft.com/en-us/library/bb756929.aspx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/pull/2446#issuecomment-96742287>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by JanWerder** [comment]
From my point of view, the ReadMe is not long enough, it way too brief. It doesn't explain the features or how to use r2 well. The ReadMe, in my oppinion, should be a "Getting Started" and it is certainly missing that at the moment

**Comment by JanWerder** [comment]
Also, wouldn't I have to manually create that symlink since there is no installer?

**Comment by radare** [comment]
We should distribute r2 for windows with a proper installer, context menu for explorer, etc, same for OSX, this must be done for 1.0 though. But it's good to enumerate all those issues. About the README. Maybe it takes sense to be an introduction to the program for simple projects, but r2 is *a lot*, to begin with, its not just a single program, and the amount of things you can do is quite big, so i would preferibly just provide a good description and point to other doc/* files which can give a deeper understanding of each tool

**Comment by radare** [comment]
@crowell @XVilka yep. looks like latest windows doesnt allow you to listen on any port (even unprivileged) without admin or certificate rights.

**Comment by radare** [comment]
Dunno if zip can store ntfs symlinks... Any suggestion to create a windows installer from linux? Something batchy...

**Comment by XVilka** [comment]
NSIS http://nsis.sourceforge.net/Main_Page ?

**Comment by JanWerder** [comment]
Maybe you should open an issue for that

**Comment by radare** [comment]
Added https://github.com/radare/radare2/issues/2461and https://github.com/radare/radare2/issues/2460 to track windows/osx packaging steps and merged this thing, so we can focus on the issues discussed here.

**Comment by JanWerder** [comment]
Shouldn't we merge the instructions?

**Comment by radare** [comment]
It was already merged as I said in the previous message: https://github.com/radare/radare2/commits/master

**Pull request closed without merging**
