### PR TITLE
Config variables for jmp/cjmp references

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by radare** [comment]
we should probably want to enable jmp/cjmp refs only if they are out of the function boundaries.

**Comment by dmtch** [comment]
Reasonably

**Comment by dmtch** [comment]
Also I think that it will be useful that string references will be identified when function analyzed.

**Comment by dmtch** [comment]
Strings list core->bin->cur->o->strings is always sorted by addresses, right? I want to use binary search to identify reference destination as string from this list.

**Comment by radare** [comment]
did you tried aar command?, strings can be referenced in many ways, sometimes thhe pointer is computed at runtime and you need to emulate code to get the reference. so we need to mix different kind of analysis to get all the references you are looking for.

yes, strings are sorted by adddress because that's how they are found. but strings are taken from "rabin2 -z", not by analysis. you can later run /r to find the ref to a speicifc string, or use asm.emu to find them too.

**Comment by radare** [comment]
ive merged it for testing sake :P we'll have time after release to remove unnecessary analysis options and enhace the default ones.

Thanks

**Pull request closed without merging**
