### PR TITLE
Fix build for !(__linux__ && !__powerpc__)

### PR DESCRIPTION
**Pull request by krytarowski**
This patch reenables build on NetBSD

### CODE REVIEW

**Comment by radare** [comment]
ptrace-getregs is suposed to work on netbsd too, the debugger works on openbsd and freebsd, i didnt tried recently, but the code is there. as fara as i understand this patch fixes the build for netbsd. :? please clarify

**Comment by krytarowski** [comment]
#endif was placed wrongly producing invalid code

**Comment by krytarowski** [comment]
switch(){} was unclosed.

**Comment by radare** [comment]
Confirmed. Works on openbsd. So it looks right

**Comment by krytarowski** [comment]
Thank you!

**Pull request closed without merging**
