### PR TITLE
fix crash where reg is past end of regnames

### PR DESCRIPTION
**Pull request by crowell**
ty to mike_pizza for bug report~

crash is in
https://github.com/ctfs/write-ups/blob/master/31c3-ctf-2014/pwn/cfy/cfy

`aa`
`pd sym.main`

### CODE REVIEW

**Comment by radare** [comment]
Which instruction is producing that case? Its a bug in cs or just wrong usage?

**Comment by crowell** [comment]
seems to be at addr `0x00402e7d` which `x/1i` claims to be 

```
[0x00402e7d]> x/1i 
0x00402e7d  664040474c4942435f  pop r15w
```

but but in reality it actually isn't...

because `pop r15w` should be 

```
66 41 5f                pop    r15w 
```

**Comment by crowell** [comment]
after my patch, this works...
```
[0x00402e7d]> pd 1
           0x00402e7d    664040474c4. pop r15w
```

**Comment by radare** [comment]
Can u increase asm.nbytes to show all the bytes of that instruction?

**Comment by crowell** [comment]
```
[0x00402e7d]> pd 1
           0x00402e7d    664040474c4942435f                           pop r15w
```

**Comment by radare** [comment]
Maybe @aquynh have something to say here.. there were some rex-related commits lately in capstone.
But udis86 and capstone output the same (pop r15w). What i'm worried is that if that out-of-bounds access on the regnames array is produced by a bug in capstone or on our side. Will look at it later when i have some more time.

thanks

**Comment by aquynh** [comment]
can you try with the `v3` branch & `next` branch, and report back the result?

anyway, the output of GNU is horrible.

thanks.

**Comment by aquynh** [comment]
looked again, i dont see anything wrong here: Capstone removes all the redundant REX bytes in the middle, as it should. if you take GNU disassembler as the reference, then i think you get the wrong choice in this case.

thanks.

**Comment by aquynh** [comment]
what is this *out-of-bounds access on the regnames array* you are talking about? how to reproduce that with a minimal code (no Radare, but Capstone only)?

**Comment by crowell** [comment]
the out of bounds access is in a radare2 array.

On Fri, Jan 2, 2015 at 11:37 AM, Nguyen Anh Quynh <notifications@github.com>
wrote:

> what is this *out-of-bounds access on the regnames array* you are talking
> about? how to reproduce that with a minimal code (no Radare, but Capstone
> only)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/pull/1928#issuecomment-68540162>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by aquynh** [comment]
ok so i hope that has nothing to do with Capstone.

**Comment by radare** [comment]
capstone provides a primitive to resolve registername, i think our array 
was not properly updated, but im not able to reproduce any crash, and 
the reg which is accessing is the last one in the array.. so that may be 
the issue.

i'm currently refactoring our plugin to use the capstone api to do that 
(dunno if there's any generic way to do that), but at least we will not 
need to maintain that dupped register list.

**Comment by radare** [comment]
Please test now, because i was not able to reproduce the crash, but the code looks better now.

Thanks

**Comment by crowell** [comment]
can't repro any more :+1:

**Pull request closed without merging**
