### PR TITLE
8051: allocate mapped memory

### PR DESCRIPTION
**Pull request by astuder**
More work on 8051:
- automatically allocate and map memory used for idata, sfr and xdata emulation <s>, required adding r_io to rasm dependencies</s>
- moved mapped memory to high range to avoid conflict with 8051 firmware images > 64K
- adjusted mapping of SFR to only occupy 128 bytes

Also see new pull request in radare-regressions

### CODE REVIEW

**Comment by astuder** [comment]
Gah! Can't make AppVeyor happy. Complains about mission r_io dependencies when building rasm.

**Comment by XVilka** [comment]
@astuder this is because AppVeyor builds using Meson build system, so you have to change corresponding files along with Makefiles: https://github.com/radare/radare2/blob/master/libr/anal/meson.build#L101

**Comment by radare** [comment]
dont add rio as dep, use the anal->iob instead

**Comment by astuder** [comment]
That's where I get io from.
mem_idata = cpu_memory_map (anal->iob.io, mem_idata, cpu_models[i].map_idata, 0x100);

I still need to link r_io into anal to make rasm compile.

**Comment by astuder** [comment]
Ok, I think I get it.. use ->iob.load_at etc. instead of getting the io object.

Will have to add another function for remap, probably encapsulated as r_io_remap(RIODesc*) or similar.

**Comment by radare** [comment]
yeah, add it

**Pull request merged**
