### PR TITLE
NetBSD declares forkpty(3) in <util.h>

### PR DESCRIPTION
**Pull request by krytarowski**
```
OPENPTY(3)                 Library Functions Manual                 OPENPTY(3)

NAME
     openpty, login_tty, forkpty -- tty utility functions

LIBRARY
     System Utilities Library (libutil, -lutil)

SYNOPSIS
     #include <util.h>

     int
     openpty(int *amaster, int *aslave, char *name, struct termios *termp,
         struct winsize *winp);

     int
     login_tty(int fd);

     pid_t
     forkpty(int *amaster, char *name, struct termios *termp,
         struct winsize *winp);
```

### CODE REVIEW

**Comment by ret2libc** [comment]
Thanks a lot! Please, try to refactor it to include only one time util.h because also APPLE uses util.h.

**Comment by radare** [comment]
Waiting for those changes to merge.

**Comment by krytarowski** [comment]
Done!

**Comment by radare** [comment]
Merged!

**Pull request closed without merging**
