### PR TITLE
Fix aaft Stack isn't initialized and run aaft in aaa/aaaa

### LINKED ISSUE #13776: aaa (aaft) - Stack isn't initialized
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | WSL Debian x64 (buster)
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21907 @ linux-x86-64 git.3.4.1-142-ge4c9b1053 commit: e4c9b10533dbe945c2f7412975401a853d90b5ef build: 2019-04-15__21:43:39

### Expected behavior
No errors

### Actual behavior
Multiple 
```
Try running aei and aeim commands before aft for default stack initialization
Stack isn't initialized.
```
`aei` and `aeim` seems to have no effect

### Steps to reproduce the behavior 
`$ r2 ls`
`aaa`

### Additional Logs, screenshots, source-code,  configuration dump, ...

[ls.zip](https://github.com/radare/radare2/files/3082561/ls.zip)

### PR DESCRIPTION
**Pull request by sivaramaaa**
Fixes #13776 , #13854

### CODE REVIEW

**Comment by radare** [comment]
2 XX, one sems fine the othre seeems wtf

Screenshot 2019-04-22 at 13 08 21

**Comment by sivaramaaa** [comment]
> othre seeems wtf

exactly :( ,  i will check this out !

**Comment by radare** [comment]
Grin

**Comment by sivaramaaa** [comment]
yup :) , sent a PR to r2r fixing tests !

**Pull request merged**
