### PR TITLE
asm.strenc -> bin.str.enc

### PR DESCRIPTION
**Pull request by kazarmy**
Make it global.

### CODE REVIEW

**Comment by radare** [comment]
We should group all the bin.str* into bin.str.*

we have this right now:

* bin.strfilter
* bin.strings
* bin.strpurge

so i suggest:

* bin.strings
* bin.str.{purge,filter,enc}

**Comment by kazarmy** [comment]
sgtm

**Comment by radare** [comment]
Can you do another pr with the changes i suggested?

**Comment by kazarmy** [comment]
Yes

**Pull request merged**
