### PR TITLE
baddr/vaddr/paddr/laddr fixes

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by radare** [comment]
yay, waiting for travis :D

**Comment by ret2libc** [comment]
https://github.com/radare/radare2-regressions/pull/212

**Comment by ret2libc** [comment]
still not ready to merge even if tests are green.

**Comment by radare** [comment]
Greentesting is a good sign :)

**Comment by radare** [comment]
Please rebase into a single commit and solve conflicts

**Comment by ret2libc** [comment]
Please keep those commits as they are. This pr touches multiple things and i prefer to not have one huge commit.

**Comment by radare** [comment]
Ok

**Pull request merged**
