### PR TITLE
XREF in local variables ##anal

### LINKED ISSUE #11865: XREF in local variables
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86 
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0 19966 @ darwin-x86-64 git.2.9.0-395-g9beda2f60 commit: 9beda2f60f97a35f3e20c2c5f6933241bb78afbf build: 2018-10-18__11:04:28

### Expected behavior

- Get file [ch2.zip](https://github.com/radare/radare2/files/2494822/ch2.zip)
- aaa
- axt @ local_ch # But needs to be able to select function though

Should display something like:

```
main 0x0804831a [DATA] mov dword [local_ch], str.john
main 0x08048366 [DATA] mov eax, dword [local_ch]
```

### Actual behavior

Display nothing

### PR DESCRIPTION
**Pull request by sivaramaaa**
fixes #11865 

**Updated** 

screenshot from 2018-11-20 11-24-28

### CODE REVIEW

**Comment by radare** [comment]
That wont work if the fcn have a dot in its name?

**Comment by sivaramaaa** [comment]
@radare yup , what about a solution like this , split this input with "."  and use last one as var name

for example `func.a.b.c.var_name` ==> [func,a,b,c,var_name] 

what do u think @Maijin , @XVilka

**Comment by Maijin** [comment]
We need a way to do this, so any solution you can come with I'm all in 👍

**Comment by sivaramaaa** [comment]
> axt main local_10h

sounds great , will do it !

**Comment by radare** [comment]
Only problem i see is that current arg can contain spaces as a math expression ans with this change we enforce no spaces in those expressions

**Comment by XVilka** [comment]
What's wrong with taking the last dot? We have the same approach for local
flags. So it will be consistent.

**Comment by radare** [comment]
imageina f ucntion named fcn.main.loop and another one named fcn.main with  a local v ar named "loop".

using a space is safer here

**Comment by XVilka** [comment]
Well, then lets go for space.

**Pull request merged**
