### PR TITLE
x86.cs: fix XOR and AND esil analysis

### PR DESCRIPTION
**Pull request by zamaudio**
Signed-off-by: Damien Zammit <damien@zamaudio.com>

### CODE REVIEW

**Comment by sushant94** [comment]
I'm not sure if this is the best way to implement this. It makes the ESIL string longer. Another problem is that I foresee is deciphering what the actual instruction is, which is important for most static analysis (and of course, decompilation). For these purposes, it's easier if an ESIL instruction is always of the form: <instructions>,<side-effects due to instruction>. Besides, imo, the zero-extend while using eax,..., should be handled at the register write level rather than adding instructions for this in ESIL itself.

**Comment by zamaudio** [comment]
Your response sounds reasonable.  But if your register writing is arch dependent, doesn't that add another layer of obscurity to the decompilation?  At least with my method, the instruction is of the form: `<zero extend>,<instruction>,<side effects>` so what is the difference?

**Comment by zamaudio** [comment]
It is possible to move the zero extending to after the instruction with the same code... and it becomes a side effect.

**Comment by sushant94** [comment]
Yes, but the decompilation will have an architecture dependent phase which will take care of that (and a couple of other things like function prologue, epilogue etc.). If you add this information through ESIL instructions, I feel (I may be wrong here and need to think deeper into this) it would be harder to remove these extra operations and infer the "true" instruction.

> At least with my method, the instruction is of the form: <zero extend>,<instruction>,<side effects> so what is the difference?

So, the problem as I see is, the arguments to the operation(/instruction) is already a 32-bit register. It does not make much sense to add a zero-extend before it when this was supposed to be taken care of the underlying arch's register write. Going along the same lines, we should also be using something like `rax & 0xFF` and use the result for `al` rather than using `al` itself.

> It is possible to move the zero extending to after the instruction with the same code... and it becomes a side effect.

I like this idea better :) Though I still prefer it is handled at the register level.

**Comment by zamaudio** [comment]
Okay I think I understand better now, so the "hardware" part should know how to zero extend on register writes, and not the esil.  And this part has to be arch dependent.  This way the esil is simplified and better represents basic instructions that can be decompiled... So where is the code that represents the "hardware"?  Perhaps there should be a libr/reg/p for each arch that takes care of the arch specific register stuff...

**Comment by Maijin** [comment]
@condret See this ^

**Comment by radare** [comment]
There are cornflakes for this pr, please rebase to master

**Comment by zamaudio** [comment]
I'm closing this, as it is the wrong approach for fixing the analysis.  The esil is correct, it's just that the underlying reg writes need to be aware of the finer details of the arch.

**Comment by radare** [comment]
thanks

**Comment by condret** [comment]
@zamaudio you are wrong, esil is designed to cover lots of different architectures, not for x86_64-specific regwrites. If x86_64 behaves weird, you need to create specific expressions, not a specific vm

**Pull request closed without merging**
