### PR TITLE
Kill the _end section flags and fix flag size

### PR DESCRIPTION
**Pull request by radare**
Fix https://github.com/radare/radare2/issues/11348

### CODE REVIEW

**Comment by radare** [comment]
the XX look good to me, updating them should be harmless. Also noticed some improvements.
screen shot 2018-09-02 at 03 24 27

**Comment by ret2libc** [comment]
of course after fixing tests :D

**Comment by radare** [comment]
yep :P if anyone in the mood :P

**Comment by kazarmy** [comment]
Some people are going to miss those `_end` flags since:

1. The alternative of `section..<section> + $s{section..<section>}` is less convenient.
2. It would be nice to have a visual indicator of the section you're entering when moving backwards in Visual mode.

> 

Regarding the above, it might be better to have an `asm` config var to show all flags at an address.

**Comment by ret2libc** [comment]
> It would be nice to have a visual indicator of the section you're entering when moving backwards in Visual mode.

that's true, though I think things should be displayed based on flag starting address + flag size, instead of having two flags as it is right now in master.

**Comment by kazarmy** [comment]
might be tricky to implement efficiently but ok

**Comment by radare** [comment]
because i think its easier to improve the RNumCallback to handle $$flagname for this

```
[0x100001200]> ?v $$section.2.__TEXT.__stub_helper
0x100004900
[0x100001200]> ?v section.2.__TEXT.__stub_helper
0x1000045f8
[0x100001200]>
```

i have a bunch of suggestions and ideas to improve the syntax for those numbers

**Comment by radare** [comment]
moved to $e{}
```
[0x100001200]> ?v section.0.__TEXT.__text
0x100000f20
[0x100001200]> ?v $e{section.0.__TEXT.__text}
0x10000442e
[0x100001200]> ?v $s{section.0.__TEXT.__text}
0x350e
[0x100001200]>
```

**Comment by Maijin** [comment]
The e{} Sgtm

**Comment by XVilka** [comment]
Agree, we just need add this into the Sections chapter of r2book.

**Comment by radare** [comment]
ok, rebasing and updating tests for the glory of the merge

**Comment by radare** [comment]
before adding this to the book i would prefer to discuss all the ?$? vars

**Pull request merged**
