### PR TITLE
Add function signature here and there and solve (null) in fcn->cc ##visual

### PR DESCRIPTION
**Pull request by radare**
screenshot 2019-03-07 at 18 26 10

as requested by @XVilka

### CODE REVIEW

**Comment by XVilka** [comment]
Good, just need to be a different color I think, so will be easily distinctive from the 1t line

**Comment by radare** [comment]
graph ttile cant use colors... yet i also prefer a different alignment and such, but that requires more work and didnt wanted to complicate the thing

**Comment by radare** [comment]
maybe i should update the tests... or we should discuss a better title or hide title when not in interactivie

image 2019-03-07 19 03 04

**Comment by radare** [comment]
actually the 2 line thing looks pretty bad, i would go for just showing the function signature and the offset.. and show the n/e/z/m.. in '?'. comments?

screenshot 2019-03-07 at 19 08 06

**Pull request merged**
