### PR TITLE
Fix wrong r2 emulate ARM

### LINKED ISSUE #11648: Wrong r2 emulate ARM
I compiled source code from this [Article](http://www.mien.in/2018/08/15/emulating-decryption-function-with-radare2/) to arm x32 architecture

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | docker radare/radare2
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            | arm 32 le.
| $ r2 -v                                                           | radare2 3.0.0-git 1 @ linux-x86-64 git.3.0.0-git
commit: 17f2f3abf1fed2f2966a17a19f24c85ce95ae2d9 build: 2018-09-25__11:36:56
### Steps to reproduce the behavior 
$ r2 ./decode
```
[0x00008110]> e asm.emu=true
[0x00008110]> ar0
[0x00008110]> s sym.is_valid
[0x00008218]> aei
[0x00008218]> aeim
[0x00008218]> aeip
[0x00008218]> w oSekma @ sp
[0x00008218]> aer r0=sp
[0x00008218]> aes; aer ; pxW 50 @ sp ; pd 10 @ pc
```
- Next I trace the program use next command: `aes; aer ; pxW 50 @ sp ; pd 10 @ pc`
- Look at the next souce:
```
            0x00008244      0030a0e3       mov r3, 0                   ; r3=0x0
            0x00008248      24300be5       str r3, [fp, -0x24]         ; sym.__libc_tsd_CTYPE_TOLOWER
            0x0000824c      24301be5       ldr r3, [fp, -0x24]         ; sym.__libc_tsd_CTYPE_TOLOWER ; r3=0x0
            0x00008250      050053e3       cmp r3, 5                   ; 5 ; zf=0x0
        ,=< 0x00008254      1d0000ca       bgt 0x82d0                  ; pc=0x82d0 -> 0xe55b301d ; likely
```
 - Then I trace to position `0x00008250` I have the next station:
```
sb = 0x00000000
sl = 0x00000000
fp = 0x00177ffc
ip = 0x00178000
sp = 0x00177fd8
lr = 0x00000000
pc = 0x00008250
r0 = 0x00178000
r1 = 0x00000000
r2 = 0x00000000
r3 = 0x00000000
r4 = 0x00000000
r5 = 0x00000000
r6 = 0x00000000
r7 = 0x00000000
r8 = 0x00000000
r9 = 0x00000000
r10 = 0x00000000
r11 = 0x00177ffc
r12 = 0x00178000
r13 = 0x00177fd8
r14 = 0x00000000
r15 = 0x00008250
cpsr = 0x00000000
blank = 0x00000000
```
As you can see `R3 = 0`. But radare2 on next instruction `0x00008254      1d0000ca       bgt 0x82d0` make jump to `0x82d0` anyway. Its wrong because 0<5

### Additional Logs, screenshots, source-code,  configuration dump, ...
Archive contains screenshots, source-code and compiled binary file
[decode.zip](https://github.com/radare/radare2/files/2415922/decode.zip)

### PR DESCRIPTION
**Pull request by Maijin**
Fix #11648

### CODE REVIEW

**Comment by radare** [comment]
The failing tests are a bit wtf

e3002d8f-6054-4457-bd24-fbf4afb16950

**Comment by radare** [comment]
I think that you nay try to use == instead of -

**Comment by radare** [comment]
Substracting pushes the result in the stack and you are not using it

**Comment by Maijin** [comment]
@radare feel free to change the PR, I just made a PR out from the fix proposed from the issue.

I think @mrmacete also looks at it

**Comment by radare** [comment]
@Maijin can you confirm the behaviour is correct and update the tests accordingly?

**Comment by radare** [comment]
yes i know, thats why i said to review them because its just the cpsr which is different and ts probably goo dnow. if the bebaviour is correct i would just update the tests and merge

do you have any snipped of code to test this?

**Comment by mrmacete** [comment]
hey i have investigated this, wait!

**Comment by mrmacete** [comment]
the issues are:
- the "C" (carry flag) is the OPPOSITE of borrow
- the tests have wrong assumption on other flags

i'm going to push a tweak both here and in r2r

**Pull request merged**
