### PR TITLE
Remove compressed symsrv symbol support

### LINKED ISSUE #9309: Symbol download doesn't work with newer Windows targets
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 17083 x64
| File format of the file you reverse (mandatory)      | notepad.exe
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 17169 @ windows-x86-32 git.2.2.0-361-g8b1e0bb16 commit: 8b1e0bb16e738d9e805297bca21adcac49a6b0a9 build: Sat 02/03/2018__21:59:11.96
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/riverar/51793676c82c84eced464ab44fd73e6f

### Expected behavior
Symbols for notepad to download from symsrv successfully

### Actual behavior
```
curl exited with error 1
PDB "notepad.pdb" download failed
```

### Steps to reproduce the behavior 
- `r2 -d [pid_of_syswow64_notepad]`
- `> idpd`
- Note error appears, as mentioned above

### PR DESCRIPTION
**Pull request by riverar**
Fixes #9309

Microsoft made changes server-side and has obsoleted compressed symbol support for all newer binaries (to speed up the process). (https://twitter.com/WithinRafael/status/960050544684384256)

Rather than futz with more failback code, I yanked compressed symbol support. There's no guarantee compressed symbols will exist now or in the future so radare2 shouldn't bother trying.

### CODE REVIEW

**Comment by Maijin** [comment]
This is true for MS but not for the other as you said on telegram you’ll come with a better fix

**Comment by radare** [comment]
Add an eval var handled from env in rabin2 to allow the old method disabled by default instead of removing the code

Thanks!

**Comment by XVilka** [comment]
I think should be kept, yes, disabled by default. "e pdb.compressed = true" will enable this old method.

**Comment by riverar** [comment]
Abandoning. Not needed. Turns out, my curl was super old and not returning the appropriate error codes. It is now, which triggers the fallback behavior correctly.

**Pull request closed without merging**
