### PR TITLE
Fix build with external libzip

### PR DESCRIPTION
**Pull request by krytarowski**
Caught on NetBSD with pkgsrc

### CODE REVIEW

**Comment by radare** [comment]
This should be conditional, otherwise you'll break other builds

**Comment by krytarowski** [comment]
Conditional? How?

**Comment by radare** [comment]
#ifdef ?

**Comment by krytarowski** [comment]
This is `.mk` file. I don't understand. Conditional for what condition? Alternative?

**Comment by radare** [comment]
ifeq()

**Comment by krytarowski** [comment]
And what would be the condition?

I don't see similar approach in other files, eg.
```
shlr/gdb/Makefile:include ../../shlr/zip/deps.mk
```

**Comment by radare** [comment]
the condition will be
```
ifneq(USE_LIB_ZIP,1)
…
endif

this var is defined by the configure script inside the config-user.mk which is included in all the makefiles inside the project.

the thing is that r2 should build with and without —with-syszip flag

> On 31 Oct 2015, at 17:18, krytarowski <notifications@github.com> wrote:
> 
> And what would be the condition?
> 
> I don't see similar approach in other files, eg.
> 
> shlr/gdb/Makefile:include ../../shlr/zip/deps.mk
> —
> Reply to this email directly or view it on GitHub <https://github.com/radare/radare2/pull/3641#issuecomment-152746574>.
>

**Comment by krytarowski** [comment]
Isn't it already handled in `libr/util/deps.mk`?

```
ifeq ($(USE_LIB_ZIP),1)
LINK+=$(LIBZIP)
else
LINK+=$(SHLR)/zip/librz.a
CFLAGS+=-I$(SHLR)/zip/include
endif
```

**Comment by radare** [comment]
yes, that’s how it should work

**Comment by radare** [comment]
uhm, the patch looks good, let me try to build on all platforms

1m

**Comment by radare** [comment]
Merged!

**Pull request closed without merging**
