### PR TITLE
Add "doc" for Cannot find DLLNAME.sdb

### PR DESCRIPTION
**Pull request by Maijin**
Add "doc" for Cannot find DLLNAME.sdb

### CODE REVIEW

**Comment by marespiaut** [comment]
Hello @Maijin 
I've tried following your documentation to create a `dplayx.sdb.txt` but it doesn't seems to work since the output is
```
directx.inf:      1, directx\d3dhalf.dll,,,COPY,1996-08-29,,,,!READONLY,,,,,SHARED,110080,SYSTEM,999,,,
```
which is very different from the expected result.
Linked here is the directx directory I've used.
[directx.tar.gz](https://github.com/radare/radare2/files/1649806/directx.tar.gz)

**Comment by Maijin** [comment]
This is due to the change of format of the output

**Comment by Maijin** [comment]
nvm

`rabin2 -rs directx/d3dhalf.dll | grep -i d3dhalf |grep -v Ordi | grep ^k| cut -d / -f 4-`

works here

**Comment by Maijin** [comment]
```
1=RLDDIGetCaps
2=D3DHAL_CleanUp
3=RLDDIDDrawCreateDriver
4=RLDDIFree
5=RLDDIInit
6=RLDDIMalloc
7=RLDDIPopDriver
8=RLDDIPushDriver
9=RLDDIRaise
10=RLDDIRealloc
```

**Comment by Maijin** [comment]
This script is for the dll not for the .inf stuff

**Comment by radare** [comment]
Rabin output has changed. And the script hasnt been updated accordingly

**Comment by Maijin** [comment]
The scripts works i just tried

**Comment by radare** [comment]
Kk

**Pull request merged**
