### PR TITLE
Update intro.md

### PR DESCRIPTION
**Pull request by ahhh**
Minor spelling corrections

### CODE REVIEW

**Comment by Maijin** [comment]
This https://github.com/pwntester/cheatsheets/blob/master/radare2.md is probably what should be updated instead

**Comment by ahhh** [comment]
You'll notice the exact same pull request is in his repository / branch of the cheatsheet, however according to his comments made on March 7th 2015, he expects future changes to be made to the main radare2 repository as this is now the preferred master version to update due to it's inclusion in the main set of documents: https://github.com/pwntester/cheatsheets/issues/3#issuecomment-78545656

**Comment by ahhh** [comment]
This also begs the question that if the article is included in your documentation, what reasons would you have for leaving the spelling mistakes?

**Comment by radare** [comment]
Thanks!

**Comment by Maijin** [comment]
@ahhh oh didn't see that :) thanks

**Pull request closed without merging**
