### PR TITLE
syscalls: remove fastcall and ioports

### PR DESCRIPTION
**Pull request by jacobrosenthal**
I couldnt figure out how fastcall was used, until I figured out it wasnt.

Presumably this is vestigial and useful to keep around?

### CODE REVIEW

**Comment by XVilka** [comment]
Ioports will be used, why do you want to remove it? Return it back. It is
just not yet finished.

**Comment by Maijin** [comment]
@jacobrosenthal @XVilka the ioports needs to be moved into an sdb file and read from there see #8467

**Comment by radare** [comment]
and ioports are used from disasm already.

pls dont remove stuff if you dont know what you are doing

**Comment by jacobrosenthal** [comment]
What about fastcall?!

**Comment by Maijin** [comment]
@jacobrosenthal the code that are using fastcall need to be replaced by the sdb files that are defining the calling convention like https://github.com/radare/radare2/blob/master/libr/anal/d/cc-x86-32.sdb.txt#L21

**Pull request closed without merging**
