### PR TITLE
Try to fix attaching issues for Windows

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by josediazfer** [comment]
@XVilka Can you prevent to use both global variables winbase and wintid?

**Comment by XVilka** [comment]
@josediazfer making a quick fix for now. Feel free to kill those after.

**Comment by josediazfer** [comment]
Why you are defining w32_DebugActiveProcess? It´s not called from anywhere.

**Comment by XVilka** [comment]
@josediazfer I'm trying different things, will remove unused code when issue is fixed, using AppVeyor instead of build environment.

**Comment by XVilka** [comment]
@josediazfer thx, addressed your comments, cleaned up the final patch and it fixes the issue!

**Pull request merged**
