### PR TITLE
Wrote tests x86_new assembler and fixed some bugs

### PR DESCRIPTION
**Pull request by aaronpuchert**
There is now a test script in `libr/asm/t/test.new`. Most tests pass, except for not always selecting the shortest bytecode. And we don't understand prefixes yet. More tests would have to be added later, but many opcodes are not yet there.

### CODE REVIEW

**Comment by radare** [comment]
Great stuff! merged!

**Comment by radare** [comment]
Some invalid one:
```
$ rasm2 -a x86.new -b 64 "mov rax,33"
b021
$ rasm2 -b 64 -d b021
mov al, 0x21
```

**Comment by XVilka** [comment]
Why not in https://github.com/radare/radare2-regressions ?

**Comment by radare** [comment]
Yep. this must be moved there, I have already exposed that in another issue. But as long as this is more for testing than for regressing, it needs to be adapted and stabilized, which its part of the evolution of the assembler/disassembler module.

**Comment by aaronpuchert** [comment]
The revert commit wasn't mine, it was just on master when I last pulled. 64-bit instructions don't work at all, because I didn't write anything about them yet. Will be next on the agenda. You can move the tests later, but for now they help me (and possibly others) to find out what needs to be done.

**Pull request closed without merging**
