### PR TITLE
Fix crash in mach0 loader

### PR DESCRIPTION
**Pull request by alvarofe**

### CODE REVIEW

**Comment by radare** [comment]
this will break the hello-objc test because it chops the section names

**Comment by Maijin** [comment]
https://travis-ci.org/radare/radare2/jobs/91921017#L862-L890

**Comment by radare** [comment]
i have already dropped this because it breaks the section names. see t.formats/mach0/objc

**Comment by alvarofe** [comment]
knowing the test i can look better at it

**Pull request closed without merging**
