### PR TITLE
core/graph: sdbization of RAGraph

### PR DESCRIPTION
**Pull request by ret2libc**
This patch adds the command 'aggk' to get the info of a RAGraph in sdb form. At the moment it only works on the core->graph, but in the future we can enhance the command to accept an address of a function and retrieve the info of that graph. Also, the command will accept some query like the 'k' command.

Some things to note: numbers are set in Sdb using the sdb_set and not the sdb_num_set because it seems it only accept unsigned int, while most of what we want to display is signed. Is it ok?

This is the first step to add tests for ascii-art graph.

### CODE REVIEW

**Comment by radare** [comment]
why do you need signed integers in a graph?

**Comment by ret2libc** [comment]
because x,y coordinates of nodes in the Canvas can be also negative

**Comment by radare** [comment]
This can be solved by adding a base delta to all the offsets and add another key to specify that base, this is what canvas_x/_y can represent, having absolute numbers was a decision for simplicity, so all numeric operations are performed on unsigned 64 bit integers.

**Comment by ret2libc** [comment]
Mmm I don't think I got it. If i add a delta and make all the numbers unsigned, it can be a problem when, later, I will try to restore the state of a graph from Sdb, since I will put an unsigned value in a signed field.

**Comment by radare** [comment]
U'll have a honor that delta every time u serialize/deserialize a value from one place to another

**Comment by ret2libc** [comment]
For the moment i have only serialization.
I've added the delta(x and y).

**Comment by radare** [comment]
Ok, waiting for the deserialization to squash and merge.

**Comment by ret2libc** [comment]
How should the deserialization command work?
```
agg+ < graph.sdb
```
Something like that? Or is there another command I can take as an example?

**Comment by radare** [comment]
no, sdb is not suposed to be used as a stream. also, r2 inverse pipe, and sdb files are binary, not plain text, so that may fail.

sdb databases are suposed to be mmaped in memory. so not sure what you are looking for exactly, but i would suggest just loading the sdb file, i plan to support plain text sdb databases soon or late, so this may be the way imho. also agg+ doesnt looks like a good command to me. its not adding anything, you want to display that graph, right? or just load it? what about just using plain text for input and output? to dump r2 commands using agg* and load them with . graph.r2 ?

no need for sdb here if you are going to rebuild the information every time.

**Comment by ret2libc** [comment]
Using agg* and '.' seems the best option imo! I've used sdb because i thought it's a good way to serialize an object and it will be used later to add tests for the ascii art graph.
So i will add support for 'agg*' command and then we can merge it. Is it ok?

**Comment by radare** [comment]
Good!

**Comment by ret2libc** [comment]
Added 'agg*' to print r2 commands to regenerate the core->graph

**Comment by radare** [comment]
What's missing to merge? apart from squashing?

**Comment by ret2libc** [comment]
squashed and merged

**Pull request closed without merging**
