### PR TITLE
Initial RISC-V 32/64 analysis

### PR DESCRIPTION
**Pull request by q6r**
This is a basic analysis for RISC-V. It detects returns, jumps, a bunch of instructions. Needs much improvements.

### CODE REVIEW

**Comment by q6r** [comment]
Two sample binaries (risc-v 64bit) for testing : http://0x80.org/samples_riscv64.tgz
I'll appreciate it if someone can generate 32bit binaries.

**Comment by Maijin** [comment]
Add those binaries in https://github.com/radare/radare2-regressions t.format

**Comment by q6r** [comment]
@Maijin sent https://github.com/radare/radare2-regressions/pull/244

**Comment by Maijin** [comment]
See also tons of warnings: 

* https://travis-ci.org/radare/radare2/jobs/88490904#L147-L176
* https://travis-ci.org/radare/radare2/jobs/88490904#L203-L220

**Comment by radare** [comment]
Fixed warnings, squashed and pushed. Thanks!

**Pull request closed without merging**
