### PR TITLE
travis: Dockerise build deps to speed up end-to-end test

### PR DESCRIPTION
**Pull request by zamaudio**

### CODE REVIEW

**Comment by zamaudio** [comment]
See radare/radare2-regressions#1367 for r2r change

**Comment by zamaudio** [comment]
Latest build/test took 11mins 4sec, if merged this time could reduce since it would cache docker hub image.

**Comment by radare** [comment]
Thanks!

**Comment by Maijin** [comment]
@radare yes but now we only test linux and only gcc, no OSX anymore nor CLANG looks like :/

**Comment by zamaudio** [comment]
@Maijin if clang is still required, it could be added to the docker image but that could double your time to test end-to-end in the worst case.  Having all three means you could have to wait up to 45 minutes for a commit before you know something is wrong... is it really necessary to build all these three every commit?

**Comment by XVilka** [comment]
Yes, it is necessary, we saw many cases when GCC build failed but Clang -
not, and vice versa.

**Comment by radare** [comment]
Mainly because of invalid chars being ignored or c99 features

**Pull request merged**
