### PR TITLE
Add red-black tree to util/r_rbtree.c

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by condret** [comment]
AWESOM

**Comment by Maijin** [comment]
@MaskRay Could you check here if you can make some unit tests for this https://github.com/radare/radare2-regressions/tree/master/unit ?

**Comment by Maijin** [comment]
instead of the assert

**Comment by MaskRay** [comment]
@Maijin https://github.com/radare/radare2-regressions/pull/977

**Pull request closed without merging**
