### PR TITLE
Fix #12654 - resolv reloc symbols

### LINKED ISSUE #12654: Missing reloc symbols
Hi there,
I came a across the fact that some reloc symbols are not recognized by radare2. I'm already trying to debug this for some time now, and I fear I'm might missing some detail.  So I would appreciate any help on this.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Manjaro X86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20627 @ linux-x86-64 git.3.1.3-217-g399fcc24a commit: 399fcc24aad065fe08fefc6d74bebdbc53e0181a build: 2019-01-04__23:00:04

### Expected behavior
```
r2 /usr/lib/libc.so.6
[0x00024330]> aa
...
[0x00024330]> sf sym.__run_exit_handlers
[0x0003a320]> agcj~{}
[
  {
    "name": "sym.__run_exit_handlers",
    "size": 588,
    "imports": [
      "sym.__lll_lock_wait_private",
      "sym.__lll_unlock_wake_private",
      "reloc.free",
      "rsp",
      "sym._Exit",
      "sym.__call_tls_dtors"
    ]
  }
]
```
From BinaryNinja:
screenshot from 2019-01-04 23-22-32

### Actual behavior
```
r2 /usr/lib/libc.so.6
[0x00024330]> aa
...
[0x00024330]> sf sym.__run_exit_handlers
[0x0003a320]> agcj~{}
[
  {
    "name": "sym.__run_exit_handlers",
    "size": 588,
    "imports": [
      "sym.__lll_lock_wait_private",
      "sym.__lll_unlock_wake_private",
      "unk.0x1bdfa8",
      "rsp",
      "sym._Exit",
      "sym.__call_tls_dtors"
    ]
  }
]
```
Visual Mode shows same behaviour:
screenshot from 2019-01-04 23-23-33

### Steps to reproduce the behavior 
Execute steps as shown above using (extracted) [libc.so.6.zip](https://github.com/radare/radare2/files/2728760/libc.so.6.zip)

### PR DESCRIPTION
**Pull request by blenk92**
Hi there,
this patch aims to fix https://github.com/radare/radare2/issues/12654. I would however rather call this a workaround that should be revised a some point.

### CODE REVIEW

**Comment by ret2libc** [comment]
I will review this. Thanks!

**Comment by radare** [comment]
I think that if it works, even as a workaround is an important fix, and the correct fix may take more time. we can revert it when refactoring it properly like you said. And doesnt breaks any test

**Comment by radare** [comment]
i've tested the patch and i can confirm that it works. can you submit a test with a smaller binary as a PR in r2r?

**Comment by ret2libc** [comment]
As said, I think this is not the right solution... and with pretty much every workaround, it has its problems and I think we should revert it @radare .

Example:
```
$ r2-before ./libc.so.6
> ii
[Imports]
Num  Vaddr       Bind      Type Name
   1 0x00000000    WEAK  NOTYPE __libpthread_freeres
   2 0x00000000  GLOBAL     OBJ _rtld_global
   3 0x00000000  GLOBAL     OBJ __libc_enable_secure
   4 0x00000000  GLOBAL    FUNC __tls_get_addr
   5 0x00000000  GLOBAL    FUNC _dl_exception_create
   6 0x00000000  GLOBAL     OBJ _rtld_global_ro
   7 0x00000000  GLOBAL    FUNC __tunable_get_val
   8 0x00000000  GLOBAL    FUNC _dl_find_dso_for_object
   9 0x00000000    WEAK  NOTYPE _dl_starting_up
  10 0x00000000    WEAK  NOTYPE __libdl_freeres
  11 0x00000000  GLOBAL     OBJ _dl_argv
   1 0x00000000    WEAK  NOTYPE __libpthread_freeres
   2 0x00000000  GLOBAL     OBJ _rtld_global
   3 0x00000000  GLOBAL     OBJ __libc_enable_secure
   4 0x00000000  GLOBAL    FUNC __tls_get_addr
   5 0x00000000  GLOBAL    FUNC _dl_exception_create
   6 0x00000000  GLOBAL     OBJ _rtld_global_ro
   7 0x00000000  GLOBAL    FUNC __tunable_get_val
   8 0x00000000  GLOBAL    FUNC _dl_find_dso_for_object
   9 0x00000000    WEAK  NOTYPE _dl_starting_up
  10 0x00000000    WEAK  NOTYPE __libdl_freeres
  11 0x00000000  GLOBAL     OBJ _dl_argv
```

```
$ r2-after ./libc.so.6 (taken from the original issue)
> ii
[Imports]
Num  Vaddr       Bind      Type Name
   1 0x00000000    WEAK  NOTYPE __libpthread_freeres
   2 0x00000000  GLOBAL     OBJ _rtld_global
   3 0x00000000  GLOBAL     OBJ __libc_enable_secure
   4 0x00000000  GLOBAL    FUNC __tls_get_addr
   5 0x00000000  GLOBAL    FUNC _dl_exception_create
   6 0x00000000  GLOBAL     OBJ _rtld_global_ro
   7 0x00000000  GLOBAL    FUNC __tunable_get_val
   8 0x00000000  GLOBAL    FUNC _dl_find_dso_for_object
   9 0x00000000    WEAK  NOTYPE _dl_starting_up
  10 0x00000000    WEAK  NOTYPE __libdl_freeres
  11 0x00000000  GLOBAL     OBJ _dl_argv
  83 0x001c333c  GLOBAL     OBJ getdate_err
 199 0x001c3538  GLOBAL     OBJ __rcmd_errstr
 207 0x001be1a4  GLOBAL     OBJ optind
 213 0x001c3370  GLOBAL     OBJ argp_program_version
 224 0x001c0748    WEAK     OBJ __free_hook
 282 0x001bf350  GLOBAL     OBJ __tzname
 287 0x001bf360  GLOBAL     OBJ __progname
 322 0x001c3350  GLOBAL     OBJ error_print_progname
 374 0x001be860  GLOBAL     OBJ _IO_2_1_stdin_
 416 0x001c2760  GLOBAL     OBJ _res
 473 0x000865f0    WEAK    FUNC memalign
 512 0x001c3378  GLOBAL     OBJ argp_program_version_hook
 517 0x00086180  GLOBAL    FUNC realloc
 542 0x001bf6b0  GLOBAL     OBJ stdin
 590 0x001bf368    WEAK     OBJ program_invocation_name
 717 0x001c35b8  GLOBAL     OBJ __key_encryptsession_pk_LOCAL
 725 0x001be558  GLOBAL     OBJ __ctype_tolower
 771 0x0006e8b0  GLOBAL    FUNC _IO_funlockfile
 805 0x000866b0    WEAK    FUNC calloc
 826 0x001be568  GLOBAL     OBJ __ctype_b
 845 0x001bf5c0  GLOBAL     OBJ _IO_2_1_stdout_
 864 0x001bcf00  GLOBAL     OBJ h_errlist
1097 0x001bf6a8  GLOBAL     OBJ stdout
1103 0x001c0f00  GLOBAL     OBJ __curbrk
1111 0x001be550  GLOBAL     OBJ __ctype_toupper
1143 0x001bea90    WEAK     OBJ __malloc_hook
1177 0x001c3368  GLOBAL     OBJ argp_program_bug_address
1242 0x000858d0  GLOBAL    FUNC malloc
1243 0x001c2c00  GLOBAL     OBJ svcauthdes_stats
1249 0x001be548  GLOBAL     OBJ __ctype32_tolower
1307 0x001c32d0  GLOBAL     OBJ mallwatch
1357 0x001be264  GLOBAL     OBJ argp_err_exit_status
1363 0x001c0ee0  GLOBAL     OBJ __environ
1399 0x001c3348  GLOBAL     OBJ optarg
1404 0x001bf6a0  GLOBAL     OBJ stderr
1414 0x001bf4e0  GLOBAL     OBJ _IO_2_1_stderr_
1448 0x001be004  GLOBAL     OBJ __fpu_control
1454 0x001be19c  GLOBAL     OBJ optopt
1455 0x001c335c  GLOBAL     OBJ error_message_count
1469 0x001c3340  GLOBAL     OBJ re_syntax_options
1558 0x001bea88    WEAK     OBJ __realloc_hook
1580 0x001c3560  GLOBAL     OBJ _res_hconf
1589 0x001be268  GLOBAL     OBJ __check_rhosts_file
1630 0x001be540  GLOBAL     OBJ __ctype32_toupper
1646 0x001bf368  GLOBAL     OBJ __progname_full
1650 0x001c3358  GLOBAL     OBJ error_one_per_line
1827 0x001c0a00  GLOBAL     OBJ __timezone
1835 0x001c31e8  GLOBAL     OBJ _nl_domain_bindings
1875 0x001c0750    WEAK     OBJ __malloc_initialize_hook
1883 0x001bf360    WEAK     OBJ program_invocation_short_name
1914 0x001c0740    WEAK     OBJ __after_morecore_hook
1957 0x001bf340  GLOBAL     OBJ obstack_alloc_failed_handler
2054 0x001be150  GLOBAL     OBJ obstack_exit_failure
2075 0x001be560  GLOBAL     OBJ __ctype32_b
2106 0x001c31f0  GLOBAL     OBJ _nl_msg_cat_cntr
2154 0x001bf338  GLOBAL     OBJ __morecore
2174 0x001c1288  GLOBAL     OBJ loc1
2177 0x001c1280  GLOBAL     OBJ loc2
2184 0x001be1a0  GLOBAL     OBJ opterr
2203 0x001c35c8  GLOBAL     OBJ __key_decryptsession_pk_LOCAL
2332 0x001bea80    WEAK     OBJ __memalign_hook
2342 0x00085f20  GLOBAL    FUNC free
2346 0x001c0a08  GLOBAL     OBJ __daylight
```

The right behaviour was the one we had before. This issue introduced by this PR can be in generally seen in most .so libraries, because symbols inside the library are mistakenly identified as import. Now, before going to add another workaround on top of this workaround, please let's just revert it and work on the proper fix :)

**Comment by blenk92** [comment]
> The right behaviour was the one we had before. This issue introduced by this PR can be in generally seen in most .so libraries, because symbols inside the library are mistakenly identified as import. Now, before going to add another workaround on top of this workaround, please let's just revert it and work on the proper fix :)

Yeah i guess my workaround breaks the import list even more. However, the earlier behaviour is also kinda odd as it contains all the symbols twice. 

I'm not sure how you usually split work, or work on such issues, but i kinda need this working so I may spent some more time on this, although I might need some support at some point

**Comment by ret2libc** [comment]
@blenk92 if you want to work on this, that's great! Feel free to create another PR and add me as reviewer. I think the best thing would be to split symbols_by_ord and "symbols". The former is used to resolve symbols by ordinal, for imports, etc., the latter is used to list all possible symbols and to create flags. symbols_by_ord would contain only the symbols in the DYNSYM table, while "symbols" would contain all of them (with potentially more than one symbol with the same ord number, because coming from DYNSYM and SYMTAB)

**Pull request merged**
