### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Vane11ope**
...and fix a few potential bugs

### CODE REVIEW

**Comment by Vane11ope** [comment]
is Appveyor fucked up?

**Comment by XVilka** [comment]
@Vane11ope no, it seems that it timed out, due to the slow regression tests passing. I wonder what changed recently.

**Comment by Vane11ope** [comment]
i closed it and reopened it just now to try the test one more time

**Comment by Vane11ope** [comment]
it worked :D

**Comment by radare** [comment]
Magic!

**Pull request merged**
