### PR TITLE
arm ESIL improvements:

### PR DESCRIPTION
**Pull request by mrmacete**
+ added UBFX, UXTB, RSB, BIC instructions
+ added generic support for shifted registers ARG function
+ small fixes, taking into account 2 and 3 operators version of instructions
+ handling memory shift in non-pc based LDRs too

### CODE REVIEW

**Comment by mrmacete** [comment]
i think in the next few days i'll add some regression test for arm ESIL

**Comment by radare** [comment]
The memshift thing is a bug from capstone and this is going to change soon. But thats the only way to handle that right now.

**Comment by radare** [comment]
Cool! If u are in the mood for arm-esil, feel free to check other related issues like the cmp one.

Also, we should add more esil commands to handle the unaligned exceptions. Which is working in the disasm but not for esil.

This will be useful to handle the thumb switch thing. And the cpsr should be splitted into individiual Bit sized subregisters in all the arm regprofiles

**Comment by radare** [comment]
I'll review the commit later or tomorrow. Im afk now

**Comment by radare** [comment]
Thanks!

**Pull request closed without merging**
