### PR TITLE
Testing re-enabling debug tests

### PR DESCRIPTION
**Pull request by GustavoLCR**
This is to fire up Travis to see if the tests are passing fine.
For radare/radare2-regressions#1771

### CODE REVIEW

**Comment by ret2libc** [comment]
Cool it seems to work! What did you change?

**Comment by radare** [comment]
the day

**Comment by GustavoLCR** [comment]
> Cool it seems to work! What did you change?

I only disabled the fork tests as those were the only ones hanging. I cannot reproduce it so I can't investigate further.

**Comment by radare** [comment]
Can we merge this?

**Comment by ret2libc** [comment]
I didn't have a chance to carefully look at it, but if tests are green I think it's the perfect moment to merge this. We will have plenty of time to check if all is good.

**Comment by radare** [comment]
Screenshot 2019-04-08 at 16 19 27

**Comment by ret2libc** [comment]
@radare that's done just to trigger a new travis build with the changes in r2r.

**Comment by radare** [comment]
there's no need to do that to trigger r2r, just press the travis button or push -f without any commit

**Comment by ret2libc** [comment]
how do you create a PR without any change? The travis button is available only to "us", I think.

**Comment by radare** [comment]
shouldnt this pr just touch .travis.yml ?

**Comment by GustavoLCR** [comment]
This pr doesnt need to be merged it was just for testing, 
this is the one that matters -> radare/radare2-regressions#1771 
I will close this one if it gets merged

**Comment by radare** [comment]
tired of waiting for this PR. a month hpassed since last test. wat du

**Comment by XVilka** [comment]
@radare it is located here: https://github.com/radare/radare2-regressions/pull/1771

**Comment by GustavoLCR** [comment]
@radare these tests are now failing and it's probably related to #14157 (they were passing before)

**Comment by radare** [comment]
Too bad. This pr should be merged 2 months ago. Can anyone help tracking down that regression?

**Comment by GustavoLCR** [comment]
radare/radare2-regressions#1771 was merged

**Pull request closed without merging**
