### PR TITLE
Tweaking doc for CC

### PR DESCRIPTION
**Pull request by bannsec**
Slight change. I believe i would have found the correct command if that `@addr` was listed for this command. #10380

### CODE REVIEW

**Comment by radare** [comment]
that's obvious. isnt?

**Comment by bannsec** [comment]
I found it confusing. Especially since everywhere else has that "@address" qualifier in the help. My opinion is either add that "@address" everywhere or nowhere. As it stands, i found it misleading.

**Comment by XVilka** [comment]
`@` is a separate command, no need to duplicate it everywhere.

**Comment by radare** [comment]
@ is a modifier that affects all commands. If the command uses the current offset or not, thats specified in the help msg.. so i dont see the missleading part here

**Pull request closed without merging**
