### PR TITLE
Organize string macros

### PR DESCRIPTION
**Pull request by SchumBlubBlub**
Merge after #6700, needs

https://github.com/radare/radare2/pull/6700/commits/12758e2ed42e6c450ae6972f120b83f4eaea3ec8 "Rename IS_NUMBER to IS_DIGIT" 

- Move lowercase macros from r_str.h to `r_str_util.h` and uppercase them
- Move related macros like IS_DIGIT, IS_WHITESPACE from r_types.h to `r_str_util.h`
- Fixup all the use locations
- Convert all cases of `( c>= '0' && c <= '9')` to use IS_DIGIT, but left "external code" unchanged.

### CODE REVIEW

**Comment by Maijin** [comment]
image
How is that a thing ? XD

**Comment by SchumBlubBlub** [comment]
\o/

**Comment by Maijin** [comment]
What about using a different author name/email ? 🐃

**Comment by radare** [comment]
are you my future self?

**Comment by SchumBlubBlub** [comment]
Yes, I've come from the future to tell you trump is going to devastate earth. Get your terminator underpants ready.

**Comment by SchumBlubBlub** [comment]
actually, I hate big code style fixes/whitespaces commits. so i always put them under the owner name. Inflated contributions LOC annoy me.

**Comment by radare** [comment]
Merged in 6c00c9e2d5b2f0ff759b259796622b6ea3b12023

**Pull request closed without merging**
