### PR TITLE
Fix ET_REL: load sections if there is no PHDR & fix a few x86_64 relocation types for non-PIC .o files

### PR DESCRIPTION
**Pull request by MaskRay**
Only ehdr is mapped without the change.

### CODE REVIEW

**Comment by MaskRay** [comment]
`__patch_reloc` has been incorrect for a long time:

```
% /usr/bin/r2 -v
radare2 1.6.0 0 @ linux-x86-64 git.1.6.0
commit: HEAD build: 2017-07-12__22:52:36

% /usr/bin/r2 -e io.cache=1 /tmp/c/a.o -c 'aa;s sym.main;pdf'                               
r_config_set: variable 'cfg.newtab' not found 
Warning: Cannot initialize program headers    
Warning: Cannot initialize dynamic strings    
Warning: Cannot initialize dynamic section    
[x] Analyze all flags starting with sym. and entry0 (aa)                                    
┌ (fcn) sym.main 40    
│   sym.main ();       
│           0x08000076      55             push rbp                                         
│           0x08000077      4889e5         mov rbp, rsp                                     
│           0x0800007a      53             push rbx                                         
│           0x0800007b      4883ec08       sub rsp, 8                                       
│           0x0800007f      bf05000000     mov edi, 5                                       
│           0x08000084      e8ffffc3ff     call 0x7c40088                                   
│           0x08000089      89c3           mov ebx, eax                                     
│           0x0800008b      b800000000     mov eax, 0                                       
│           0x08000090      e8ffffabff     call 0x7ac0094                                   
│           0x08000095      01d8           add eax, ebx                                     
│           0x08000097      4883c408       add rsp, 8                                       
│           0x0800009b      5b             pop rbx                                          
│           0x0800009c      5d             pop rbp                                          
└           0x0800009d      c3             ret
 -- Enable ascii-art jump lines in disassembly by setting 'e asm.lines=true'. asm.linesout and asm.linestyle may interest you as well
[.text:0x08000076]>    
```

The two `call` were incorrect. With the PR:

```
% r2 -e io.cache=1 /tmp/c/a.o -c 'aa;s sym.main;pdf'                                 
Warning: Cannot initialize program headers                                           
Warning: Cannot initialize dynamic strings                                           
Warning: Cannot initialize dynamic section                                           

[x] Analyze all flags starting with sym. and entry0 (aa)                             
┌ (fcn) sym.main 40  
│   sym.main ();     
│           0x08000076      55             push rbp                                  
│           0x08000077      4889e5         mov rbp, rsp                              
│           0x0800007a      53             push rbx                                  
│           0x0800007b      4883ec08       sub rsp, 8                                
│           0x0800007f      bf05000000     mov edi, 5                                
│           0x08000084      e8c3ffffff     call reloc.foo_76                         
│           0x08000089      89c3           mov ebx, eax                              
│           0x0800008b      b800000000     mov eax, 0                                
│           0x08000090      e8abffffff     call entry0                               
│           0x08000095      01d8           add eax, ebx                              
│           0x08000097      4883c408       add rsp, 8                                
│           0x0800009b      5b             pop rbx                                   
│           0x0800009c      5d             pop rbp                                   
└           0x0800009d      c3             ret                                       
 -- In soviet russia, radare2 debugs you! 
[.text:0x08000076]>  
```

**Comment by MaskRay** [comment]
Added a few R_PPC64 relocation types.

**Comment by alvarofe** [comment]
good catch about PHDR since .o wouldn't be loaded

**Comment by alvarofe** [comment]
Do you have test for those relocs? the PR lgtm

**Comment by alvarofe** [comment]
Please create some test for the reloc

**Comment by MaskRay** [comment]
There are a few other issues.

**Comment by MaskRay** [comment]
Some relocated addresses in ET_REL (object files) point to .plt .got .got.plt (x86_64, other arch may have different names). `bin/p/bin_elf.c` currently creates a fake `.got.r2` section to handle some GOT related relocation types.

**Comment by alvarofe** [comment]
Yep, i am aware. I should delve into ELF again to see if this can be handled without depending on the name but in a type or something

**Pull request merged**
