### PR TITLE
Add: dbf - put a breakpoint into every no-return func

### PR DESCRIPTION
**Pull request by leberus**
"dbf" puts a breakpoint into all no-return functions. I'm not sure if "dbf" is a good name at all.

Right now puts the breakpoint within the no-return function, not before the call. That's right, isn't it? Or the bp should be put before the call to the no-return function?

```
l:~> r2 -d test
[0x7f905deec150]> dbf
[0x7f905deec150]> db
0x00400420 - 0x00400421 1 --x sw break enabled cmd="" cond="" name="sym.imp.__libc_start_main" module="/home/leberus/lab/r2/test"
0x00400430 - 0x00400431 1 --x sw break enabled cmd="" cond="" name="sym.imp.exit" module="/home/leberus/lab/r2/test"
[0x7f905deec150]> db sym.main
[0x7f905deec150]> dc
Selecting and continuing: 8027
hit breakpoint at: 400420
[0x00400420]> pd 1
            ;-- imp.__libc_start_main:
            ;-- rip:
            0x00400420 b    ff25f20b2000   jmp qword [reloc.__libc_start_main_24] ; [0x601018:8]=0x400426 ; LEA reloc.__libc_start_main_24 ; "&.@" @ 0x601018
[0x00400420]> dc
Selecting and continuing: 8027
hit breakpoint at: 40053d
[0x0040053d]> pd 1
            ;-- main:
            ;-- main:
            ;-- rax:
            ;-- rip:
            0x0040053d b    55             push rbp
[0x0040053d]> dc
Selecting and continuing: 8027
hit breakpoint at: 400430
[0x00400430]> pd 1
            ;-- imp.exit:
            ;-- rip:
            0x00400430 b    ff25ea0b2000   jmp qword [reloc.exit_32]   ; [0x601020:8]=0x400436 ; LEA reloc.exit_32 ; "6.@" @ 0x601020
[0x00400430]>
```

### CODE REVIEW

**Comment by radare** [comment]
not sure if dbf is the better command for this… im open to suggestions here .. because dbn is already taken… and dbtn is not consistent with dbt… i think that db* subcommands are a bit confusing right now too much commands that do similar things in here, i thikn we can rethink them all a bit

**Comment by leberus** [comment]
What about `dbfnr?` (dbfunctionnoreturn) maybe it's too long. Or `dbrn` (dbreturnno). Actually, I suck at naming :S

**Comment by Maijin** [comment]
What about `db @@@ noreturn` or db @@ `tn*` or something instead ?

**Comment by radare** [comment]
thats not how @@ works.. but you can do something with backticks and maybe it will be good to have @@@= and update @@@ because there are a bunch of unimplemented things there: 

[0x100001174]> ?e $$ @@@ imports
TODO @@@ imports ^^


my idea would be to have @@@= to do something like this:

?e @@@= hello world

This will do the following:

?e hello
?e world

**Comment by Maijin** [comment]
Yes I know, just giving ideas.

**Pull request merged**
