### PR TITLE
Don't unset keys with expire==0 in sdb_sync.

### PR DESCRIPTION
**Pull request by sapir**
After adding xrefs with 'axd' and then saving my project with 'Ps', the xrefs disappear. This patch seems to fix it. I'm not sure I understand how sdb works, so apologies if this is off track.

### CODE REVIEW

**Comment by radare** [comment]
The patch looks good (from my phone) i should add more tests because the expire+sync is not tested yet so i guess its passing the testsuite fine.

I think that the loop can be optimized by putting the expire conditional on top and in case of being 0 save the key to disk if it's not empty. This will drop one conditional. About the now() call maybe it will be better to put before the ls_foreach. Because i think the penalty is lower than checking the contents of a variable (now) every time inside the loop. In 99% of cases, the expire time is not used, as well as the CAS parameter.

I added those options mainly to support memcache protocol, and i think both features are also useful for in-process databases, mainly for setting keys you dont want to sync and cas for multithreaded applications. But the sdb api is not thread safe, so this will require some work.

Also, you should redo the pullrequest and make it in the sdb repository. The sdb code under the r2 tree is just a copy of a stable git version that is known to work. I'll sync after merging that patch.

Thanks!

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
https://github.com/radare/sdb/pulls

**Comment by radare** [comment]
Ok, got some time to review this issue.. The logic behind this code is the following:

* if the key expires is never sync to disk
* syncing to disk doesnt cares about expire times at all, because this is checked when getting the value of an expirable key. no need to check the timeout for every key
* when the key is inserted in disk, it can be removed from memory


I have changed the code in sdb for testing, can you provide the steps to reproduce the bug? maybe a testcase. Please pull and let me know if the issue is still happening.

**Comment by sapir** [comment]
sorry, I did intend to do a pull request for sdb but didn't get around to
it yet.
I'll try to find something simple to reproduce it.

**Comment by radare** [comment]
its already commited in sdb, and merged into r2 again, so you can can
pull r2 and try if the issue was fixed for you or not.

**Comment by sapir** [comment]
Still happening:
```
$ r2 --
 -- What has been executed cannot be unexecuted
[0x00000000]> ax 1
[0x00000000]> e file.project=test
[0x00000000]> ax
types=code.jmp,code.call,data.mem,data.string
ref.unk.0x0=0x1
xref.unk.0x1=0
[0x00000000]> Ps
test
[0x00000000]> ax
[0x00000000]>
```

**Comment by sapir** [comment]
Why is that loop using `sdb_unset` and the top loop using `ls_delete` and `ht_delete_entry`?

**Comment by radare** [comment]
will try to find some time for this tonight.

**Pull request closed without merging**
