### PR TITLE
More anal fixes

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by radare** [comment]
Thanks!

**Comment by Maijin** [comment]
https://travis-ci.org/radare/radare2/jobs/96161801#L4085 o/ Can you check if this test is ok and fix it accordingly ?

**Comment by radare** [comment]
I think the test was wrong, but please confirm. I have merged the commits

**Comment by dmtch** [comment]
It was my mistake "bbs_alignment" commit, I sent new PR.
Why I can't see failed tests here:
```
run_tests.sh
***
=== Report ===

[499] SUCCESS
[0]   FIXED
[20]  BROKEN
[0]   FATAL
[0]   FAILED
[3%]        BROKENNESS
```
```
./fcnbbs 
[XX]  1  fcnbbs: ./fcnbbs 
***
```

**Pull request closed without merging**
