### PR TITLE
R2CON2019 Support for amd29k

### LINKED ISSUE #13011: AMD Am29000 architecture support
The AMD Am29000 (commonly shortened to 29k) is a family of 32-bit RISC microprocessors and microcontrollers developed and fabricated by Advanced Micro Devices (AMD). They were, for a time, the most popular RISC chips on the market, widely used in laser printers from a variety of manufacturers.

[29kprog.pdf](https://github.com/radare/radare2/files/2839293/29kprog.pdf)
image

### PR DESCRIPTION
**Pull request by wargio**
Fixes #13011

### CODE REVIEW

**Comment by XVilka** [comment]
Good one!

**Comment by XVilka** [comment]
Please add some tests too.

**Comment by radare** [comment]
What about having it in extras?

**Comment by radare** [comment]
move this to extras and make the r2pm pkg pls

**Comment by radare** [comment]
its a  nice  arch, but sadly  dead and i dont  think its used anywhere nowadays, @XVilka ?

**Comment by radare** [comment]
uhm well 
Screenshot 2019-08-18 at 12 57 35

**Comment by radare** [comment]
can you make this green?

**Comment by XVilka** [comment]
Dead architectures precisely the best target for reverse engineering. So many sources, so many old high tech was implemented for those.

**Comment by radare** [comment]
Ok then make it green and merge

**Comment by wargio** [comment]
i'm writing the tests. please wait before merging.

**Comment by officialcjunior** [comment]
Shouldn't this be under the Supported Architectures on the README, too?

**Comment by XVilka** [comment]
Yes, it should be.

**Pull request merged**
