### PR TITLE
Fix ESIL for x86 INC and DEC

### PR DESCRIPTION
**Pull request by Darredevil**
While working on #4362 I noticed a bug in ESIL. Fixed it :P

### CODE REVIEW

**Comment by radare** [comment]
Thanks! Do we have some tests for this?

**Comment by Maijin** [comment]
@Darredevil see https://ci.appveyor.com/project/radare/radare2-shvdd/build/0.10.0.3895#L2838

**Comment by Darredevil** [comment]
@Maijin Fixed

**Comment by radare** [comment]
Thanks!

**Pull request closed without merging**
