### PR TITLE
remove %hh usage

### PR DESCRIPTION
**Pull request by P4N74**

### CODE REVIEW

**Comment by radare** [comment]
Are u sure this patch is ok? The %hh works on wine so not sure if theres a reaskn to kill it, also. The cast is maybe only 50% of whats needsd because we probably need to & with a mask. I wanted to do some tests before merging and see when %hh was introducdd

**Comment by P4N74** [comment]
regarding `%hh`, I checked it on windows system. It failed to give expected output. Regarding testing, I agree with you, so that r2 does not break due to this.

**Comment by radare** [comment]
We have nontests on this and i m not 100% sure that a single cast is enough

**Comment by P4N74** [comment]
Then can we revert this for now?

**Comment by radare** [comment]
Ok did some tests:
```
%hhd -> (char)x
%hhu -> (ut8)x
```

The &0xFF is not necessary, a cast seems to be enough

**Comment by radare** [comment]
@P4N74 please send another PR using (char) where hhd was and ut8 cast when hhu was used

**Comment by P4N74** [comment]
@radare this pr already does that.

**Comment by XVilka** [comment]
@radare here is the starts the question - what about uniform sprintf function for all platforms?
So it will be able to have formats we want/need only, in one way everywhere, as long as a possible extensions of it.

**Pull request merged**
