### PR TITLE
Temp fix for .idp*

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by xarkes** [comment]
Because some c++ files output symbols containing <> which should not be present while calling rabin2 with -r

**Comment by radare** [comment]
Theres a function in rflag that filters the names to avoid those chars while keeping realname for display. Dont replace chars by hand pls

**Comment by xarkes** [comment]
done, mb

**Comment by radare** [comment]
It's r_name_filter

**Comment by xarkes** [comment]
sry

**Comment by xarkes** [comment]
As the tests show r_name_filter remove the '=' character, I don't know if that's what we want

**Comment by radare** [comment]
If you dont remove the = then f foo=bar=0x73847 may happen which is bad. This char is not valid for flags

**Comment by xarkes** [comment]
kk then I'll fix the tests

**Comment by radare** [comment]
The output can be quotes to avoid those issues and the f commane will do the filtering for u iirc

**Pull request merged**
