### PR TITLE
Revert "Misc fixes to siol (#8262)"

### PR DESCRIPTION
**Pull request by condret**
This reverts commit a9bf4aae2bdca2c139f482c3f0e098fe6ece1ee0.

It's not that I think, there is no justification for good error-handling in general, But i think here it is done completly wrong. vread != pread, and cannot be handled like pread. int as a return value provides the same amount of information as bool for vread. It either worked or didn't work, does not tel you where it failed. pls accept this patch, and give @alvarofe and me a few days to come up with something more accurate. If our solution does not satisfy the majority of collaborators, we can roll back. I promise to do the work in that case, even if I don't like it

### CODE REVIEW

**Comment by alvarofe** [comment]
I am with condret on this. The places where the return value is used, should be equal to the argument passed, otherwise there was an error and a bool is enough to express it. This was already discussed long time ago and it seems a waste of time and energy trying to change this back and forth

**Comment by alvarofe** [comment]
I would focus first make all green with boolean and better performance and then design discussions can be opened, we are running out of time for r2con, r2wars, etc

**Comment by alvarofe** [comment]
The code in master handles very bad the binary 65535.exe, creating for each section two maps: fmap (size = 0) and mmap. Which is wrong. The revert fixes it

**Comment by MaskRay** [comment]
I feel disappointed that the misconception is deeply ingrained in your mind.

It is possible for `r_io_pread_at` to return partial result, that is `0 <= ret && ret < len`. This indicates 

Now you are happy, the number of `FAILED` targets largely increased.

```
[679]UCCESS                       
[0] FIXED                         
[42]BROKEN                        
[0] FATAL                         
[318]AILED                        
[34%]      BROKENNESS   
```

```
[959]UCCESS                       
[0] FIXED                         
[42]BROKEN                        
[0] FATAL                         
[38]FAILED                        
[1039]  TOTAL 
```

**Pull request closed without merging**
