### PR TITLE
Lua 5.3 Assembler/Disassembler, Analyzer and Binary Plugin (#3836)

### PR DESCRIPTION
**Pull request by Cararasu**
Implementation of an assembler and disassembler of the Lua 5.3 VM bytecode
Implementation of a binary plugin, that can analyze the binary format of a Lua 5.3 compiler
Implementation of an analyzer plugin for Lua 5.3 VM bytecode

### CODE REVIEW

**Comment by radare** [comment]
Please, use r2-indent or follow the indentation rules.

Not sure if we should have this in r2 core or extras, seems like an interesting addition to me and pretty well implemented. We shoul add some tests and fuzz it a bit beforee the release

**Comment by Maijin** [comment]
@radare 

`+	.license = "MIT",` ->another reason for r2extras

**Comment by radare** [comment]
No problem with the license. Mit is comptible with lgpl. But im trying not to make core bigger and slowly move things to extras, to reduce codebase, compilation times and tests for core. But anyway i guess that we should do some kind of poll to see how many prople want things in core or not.

But adding lua dis/asm/anal have been in my list for long time so its ok to go into core for me.

**Comment by radare** [comment]
meh, tired of waiting

**Comment by radare** [comment]
thanks for the contrib! very nice addition, i'll try to find some time to fix the indentation hints and prepare a good path to move things into extras in future releases after some polls :)

**Comment by Cararasu** [comment]
Great!
Btw. is there a way to set the address of a function to a non executable section or have the base address of a function be a different one than the actual address of the code, because in lua there is much function-related data before the actual code-section of each function?

**Comment by radare** [comment]
e anal.noncode

**Pull request merged**
