### PR TITLE
msvc compile with /MT to include redistributables into binaries

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by xarkes** [comment]
Ah yes I did not read the warnings, /MT is incompatible with /MDd (Debug mode).
So either we can let this like this, so people can download the release on appveyor without having to download and install the required runtimes, or we can set the meson buildtype to release which I think will remove the warnings.

**Comment by radare** [comment]
so? wat du

**Comment by xarkes** [comment]
To me it's okay not to have debugging symbols on the appveyor build. If people want them they just have to compile theirselves no ?

**Comment by xarkes** [comment]
Anyway it's more important to have portable binaries than debugging symbols imho.

**Comment by XVilka** [comment]
@radare so, what's your decision? I think having working binaries is more important than debuginfo, at least for now.

**Comment by radare** [comment]
Its ok for me. Feel free to merge

**Pull request merged**
