### PR TITLE
Reverts fix for bug #3788

### PR DESCRIPTION
**Pull request by ricardoquesada**
please, reopen bug #3788

### CODE REVIEW

**Comment by radare** [comment]
why?

**Comment by ricardoquesada** [comment]
I added more info in this comment: https://github.com/radare/radare2/issues/3788#issuecomment-163042481

**Comment by radare** [comment]
can you cherry-pick, squash and rebase the correct patch on top of master?

thanks!

**Comment by ricardoquesada** [comment]
yes... I'll do that.

**Comment by ricardoquesada** [comment]
this PR supersedes this one:
https://github.com/radare/radare2/pull/3820

**Pull request closed without merging**
