### PR TITLE
Added display of strings in disassembly for PIC binaries

### PR DESCRIPTION
**Pull request by SrimantaBarua**
```
[0x08048320]> e anal.strings = true
[0x08048320]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x08048320]> aae
[0x08048320]> pdf @ main
...
│           0x08048427      e824ffffff     call fcn.08048350
│           0x0804842c      81c3d41b0000   add ebx, 0x1bd4
│           0x08048432      8d83e0e4ffff   lea eax, str.Hello_PIC_     ; "Hello PIC!" @ 0x80484e0
...
```

### CODE REVIEW

**Comment by Maijin** [comment]
Niiice 👍

**Comment by radare** [comment]
so many regressions, please rebase, there are some things in master that have new tests in r2r, so pls update

**Comment by SrimantaBarua** [comment]
The updated tests for this in r2r should fix all problems in Travis.

**Comment by radare** [comment]
cornflakes with disasm.c cant merge

**Comment by SrimantaBarua** [comment]
Fixed merge conflicts

**Comment by radare** [comment]
Still red

**Comment by SrimantaBarua** [comment]
Yeah, I made a few changes to tests [here](https://github.com/radare/radare2-regressions/pull/770).

**Pull request merged**
