### PR TITLE
r_vector.h -> r_vec.h and s/(RP?Vec)tor/\1/g; s/(r_p?vec)tor/\1/g

### PR DESCRIPTION
**Pull request by MaskRay**
RVector* -> RVec*
RPVector* -> RPVec*
r_pvector_* -> r_pvec_*
r_vector_* -> r_vec_*

https://github.com/radare/radare2-regressions/pull/1455

The commit is generated by:

`sed -ri 's/(RPVec)tor/\1/g; s/(r_p?vec)tor/\1/g' libr/**/*.[ch]`, renaming in meson.build and `git mv`

### CODE REVIEW

**Comment by radare** [comment]
why

**Comment by MaskRay** [comment]
Now that `r_pvector_[gs]et` seems more preferable than raw `.a[i]` access, this makes functions easier to use as what Rust does.

**Comment by MaskRay** [comment]
Rebased

**Comment by ret2libc** [comment]
Are you sure you have correctly rebased? I still see some old broken tests

**Comment by XVilka** [comment]
Still broken

**Comment by radare** [comment]
I like short names for variables, but not for functions or types. Even if Rust goes for `vec`, i think that the current naming is good and is not really that long. In fact i was checking Sdb, and the hashtable is named SdbHash, which is a pretty bad name, should be SdbHashTable, but the method apis are sdb_ht_* which lgtm even if it breaks the naming of sdb_hash_table_*, so maybe we can go for a mixed approach or extend the discussion to other data structures

**Comment by MaskRay** [comment]
@XVilka Rebase does not make sense (though I did it) if it would be rejected.

**Comment by XVilka** [comment]
So?

**Comment by radare** [comment]
RVector is not that long and descriptive enough.

**Pull request closed without merging**
