### PR TITLE
Address comments in #13094 related to maxbbsize and maxfcnsize ##anal

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
the a-b thing was wrong because you cant get a signed value out of unsigned values. also, comparing and resulting in -1,0,1 makes the code easier to maintain, i can make a ternary conditional if you want, but the a-b is wrong

**Comment by ret2libc** [comment]
Ok, fine as it is then.

**Comment by radare** [comment]
this "fix" introduces 3 regressions

```
[35m-/ (fcn) fcn.00560e67 6412[39m
[35m[39m[32m+/ (fcn) fcn.00560e67 1366[39m
[32m[39m |           0x00560e67      push esi
 |       ,=< 0x00560e68      jmp 0x560e7d
```

**Comment by radare** [comment]
Still red

**Comment by ret2libc** [comment]
It is red because the technique of using random limits is too fragile.
But btw I'm not even sure the current test is right. It says the function size is 1025, while the malloc is of 1024 bytes, so I'm not sure how the function can be 1025 bytes... At least after this patch the function is of size 1023, which makes more sense IMO.

**Comment by radare** [comment]
the test fails because of the function boundary changed. but i dont think it was even correct before either. because it was 1018 and now its 1020 (dont know where u get the 1024, 1023, 1025 values)

im tempted to merge and update the test and forget about this until the rerlease

**Comment by ret2libc** [comment]
yes please just update that test.

(1024 and 1024 comes from `afi` command. `fcn_last` is not exacty the size of the function... you can check the code)

**Pull request merged**
