### PR TITLE
Honor cpu on anal_mips_cs and add/fix some mips64 instruction

### PR DESCRIPTION
**Pull request by mrmacete**
Partly related to https://github.com/radare/radare2/issues/7636

### CODE REVIEW

**Comment by radare** [comment]
we can ship your capstone-mips64 patch until gets merged

**Comment by mrmacete** [comment]
yeah that's a good idea, would avoid to use `64v2` at all, and add a `mips2` or `v2` cpu for opt-in the COP3 stuff

**Comment by radare** [comment]
Please add this patch https://github.com/aquynh/capstone/pull/939 inside shlr/capstone-patches so i can merge this

thanks!

**Comment by mrmacete** [comment]
ok so my plan is:
- add that patch in shlr/capstone-patches
- remove the "64v2" mode everywhere, add the "v2" mode (needed only in the unlikely case coprocessor 3 instructions are needed)
- since this will change the default mips64 behaviour, i'll check also r2regressions

**Comment by radare** [comment]
sounds good

**Pull request merged**
