### PR TITLE
Fix ragg2 `-s` flag

### PR DESCRIPTION
**Pull request by qsantos**

### CODE REVIEW

**Comment by radare** [comment]
if that 928-936 case misses a newline this patch will break the thing. so this case must be taken in care too. i just appended \n always just to avoid being so picky on catching those errors

**Comment by qsantos** [comment]
You are right, an additional blank line is not much of a deal. You can just skip the last commit when merging.

**Comment by radare** [comment]
Can you cleanup the pullreq acording to the comments we have discussed? thanks!

**Comment by qsantos** [comment]
Just done it. Previous discussions for future reference:
* https://github.com/qsantos/radare2/commit/552445fe867ba8e692c4a36530261f3b01779a40
* https://github.com/qsantos/radare2/commit/439c30f003b4307ca0bf95acc37bbf3771691a28
* https://github.com/qsantos/radare2/commit/e865f3e066b83e68e611af0a0fff89c6ca0cbcb9
* https://github.com/qsantos/radare2/commit/7e7c6d20415fb853d56ec218c8d17b01848787c9

**Comment by radare** [comment]
it's not passing the testsuite

**Comment by radare** [comment]
The commit with comments is still there. I'm sure changing where buf is initialized can cause problems in some cases, and I would like to have more tests with ragg2 before merging this. Also, can you rebase again? otherwise it will not pass the latest testsuite. Thanks

**Comment by qsantos** [comment]
I was not able to access Travis yesterday to check the logs. The two failing cases seems to indeed have come to the additional initialization I removed.

**Comment by radare** [comment]
yep. rebase it to master r2 and put only the good commits. then just wait for travis again.

yeah, travis was down yesterday :(

**Comment by qsantos** [comment]
Oh, that explains it. I had forgotten to pull master, here it is.

**Comment by radare** [comment]
@Maijin can you do some tests with ragg2 to verify different constructions of buffers with prefixes, sufixes, nopsleds, etc... to confirm that those patches are not breaking anything? I'll try to do some tests later at night. thanks!

**Comment by radare** [comment]
Merged them all, the tests are almost broken actually, so it's better to start after this. I'm fixing some ragg2 tests and will write more tests, feel free to join the party

**Pull request closed without merging**
