### PR TITLE
Fix iM paddr when it's from the main symbol

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
Uhm isnt main suposed to return vaddr?

**Comment by MaskRay** [comment]
I don't know why `main` is given priority to have the extra command `iM`.

**Comment by kazarmy** [comment]
No,  `getmainsymbol` is used by `Elf_(r_bin_elf_get_main_offset)` which should always return a paddr, since that's what `binsym` expects: https://github.com/radare/radare2/blob/e2df259a8ecd6570cb72b7ddf47df36f0a5f715c/libr/bin/p/bin_elf.inc#L148-L149 https://github.com/radare/radare2/blob/e2df259a8ecd6570cb72b7ddf47df36f0a5f715c/libr/bin/p/bin_elf.inc#L161-L162

**Comment by kazarmy** [comment]
> I don't know why main is given priority to have the extra command iM.

Someone might be mass-processing binaries using `iMj` and checking whether `main` exists (not me though).

**Pull request merged**
