### PR TITLE
Added no of call reference in afl with column headings

### PR DESCRIPTION
**Pull request by PankajKataria**
Fixed  [#4598](https://github.com/radare/radare2/issues/4598)

### CODE REVIEW

**Comment by PankajKataria** [comment]
Current Output
```
r2 radare2-regressions/bins/elf/a.out.partialrel
aaa
afl
```
```
Offset	    Size  nbbs  Function Name                  Call Refs
======	    ====  ====  =============                  =========
0x080482b8  38    3     sym._init                      2   
0x080482f0  16    2     loc.imp.__gmon_start__         2   
0x08048300  16    2     sym.imp.__libc_start_main      2   
0x08048310  34    1     entry0                         1   
0x08048340  43    4     sym.deregister_tm_clones       0   
0x08048370  56    4     sym.register_tm_clones         0   
0x080483b0  30    3     sym.__do_global_dtors_aux      1   
0x080483d0  44    4     sym.frame_dummy                2   
0x080483fc  10    1     sym.main                       0   
0x08048410  5     1     sym.__libc_csu_fini            0   
0x08048420  90    4     sym.__libc_csu_init            2   
0x0804847a  4     1     sym.__i686.get_pc_thunk.bx     0   
0x08048480  23    1     sym._fini                      1   

```

**Comment by radare** [comment]
This will break many tests and it is better to wait for 0.10.3. Also i think that those headers must be hidden or many scripts will fail (counting number of functions with afl~?). So we need some discussion on this decision.

Maybe add aflq for quiet output?

**Comment by PankajKataria** [comment]
oh! ok so i should add aflq for this kinda output ?

**Comment by radare** [comment]
Any other column of info that can be interesting to add?

**Comment by Maijin** [comment]
Show counter of xrefs in afl #4606

**Comment by Maijin** [comment]
This is what idapro gives as information (/bin/ls mach0)

```
start         __text 0000000100001174 00000924 00000668 00000000 R . . . B T .
sub_100001B58 __text 0000000100001B58 000002AF 00000048 00000000 R . . . B . .
sub_100001E24 __text 0000000100001E24 00000068 00000008 00000000 R . . . B . .
sub_100001E8C __text 0000000100001E8C 00000A6C 000005A8 00000000 R . . . B . .
```

**Comment by radare** [comment]
Can you describe each column? Those random numbers make no sense to me

**Comment by radare** [comment]
@Maijin ping

**Comment by P4N74** [comment]
IDA pro's information goes something like:

name_of_function   segment    start_address    length   locals    arguments     R  F  L  S  B  T  =

Flags:
R -> returns to caller
F -> far function
L -> library function
s -> static function
B -> BP based frame
T ->                  (no idea for this)
= -> BP equals SP

**Comment by radare** [comment]
Ok, so i think we can do something like this:

```
offset min_bound max_bound size stack bbs xrefs calls vars args type name
```
which is:

offset: offset where the function starts
min_bound: min(bb.addr)
max_bound: max(bb.addr)
size: sum(bb.size)
stack: stackframe size
bbs: count(bb)
xrefs: count(xrefs)
calls: count(refs.type == CALL)
vars: number of local variables
args: number of function arguments
type: ***
name: function name

*** The type field is up for discussion. we can add a custom string to represent some attributes of the function, like the type of calling convention, if its a terminator function (calls exit, abort, ..), etc

we can probably implement this without the `type` and add that `type` column after merging this.

@PankajKataria do you mind updating the PR adding those fields? try to make it fit in 80 columns, im thinking that maybe we should have `aflq` and `aflqq` or just make the current `aflq` be named `afl=` and use a simpler function listing that fits in 60 columns or so like we do now

**Comment by PankajKataria** [comment]
@radare sure, i will try to submit a pull request as soon as possible

**Comment by radare** [comment]
cool. looking forward the updated pr!

**Comment by PankajKataria** [comment]
@radare Updated and finally which out of aflq , aflqq, afl= should we put for this kinda output.

**Comment by radare** [comment]
cant merge on top of master. there are conflicts in core/anal.c. , can you squash the commits and rebase?

**Comment by PankajKataria** [comment]
sorry for all these I will create a new one

**Comment by radare** [comment]
please @maijin check this and add your comments, we should update all tests on every change we do here. so i want some 3rd party feedback

thx

**Comment by Maijin** [comment]
waiting for @PankajKataria to do the PR

**Comment by radare** [comment]
ping @PankajKataria

**Pull request closed without merging**
