### PR TITLE
8051 doc

### PR DESCRIPTION
**Pull request by astuder**
Documenting how to use r2 with 8051.

### CODE REVIEW

**Comment by Maijin** [comment]
We are trying to get rid of the documentation here can you please the radare2book instead ? https://github.com/radare/radare2book

**Comment by astuder** [comment]
Ah, that's where the up-to-date esil documentation is :-)
Should I create a new subfolder /arch? Or do you have a better idea where to add information specific to an architecture?

**Comment by Maijin** [comment]
You sure can make a folder arch

**Comment by radare** [comment]
closing?

**Comment by astuder** [comment]
https://github.com/radare/radare2book/pull/80

**Pull request closed without merging**
