### PR TITLE
Fix #7193 : R2PM_ETCD has an extra "radare2" path

### LINKED ISSUE #7193: R2PM_ETCD in r2pm has an extra "radare2" path
When using R2PM_ETCD var in r2pm, the output has an extra "radare2" path, e.g.:
/<user's_home_path>/.config/radare2/radare2/radare2rc

That happens because "radare2" is already in RHOMEDIR, so it should not be included in R2PM_ETCD again:

$ r2 -H RHOMEDIR -> /<user's_home_path>/.config/radare2
./binr/r2pm/r2pm:27:export R2HOMEDIR="`r2 -H RHOMEDIR`"
./binr/r2pm/r2pm:61:R2PM_ETCD="${R2HOMEDIR}/radare2/radare2rc.d"

This issue is affecting r2pm packages like [esilburner](https://github.com/radare/radare2-pm/blob/master/db/esilburner).

I am creating the fix right now, it will be pull-requested soon.

### PR DESCRIPTION
**Pull request by giomismo**
Fixes alias in radare2rc at r2pm packages like esilburner

### CODE REVIEW

**Comment by radare** [comment]
Thanks

**Comment by radare** [comment]
Maybe worth to have a test for r2 -H

**Comment by giomismo** [comment]
You're welcome, thanks to you and to the collaborators for this amazing project. I am glad to contribute even it is such a very minor fix, hope to contribute better in the future.
I will take a look at the tests, but change is at r2pm so maybe the test should be in the r2pm right?

**Comment by radare** [comment]
r2pm just runs r2 -H to grab those paths. I fixed one of those paths last week and forgot to check the implications in r2pm. So thx for catching this :)

**Pull request merged**
