### PR TITLE
Initial RISC-V support (32,64bit disasm)

### PR DESCRIPTION
**Pull request by q6r**
This is the initial risc-v support 32 and 64 bit disassembler, code taken from binutils see headers. I tested it only with 64bit elf binaries, when this is improved. I'll work on anal_riscv.

- Code level : spaghetti

### CODE REVIEW

**Comment by radare** [comment]
The license of the plugin must be gpl instead of lgpl because that code comes from gnu.

**Comment by radare** [comment]
Name the plugin "riscv" instead of "riscv.gnu" because there's no other riscv disassembler right now

**Comment by radare** [comment]
The same applies to microblaze

**Comment by radare** [comment]
also, asm.riscv is not included in plugins.def.cfg

(im doing all those changes, and will merge in few mins)

**Comment by radare** [comment]
Drop ALL THE TABS from the instructions otherwise the visual looks like crap

**Comment by radare** [comment]
%lx is non-portable, use the correct macros. modern compilers warn about this

**Comment by radare** [comment]
always put a space after every comma (all disassemblers are tuned a bit to get a common syntax for readability

**Comment by radare** [comment]
An anal plugin is needed to get proper disassembly colors and jump lines. if you feel brave, you can implement esil for this platform too

**Comment by radare** [comment]
Merged! See f88b35afbab60bc23ace102034b55483c17c23fd

**Comment by q6r** [comment]
Sorry was not around to fix those. Thank you for doing it :).

**Comment by radare** [comment]
Are you up for doing the anal plugin? I can write a quick implementation if you want, so you can test and enhace it.

Can you submit some test cases?

**Comment by q6r** [comment]
Yes I'm working on it

**Comment by Maijin** [comment]
@q6r You can also enrich the https://github.com/radare/radare2/blob/master/README.md

**Comment by radare** [comment]
😄

**Pull request closed without merging**
