### PR TITLE
Silent warning for exceeding max block size

### PR DESCRIPTION
**Pull request by giuscri**
Show it only when VERBOSE_ANAL

### CODE REVIEW

**Comment by radare** [comment]
Uhm, why hide it? it is too noisy?

**Comment by giuscri** [comment]
actually, yes it's scary. Anyway you can't hide that as opposed to other messages

**Comment by giuscri** [comment]
now this builds correctly.

**Comment by sivaramaaa** [comment]
lgtm , i actually added these warnings because when u have block size > maxbbsize 
 pdf and some other command fails to display it properly 
but i too saw a few people getting scared due to this , so we shall make it silent for now :)

But imo , we can  extend the bufsize and realloc it automatically if it excceds maxbsize and if still analysis of basic-block yet to complete!!!

**Comment by giuscri** [comment]
that would mean ignoring `anal.bb.maxsize` though

**Comment by sivaramaaa** [comment]
Yes imo we shall ignore that config var during analysis , see this regression for instance : 
 
https://github.com/radare/radare2-regressions/blob/e829667c91fcd02742e1b1cac0a6187b385cfa6e/t.anal/others_anal/aaa#L14

u have to increase anal.bb.maxsize inorder  to view function end properly !!!!

**Comment by radare** [comment]
at least it gives you a hint to understand why some functions are not analized properly... i wouldnt remove this warning, rather fix it

**Comment by giuscri** [comment]
@radare fix it how? ideas?

**Comment by radare** [comment]
You cant ignore it. We should fix code analysis to not depend on this variable. I agree on that but its also a protection against infinite analysis loops like anal depth is. But ignoring it or removing the warn is not a clean solution

**Comment by sivaramaaa** [comment]
Yup agree i on that @radare , so i think i have a solution for this 

we shall change anal.bb.maxsize ------> anal.bb.maxresize
And set that to default say 1 MB

And then in anal loop we keep on resizing the basic-block buffer until analysis is complete or it reaches anal.bb.maxresize

So with this we can accommodate basic-block upto 1 MB by default and also avoid running into infinite analysis , this is more or less similar to anal.depth

**Comment by giuscri** [comment]
i'll try to handle that, but ...@radare? what do you think?

**Comment by radare** [comment]
ideally that size should be dynamic

**Comment by sivaramaaa** [comment]
Yup that's exactly my point too **resizing the basic-block buffer until analysis** , but it can be limited by a config var (to avoid infinite anal)

But meh ... i can't make this too clear as a PR could do ...
So @giuscri  wanna try this , we could discuss and review once a PR is made

**Comment by giuscri** [comment]
ok, I underestimated the problem. Future fixers, feel free to work on this. I'm not right now. /cc @sivaramaaa

**Comment by kazarmy** [comment]
I think any resizing should be done only once, keep anal.bb.maxsize (renaming it to anal.bb.size) for the common cases and resize to anal.bb.overlargesize for the uncommon ones.

**Comment by radare** [comment]
I would just keep some internal decent defaults instead of allowing the user to specify that. And let r2 manage any size of bb within some sane boundaries

**Comment by kazarmy** [comment]
sgtm

**Pull request closed without merging**
