### PR TITLE
Add sys/release-notes.sh and define commit message conventions ·rules

### PR DESCRIPTION
**Pull request by radare**
screenshot 2018-10-16 at 03 24 09

### CODE REVIEW

**Comment by radare** [comment]
The idea for this PR is to define commit message conventions. This proposal is pretty simple and i think it heavily simplifies the time we need to spend to write the release notes

**Comment by radare** [comment]
This is.. we should append a middle-dot + tagname on all the commits with things that must appear in the release notes.

**Comment by radare** [comment]
Go uses this char too. And its available in the catalan layout, but its accessible on all layouts using the altgr+.

**Comment by radare** [comment]
All other chars i though could appear as r2 commands therefor not valid for commit messsages

**Comment by ret2libc** [comment]
Altgr+. seems to work on IT layout, but not on EN-US layot.

**Comment by ret2libc** [comment]
Altgr+. seems to work on IT layout, but not on EN-US layout.

**Comment by radare** [comment]
https://github.com/marcioAlmada/yay/issues/1

it’s \xc2\xb7

https://middot.net

$ printf "·•" |hexdump -C
00000000  c2 b7 e2 80 a2

**Comment by radare** [comment]
but im open for other suggestions

**Comment by ret2libc** [comment]
What about `##` or `>>` or `<<` or just a particular line in the full commit log?
Like:
```
Add sys/release-notes.sh and define commit message conventions

Changelog-Section: rules
```

**Comment by radare** [comment]
## is good, that was my first though, but i was afraid of github managing it somehow,. but seems like its not. so i can change to ## if you want

**Comment by ret2libc** [comment]
After thinking a bit about this, I think using a separate line in the git commit message may be better because otherwise you are going to steal useful characters from the first line of the commit message, which usually shouldn’t be longer than 78 chars.

**Comment by radare** [comment]
Its ok because we want short statements in the changelogs and hashtags will be short and only one per commit

**Pull request merged**
