### PR TITLE
CMake support for Radare2

### PR DESCRIPTION
**Pull request by igiagkiozis**
Hi pancake, 

Thanks for the great project! 

My primary platform at work is Windows, and since CMake is now supported in Visual Studio it makes it a convenient build system as opposed to Meson. 

So, here's a CMake version that I've tested on Windows 10 with Visual Studio 2017. 

Regards,
Ioannis

### CODE REVIEW

**Comment by radare** [comment]
Meson supports visual studio already

**Comment by igiagkiozis** [comment]
True, but Meson doesn't have the same integration with visual studio, for example you can open the project directly in VS if has a CMake build system, i.e. without first generating it in an intermediate folder. Also see this https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/

**Comment by Maijin** [comment]
Instead of PR directly for such big stuff, next time please can you come and discuss on the IRC/Telegram to avoid waste of energy 👍

**Comment by igiagkiozis** [comment]
@radare, by submitting a pull request it goes without saying that I volunteer to support this build system for radare as, in my view, this adds value to the project as CMake offers much better integration with Visual Studio which is the de-facto development environment on Windows.

@Maijin no energy wasted - I needed this and I coded it up. I thought it may be useful to the project as a whole, hence the pull request.

**Comment by Maijin** [comment]
ok !

**Pull request closed without merging**
