### PR TITLE
Disable colors when stdout is not a terminal

### LINKED ISSUE #5038: Support color=auto like GNU tools
From the "ls(1)" man page:

```
Using color to distinguish file types is disabled both by default and with --color=never.  With --color=auto, ls emits color codes only when standard output is connected to a terminal.  The LS_COLORS
```

I'm not proposing adding these --long-options, but simply making the right decision based on terminal. There should (of course) be a way to force colors on (perhaps just be doing e scr.color=true after detection makes its determination).

### PR DESCRIPTION
**Pull request by jduck**
This fixes #5038 and is based on #5067

### CODE REVIEW

**Comment by radare** [comment]
can you rebase on top of master?

**Comment by jduck** [comment]
Done.

**Comment by jduck** [comment]
Is this PR waiting on something?

**Comment by jduck** [comment]
From #5067, this is making Travis tests for clang+osx fail on cmd_visual. It's not clear why at this point.

**Comment by radare** [comment]
To make travis green at least. Also, im still not 100% confident that this change must be done by default. also maybe we should memoize isatty to avoid making r2 slower

**Comment by jduck** [comment]
Memoization is fine, but IMHO removing unnecessary calls to ```r_cons_isatty``` is superior. I don't believe there are any extraneous calls happening.

As mentioned in chat, the fact that ```cmd_visual``` is failing makes no sense. I cannot see how this change is causing that since 1) scr.color is already forced to 0 and 2) it isn't called until after the output is printed.

Is there some way to do some more interactive testing within the travis environment?

**Comment by radare** [comment]
i will take a look soon or late :) a bit low-prio to me, and im afraid we will not be able to test colors with that option or pipe with ansi escape chars.. also, if colors is disabled, the webserver will not be able to show colors in case of running r2 in daemon mode, right?

**Comment by radare** [comment]
i'll review this behaviour change after release. lets focus on correctness, crashes and other important bugs for now. thanks for the pr and sorry for the wait

**Comment by XVilka** [comment]
Any updates/decision on this?

**Comment by radare** [comment]
I think that we should merge this PR but just #if 0 by default. so we can close the PR and we can do some tests in local to decide that behaviour. but im afraid some people will be dissapointed for their use cases. this will allow us to better decide if we need an env var to enable or disable this behaviour depending on the user experience.

Can you update the PR with this change?

**Comment by jduck** [comment]
Rebased!

**Comment by radare** [comment]
Thanks! merged and squashed, and adjusted in 4bd92f322176a60eb1d6dbccfcec0e9573e5b252

**Comment by radare** [comment]
so this behaviour is disabled by default, but at least we have a better r_cons_isatty() and we can properly test that behaviour if we find it necessary in the future or decide which env var to honor.

thanks

**Pull request closed without merging**
