### PR TITLE
Fix ljmp with immediate segment:offset

### PR DESCRIPTION
**Pull request by mrmacete**

### CODE REVIEW

**Comment by Maijin** [comment]
Wait, is that #36 ?

**Comment by mrmacete** [comment]
uhm, related. yeah the last part - the `$j` is fixed, where capstone works. Could you point me to the existing test for https://github.com/radare/radare2/issues/36 so that i can check what i did is spot on?

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/t.formats/firmware/bios#L30

**Comment by Maijin** [comment]
And check also #4344 #4952

**Comment by mrmacete** [comment]
unbroken the test: https://github.com/radare/radare2-regressions/pull/615

**Pull request merged**
