### PR TITLE
Fixed out/in instructions assembling; Fixed branched operands: you could assemble multiple intructions now correctly.

### PR DESCRIPTION
**Pull request by Darkkey**

### CODE REVIEW

**Comment by radare** [comment]
Please rebase into a single commit

**Comment by Darkkey** [comment]
Any suggestions how to do it correctly without complete smashing of forked repo? Wasted several hours trying to fix this :(

**Comment by jvoisin** [comment]
`git rebase -i` is your _best_ friend!

**Comment by radare** [comment]
Dont worry im doing it here. wait a bit

**Comment by radare** [comment]
Thanks!

**Comment by radare** [comment]
Please close this branch, fork from master and use a single branch for every pullreq

**Comment by Darkkey** [comment]
Thank you!

**Pull request closed without merging**
