### PR TITLE
Fix debug rap reg profile setup

### PR DESCRIPTION
**Pull request by ScrimpyCat**
The operation was not being flushed prior to reading it, causing the `r_file_slurp` to not return anything.

This is part of the fix addressing some of the issues discussed in #9286 But it still is not enough to allow for remotely setting of the reg profile, due to it being replaced later (see my last comment in that issue).

So just thought I'd submit the PR now, as I'm not sure how to resolve the rest. If I can get some details about it I'd be happy to try and fix the remaining issue.

### CODE REVIEW

**Comment by radare** [comment]
uhm, shouldnt this flushing happen inside the pipe_close?

**Comment by ScrimpyCat** [comment]
Honestly I'm not sure, but adding the flush means `out = r_file_slurp (tf, NULL);` will actually contain the string (register profile) a server replies back with. Whereas without, it's just empty. Maybe the problem lies elsewhere?

This isn't a full solution to the problem though, this fix does allow for the register profile to be retrieved and then passed on so it's actually set. However afterwards the profile is being cleared again by the `r_config_set` (see the issue #9286 for more details regarding that). 

Basically in my use case I have a game I'm working on that I'm adding a RAP server implementation to ([WIP server](https://github.com/ScrimpyCat/Hacking-Game/blob/master/src/rap/RapServer.c)), as I thought I could leverage the RAP protocol (instead of adding a debug plugin) to allow for radare to debug programs in the game (I've added an [asm plugin](https://github.com/radare/radare2/compare/master...ScrimpyCat:master) to my own fork; I'm not going to try get any of this specific stuff into upstream though as it's just a toy/not of much use to anyone beyond the context of the game). If there's things that need to be fixed up with the RAP implementation in order to achieve working with custom RAP servers, then I'm interested in helping with that (though I'd need some pointers, since beyond this change I'm not sure how to get the rest to work). Or is there no intention to use the RAP protocol in this way (outside of radare to radare communication)?

**Comment by radare** [comment]
Yes i understand the issue but i was suggesting to move that call info the pipe close but i think its fine right now, we may probably find other places where pipe_open is misused like this?

**Comment by ScrimpyCat** [comment]
My bad didn't realise that's what you meant, would that have been more appropriate? Looking where else the `r_cons_pipe_open` is called, the only other file is https://github.com/radare/radare2/blob/73f76a99b29ea98fd286376b2fd470aa55e22666/libr/core/cmd.c but all of those pipes are being flushed before closing.

**Comment by radare** [comment]
Then its finw but its a common mistake that we can avoid by moving the flush in there. What do you think?

**Comment by ScrimpyCat** [comment]
That certainly would make it less error prone, so I think it could be a good idea. But I guess it just depends on whether you want the interface to closer resemble the regular close function (which isn't guaranteed to flush, but some devs might be familiar with close methods on other systems or languages which do flush).

**Pull request merged**
