### PR TITLE
Fixing ds in x86

### PR DESCRIPTION
**Pull request by saucec0de**
This pr is not for merge, but to have a look at the current regressions

### CODE REVIEW

**Comment by radare** [comment]
please rebase on top of master, cant merge this thing

**Comment by saucec0de** [comment]
still not for merge

**Comment by radare** [comment]
Also, check https://github.com/radare/radare2/issues/5801

**Comment by saucec0de** [comment]
this latest commit should (hopefully) solve all the regressions. however, i think it could be done in a better way. for now it might be enough...

after this merge, i will take a go at #5801 :-)

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/pull/552

**Comment by saucec0de** [comment]
rebased to 85371bc3

**Comment by saucec0de** [comment]
Yes... and this was the reason of the previous regressions.
Also, that is the reason of my previous statement that this "could be done better" - I have solved the regressions by moving the RCALL, etc to | R_ANAL_OP_TYPE_UCALL instead of | R_ANAL_OP_TYPE_CALL, i.e. they are still categorized as undefined calls". I am too new to r2 to know all the places where this can break things.  If the bitmasks are selecting only the lower bits of OP_TYPE, hopefully no change of behaviour should be expected...

**Comment by radare** [comment]
yep agree :) so we are aligned on that, and its good to have to regressions but grepping for R_ANAL_OP_TYPE_CALL reveals more places where this should be handled that are not tested. using op.type == OpType.CALL is not always a good idea after your change.

grep hints:

* “case R_ANAL_OP_TYPE_CALL”
* “== R_ANAL_OP_TYPE_CALL”

**Comment by saucec0de** [comment]
good point :-) I will grep for that and change accordingly.

**Comment by radare** [comment]
checkout https://github.com/radare/radare2/issues/5472#issuecomment-248580993 i guess your PR fixes this issue

**Comment by Maijin** [comment]
@radare 
image

**Comment by radare** [comment]
let's merge this now and do as much testing as possible :E the analop.type.toString should be updated too

**Pull request merged**
