### PR TITLE
Special syms hints

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by ret2libc** [comment]
This is broken right now.

**Comment by ret2libc** [comment]
This seems to work in general however in some cases $d are placed in weird places... @radare please have a look.

For example, there is a $d in the middle of a function (r2 ./r2r/bins/elf/analysis/example.elf)
```
            ;-- uart_event_handler:                                                                                                                                                                                
            0x0000045c      30b5           push {r4, r5, lr}                                                                                                                                                       
            0x0000045e      0478           ldrb r4, [r0]                                                                                                                                                           
            0x00000460      85b0           sub sp, 0x14                                                                                                                                                            
            0x00000462      012c           cmp r4, 1                                                                                                                                                               
        ┌─< 0x00000464      19d0           beq 0x49a                   ;[1]                                                                                                                                        
        │   0x00000466      022c           cmp r4, 2                   ; loc.NRF_POWER_RAMONx_RAMxON_ONMODE_Msk                                                                                                    
       ┌──< 0x00000468 hex length=68 delta=0                                                                                                                                                                       
0x00000468  34d0 002c 01d0 05b0 30bd 254c 254d 201c  4..,....0.%L%M .                                                                                                                                              
0x00000478  291c fff7 c5ff 0028 23d0 a268 e368 9a42  )......(#..h.h.B                                                                                                                                              
0x00000488  f1d1 0323 02aa 1370 1f4b 101c 1b68 9847  ...#...p.K...h.G                                                                                                                                              
0x00000498  e9e7 4368 1d4d 1978 281c fff7 9dff 0028  ..Ch.M.x(......(                                                                                                                                              
0x000004a8  1ed1 aa68                                ...h                                                                                                                                                          
 ;[2]                                                                                                                                                                                                              
       │    0x000004ac hex length=44 delta=0                                                                                                                                                                       
0x000004ac  eb68 9b1a 012b 21d0 aa68 eb68 9b1a aa88  .h...+!..h.h....                                                                                                                                              
0x000004bc  9342 d6d8 0121 1548 00f0 ccf9 d1e7 281c  .B...!.H......(.                                                                                                                                              
0x000004cc  0121 00f0 6df9 d6e7 02ab 1c70            .!..m......p                                                                                                                                                  
                                                                                                                                                                                                                   
            0x000004d8 hex length=44 delta=0                                                                                                                                                                       
0x000004d8  c368 02a8 0193 0393 0b4b 1b68 9847 c2e7  .h.......K.h.G..                                                                                                                                              
0x000004e8  02ab 1c70 084b 0390 1b68 02a8 9847 dde7  ...p.K...h...G..                                                                                                                                              
0x000004f8  02ab 1870 044b 02a8 1b68 9847            ...p.K...h.G                    
```

It doesn't seem to be a bug though, readelf does report a $d at those addresses. Do you have any idea why? The only way I could think of to solve this issue is that when analysis is certain that a given range of bytes is definitely code, it should mark that as code. But I don't intend to touch analysis... so we either live with this bug, or we fix it somehow (though I'm not the best person for this, as I don't work with ARM)

**Comment by radare** [comment]
lgtm

**Comment by radare** [comment]
yeah those $d inside the code are quite wtf.. maybe we are good in just ignoring them

**Comment by ret2libc** [comment]
@radare if green, i'm going to merge it. For now, let's ignore $d as agreed.

**Comment by radare** [comment]
👍

**Pull request merged**
