### PR TITLE
set function size as length of continuous sequence of bbs

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by dmtch** [comment]
It is neccessary to handle jmp-connected functions. For example look at EP in this borland-c compiled file: http://rghost.net/8DWCDlwpK (be careful - it's malware, pwd "Test").

**Comment by dmtch** [comment]
I will add also some tweaks for correct analysis of delphi codes.

**Comment by ret2libc** [comment]
Seems like the function at the EntryPoint of that binary is wrong both before and after this patch.
If I do ```aaa``` and ```afb entry0``` I can see only two basic blocks. Instead, if I do ```af entry0``` and ```afb entry0```I can see all the basic blocks in the function. Probably some issues with the resizing?

**Comment by dmtch** [comment]
I see only one bb.

[0x00401000]> aaa
[0x00401000]> afb
0x00401000 0x00401002 00:0000 2

[0x00401000]> af
[0x00401000]> afb
0x00401000 0x00401002 00:0000 2

**Comment by dmtch** [comment]
Issue with the resizing: CFG traversal (fcn_recurse) returns an error R_ANAL_RET_ERROR when anal.recont is not set and after resizing do not called. Error condition became here:
```
	bb = bbget (fcn, addr);
	if (bb) {
		r_anal_fcn_split_bb (anal, fcn, bb, addr);
		if (anal->opt.recont)
			return R_ANAL_RET_END;
		return R_ANAL_RET_ERROR; // MUST BE NOT DUP
	}
```
If any BB is visited twice, it returns an error... But why?

**Comment by dmtch** [comment]
Thanks, I will make some test for this.

**Comment by radare** [comment]
yes, i have merged, for the sake of testing, the best way to understand how analysis works or must be enhaced is by adding more tests and fixing them by tuning default config options.

**Pull request closed without merging**
