### PR TITLE
Four tiny fixes

### PR DESCRIPTION
**Pull request by sghctoma**
This PR contains 4 commits with the following small fixes:

- commit 1e5c855343b060e0321c68d4dd20ba63caa1a661: sys/purge.sh uses "make" directly, so that it doesn't work on systems where "gmake" should be used (e.g. on FreeBSD). I've copied the check from install.sh into purge.sh, and it works now.

- commit c9c618214de7ff9298a96e10abc1e28e5a5fe4d0: When radare2 is installed using sys/user.sh, the executables are called using wrapper shell scripts. Parameters are not quoted properly, so for example `rasm2 'mov eax,0x1337'` simply won't work. This is because the shell eats up the quotes, so rasm2 will think that 'mov' is the entire code you want to assemble. I think I've fixed this in this commit.

- commit aa5cd4dd9025b777adc29a73687c96e0f82984a5: Function names are not preserved during a project save/load cycle. This is because in the "af+" implementation there is a check that changes the function name to "fcn.\<addr\>" if the function name starts with "fcn.". Since "fcn." is prepended to every function's name that was created with "af" or renamed with "afn", every manually changed function names will be reverted. I don't really know the reason behind that check, but I've found it save to remove.

- commit 7cd4f097b631a54325f74337dc1560ef6910d755: When using the prompt (with the ':' key) in graph mode to e.g. rename local vars or arguments, one have to refresh the graph manually to reflect these changes. I think there is no drawback in refreshing it automatically.

Regards,
Toma

### CODE REVIEW

**Comment by ret2libc** [comment]
I'm not sure about refreshing the graph every time you use ```:```, because if you refresh the graph, you will get back the original layout and you will be moved to the position of the selected node, which seems quite annoying to me. Maybe you can use ```get_bbupdate``` instead of ```g->need_reload_nodes```, so that you will update only the text of the nodes, instead of everything.

**Comment by radare** [comment]
Agree with riccardo, i already discussed this. And we should just update the contents of the nodes, not the entire graph. In fact it will be good to make this only when needed. But this will require to make r2 totally event based which requires too much redesign and probably overhead.

**Comment by sghctoma** [comment]
You are right, `g->need_reload_nodes` was not a good choice here, somehow I missed `get_bbupdate`. I've tried it, and works OK. Refreshing only when needed would be nice, but I don't yet have the kind of understanding of the whole code that would make me able to see how big a challenge would that be :)

So what should I do with this? Are the other three commits OK? Should I close this PR and create another with those three, or should I include the fourth too with `get_bbupdate`?

**Comment by ret2libc** [comment]
I think get_bbupdate for the moment may be ok. @radare what do you think?

**Comment by radare** [comment]
yeah that way lgtm

**Comment by radare** [comment]
Make this change and i'll merge! thanks

**Comment by sghctoma** [comment]
Pushed the change. Thanks!

**Comment by radare** [comment]
Merged

**Pull request closed without merging**
