### PR TITLE
Fix #11237: rename rasm2 -o -O

### LINKED ISSUE #11237: rasm2 flag change proposal
```
 -o [offset]  Set start address for code (default 0)
 -O [file]    Output file name (rasm2 -Bf a.asm -O a)
```

my proposal is to use this:

```
-o [file]
-@ [offset]
```

this way is in sync with rabin2

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by MaskRay** [comment]
new/bin/r2r.js runs the `!rasm2 -@ 0x4000 -a arm -b 16 -d 80f018ea` command in r2. However, `@` will be interpreted as a tmpseek.

**Comment by MaskRay** [comment]
I cannot fix the tests until r2r.js can run rasm2 radiff2 ... commands as well as radare2, not relying on

```
| !ls                      execute 'ls' in shell
```

And I'm also against https://github.com/radare/radare2/issues/11318

**Comment by radare** [comment]
Wat

> On 2 Sep 2018, at 05:49, Fangrui Song <notifications@github.com> wrote:
> 
> I cannot fix the tests until r2r.js can run rasm2 radiff2 ..
> 

U mean the busybox style pr?
> . commands as well as radare2, not relying on
> 
> | !ls                      execute 'ls' in shell

Why. Use just ls
> And I'm also against #11318
> 

Completelly unrelated

**Comment by Maijin** [comment]
Tools are already in r2r.js -> https://github.com/radare/radare2-regressions/tree/master/new/db/tools

**Comment by radare** [comment]
I think the less painful solution to this would be to just add -@ as an alias for -o, otherwise calling !rasm2 from inside r2 can be a bit anoying because of the quoting. Also this way we dont have to change any test from the regressions repo to make it green.

**Comment by radare** [comment]
Done in 3e98d0f7780040175c4097b6d49eef4be4f1498b

**Pull request closed without merging**
