### PR TITLE
proper virtual address for GBA ROMs

### PR DESCRIPTION
**Pull request by cosarara97**

### CODE REVIEW

**Comment by Maijin** [comment]
@cosarara97 doesn't build see the travis log https://travis-ci.org/radare/radare2/jobs/96323025

**Comment by cosarara97** [comment]
Ouch, that was stupid. Well, should be fixed now.

**Comment by radare** [comment]
Merci!

**Comment by radare** [comment]
ping. can you send the PR for the ARM stuff too?

thanks!

**Pull request closed without merging**
