### PR TITLE
Fix invalid instruction warning

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
how is this fixing the warning?

**Comment by radare** [comment]
should honor anal.verbose, and whats wrong with showing the length?

**Comment by kazarmy** [comment]
> whats wrong with showing the length?

well if the instruction is invalid, we'll never know for sure how long the instruction should be, and so showing the length is pointless

**Comment by kazarmy** [comment]
... showing any length is pointless with regard to the invalid instruction

**Comment by radare** [comment]
well it's useful as a hint because we were using fixed size buffers before.. not sure if that's still the case

**Comment by kazarmy** [comment]
> should honor anal.verbose

ok 772e63280695788126d82b743b23d2aedfabeb1c ... if anal.verbose is honored, i think it's better that the filtering is removed ... might want to know where all the false positives are

**Comment by radare** [comment]
yeah sounds reasonable

**Pull request merged**
