### PR TITLE
Add crypto ROT, ROL and ROR

### PR DESCRIPTION
**Pull request by P4N74**
Implementing ROTn instead of ROT13 as specified in https://github.com/radare/radare2/issues/4254. Also `rahash2 -S` used to convert the seed to hex even though `s:` was given in the seed string, hence it is corrected and recalculation of `seed` is removed.

### CODE REVIEW

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/pull/363

**Comment by P4N74** [comment]
Please don't merge it now.

**Comment by radare** [comment]
Whats missing?

**Comment by P4N74** [comment]
@radare I didn't get you.

**Comment by radare** [comment]
Merged!

**Pull request closed without merging**
