### PR TITLE
Meson: Update list of anal/asm/bin plugins

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by xarkes** [comment]
For some reason, it is still not working.
```
[XX] db\asm\java java: 91 => "i2b" (disassemble)  
12281
$ r2 
12282
-i2b
12283
+addx #0x61:8,r1h
```

**Comment by XVilka** [comment]
Well, there are 891 broken tests..., looks all assembly related are down too.

**Comment by XVilka** [comment]
Also note, there is whitespace issue somewhere:
```
-            0x00000000      0149           ldr r1, [0x00000008]        ; [0x8:4]=0x22221111 ; 8
12455
-            0x00000002      014a           ldr r2, [0x00000008]        ; [0x8:4]=0x22221111 ; 8
12456
-            0x00000004      014b           ldr r3, [0x0000000c]        ; [0xc:4]=0x44443333 ; 12
12457
+            0x00000000      0149           ldr r1, [0x00000008] ; [0x8:4]=0x22221111 ; 8
12458
+            0x00000002      014a           ldr r2, [0x00000008] ; [0x8:4]=0x22221111 ; 8
12459
+            0x00000004      014b           ldr r3, [0x0000000c] ; [0xc:4]=0x44443333 ; 12
12460
EXPECT64=ICAgICAgICAgICAgMHgwMDAwMDAwMCAgICAgIDAxNDkgICAgICAgICAgIGxkciByMSwgWzB4MDAwMDAwMD
```

**Comment by XVilka** [comment]
All tests for EBC are broken too.

**Comment by xarkes** [comment]
No that's the broken tests, not the XX ones.

**Comment by XVilka** [comment]
Ah, "just" 259. But my notes regarding nature of those tests are still valid.

**Comment by pelijah** [comment]
And now?

**Comment by pelijah** [comment]
It seems that it works.

**Comment by pelijah** [comment]
ping @xarkes

**Comment by xarkes** [comment]
Yep 78XX, looks good!
Remaining issues are mainly in cmd_pd cmd_pf.
There are weird issues in asm\x86_16 and asm\x86_32

**Pull request merged**
