### PR TITLE
Fix spp on Windows

### PR DESCRIPTION
**Pull request by GustavoLCR**
#10613

### CODE REVIEW

**Comment by XVilka** [comment]
Please send a PR to https://github.com/radare/spp

**Comment by radare** [comment]
This fix must be in spp. So you need to move this getenv function inside spp. Otherwise we will break things next time we sync

**Comment by radare** [comment]
is your PR exactly the same as mine? :( read it late

**Comment by GustavoLCR** [comment]
Np

Em sex, 21 de jun de 2019 às 15:47, radare <notifications@github.com>
escreveu:

**Pull request closed without merging**
