### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by alvarofe**

### CODE REVIEW

**Comment by crowell** [comment]
some pdb test is failing from this

**Comment by alvarofe** [comment]
Is failing from this https://travis-ci.org/radare/radare2/builds/67593950

**Comment by radare** [comment]
You can just use (!*p) instead of (*p=='\0') :P

**Comment by radare** [comment]
the pdb test is failing because of the PE exports commit. it is not failing in localhost, so i wonder what is going on... i have removed a debug printf.. so let's wait for travis to build again. merged this stuff

**Pull request closed without merging**
