### PR TITLE
Fix a few anal leaks

### PR DESCRIPTION
**Pull request by dequis**
Mostly sdb_get() calls that didn't free the result, but there are others.

### CODE REVIEW

**Comment by radare** [comment]
Maybe const_get is better unless the contents need to be modified

**Comment by dequis** [comment]
Uhhh, is `sdb_const_get_len` a copypasted version of `sdb_get_len` with one strdup less? Out of scope of this pr but whyyyy

**Comment by dequis** [comment]
Updated, thanks for pointing that out, it's neater for this kind of usage.

**Comment by radare** [comment]
Yep there are some apis in sdb that look redundant but are basically useful for those cases where you dont wanna mess with the heap and such :)

**Comment by dequis** [comment]
The api is okay, the implementation is redundant. `sdb_get_len` looks like it could be

```c
SDB_API char *sdb_get_len (Sdb* s, const char *key, int *vlen, ut32 *cas) {
	return strdup(sdb_const_get_len (s, key, NULL, cas));
}
```

Instead of a copypaste of the same function

(the real version would have proper null checking before the strdup, but you get the idea)

**Pull request merged**
