### PR TITLE
Enable ASSERTS on all travis builds, to avoid confusion

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by ret2libc** [comment]
I don't think the red status is related to this PR. It seems also master has some red builds because it stalled somehow.

**Comment by radare** [comment]
well... master have only one timeout, this one have 4. and there are other PRs with 0 or 1 timeout only and always in the same test. so not sure what's going on

**Comment by XVilka** [comment]
It is general Travis breakage, see the service status.

**Comment by radare** [comment]
confirmed its random by forcing some reruns

**Pull request merged**
