### PR TITLE
fix #1503

### LINKED ISSUE #1503: Duplicates info in `i`
```
jvoisin@kaa 16:36 ~ r2 =true
 -- Enable asm.trace to see the tracing information inside the disassembly
[0x004013e2]> i
file	/bin/true
type	EXEC (Executable file)
pic	false
canary	true
nx	true
crypto	false
has_va	true
root	elf
class	ELF64
lang	c
arch	x86
bits	64
machine	AMD x86-64 architecture
os	linux
subsys	linux
endian	little
strip	true
static	false
linenum	false
lsyms	false
relocs	false
rpath	NONE
type	EXEC (Executable file)
os	linux
arch	AMD x86-64 architecture
bits	64
endian	little
file	/bin/true
fd	6
size	0x6a20
mode	r--
block	0x100
uri	/bin/true
format	elf64
```

This should be easy to fix, and a good task for a newcomer.

### PR DESCRIPTION
**Pull request by alvarofe**
Let me know if this is the behavior and also If it continues having some repeated fields that I couldn't see. Before to merge perhaps is needed to upgrade the regression repository but I wanted to receive feedback before. So after confirmation that is ok I will update the necessary test.

I decided to erase the bin information for those files that are not executable because these fields are either empty or false.

There are fields that are equal in core and bin and I decided to keep them in the core since for the images, pdf the bin information is not showed. However the fields "machine" and "os" with these kind of files are empty, so would be better to move them in the bin_info? ( I did this for "os" field but not with "machine") since in the json output these fields will be empty and we can save some bytes.

 

captura de pantalla 2015-04-07 a las 19 52 55
captura de pantalla 2015-04-07 a las 19 56 56
captura de pantalla 2015-04-07 a las 19 55 25
captura de pantalla 2015-04-07 a las 20 17 55

### CODE REVIEW

**Comment by radare** [comment]
You can get this by checking the associated binobject.
```
 R_API RBinObject * r_bin_file_object_get_cur (RBinFile *binfile) {
```
let me know if that helps in all the cases

**Comment by alvarofe** [comment]
I've checked with executables, images, pdf and shared library and it works. If there are other kind of files to test just tell me. 

If it is ok, I have to update the regressions since cmd_info is broken

**Comment by radare** [comment]
Maybe we can asume that its a program if it contains a section with executable perms

**Comment by alvarofe** [comment]
I thought on that but instead to look in the sections I was checking if the RBinObject had a format attached but maybe the format is not related with only executables files I guess.

I will update to look in the sections

**Comment by Maijin** [comment]
@alvarofe Take a look at the anal.java test https://travis-ci.org/radare/radare2/jobs/57800740 your patch doesn't seem to display class for example.

    -class    0x3300 0x0000

**Comment by alvarofe** [comment]
@Maijin that is because the file is not executable and I am no showing the bin information only the core. Should I show the whole information from all files or distinct between executables and not executables? 

With my patch only shows this

```

type     JAVA CLASS
bits     32
endian   little
file     malloc://1023
fd       5267984
size     0x3ff
blksz    0x0
mode     r--
block    0x100
format   java

```

Without the patch 

```
file     malloc://1023
type     JAVA CLASS
pic      false
canary   false
nx       false
crypto   false
va       false
root     class
class    0x3300 0x0000
lang     java
arch     java
bits     32
machine  jvm
os       any
subsys   any
endian   little
strip    false
static   false
linenum  true
lsyms    true
relocs   false
rpath
binsz    1023
type     JAVA CLASS
os       any
machine  jvm
bits     32
endian   little
file     malloc://1023
fd       12777872
size     0x3ff
blksz    0x0
mode     r--
uri      malloc://1023
block    0x100
format   java
```

**Comment by radare** [comment]
A java class file is executable. Why not think the otherway around? Only hide the files we know it should not have rbininfo?

**Comment by alvarofe** [comment]
It has not any executable section

```
[Sections]
idx=00 vaddr=0x00000111 paddr=0x00000111 sz=259 vsz=0 perm=---- name=constant_pool
idx=01 vaddr=0x00000115 paddr=0x00000115 sz=270 vsz=0 perm=---- name=methods
idx=02 vaddr=0x0000011f paddr=0x0000011f sz=69 vsz=0 perm=---- name=attrs._init_
idx=03 vaddr=0x0000015c paddr=0x0000015c sz=215 vsz=0 perm=---- name=attrs.simple_case_stmt_4val
idx=04 vaddr=0x00000223 paddr=0x00000223 sz=10 vsz=0 perm=---- name=attributes

5 sections

```
And I was using that.

The problem at least to me is how to distinct that in code. Is there any field in some struct that give that? because the type of the files are strings and I would need to compare against the all possibilities. Even for images files the `RBinInfo`  from `RBinObject` is not NULL.

We could consider the files without section not executable? 

Enlighten me :)

**Comment by radare** [comment]
The perms are wrong in java class sections. Thats easy to fix, can you patch this? (In the same or diff pr)

Also i think that rbin.fs may show interesting info in rbininfo that will not be displayed.

**Comment by alvarofe** [comment]
Yeah of course any problem. I will try to patch it in the same PR

rbin.fs? I don't see any field in RBin with fs. Tell me and I will add to in the cmd_info ;)

**Comment by alvarofe** [comment]
I've assumed after reading a little bit that the only section executable is "method" since is the only with bytecode the rest are like definitions and symbol tables that its why I've written readable. If I am wrong let me know since I don't have IDA to compare

**Comment by radare** [comment]
Yep, but the rest of sections should be marked as readonly

**Comment by alvarofe** [comment]
Yep, the rest of the sections I've added only `R_BIN_SCN_READABLE` for method `section->srwx = R_BIN_SCN_READABLE | R_BIN_SCN_EXECUTABLE;`

**Comment by radare** [comment]
I have merged your patches, it breaks some tests, but this is the best way to verify that everything is working fine, please, take a look at this output: https://travis-ci.org/radare/radare2/jobs/58207990 i'm going to review it a bit now.

thanks!

**Comment by Maijin** [comment]
@alvarofe https://github.com/radare/radare2-regressions/commit/f0125c2b6def83493c3df1480d7196be658b35b0

**Pull request closed without merging**
