### PR TITLE
 Add cfg.escbslash: Escape the backslash (currently Cs output only)

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by kazarmy** [comment]
Oh great I broke rasm2

**Comment by radare** [comment]
Wat

**Comment by radare** [comment]
i think all those vars should be under str.

**Comment by kazarmy** [comment]
> i think all those vars should be under str.

Ok done (e7afd67991b3315d55abc87037bce09252afe82f).

**Pull request merged**
