### PR TITLE
more work into ELF

### PR DESCRIPTION
**Pull request by alvarofe**
the aim of this PR is to merge symbols from phdr. If the binary says that it only has a symbol, we only would return it missing information from phdr. I have introduced code to add into symbols those that are not present in shdr once we have fixed overlapped symbols. I have to cook a binary to show the usefulness of this and fix a test in ELF.

### CODE REVIEW

**Comment by radare** [comment]
cool!

**Comment by Maijin** [comment]
segfault on 14 bin check the logs

**Comment by alvarofe** [comment]
doesn't segfault in local though but sure will check

**Comment by alvarofe** [comment]
I didn't test the case changing the section header to fool the parser, so maybe the work is not done 100%

**Pull request merged**
