### PR TITLE
Meson: disable libversion info for Windows

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by xarkes** [comment]
Why?

**Comment by pelijah** [comment]
Because it is useless.

**Comment by xarkes** [comment]
Ah ok so it doesn't break `r2 -V` ?

**Comment by pelijah** [comment]
No, this commit just restore previous names for dlls: `librblah.dll` instead of ugly `librblah-x.x.x-git.dll`

**Comment by xarkes** [comment]
Ah ok ok.

**Pull request merged**
