### PR TITLE
Makefiles: use "git clone --depth 1 ..." when possible

### PR DESCRIPTION
**Pull request by fenugrec**
When cloning {sdb,tcc,udis86,radare-regressions} repos: slightly reduces build time with slow connections.

### CODE REVIEW

**Comment by radare** [comment]
Those git lines are never executed at build time. are only for maintainance to update our clones from master. The only one that will be called at build time is the capstone one. and you didnt updated it

**Comment by radare** [comment]
Oh, nevermind, --depth cant be used with the capstone fetch, because, otherwise we can't get the specified commit.

Merged. thanks

**Comment by radare** [comment]
It would be great if git could allow us to just clone a specific commit, but it's not yet possible :(

**Comment by fenugrec** [comment]
The best that could be done for capstone is maybe "git -b ${CS_BRA} --single-branch ${CS_URL}" but it hardly makes a difference (26s instead of 28s here)

**Comment by radare** [comment]
meh, no need to make things more complicated for now
thanks

**Pull request closed without merging**
