### PR TITLE
HTTP/ reuse port option feature.

### PR DESCRIPTION
**Pull request by devnexen**
Allow multiple instances, might be of use
but is optional.

### CODE REVIEW

**Comment by wargio** [comment]
i would suggest to extend the check on `#ifdef SO_REUSEPORT/#endif` in all the files, but i would wait @radare to confirm this.

**Comment by radare** [comment]
what's the actual use case for this? im not sure what will benefit us from having this

**Comment by devnexen** [comment]
@radare for now probably not much use, was thinking for possible evolution of this embedded web server.

**Comment by radare** [comment]
i dont see the need to add new cmdline flags, config vars and such for something we dont know why would be useful for.

**Comment by devnexen** [comment]
All right then.

**Pull request closed without merging**
