### PR TITLE
Fixes from JMPTBL PR from Alvaro

### PR DESCRIPTION
**Pull request by XVilka**
From https://github.com/radare/radare2/pull/7699
Picked up the part that shouldnt break the tests, lets see

### CODE REVIEW

**Comment by radare** [comment]
looks green to me

**Comment by radare** [comment]
can we have some tests?

**Comment by XVilka** [comment]
Just a first ball, playing with jump tables in general. Will add stuff here.

**Comment by radare** [comment]
ok, but dont wait too much to merge ;)

**Pull request merged**
