### PR TITLE
aae improvements

### PR DESCRIPTION
**Pull request by resetnow**
https://asciinema.org/a/1n8wfswmadc5ly8jg9r9di5fn

Things I'm not sure about:

1. 12 is a magic number, is there a macro somewhere like INSN_SIZE_MAX?
1. code for printing function reference in cmd_anal.c and core/disasm.c is identical, should I make it a part of disasm api and call it from core?

### CODE REVIEW

**Comment by radare** [comment]
Insn size max is available in the rasm plugin thats different for each arch

**Comment by radare** [comment]
Yep refactoing this out to a separate function makes sense

**Comment by resetnow** [comment]
I actually just found that when asm.emu is enabled, computed calls are visible too, although along with a lot of other information. Now I'm not sure whether pd should have its own call target name printing.

**Comment by radare** [comment]
Enable asm.emustr and all the garbage will be gone

**Comment by resetnow** [comment]
>Enable asm.emustr and all the garbage will be gone

So basically I duplicated the output in pd, sorry about that. Should I remove the PD addition then?

**Comment by radare** [comment]
well, asm.emustr is done on pd, your work is in aae which aims to put this info static as comments, right?

**Comment by resetnow** [comment]
yes. As a result, when asm.emu, asm.emustr and asm.cmtrefs are enabled, call info is essentially duplicated. Although if aae changes behaviour in future and provides better analysis, pd printing part (ec291e476740ec71ce7d3f734e0c59a52ee391e1) can also stay.

**Comment by radare** [comment]
so its fine for now i guess. we can improve to avoid that dupped info later :)

**Pull request merged**
