### PR TITLE
Fix #10980 - ESIL output without duplicating eXX-rXX registers

### LINKED ISSUE #10980: esil mixes register name styles
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macos (modern ie 64bit)
| File format of the file you reverse (mandatory)      | elf
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18984 @ darwin-x86-64 git.2.7.0-276-g319e20cea commit: 319e20cea731a033ad339d686e1413730c9da90b build: 2018-08-06__20:25:48

I would expect radare to maintain register naming styles but its mixing in edi rdi, eax rax, etc leading to a lot of noise
```
[0x010578a9]> s 0x01057929
[0x01057929]> pdf
/ (fcn) sym.runtime.closefd 23
|   sym.runtime.closefd (int arg_8h, int arg_10h);
|           ; arg int arg_8h @ rsp+0x8
|           ; arg int arg_10h @ rsp+0x10
|           ; CALL XREF from sym.runtime.getRandomData (0x1028e30)
|           0x01057920      8b7c2408       mov edi, dword [arg_8h]     ; [0x8:4]=-1 ; 8 ; edi=0xffffffff ; rdi=0xffffffff
|           0x01057924      b806000002     mov eax, 0x2000006          ; eax=0x2000006 ; rax=0x2000006
|           ;-- hit0_3:
|           0x01057929      0f05           syscall                     ; 33554438 = close (0xffffffff)
|       ,=< 0x0105792b      7305           jae 0x1057932               ; unlikely
|       |   0x0105792d      b8ffffffff     mov eax, 0xffffffff         ; -1 ; eax=0xffffffff ; rax=0xffffffff
|       `-> 0x01057932      89442410       mov dword [arg_10h], eax
\           0x01057936      c3             ret                         ; rip=0xffffffffffffffff ; rsp=0xffffffff0683eb46
[0x01057929]> 
```

### PR DESCRIPTION
**Pull request by NotSoOld**
Fixes #10980 
Now there will be only one ESIL comment showing info about result in rXX register for operations on both eXX and rXX registers. Just merged two ESIL operations - opcode operation and correction of bytes 32-63 - into one.
BTW I saw correction only for MOV, XOR and AND; I guess there are more opcodes which may require that.

### CODE REVIEW

**Comment by radare** [comment]
i think the 15 XX shuold be updated if the new behaviour is correct. but didnt checked them in detail

**Comment by radare** [comment]
https://api.travis-ci.org/v3/job/414421007/log.txt

**Comment by NotSoOld** [comment]
It seems like not fixing everything, please do not merge until I resolve all mistakes.

**Comment by XVilka** [comment]
Still 18 [XX]

**Comment by jacobrosenthal** [comment]
I looked at this commit in tests and I think it fails the same things that are failing in master so I dont think this affects any tests

```
Jacobs-MacBook-Air:radare2-regressions jacobrosenthal$ ./run_tests.sh 
radare2 2.9.0-git 19352 @ darwin-x86-64 git.2.8.0-139-gbfecffe2f
commit: bfecffe2fea4bb067887163d1f359eeb1b39d8d9 build: 2018-08-19__10:51:29
[166]  SUCCESS
[1]    FIXED
[13]   BROKEN
[0]    FATAL
[0]    FAILED
[7%]    BROKENNESS


Jacobs-MacBook-Air:radare2-regressions jacobrosenthal$ ./run_tests.sh 
radare2 2.9.0-git 19285 @ darwin-x86-64 git.2.8.0-124-gec0257e2e
commit: ec0257e2e4b5dc56e184be60f20a9db74a0f86eb build: 2018-08-18__21:16:34
[166]  SUCCESS
[1]    FIXED
[13]   BROKEN
[0]    FATAL
[0]    FAILED
[7%]    BROKENNESS
```

**Comment by radare** [comment]
Just use r2r.js -i and u will get promted for every failing test and will update everything for u.

**Comment by Maijin** [comment]
`make -k all` will execute both old and new testsuite

**Comment by radare** [comment]
can you rebase?

**Comment by radare** [comment]
it's red because tests needs to be updated

**Comment by radare** [comment]
ping

**Comment by NotSoOld** [comment]
Wat d'you want from me?

**Comment by radare** [comment]
To review and fix the tests in a pr to make travis green

**Comment by XVilka** [comment]
@NotSoOld see https://github.com/radare/radare2-regressions/pull/1504

**Pull request closed without merging**
