### PR TITLE
Java fixes with several regressions

### PR DESCRIPTION
**Pull request by radare**
Do not merge, just use this branch in order to track travis testing

### CODE REVIEW

**Comment by Maijin** [comment]
@radare it passes no?

**Comment by radare** [comment]
Nope. its full of regressions. but tests are wrong. just open any random .class file and observe tons of warnings, and lot of missing symbols, etc

**Comment by Maijin** [comment]
oh ok :(

**Comment by radare** [comment]
We need more tests for java

**Pull request closed without merging**
