### PR TITLE
ESIL support for Intel 8051

### PR DESCRIPTION
**Pull request by dkreuter**
Do not merge, this PR is just for tracking of progress.

### CODE REVIEW

**Comment by radare** [comment]
Change pullreq title to 8015 and squash those commits into a single one (git rebase -i @~6) mark as 's' all the commits except the first and push -f

Thx

**Comment by radare** [comment]
Ping me when you think it needs review to merge

**Comment by radare** [comment]
doesnt compiles
```
//libr/anal/p/anal_8051.c:82:29: error: use of undeclared identifier 'L1'
        case 0x80: /* sjmp */ emit(SJMP1); break;
                                   ^
//libr/anal/p/anal_8051.c:25:15: note: expanded from macro 'SJMP1'
#define SJMP1 L1 JMP("2")
              ^
/libr/anal/p/anal_8051.c:12:48: note: expanded from macro 'emit'
#define emit(frag) r_strbuf_appendf(&op->esil, frag)
                                               ^
1 error generated.
```

**Comment by radare** [comment]
The switch case ranges are not that far to make this code depend on them. i would prefer to have all the cases. I see still several instructions in TODO. the L1 and L2 are not defined.

I will try to push DUP and SWAP this week which may help useful for your esil use case. the inclusion of new core instructions in ESIL forces to update REIL and other parts of r2.

**Comment by radare** [comment]
Squash those two commits into a single one and change the commit message to be something like:
```
Initial ESIL support for i8051 CPU
```

**Comment by radare** [comment]
Thanks!

I'm merging this, but the patch is not complete, the invalid instruction must be handled as a trap. also there are some instructions that are not yet handled: push, djnz, rlc, movc,.. but that's a good start.

Keep up the good work!

**Comment by XVilka** [comment]
:+1: nice piece of work!

**Comment by jvoisin** [comment]
Awesome!

**Pull request closed without merging**
