### PR TITLE
Refactored meson scripts

### PR DESCRIPTION
**Pull request by pelijah**
Related issue: #8690.

### CODE REVIEW

**Comment by pelijah** [comment]
Hmm msbuild works fine on my machine.

**Comment by pelijah** [comment]
Very strange msbuild's behaviour. Now it's working.

**Comment by XVilka** [comment]
Can you please rebase upon latest master?

**Comment by pelijah** [comment]
Done

**Comment by xarkes** [comment]
I see appveyor is green, good to merge?

**Comment by pelijah** [comment]
Ok you can merge it. I will try to update makefile tomorrow.

**Pull request merged**
