### PR TITLE
OMF loader #219

### PR DESCRIPTION
**Pull request by ampotos**
This omf loader load :
* omf segment (separate in different section to have all the record in a segment side by side in memory)
* omf data (opcode and data, lidata are not load because i don't know how to manage repeating data in radare)
* symbols (only local and export)
* detect 16/32 bits opcodes
* detect 16/32 bits address space

### CODE REVIEW

**Comment by ampotos** [comment]
Actually there is 2 problem, in 32 bit omf the section vaddr take the value of the section paddr (but there are both set correctly in RBinSection file).
When a try to disass at addr 0 (pd @0) radare disassemble from the start of the file (so it take the vaddr as offset and not the paddr). This problem is present in both 16 and 32 bits file, maybe i don't understand correctly how it's suppose to work.

**Comment by radare** [comment]
OMF G. waiting for travis

**Comment by radare** [comment]
oh noes. do not merge with master in a branch. ever. Can you please rebase and squash your commits to be just a single one on top of the current master, in order to do proper code review? thanks

**Comment by ampotos** [comment]
it's done.

**Comment by XVilka** [comment]
@ampotos still from master. Please create another branch next time. Because it will be a mess after radare2 will update master after your PR.

**Comment by radare** [comment]
Merged! time to fuzz that thing can you provide some tests for that new file format?

**Comment by radare** [comment]
I have changed the indentation of the whole commit because it was wrong. use tabs please and try to follow the syntax rules of the rest of the project

**Comment by radare** [comment]
Also, there was a missing return in a non-void function `ut64 r_bin_omf_get_paddr_sym(r_bin_omf_obj *obj, OMF_symbol *sym) {`

**Comment by radare** [comment]
Use spaces before every `(`

**Comment by radare** [comment]
Do not align local var names

**Comment by radare** [comment]
Use `R_NEW0` instead of R_NEW + memset

**Comment by ampotos** [comment]
I'm working on some test for redare2-regression.

**Comment by jvoisin** [comment]
Yay, an OMF loader! Thank you :)

**Comment by Maijin** [comment]
@ampotos added https://github.com/radare/radare2/wiki/Implementing-a-new-format

**Pull request closed without merging**
