### PR TITLE
Refactor nz assembler 

### PR DESCRIPTION
**Pull request by Svenito**
Beginning to refactor the handmade assembler to incorporate some concepts of the tab assembler with the hackability of the nz assembler.
The idea is that each instruction that takes arguments is handled by its own function. Instructions without arguments just resolve to hardcoded instructions for the lookup table. Special cases are also group 1 and group 2 instructions

http://www.sandpile.org/x86/opc_grp.htm

A further aim is to remove the tab assetmbler in order to reduce the number of assemblers that ship with r2.

Second PR

### CODE REVIEW

**Comment by Maijin** [comment]
ping

**Comment by Svenito** [comment]
Still in it. Holiday this week though, so won't get much done.

**Comment by Svenito** [comment]
Will squash when it passes

**Comment by Maijin** [comment]
Doesn't build on windows:
```
p/asm_x86_nz.o: In function `parseOpcode':
c:\projects\radare2-shvdd\libr\asm/p/asm_x86_nz.c:1692: undefined reference to `strndup'
collect2.exe: error: ld returned 1 exit status
make[3]: *** [libr_asm.dll] Error 1
make[3]: Leaving directory `/c/projects/radare2-shvdd/libr/asm'
```

Use `r_str_ndup `

**Comment by Svenito** [comment]
squashed

**Comment by Maijin** [comment]
I see stuff in travis that aren't fix via your r2r pr i.e feat_variables

**Comment by Svenito** [comment]
checking it out now

**Comment by alvarofe** [comment]
I attach a patch since i can't comment on github. Mostly the changes are coding style but in opjc i think you forgot to add `!` in strcmp (op.mnemonic, "jz") i added myself in the patch, but if that is the behavior intended just remove it
```
diff --git a/libr/asm/p/asm_x86_nz.c b/libr/asm/p/asm_x86_nz.c
index 3e86c74..6a6ad05 100644
--- a/libr/asm/p/asm_x86_nz.c
+++ b/libr/asm/p/asm_x86_nz.c
@@ -106,7 +106,9 @@ typedef struct Opcode_t {
 } Opcode;
 
 static ut8 getsib(const ut8 sib) {
-	if (!sib) return 0;
+	if (!sib) {
+		return 0;
+	}
 	return (sib & 0x8) ? 3 : getsib ((sib << 1) | 1) - 1;
 }
 
@@ -138,7 +140,8 @@ static int process_group_1(RAsm *a, ut8 *data, const Opcode op) {
 	}
 	immediate = op.operands[1].immediate * op.operands[1].sign;
 
-	if (op.operands[0].type & OT_DWORD || op.operands[0].type & OT_QWORD) {
+	if (op.operands[0].type & OT_DWORD || 
+		op.operands[0].type & OT_QWORD) {
 		data[l++] = (op.operands[1].immediate > 127) ? 0x81 : 0x83;
 	} else if (op.operands[0].type & OT_BYTE) {
 		if (immediate > 255 || immediate < -256) {
@@ -188,7 +191,9 @@ static int process_group_2(RAsm *a, ut8 *data, const Opcode op) {
 	int mod_byte = 0;
 	int reg0 = 0;
 
-	if (a->bits == 64) data[l++] = 0x48;
+	if (a->bits == 64) {
+		data[l++] = 0x48;
+	}
 
 	if (!strcmp (op.mnemonic, "rol")) {
 		modrm = 0;
@@ -252,14 +257,17 @@ static int process_1byte_op(RAsm *a, ut8 *data, const Opcode op, int op1) {
 	int rm = 0;
 	st32 offset = 0;
 
-	if (a->bits == 64 && ((op.operands[0].type & OT_QWORD) | (op.operands[1].type & OT_QWORD))) {
+	if (a->bits == 64 && 
+		((op.operands[0].type & OT_QWORD) | 
+		 (op.operands[1].type & OT_QWORD))) {
 		data[l++] = 0x48;
 	}
 
 	if (op.operands[0].type & OT_MEMORY && op.operands[1].type & OT_REGALL) {
 		if (op.operands[0].type & OT_BYTE && op.operands[1].type & OT_BYTE) {
 			data[l++] = op1;
-		} else if (op.operands[0].type & (OT_DWORD | OT_QWORD) && op.operands[1].type & (OT_DWORD | OT_QWORD)) {
+		} else if (op.operands[0].type & (OT_DWORD | OT_QWORD) && 
+				   op.operands[1].type & (OT_DWORD | OT_QWORD)) {
 			data[l++] = op1 + 0x1;
 		} else {
 			eprintf ("Error: mismatched operand sizes\n");
@@ -279,7 +287,8 @@ static int process_1byte_op(RAsm *a, ut8 *data, const Opcode op, int op1) {
 		if (op.operands[1].type & OT_MEMORY) {
 			if (op.operands[0].type & OT_BYTE && op.operands[1].type & OT_BYTE) {
 				data[l++] = op1 + 0x2;
-			} else if (op.operands[0].type & (OT_DWORD | OT_QWORD) && op.operands[1].type & (OT_DWORD | OT_QWORD)) {
+			} else if (op.operands[0].type & (OT_DWORD | OT_QWORD) && 
+					   op.operands[1].type & (OT_DWORD | OT_QWORD)) {
 				data[l++] = op1 + 0x3;
 			} else {
 				eprintf ("Error: mismatched operand sizes\n");
@@ -291,11 +300,14 @@ static int process_1byte_op(RAsm *a, ut8 *data, const Opcode op, int op1) {
 			if (op.operands[1].scale[0] > 1) {
 				if (op.operands[1].regs[1] != X86R_UNDEFINED) {
 					data[l++] = op.operands[0].reg << 3 | 4;
-					data[l++] = getsib (op.operands[1].scale[0]) << 6 | op.operands[1].regs[0] << 3 | op.operands[1].regs[1];
+					data[l++] = getsib (op.operands[1].scale[0]) << 6 | 
+										op.operands[1].regs[0] << 3 | 
+										op.operands[1].regs[1];
 					return l;
 				}
 				data[l++] = op.operands[0].reg << 3 | 4; // 4 = SIB
-				data[l++] = getsib (op.operands[1].scale[0]) << 6 | op.operands[1].regs[0] << 3 | 5;
+				data[l++] = getsib (op.operands[1].scale[0]) << 6 | 
+									op.operands[1].regs[0] << 3 | 5;
 				data[l++] = op.operands[1].offset * op.operands[1].offset_sign;
 				data[l++] = 0;
 				data[l++] = 0;
@@ -393,7 +405,9 @@ static int opsbb(RAsm *a, ut8 *data, const Opcode op) {
 static int opbswap(RAsm *a, ut8 *data, const Opcode op) {
 	int l = 0;
 	if (op.operands[0].type & OT_REGALL) {
-		if (op.operands[0].reg == X86R_UNDEFINED) {return -1;}
+		if (op.operands[0].reg == X86R_UNDEFINED) {
+			return -1;
+		}
 		data[l++] = 0x0f;
 		data[l++] = 0xc8 + op.operands[0].reg;
 	}
@@ -407,12 +421,16 @@ static int opcall(RAsm *a, ut8 *data, const Opcode op) {
 	int mod = 0;
 
 	if (op.operands[0].type & OT_GPREG) {
-		if (op.operands[0].reg == X86R_UNDEFINED) {return -1;}
+		if (op.operands[0].reg == X86R_UNDEFINED) {
+			return -1;
+		}
 		data[l++] = 0xff;
 		mod = 3;
 		data[l++] = mod << 6 | 2 << 3 | op.operands[0].reg;
 	} else if (op.operands[0].type & OT_MEMORY) {
-		if (op.operands[0].regs[0] == X86R_UNDEFINED) {return -1;}
+		if (op.operands[0].regs[0] == X86R_UNDEFINED) {
+			return -1;
+		}
 		data[l++] = 0xff;
 		offset = op.operands[0].offset * op.operands[0].offset_sign;
 		if (offset) {
@@ -498,9 +516,10 @@ static int opimul(RAsm *a, ut8 *data, const Opcode op) {
 			return -1;
 		}
 		immediate = op.operands[1].immediate * op.operands[1].sign;
-		if (a->bits == 64 && immediate > 4294967295) {data[l++] = 0x48;}
+		if (a->bits == 64 && immediate > 4294967295) {
+			data[l++] = 0x48;
+		}
 		if (op.operands[0].type & OT_GPREG) {
-
 			data[l++] = 0xb8 | op.operands[0].reg;
 			data[l++] = immediate;
 			data[l++] = immediate >> 8;
@@ -513,13 +532,11 @@ static int opimul(RAsm *a, ut8 *data, const Opcode op) {
 				data[l++] = immediate >> 56;
 			}
 		} else if (op.operands[0].type & OT_MEMORY) {
-
 			if (op.operands[0].type & OT_DWORD) {
 				data[l++] = 0xc7;
 			} else if (op.operands[0].type & OT_BYTE) {
 				data[l++] = 0xc6;
 			}
-
 			offset = op.operands[0].offset * op.operands[0].offset_sign;
 			if (offset) {
 				mod = (offset > 128 || offset < 129) ? 0x2 : 0x1;
@@ -532,8 +549,12 @@ static int opimul(RAsm *a, ut8 *data, const Opcode op) {
 			} else {
 				data[l++] = mod << 6 | op.operands[0].regs[0];
 			}
-			if (op.operands[0].regs[0] == X86R_ESP) data[l++] = 0x24;
-			if (op.operands[0].regs[0] == X86R_EBP && !offset) data[l++] = 0x00;
+			if (op.operands[0].regs[0] == X86R_ESP) {
+				data[l++] = 0x24;
+			}
+			if (op.operands[0].regs[0] == X86R_EBP && !offset) {
+				data[l++] = 0x00;
+			}
 			if (offset) {data[l++] = offset;}
 			if (mod == 2) {
 				data[l++] = offset >> 8;
@@ -547,8 +568,11 @@ static int opimul(RAsm *a, ut8 *data, const Opcode op) {
 				data[l++] = immediate >> 24;
 			}
 		}
-	} else if (op.operands[1].type & OT_GPREG && !(op.operands[1].type & OT_MEMORY)) {
-		if (a->bits == 64) {data[l++] = 0x48;}
+	} else if (op.operands[1].type & OT_GPREG && 
+			 !(op.operands[1].type & OT_MEMORY)) {
+		if (a->bits == 64) {
+			data[l++] = 0x48;
+		}
 		offset = op.operands[0].offset * op.operands[0].offset_sign;
 		data[l++] = (op.operands[0].type & OT_BYTE) ? 0x88 : 0x89;
 
@@ -571,10 +595,16 @@ static int opimul(RAsm *a, ut8 *data, const Opcode op) {
 				if (offset) {
 					mod = (offset > 128 || offset < 129) ? 0x2 : 0x1;
 				}
-				if (op.operands[0].regs[0] == X86R_EBP) mod = 0x2;
+				if (op.operands[0].regs[0] == X86R_EBP) {
+					mod = 0x2;
+				}
 				data[l++] = mod << 6 | op.operands[1].reg << 3 | op.operands[0].regs[0];
-				if (op.operands[0].regs[0] == X86R_ESP) data[l++] = 0x24;
-				if (offset) {data[l++] = offset;}
+				if (op.operands[0].regs[0] == X86R_ESP) {
+					data[l++] = 0x24;
+				}
+				if (offset) {
+					data[l++] = offset;
+				}
 				if (mod == 2) {
 					data[l++] = offset >> 8;
 					data[l++] = offset >> 16;
@@ -583,9 +613,12 @@ static int opimul(RAsm *a, ut8 *data, const Opcode op) {
 			}
 		}
 	} else if (op.operands[1].type & OT_MEMORY) {
-		if (a->bits == 64 && !(op.operands[1].regs[0] == X86R_RBP)) {data[l++] = 0x48;}
+		if (a->bits == 64 && !(op.operands[1].regs[0] == X86R_RBP)) {
+			data[l++] = 0x48;
+		}
 		offset = op.operands[1].offset * op.operands[1].offset_sign;
-		data[l++] = (op.operands[1].type & OT_BYTE || op.operands[0].type & OT_BYTE) ? 0x8a : 0x8b;
+		data[l++] = (op.operands[1].type & OT_BYTE || 
+					 op.operands[0].type & OT_BYTE) ? 0x8a : 0x8b;
 		if (op.operands[1].regs[0] == X86R_UNDEFINED) {
 			data[l++] = op.operands[0].reg << 3 | 0x5;
 			data[l++] = offset;
@@ -598,9 +631,11 @@ static int opimul(RAsm *a, ut8 *data, const Opcode op) {
 
 				if (op.operands[1].scale[0] > 2) base = 5;
 				if (base) {
-					data[l++] = getsib (op.operands[1].scale[0]) << 6 | op.operands[1].regs[0] << 3 | base;
+					data[l++] = getsib (op.operands[1].scale[0]) << 6 | 
+										op.operands[1].regs[0] << 3 | base;
 				} else {
-					data[l++] = getsib (op.operands[1].scale[0]) << 3 | op.operands[1].regs[0];
+					data[l++] = getsib (op.operands[1].scale[0]) << 3 | 
+										op.operands[1].regs[0];
 				}
 				if (offset || base) {
 					data[l++] = offset;
@@ -645,16 +680,19 @@ static int opin(RAsm *a, ut8 *data, const Opcode op) {
 	int l = 0;
 	st32 immediate = 0;
 	if (op.operands[1].reg == X86R_DX) {
-		if (op.operands[0].reg == X86R_AL && op.operands[0].type & OT_BYTE) {
+		if (op.operands[0].reg == X86R_AL && 
+			op.operands[0].type & OT_BYTE) {
 			data[l++] = 0xec;
 			return l;
 		}
-		if (op.operands[0].reg == X86R_AX && op.operands[0].type & OT_WORD) {
+		if (op.operands[0].reg == X86R_AX && 
+			op.operands[0].type & OT_WORD) {
 			data[l++] = 0x66;
 			data[l++] = 0xed;
 			return l;
 		}
-		if (op.operands[0].reg == X86R_EAX && op.operands[0].type & OT_DWORD) {
+		if (op.operands[0].reg == X86R_EAX && 
+			op.operands[0].type & OT_DWORD) {
 			data[l++] = 0xed;
 			return l;
 		}
@@ -663,12 +701,15 @@ static int opin(RAsm *a, ut8 *data, const Opcode op) {
 		if (immediate > 255 || immediate < -128) {
 			return -1;
 		}
-		if (op.operands[0].reg == X86R_AL && op.operands[0].type & OT_BYTE) {
+		if (op.operands[0].reg == X86R_AL && 
+			op.operands[0].type & OT_BYTE) {
 			data[l++] = 0xe4;
-		} else if (op.operands[0].reg == X86R_AX && op.operands[0].type & OT_BYTE) {
+		} else if (op.operands[0].reg == X86R_AX && 
+				   op.operands[0].type & OT_BYTE) {
 			data[l++] = 0x66;
 			data[l++] = 0xe5;
-		} else if (op.operands[0].reg == X86R_EAX && op.operands[0].type & OT_DWORD) {
+		} else if (op.operands[0].reg == X86R_EAX && 
+				   op.operands[0].type & OT_DWORD) {
 			data[l++] = 0xe5;
 		}
 		data[l++] = immediate;
@@ -744,25 +785,36 @@ static int opjc(RAsm *a, ut8 *data, const Opcode op) {
 	}
 	immediate -= 6;
 	data[l++] = 0x0f;
-	if (!strcmp (op.mnemonic, "ja") || !strcmp (op.mnemonic, "jnbe")) {
+	if (!strcmp (op.mnemonic, "ja") || 
+		!strcmp (op.mnemonic, "jnbe")) {
 		data[l++] = 0x87;
-	} else if (!strcmp (op.mnemonic, "jae") || !strcmp (op.mnemonic, "jnb") || !strcmp (op.mnemonic, "jnc")) {
+	} else if (!strcmp (op.mnemonic, "jae") || 
+			   !strcmp (op.mnemonic, "jnb") || 
+			   !strcmp (op.mnemonic, "jnc")) {
 		data[l++] = 0x83;
-	} else if (!strcmp (op.mnemonic, "jz") || !strcmp (op.mnemonic, "je")) {
+	} else if (!strcmp (op.mnemonic, "jz") || 
+			   !strcmp (op.mnemonic, "je")) {
 		data[l++] = 0x84;
-	} else if (!strcmp (op.mnemonic, "jb") || !strcmp (op.mnemonic, "jnae") || !strcmp (op.mnemonic, "jc")) {
+	} else if (!strcmp (op.mnemonic, "jb") || 
+			   !strcmp (op.mnemonic, "jnae") || 
+			   !strcmp (op.mnemonic, "jc")) {
 		data[l++] = 0x82;
-	} else if (!strcmp (op.mnemonic, "jbe") || !strcmp (op.mnemonic, "jna")) {
+	} else if (!strcmp (op.mnemonic, "jbe") || 
+			   !strcmp (op.mnemonic, "jna")) {
 		data[l++] = 0x86;
 	} else if (!strcmp (op.mnemonic, "jg")) {
 		data[l++] = 0x8f;
-	} else if (!strcmp (op.mnemonic, "jge") || !strcmp (op.mnemonic, "jnl")) {
+	} else if (!strcmp (op.mnemonic, "jge") || 
+			   !strcmp (op.mnemonic, "jnl")) {
 		data[l++] = 0x8d;
-	} else if (!strcmp (op.mnemonic, "jl") || !strcmp (op.mnemonic, "jnge")) {
+	} else if (!strcmp (op.mnemonic, "jl") || 
+			   !strcmp (op.mnemonic, "jnge")) {
 		data[l++] = 0x8c;
-	} else if (!strcmp (op.mnemonic, "jle") || !strcmp (op.mnemonic, "jng")) {
+	} else if (!strcmp (op.mnemonic, "jle") || 
+			   !strcmp (op.mnemonic, "jng")) {
 		data[l++] = 0x8e;
-	} else if (!strcmp (op.mnemonic, "jne") || !strcmp (op.mnemonic, "jnz")) {
+	} else if (!strcmp (op.mnemonic, "jne") || 
+			   !strcmp (op.mnemonic, "jnz")) {
 		data[l++] = 0x85;
 	} else if (!strcmp (op.mnemonic, "jno")) {
 		data[l++] = 0x81;
@@ -772,9 +824,12 @@ static int opjc(RAsm *a, ut8 *data, const Opcode op) {
 		data[l++] = 0x89;
 	} else if (!strcmp (op.mnemonic, "jo")) {
 		data[l++] = 0x80;
-	} else if (!strcmp (op.mnemonic, "jp") || !strcmp(op.mnemonic, "jpe")) {
+	} else if (!strcmp (op.mnemonic, "jp") || 
+			   !strcmp(op.mnemonic, "jpe")) {
 		data[l++] = 0x8a;
-	} else if (!strcmp (op.mnemonic, "js") || strcmp (op.mnemonic, "jz") || !strcmp (op.mnemonic, "jpo")) {
+	} else if (!strcmp (op.mnemonic, "js") || 
+			   !strcmp (op.mnemonic, "jz") || 
+			   !strcmp (op.mnemonic, "jpo")) {
 		data[l++] = 0x88;
 	}
 	data[l++] = immediate;
@@ -790,7 +845,8 @@ static int oplea(RAsm *a, ut8 *data, const Opcode op){
 	st32 offset = 0;
 	int reg = 0;
 	int rm = 0;
-	if(op.operands[0].type & OT_REGALL && op.operands[1].type & OT_MEMORY) {
+	if(op.operands[0].type & OT_REGALL && 
+	   op.operands[1].type & OT_MEMORY) {
 		data[l++] = 0x8d;
 		if (op.operands[1].regs[0] == X86R_UNDEFINED) {
 			data[l++] = op.operands[0].reg << 3 | 5;
@@ -880,19 +936,21 @@ static int opmov(RAsm *a, ut8 *data, const Opcode op) {
 			return -1;
 		}
 		immediate = op.operands[1].immediate * op.operands[1].sign;
-
-
-
-		if (op.operands[0].type & OT_GPREG && !(op.operands[0].type & OT_MEMORY)) {
-			if (a->bits == 64 && ((op.operands[0].type & OT_QWORD) | (op.operands[1].type & OT_QWORD))) {
+		if (op.operands[0].type & OT_GPREG && 
+		  !(op.operands[0].type & OT_MEMORY)) {
+			if (a->bits == 64 && 
+			   ((op.operands[0].type & OT_QWORD) | 
+			    (op.operands[1].type & OT_QWORD))) {
 				data[l++] = 0x48;
 			}
 			if (op.operands[0].type & OT_BYTE) {
 				data[l++] = 0xb0 | op.operands[0].reg;
 				data[l++] = immediate;
 			} else {
-				if (a->bits == 64 && ((op.operands[0].type & OT_QWORD) | (op.operands[1].type & OT_QWORD))
-					&& immediate < UT32_MAX) {
+				if (a->bits == 64 && 
+					((op.operands[0].type & OT_QWORD) | 
+					 (op.operands[1].type & OT_QWORD)) && 
+					 immediate < UT32_MAX) {
 						data[l++] = 0xc7;
 				 		data[l++] = 0xc0 | op.operands[0].reg;
 				} else {
@@ -910,7 +968,9 @@ static int opmov(RAsm *a, ut8 *data, const Opcode op) {
 				}
 			}
 		} else if (op.operands[0].type & OT_MEMORY) {
-			if (a->bits == 64 && !(op.operands[0].type & OT_QWORD)) {data[l++] = 0x67;}
+			if (a->bits == 64 && !(op.operands[0].type & OT_QWORD)) {
+				data[l++] = 0x67;
+			}
 			if (op.operands[0].type & (OT_DWORD | OT_QWORD)) {
 				data[l++] = 0xc7;
 			} else if (op.operands[0].type & OT_BYTE) {
@@ -929,9 +989,15 @@ static int opmov(RAsm *a, ut8 *data, const Opcode op) {
 			} else {
 				data[l++] = mod << 6 | op.operands[0].regs[0];
 			}
-			if (op.operands[0].regs[0] == X86R_ESP) data[l++] = 0x24;
-			if (op.operands[0].regs[0] == X86R_EBP && !offset) data[l++] = 0x00;
-			if (offset) {data[l++] = offset;}
+			if (op.operands[0].regs[0] == X86R_ESP) {
+				data[l++] = 0x24;
+			}
+			if (op.operands[0].regs[0] == X86R_EBP && !offset) {
+				data[l++] = 0x00;
+			}
+			if (offset) {
+				data[l++] = offset;
+			}
 			if (mod == 2) {
 				data[l++] = offset >> 8;
 				data[l++] = offset >> 16;
@@ -944,14 +1010,20 @@ static int opmov(RAsm *a, ut8 *data, const Opcode op) {
 				data[l++] = immediate >> 24;
 			}
 		}
-	} else if (op.operands[1].type & OT_GPREG && !(op.operands[1].type & OT_MEMORY)) {
-		if (op.operands[0].type & OT_CONSTANT) {return -1;}
-		if (a->bits == 64) {data[l++] = 0x48;}
+	} else if (op.operands[1].type & OT_GPREG && 
+			 !(op.operands[1].type & OT_MEMORY)) {
+		if (op.operands[0].type & OT_CONSTANT) {
+			return -1;
+		}
+		if (a->bits == 64) {
+			data[l++] = 0x48;
+		}
 		offset = op.operands[0].offset * op.operands[0].offset_sign;
 		data[l++] = (op.operands[0].type & OT_BYTE) ? 0x88 : 0x89;
 
 		if (!(op.operands[0].type & OT_MEMORY)) {
-			if (op.operands[0].reg == X86R_UNDEFINED || op.operands[1].reg == X86R_UNDEFINED) {
+			if (op.operands[0].reg == X86R_UNDEFINED || 
+				op.operands[1].reg == X86R_UNDEFINED) {
 				return -1;
 			}
 			mod = 0x3;
@@ -972,10 +1044,16 @@ static int opmov(RAsm *a, ut8 *data, const Opcode op) {
 				if (offset) {
 					mod = (offset > 128 || offset < 129) ? 0x2 : 0x1;
 				}
-				if (op.operands[0].regs[0] == X86R_EBP) mod = 0x2;
+				if (op.operands[0].regs[0] == X86R_EBP) {
+					mod = 0x2;
+				}
 				data[l++] = mod << 6 | op.operands[1].reg << 3 | op.operands[0].regs[0];
-				if (op.operands[0].regs[0] == X86R_ESP) data[l++] = 0x24;
-				if (offset) {data[l++] = offset;}
+				if (op.operands[0].regs[0] == X86R_ESP) {
+					data[l++] = 0x24;
+				}
+				if (offset) {
+					data[l++] = offset;
+				}
 				if (mod == 2) {
 					data[l++] = offset >> 8;
 					data[l++] = offset >> 16;
@@ -984,9 +1062,13 @@ static int opmov(RAsm *a, ut8 *data, const Opcode op) {
 			}
 		}
 	} else if (op.operands[1].type & OT_MEMORY) {
-		if (a->bits == 64 && !(op.operands[1].regs[0] == X86R_RBP)) {data[l++] = 0x48;}
+		if (a->bits == 64 && !(op.operands[1].regs[0] == X86R_RBP)) {
+			data[l++] = 0x48;
+		}
 		offset = op.operands[1].offset * op.operands[1].offset_sign;
-		data[l++] = (op.operands[1].type & OT_BYTE || op.operands[0].type & OT_BYTE) ? 0x8a : 0x8b;
+		data[l++] = (op.operands[1].type & OT_BYTE || 
+					op.operands[0].type & OT_BYTE) ? 
+					0x8a : 0x8b;
 		if (op.operands[1].regs[0] == X86R_UNDEFINED) {
 			data[l++] = op.operands[0].reg << 3 | 0x5;
 			data[l++] = offset;
@@ -996,8 +1078,9 @@ static int opmov(RAsm *a, ut8 *data, const Opcode op) {
 		} else {
 			if (op.operands[1].scale[0] > 1) {
 				data[l++] = op.operands[0].reg << 3 | 4;
-
-				if (op.operands[1].scale[0] > 2) base = 5;
+				if (op.operands[1].scale[0] > 2) {
+					base = 5;
+				}
 				if (base) {
 					data[l++] = getsib (op.operands[1].scale[0]) << 6 | op.operands[1].regs[0] << 3 | base;
 				} else {
@@ -1164,7 +1247,7 @@ static int opout(RAsm *a, ut8 *data, const Opcode op) {
 }
 
 static int opret(RAsm *a, ut8 *data, const Opcode op) {
-	int l =0;
+	int l = 0;
 	int immediate = 0;
 	 if (op.operands[0].type == OT_UNKNOWN) {
 		data[l++] = 0xc3;
@@ -1178,7 +1261,7 @@ static int opret(RAsm *a, ut8 *data, const Opcode op) {
 }
 
 static int opretf(RAsm *a, ut8 *data, const Opcode op) {
-	int l =0;
+	int l = 0;
 	st32 immediate = 0;
 	if (op.operands[0].type & OT_CONSTANT) {
 		immediate = op.operands[0].immediate * op.operands[0].sign;
@@ -1192,43 +1275,58 @@ static int opretf(RAsm *a, ut8 *data, const Opcode op) {
 }
 
 static int opset(RAsm *a, ut8 *data, const Opcode op) {
-	if (!(op.operands[0].type & (OT_GPREG | OT_BYTE))) {return -1;}
 	int l = 0;
-	int mod = 0;
-	int reg = op.operands[0].regs[0];
-
+	int reg, mod = 0;
+	if (!(op.operands[0].type & (OT_GPREG | OT_BYTE))) {
+		return -1;
+	}
+	reg = op.operands[0].regs[0];
 	data[l++] = 0x0f;
 	if (!strcmp (op.mnemonic, "seto")) {
 		data[l++] = 0x90;
 	} else if (!strcmp (op.mnemonic, "setno")) {
 		data[l++] = 0x91;
-	} else if (!strcmp (op.mnemonic, "setb") || !strcmp (op.mnemonic, "setnae") || !strcmp (op.mnemonic, "setc")) {
+	} else if (!strcmp (op.mnemonic, "setb") || 
+			  !strcmp (op.mnemonic, "setnae") || 
+			  !strcmp (op.mnemonic, "setc")) {
 		data[l++] = 0x92;
-	} else if (!strcmp (op.mnemonic, "setnb") || !strcmp (op.mnemonic, "setae") || !strcmp (op.mnemonic, "setnc")) {
+	} else if (!strcmp (op.mnemonic, "setnb") || 
+			   !strcmp (op.mnemonic, "setae") || 
+			   !strcmp (op.mnemonic, "setnc")) {
 		data[l++] = 0x93;
-	} else if (!strcmp (op.mnemonic, "setz") || !strcmp (op.mnemonic, "sete")) {
+	} else if (!strcmp (op.mnemonic, "setz") || 
+			   !strcmp (op.mnemonic, "sete")) {
 		data[l++] = 0x94;
-	} else if (!strcmp (op.mnemonic, "setnz") || !strcmp (op.mnemonic, "setne")) {
+	} else if (!strcmp (op.mnemonic, "setnz") || 
+			   !strcmp (op.mnemonic, "setne")) {
 		data[l++] = 0x95;
-	} else if (!strcmp (op.mnemonic, "setbe") || !strcmp (op.mnemonic, "setna")) {
+	} else if (!strcmp (op.mnemonic, "setbe") || 
+			   !strcmp (op.mnemonic, "setna")) {
 		data[l++] = 0x96;
-	} else if (!strcmp (op.mnemonic, "setnbe") || !strcmp (op.mnemonic, "seta")) {
+	} else if (!strcmp (op.mnemonic, "setnbe") || 
+			   !strcmp (op.mnemonic, "seta")) {
 		data[l++] = 0x97;
 	} else if (!strcmp (op.mnemonic, "sets")) {
 		data[l++] = 0x98;
 	} else if (!strcmp (op.mnemonic, "setns")) {
 		data[l++] = 0x99;
-	} else if (!strcmp (op.mnemonic, "setp") || !strcmp (op.mnemonic, "setpe")) {
+	} else if (!strcmp (op.mnemonic, "setp") || 
+			   !strcmp (op.mnemonic, "setpe")) {
 		data[l++] = 0x9a;
-	} else if (!strcmp (op.mnemonic, "setnp") || !strcmp (op.mnemonic, "setpo")) {
+	} else if (!strcmp (op.mnemonic, "setnp") || 
+			   !strcmp (op.mnemonic, "setpo")) {
 		data[l++] = 0x9b;
-	} else if (!strcmp (op.mnemonic, "setl") || !strcmp (op.mnemonic, "setnge")) {
+	} else if (!strcmp (op.mnemonic, "setl") || 
+			   !strcmp (op.mnemonic, "setnge")) {
 		data[l++] = 0x9c;
-	} else if (!strcmp (op.mnemonic, "setnl") || !strcmp (op.mnemonic, "setge")) {
+	} else if (!strcmp (op.mnemonic, "setnl") || 
+			   !strcmp (op.mnemonic, "setge")) {
 		data[l++] = 0x9d;
-	} else if (!strcmp (op.mnemonic, "setle") || !strcmp (op.mnemonic, "setng")) {
+	} else if (!strcmp (op.mnemonic, "setle") || 
+			   !strcmp (op.mnemonic, "setng")) {
 		data[l++] = 0x9e;
-	} else if (!strcmp (op.mnemonic, "setnle") || !strcmp (op.mnemonic, "setg")) {
+	} else if (!strcmp (op.mnemonic, "setnle") || 
+			   !strcmp (op.mnemonic, "setg")) {
 		data[l++] = 0x9f;
 	} else {
 		return -1;
@@ -1247,7 +1345,9 @@ static int optest(RAsm *a, ut8 *data, const Opcode op) {
 		eprintf ("Error: Invalid operands\n");
 		return -1;
 	}
-	if (a->bits == 64) 	data[l++] = 0x48;
+	if (a->bits == 64) {
+		data[l++] = 0x48;
+	}
 
 	if (op.operands[1].type & OT_CONSTANT) {
 		if (op.operands[0].type & OT_BYTE) {
@@ -1302,13 +1402,16 @@ static int opxchg(RAsm *a, ut8 *data, const Opcode op) {
 			}
 		}
 	} else {
-		if (op.operands[0].reg == X86R_EAX && op.operands[1].type & OT_GPREG) {
+		if (op.operands[0].reg == X86R_EAX && 
+			op.operands[1].type & OT_GPREG) {
 			data[l++] = 0x90 + op.operands[1].reg;
 			return l;
-		} else if (op.operands[1].reg == X86R_EAX && op.operands[0].type & OT_GPREG) {
+		} else if (op.operands[1].reg == X86R_EAX && 
+				   op.operands[0].type & OT_GPREG) {
 			data[l++] = 0x90 + op.operands[0].reg;
 			return l;
-		} else if (op.operands[0].type & OT_GPREG && op.operands[1].type & OT_GPREG) {
+		} else if (op.operands[0].type & OT_GPREG && 
+				   op.operands[1].type & OT_GPREG) {
 			mod_byte = 3;
 			data[l++] = 0x87;
 			reg = op.operands[1].reg;

```

**Comment by Svenito** [comment]
thanks for the review. Will apply patch and update PR

**Comment by Svenito** [comment]
Fixed one last issue and addressed the review comment

**Comment by Maijin** [comment]
Doesn't build on OSX.

**Pull request merged**
