### PR TITLE
Russian translation for interactive help in radare2's shell

### PR DESCRIPTION
**Pull request by Ctarley**
Translated to russian description of interactive help commands in radare2's shell (?, c?, T?, ...)
Base: 1.4.0 tag

### CODE REVIEW

**Comment by radare** [comment]
why? :D

**Comment by Ctarley** [comment]
it was needed for my project, and i think maybe it is useful for smb

**Comment by radare** [comment]
translating a whole project inline like this is useless because it can't be maintained or changed to other languages neither at runtime or compile time. in fact your pr cant be merged because it have conflicts with master.

One possible solution to this that comes to my mind would be to make a radare2-translation project that can be executed before compilation to change strings matching in sources for others in a different language. So people wanting to translate or use r2 in a different language can do it. But i have no plans into adding support for runtime language change

**Comment by Ctarley** [comment]
"your pr cant be merged because it have conflicts with master"
yes, i understand it. My idea is simple - i've done translation, and pulled here, because smb is needed release version of r2 with russian language. (How many years ago, when you could download relevant version without translation or old with it...)

There is only one way to use it - compile this branch "as is" and get 1.4.0 with russian translations. So if you are needn't it, let's close this pull.

**Comment by radare** [comment]
Im preparing the scripts to make translations maintainable. Please hold on and you may want to update your pr to work like this

**Comment by radare** [comment]
Please submit your translation here: https://github.com/radare/radare2-translations

**Comment by jjdredd** [comment]
I'll just leave this here
https://www.gnu.org/software/gettext/manual/html_node/index.html#Top

**Comment by radare** [comment]
Read about the speed of grep with gettext and without ;)

Gettext is BLOATED. It requires accessibg disk and quieryijg a hashtable everytime you show a string. Im not gonna support this because i think only english makes sense to maintain, and if theres ppl willing to to translate this sed scripts are way more maintainable than patching the whole codebase and it just works at compile time. And its driven by an external repo sonwe dont mess master codebase with those wip translations.

In case of willing to switch to gettext one day.. or reimplement our own gettext on top of sdb which imho makes more sense we can reuse the results of the sed scripts to autogenerate those string translation databases. Also bear in mind that r2 contains A LOT of strings, and we should improve into reducing them to reduce final binary size. sed allows to replace similar strings in just 1 shot instead of having to create more entried because the while string doesnt matches or contains format strings.

Ive been always against locales, but if people is willing to contribute this is the less damaging option imho.

**Pull request closed without merging**
