### PR TITLE
Fix #14499: Detect ascii substrings

### LINKED ISSUE #14499: Missing strings in rabin2 -zz
**Is your feature request related to a problem? Please describe.**

The following malware contains strings that aren't found by rabin2 -zz
Password "infected"

[Reborn.zip](https://github.com/radare/radare2/files/3364960/Reborn.zip) 

```
556938:http://pomf.cat/upload.php
557277:https://a.pomf.cat/
564205:http://pomf.cat/upload.php
564258:https://a.pomf.cat/
```

**Describe the solution you'd like**
For UI requests, don't hesitate to post some draws.

rabin2 -zz find the strings and display them

via @futex

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
pascal strings should be like this:

[len][str]

so we can chk if len == strlen(str) and take those strings as valid, that may reduce false positives

**Comment by kazarmy** [comment]
how many bytes is the [len]?

**Comment by kazarmy** [comment]
ok the strings in #14499 appear to use 1 byte for the [len], but if the strings don't have null terminators, how do i do strlen(str)?

**Comment by kazarmy** [comment]
ok the strings in #14499 appear to use 1 byte for the [len], but if a string doesn't have a null terminator, how do i do strlen(str)?

**Comment by kazarmy** [comment]
and not every wide string is a pascal string

**Comment by kazarmy** [comment]
tbh this pr could just be a longwinded way of defaulting `bin.str.validchars` (#14503) to `ascii`

**Comment by kazarmy** [comment]
... for wide strings

**Comment by kazarmy** [comment]
Closing since #14503 (after defaulting to `ascii`) appears to be the best way to fix #14499.

**Comment by kazarmy** [comment]
On second thought...

**Comment by kazarmy** [comment]
now i think this pr is better than #14503 because the ascii-only constraint can only affect wide16 strings

**Comment by kazarmy** [comment]
ok to merge?

**Pull request merged**
