### PR TITLE
Colorize function arguments

### LINKED ISSUE #10614: Coloring of arguments and variables
In the visual mode make the output like
```
arg int arg_5h @rbp+0x5
```
colored with different colors - `arg` word with one, `int arg5h` with another and `@rbp+0x5` - with a 3rd color.
```
[0x00003ea0 10% 280 /bin/ls]> pd $r @ main                                                                                                                                                                                                   
┌ (fcn) main 3483                                                                                                                                                                                                                            
│   main (int arg1, int arg2, int arg_5h);                                                                                                                                                                                                   
│           ; arg int arg_5h @ rbp+0x5                                                                                                                                                                                                       
│           ; var int local_8h @ rsp+0x8                                                                                                                                                                                                     
│           ; var int local_17h @ rsp+0x17                                                                                                                                                                                                   
│           ; var char *local_28h @ rsp+0x28                                                                                                                                                                                                 
│           ; var size_t local_30h @ rsp+0x30                                                                                                                                                                                                
│           ; var int local_32h @ rsp+0x32                                                                                                                                                                                                   
│           ; var int local_38h @ rsp+0x38                                                                                                                                                                                                   
│           ; var char *s1 @ rsp+0x45                                                                                                                                                                                                        
│           ; var int local_46h @ rsp+0x46                                                                                                                                                                                                   
│           ; var int local_47h @ rsp+0x47                                                                                                                                                                                                   
│           ; var int local_48h @ rsp+0x48                                                                                                                                                                                                   
│           ; arg int arg1 @ rdi                                                                                                                                                                                                             
│           ; arg int arg2 @ rsi                                                                                                                                                                                                             
│           ; STRING XREF from 0x0000591d (entry0)                                                                                                                                                                                           
│           0x00003ea0      f30f1efa       endbr64                                                                                                                                                                                           
│           0x00003ea4      4157           push r15                                                                                                                                                                                          
│           0x00003ea6      4156           push r14                                                                                                                                                                                          
│           0x00003ea8      4155           push r13 
```

### PR DESCRIPTION
**Pull request by cyanpencil**
Closes #10614

image

They are governed by config variable `scr.color.args`
Their palette names are `func_arg`, `func_arg_type`, `func_arg_addr`.

Please say here if you do not agree with the defaults I chose (I did not spend too much time selecting them), or you think they should be given a different name.

### CODE REVIEW

**Comment by radare** [comment]
Update the themes

**Comment by XVilka** [comment]
@cyanpencil what about reusing the same color also in the comments which mark types of the argument?

**Comment by sivaramaaa** [comment]
```
0x00004049      488d3de84501.  lea rdi, ["COLUMNS"]        ; str.COLUMNS ; 0x18638 ; const char *name
```
But there is on problem though . not all type/name are mapped with variable, also the address where the comment is present and address where var is accesed could be different , so it would be difficult to find the address of instruction having this comment and map with the variables

**Comment by XVilka** [comment]
@sivaramaaa this is true, but I am not suggesting to map them somehow, I suggest just to use the same color from the theme

**Comment by sivaramaaa** [comment]
ah i get it , cool :+1:

**Comment by radare** [comment]
+1 on reusing. Otherwise doing themes is boring

**Comment by cyanpencil** [comment]
> Update the themes

@radare what do you mean by that? There are way too many themes to update manually, and I have no idea on which colors to use to be consistent with those...
Maybe I could do only the most common ones (the white / dark theme presets)

> what about reusing the same color also in the comments which mark types of the argument

@XVilka Ok, will do it, shouldn't be hard. Do you think I should also color variable names in disasm with the same color as in the function beginning? Like  `local_48h` in here:
`|           0x000035df      4889442448     mov qword [local_48h], rax                                           
`
which as of now is colored with the same color of the registers

**Comment by XVilka** [comment]
@cyanpencil make it white color for those themes you don't care, so ppl will send a fixes eventually.

Regarding variable names in the disasm - good idea too.

**Comment by radare** [comment]
if you reuse another color theres no need to change all the themes

**Comment by cyanpencil** [comment]
I think @XVilka was suggesting the opposite: to reuse the new introduced colors `func_*` in disasm where necessary, not to reuse disasm colors in function arguments @radare 

If you think we shouldn't introduce new colors at all, please state so bc then I'll have to change back a part of the pr

**Comment by radare** [comment]
if func* ones are already there you are reusing them :P i just dont wanna have over 9000 options for colors, we must find a balance

**Comment by radare** [comment]
nvm, do you want to update the themes in this PR?, as long as none have it yep it is a save merge. But we must have the themes updated before 2.8

**Pull request merged**
