### PR TITLE
Adding some more types

### PR DESCRIPTION
**Pull request by oddcoder**
just needed it for a ctf events so I got an idea of adding those I need
once I need them and eventually all common functions of libc will be
added

Signed-off-by: oddcoder <ahmedsoliman@oddcoder.com>

### CODE REVIEW

**Comment by radare** [comment]
I would prefer if we maintain just a .h and all thise types get autogenerated from there. But its ok for now

**Comment by Maijin** [comment]
It's impossible until TCC is fixed

**Comment by Maijin** [comment]
https://hackmd.io/OwNmE5gEwZhhaAjAMwAzPgFgKYGMPgwjjzC5TjJSrQBG2ATEA===

**Comment by radare** [comment]
What is broken in tcc?

**Comment by Maijin** [comment]
https://hackmd.io/OwNmE5gEwZhhaAjAMwAzPgFgKYGMPgwjjzC5TjJSrQBG2ATEA===

**Pull request merged**
