### PR TITLE
Refactor Meson project files for r_anal and r_asm

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by xarkes** [comment]
Ah. Is that what we want? From what I understand, this will generate many libraries.
Not sure if it's the way to go. Thoughts?

**Comment by xarkes** [comment]
Plus yeah, each library only has one object file if I understood correctly... I think that the best was to add the `.c` file in both `asm` and `anal` directories, rather than doing many libs.

**Comment by radare** [comment]
why not put this in the same pr as the fix-ios-sdk one? worried about conflicts or red states

**Comment by xarkes** [comment]
That's what he does:
> pelijah wants to merge 1 commit into radare:fix-ios-sdk from pelijah:meson_refactor

**Comment by radare** [comment]
Uh magic

**Comment by radare** [comment]
please rebase

**Comment by radare** [comment]
thanks

**Pull request merged**
