### PR TITLE
Fix #1118

### LINKED ISSUE #1118: Add option to show hex value in invalid instructions
For example
```
> pd 1
invalid
> e asm.invoff=true
> pd 1
0x8047570
```

This is done by gnu-mips disassembler, and it would be good to have this option all over the rest of the disasm plugins for free. Capstone is not going to add this option in his library, so it's up to us to do it in our side to make it work on all plugins.

### PR DESCRIPTION
**Pull request by alvarofe**
I'll wait to travis to see if this break something.

Let me know @radare if this was more or less your solution for this. I don't know if all the archs write in buf_asm invalid or undefined. If that is not the case I will review each one to make that generic across all archs.

### CODE REVIEW

**Comment by jvoisin** [comment]
`if (strstr (ds->asmop.buf_asm, "invalid") || strstr (ds->asmop.buf_asm, "INVALID")) {` could be replaced with `if (r_case_strstr (ds->asmop.buf_asm, "invalid"))` :)

**Comment by alvarofe** [comment]
Updated. Thanks @jvoisin :)

**Comment by radare** [comment]
That issue have some issues.. Or questions to solve. Lets enumerate in order to discuss them properly.

* al disassemblers should display the same string when the instruction is invalid. Otherwise we will be comparing to different strings which is a mess. One option would be to output an empty string. In that case the asm library will fill it with "invalid" or "0x72837273" in case the user wants to get pointers.

* this means that all disassemblers should work in a similar way. This requires reviewing the code of all of them. Maybe updating the code from upstream before doing changes.

* some plugins just return a differen number of length. But this is also invonsistent. Because error code is not the same as instruction length. and this causes some incomsistencies between plugins.

* this can be noticeable by the analysis and linear disassembly. Because for example, on arm. An invalid instruction is of 4 byte length. But on thumb it depends on the alignment of the address. And on x86 we asume its 1 byte lengthz

* this discussion can be probably merged with the one that aims to add min/max instruction length for each asm plugin.

* invalid instruxtions must be also be analyzed properly. This is. Many disassemblers show "invalid" for a specific sequence of bytes, but yhe analysis doesnt do this. If we specify that standard of empty string we can take that assumption in the analysis and mark them as invalid.

* when the instruction is invalid. The numeric value will be pased by rparse to replace it with the flagname of choice. This is very useful whena nalyzing mips or arm code because code is mixed with data and function and string pointers are marked as invalid instructions.

* i added a feature into capstone that can detect priviledged instructions and mark them acordingly. This can be useful, because those instructions are invalid on usermode. And will reduce the instructionset in order to catch more pointers like this.

* will be good to confirm all those cases using test cases.

**Comment by radare** [comment]
ping @jvoisin @alvarofe

**Comment by alvarofe** [comment]
Close this PR. As soon as I have the changes I'll make another pr. Sorry for the delays but not much time lately :(

**Pull request closed without merging**
