### PR TITLE
Cs?

### PR DESCRIPTION
**Pull request by kazarmy**
No tests since it's just a help message.

### CODE REVIEW

**Comment by Maijin** [comment]
image

Why would I check Cs? for getting Cz help ?

**Comment by kazarmy** [comment]
> for getting Cz help ?

Yep.

**Comment by kazarmy** [comment]
Can I remove `Cz` and replace it with `Csg` (where `g` stands for "guess")?

**Comment by XVilka** [comment]
@kazarmy renaming it surely better than referencing one command from another.

**Comment by kazarmy** [comment]
> @kazarmy renaming it surely better than referencing one command from another.

Might alias `Cz` with `Csg` after #8630 goes through. I didn't write the code for `Cz`.

**Pull request merged**
