### PR TITLE
Add spr32d70 and gsprop32 sdb for issue 5486

### PR DESCRIPTION
**Pull request by DanTheColoradan**
As per Maijin's request, I have added two out of the three dlls
I need to run radare2 on an exe I'm trying to disassemble. I was
unable to get any useful function exports for the third file,
mfc90u. Partially ddresses issue #5486.

@Maijin, I don't believe I need to add these files to the makefile,
but if I do, let me know how and I'll add another commit with it.

### CODE REVIEW

**Comment by radare** [comment]
The makefile must be updated to point to those files

**Comment by radare** [comment]
(i did it after merging)

**Comment by DanTheColoradan** [comment]
Thanks! I see the makefile now and will update it accordingly next time.

**Comment by Maijin** [comment]
Thanks !

**Pull request merged**
