### PR TITLE
Fix #13190 - remove sz from classlisting

### LINKED ISSUE #13190: change the (sz %d) thing from classlisting because its bad for grepping, just show the size is enough imho
```
$ git diff
diff --git a/libr/core/cbin.c b/libr/core/cbin.c
index 7d1faad87..7483bc9fe 100644
--- a/libr/core/cbin.c
+++ b/libr/core/cbin.c
@@ -2943,7 +2943,7 @@ static int bin_classes(RCore *r, int mode) {
                        }
                } else {
                        int m = 0;
-                       r_cons_printf ("0x%08"PFMT64x" [0x%08"PFMT64x" - 0x%08"PFMT64x"] (sz %"PFMT64d") class %d %s",
+                       r_cons_printf ("0x%08"PFMT64x" [0x%08"PFMT64x" - 0x%08"PFMT64x"] %6"PFMT64d" class %d %s",
                                c->addr, at_min, at_max, (at_max - at_min), c->index, c->name);
                        if (c->super) {
                                r_cons_printf (" super: %s\n", c->super);
```

### PR DESCRIPTION
**Pull request by c-urly**
deleted the "sz" from classlisting.

### CODE REVIEW

**Comment by ret2libc** [comment]
What are the reasons for this?

**Comment by radare** [comment]
Ease the grepping, and remove clutter

**Comment by radare** [comment]
If we all agree the new output looks better it may just update the tests and it can be merged.

**Comment by c-urly** [comment]
For tarvis to succeed we have to remove "sz" from test suite?

**Comment by ret2libc** [comment]
oki

**Comment by radare** [comment]
Use bin/r2r.js -i ...

Fix the outputs , submit a pr in r2r with the same name as this one and rebase this pr to get travis rerun the thing

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
please send a pr in r2r and rebase

**Comment by radare** [comment]
ping

**Pull request merged**
