### PR TITLE
Improvement of iI for PE with signatures + refactoring

### PR DESCRIPTION
**Pull request by wargio**
Added signed to RBinInfo
Added PE signature boolean
Refactoring of pkcs7 variable name, to avoid confusion.

### CODE REVIEW

**Comment by wargio** [comment]
@Maijin

**Comment by wargio** [comment]
travis will fail if those regressions tests will not be applied.

**Comment by Maijin** [comment]
Still something wrong, the `iI` should only be displayed for PE check this PR https://github.com/radare/radare2/commit/4d7767883b72aabe3f4950e3a22ae2e843245941

image

**Comment by wargio** [comment]
doesn't seems to be a bug i've introduced.
Even travis says that.
if i use that core file with `iI` it crashes due garbage in the memory.
the structure seems to be badly allocated.

**Comment by Maijin** [comment]
What the bug is not on crash, it's on "signed - false"

**Comment by wargio** [comment]
There is a PR on r2r for that

**Comment by Maijin** [comment]
Nop this is different.

**Pull request merged**
