### PR TITLE
Added custom tab to sdb json_indent function

### PR DESCRIPTION
**Pull request by xarkes**
Cf https://github.com/radare/radare2/pull/7043 and https://github.com/radare/radare2/issues/7016

### CODE REVIEW

**Comment by radare** [comment]
This pullreq must go into the sdb repo. Not our local copy

**Comment by Maijin** [comment]
At least we know which tests are broken 👍

**Comment by radare** [comment]
send the pullreq here https://github.com/radare/sdb/pulls

**Comment by radare** [comment]
please update tests

**Comment by xarkes** [comment]
See https://github.com/radare/sdb/pull/129 and https://github.com/radare/radare2-regressions/pull/762

**Pull request merged**
