### PR TITLE
core/graph: use pD instead of pI to display comments and fcn info

### PR DESCRIPTION
**Pull request by ret2libc**
core/disasm: fix some printing things

Some things I need to implement https://github.com/radare/radare2/issues/2907

### CODE REVIEW

**Comment by ret2libc** [comment]
screen shot 2015-10-04 at 14 43 26

**Comment by crowell** [comment]
:open_mouth: :dancers: 

looks amazing

**Comment by radare** [comment]
Is this optional? Nodes can be huge this way. I alread tried several alternatives to plain pd.

**Comment by ret2libc** [comment]
IT can be disabled with asm.comments false, but the default is on
Il 04/ott/2015 18:26, "radare" <notifications@github.com> ha scritto:

**Comment by crowell** [comment]
this breaks `toggle disasm mode`

see ascii enema
https://asciinema.org/a/anix7d793ci1ygzvhizafubzv

comments/etc are missing when addresses are shown.

**Comment by ret2libc** [comment]
screen shot 2015-10-06 at 15 21 58

@crowell I've fixed the other disasm mode in the graph. 
@pancake, the only test that is failing is already fixed in a PR for r2r, so for me we can merge this patch.

**Comment by radare** [comment]
lgtm, merge it yourself (with cherry-pick and such)

**Comment by radare** [comment]
lgtm feel free to merge yourself

**Comment by radare** [comment]
merged

**Comment by alvarofe** [comment]
@ret2libc when changing e asm.comments is not redraw https://asciinema.org/a/1lr24c5mhkca6mkatqiz8r6hj

**Pull request closed without merging**
