### PR TITLE
asm.cmt.fcnrefs: Show name/flag of function ref in disasm (true, false, nodup)

### PR DESCRIPTION
**Pull request by kazarmy**
Separate config var so that i can disable it in Visual mode specifically for functions.

### CODE REVIEW

**Comment by radare** [comment]
funrefs?

**Comment by kazarmy** [comment]
sorry, fcnrefs

**Comment by radare** [comment]
What are fcnrefs? Xrefs?

**Comment by ret2libc** [comment]
Can you provide a before/after example?

**Comment by kazarmy** [comment]
Hmm maybe i don't need to bother with the config var after all.

**Pull request closed without merging**
