### PR TITLE
Put flag cmt first and show it only once

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by kazarmy** [comment]
Will fix related tests, hopefully soon.

**Comment by radare** [comment]
Yep waiting for them. Also there are dupped offsets

**Comment by kazarmy** [comment]
Offsets may or may not have leading zeros, and haven't yet figured out the most efficient way to compare them.

**Comment by radare** [comment]
Addresses have leading zeroes and values does not. But i think we should just have a generic way to push comments in a list and that generic code should avoid dupes in a single place.. this way it will be easier to control boundaries of comments and reorder them if needed

**Comment by kazarmy** [comment]
See #7398. Not using leading zeros in the comments to save column space.

**Pull request merged**
