### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by thestr4ng3r**
first step for #10546

Changelog is huge, the most significant additions are in `libr/include/r_util/r_log.h`, `libr/util/log.c` and `libr/cons/cons.c`. The rest is just replacing eprintf with R_LOGFI.

### CODE REVIEW

**Comment by mcd1992** [comment]
Ruhroh, looks like we both had the same idea. https://github.com/radare/radare2/issues/10324

I've got the basic system implemented as well. Ours seems pretty different though.
https://github.com/mcd1992/radare2/blob/zflogging/libr/core/logging.c

Not sure if pancake wants to replace all usage of eprintf with something like this though. It's more aimed at debugging/being more verbose when needed.

**Comment by radare** [comment]
Random comments: 
* there are a bunch of conflicts
* the r_log api already existed in libr/util/log

**Comment by thestr4ng3r** [comment]
Yeah the conflicts were to be expected considering the amount of changes.
The old r_log api was only halfway implemented and kind of useless.
Please don't try to merge the pr right now, I'd like to get it combined with the implementation that @mcd1992 started.

**Comment by radare** [comment]
i dont see the point on changing ove r9000 eprintf for another macro that does the same. i would personally prefer to use an api similar to glib, which requires 3 arguments. and in fact. before doing such big PR is probably better to discuss things to not loose time doing changes that get conflicts all the time

* context of the log message (module, plugin, file, etc)
* level of the issue (warning, debug, error, fatal ,...)
* format string with message

There are different problems in such api.

* this may work on threads. this is, knowing which thread spits an error is important, and common data structures cant be shared without mutexing and such
* this adds a lot of complexity for just spitting out an error
* the already existing r_log api allows to redirect the output to a different file descriptor, socket or file
* doing such change requires even more engineering
* release builds probably need some debug and assert-level log messages to go away from the binary
* tasks need to capture the associated error messages, like its done for r_cons output
* each error should probably come with a timestamp to make benchmarks with logs possible, and give proper timeline information

And this is just what i though in 5min after checking this pr. there are probably more things to consider. so i'm not really in the mood to accept this change yet because it feels wrong and overengineered. and we should probably answer many questions before deciding the right way to go without having another monster API inside r2.

also if we do so i would probably go for changing few strategic eprintfs for testing and understanding the real needs for capturing and managing those messsages

**Pull request closed without merging**
