### PR TITLE
Replace dh for dL

### PR DESCRIPTION
**Pull request by Tzaoh**
Issue #7615

### CODE REVIEW

**Comment by radare** [comment]
There are more places where dh is used

**Comment by radare** [comment]
```
$ git grep  '"dh '
libr/core/cio.c:        r_core_cmdf (r, "dh %s", debugbackend);
libr/core/cmd_anal.c:                                   r_core_cmd0 (core, "dh esil");
libr/core/cmd_anal.c:                                   r_core_cmdf (core, "dh %s;dpa", dh_orig);
```

**Comment by radare** [comment]
also check in radare2-extras

**Comment by Tzaoh** [comment]
Changed the references to "dh" cmd inside source code.
Could not find anyu reference to "dh" in r2-extras apart from the 8-bit 'dh' subregister

**Comment by radare** [comment]
Right, in unicorn i was using dbg.backend instead of cmd("dh").

thanks!

**Pull request merged**
