### PR TITLE
fixed more covs

### PR DESCRIPTION
**Pull request by Vane11ope**

### CODE REVIEW

**Comment by radare** [comment]
The whole armass code looks wrong to me. Full of null derefs missing checks manual string processing when we have functions that do the same in util.. etc. I would prefer to have this fixed properly before merging

**Comment by Vane11ope** [comment]
wait so should i exclude that from this PR?

**Comment by radare** [comment]
Nope just fix it

**Comment by Vane11ope** [comment]
like whole codebase?

**Comment by Vane11ope** [comment]
because the other place in the file always be written like the way i fixed. and you dont like it then which means i fix ALL the codes in there just to fix a cov?

**Comment by Vane11ope** [comment]
okay you know what i changed me mind so i am on fixing all!

**Comment by Vane11ope** [comment]
done.

**Comment by radare** [comment]
Red

**Comment by Vane11ope** [comment]
not even sure why mine's still red

**Comment by radare** [comment]
Rebase?

**Comment by Vane11ope** [comment]
i rebased and still not being fixed. given up

**Comment by Vane11ope** [comment]
screenshot from 2018-07-07 23-58-27
all the time.

**Comment by Vane11ope** [comment]
huh wait, actually started thinking i need to fix some of my codes

**Comment by Vane11ope** [comment]
ok fuck this. if i replace all those functions with r_* then it fails the test so i exclude the file.

**Pull request merged**
