### PR TITLE
bin_sfc.c: fix NULL dereference when R_NEW0 fails

### PR DESCRIPTION
**Pull request by mikaoP**

### CODE REVIEW

**Comment by Maijin** [comment]
This does not build

**Comment by Maijin** [comment]
https://travis-ci.org/radare/radare2/jobs/234382197#L418

**Comment by radare** [comment]
the whole code in here seems a bit wtf to me, imho a rewrite would make more sense than just fixing this null deref this way. what do you think?

**Comment by mikaoP** [comment]
yeah, could be interesting do a refactor. if i have time i will do it

**Pull request merged**
