### PR TITLE
separate debruijn to it's own header file

### PR DESCRIPTION
**Pull request by crowell**
example for #5314

perhaps the includes for the utils should be in `#include <util/r_xxx.h>` instead?

### CODE REVIEW

**Comment by ret2libc** [comment]
Yeah I guess `#include <util/r_xxxx.h>` would be nicer :)

**Comment by radare** [comment]
I would prefer to use r_util_debrujn to make it clear where it belongs to

**Comment by radare** [comment]
Or r_util/...

**Comment by crowell** [comment]
dir is now `r_util`

**Pull request merged**
