### PR TITLE
Revert "Fixpanelsbug"

### PR DESCRIPTION
**Pull request by Vane11ope**
Reverts radare/radare2#13993

### CODE REVIEW

**Comment by Vane11ope** [comment]
seriously. WTF

**Comment by radare** [comment]
Syeah it was clearly wrong. We should ask for a reproducer

**Comment by KoWu** [comment]
Just append a newline at the .r2panels and it will segfault. This happens if you edit it with vim for example. I don't get the problem.

**Comment by Vane11ope** [comment]
okay thanks yeah fair point i will do something about it sooner or later :)

**Pull request merged**
