### PR TITLE
travis archos

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by ret2libc** [comment]
r2r PR: https://github.com/radare/radare2-regressions/pull/1460

**Comment by ret2libc** [comment]
fixes https://github.com/radare/radare2/issues/11015

**Comment by ret2libc** [comment]
This currently doesn't work on OS X because it requires signing. I will work on that in a separate PR after this.

**Comment by Maijin** [comment]
Can probably use the script provided in sys/ for the signing

**Comment by radare** [comment]
Binaries without aslr are not an option in many cases. What about supporting base address representation properly so aslr is no longer an issue

**Comment by ret2libc** [comment]
> What about supporting base address representation properly so aslr is no longer an issue

@radare what do you mean? I don't get it.

**Pull request merged**
