### PR TITLE
Adding "8" modifier in doc

### PR DESCRIPTION
**Pull request by Owlz**
Adding in reference to the "8" modifier for pv.

### CODE REVIEW

**Comment by Maijin** [comment]
You could also add, what is pv8 for 👍

**Comment by radare** [comment]
In theory (cant chk the src now) pv is suposed to honor asm.bits and there must be pv[1,2,4,8]

**Comment by alvarofe** [comment]
```
[0x100001174]> pv1
0x55
[0x100001174]> pv2
0x4855
[0x100001174]> pv4
0xe5894855
[0x100001174]> pv8
0x56415741e5894855
```

Print value of <amount of bytes> ?

**Comment by alvarofe** [comment]
Merged. Remain the test and `pvj` i think is not working as expected at least doesn't behave the same way as `pv`

**Comment by radare** [comment]
Is this thing honoring cfg.bigendian and there are tests for it?

**Pull request closed without merging**
