### PR TITLE
strange delphi artifact in PE header causes this bug

### PR DESCRIPTION
**Pull request by dmtch**

### CODE REVIEW

**Comment by jvoisin** [comment]
What bug?

**Comment by dmtch** [comment]
PE with flag 0x8000 is interpreted as big-endian encoded binary, it's wrong

**Comment by Maijin** [comment]
@dmtch If you're looking at PE file, you should take a look at all the binaries in radare2-regressions, a lot to fix there :)

**Comment by dmtch** [comment]
Test "cmd_zF: aa ; zF libc.sig" is broken. libc.sig is invalid, because crc and tail bytes must be checked from offset 32, not from current byte.

**Comment by radare** [comment]
Please add tests for your bug fixes in the regressions repo https://github.com/radare/radare2-regressions/pulls

**Comment by radare** [comment]
@dmtch ping

**Comment by dmtch** [comment]
I'm here.
https://github.com/radare/radare2-regressions/pull/280

**Comment by radare** [comment]
thanks!

**Pull request closed without merging**
