### PR TITLE
fix #2783

### LINKED ISSUE #2783: rahash2 escape chars in `-s`
`rahash2 -s` should accept strings like this: `\x90\x18AAA`.

Just call `r_str_unescape()` before passing the final string to the hash loop.

### PR DESCRIPTION
**Pull request by jjdredd**
shall we try once again? :P

### CODE REVIEW

**Comment by radare** [comment]
the commit message is meaningless. whats this fix about? :)

**Comment by radare** [comment]
the comment contains a typo

**Comment by radare** [comment]
function calls require a space between function name and parenthesis

**Comment by jjdredd** [comment]
sorry, didn't know it was a strict requirement.

**Comment by radare** [comment]
thx

**Pull request closed without merging**
