### PR TITLE
do not print warning for dynamic section if we are a static bin

### PR DESCRIPTION
**Pull request by grandemk**
Do not print this:
Warning: Cannot initialize dynamic section
when the binary is a static elf.

### CODE REVIEW

**Comment by ret2libc** [comment]
Why don't you just call Elf_(r_bin_elf_get_static) instead of creating a new function?

**Comment by grandemk** [comment]
isn't Elf_(r_bin_elf_get_static) the external api?

**Comment by radare** [comment]
No need to create a new function to call it, please fix that to get it merged

**Comment by ret2libc** [comment]
Yes It is, but it's also a normal function that you can call.

**Comment by ret2libc** [comment]
Also, if you want, could you please adapt that function to the style in CONTRIBUTING.md ? It only needs some braces around if and for :)

**Comment by Maijin** [comment]
Doesn't build

**Comment by grandemk** [comment]
(I know I can call it ^^) It's just that changing the API shouldn't break the internal code. I can change it, but I don't see why this is better ?

**Comment by ret2libc** [comment]
I think it's the opposite. Internal code changes shouldn't break the API. And the API *should* be much more stable (actually we change a lot also the API, but that's another thing) than the internal static functions. The semantic of ```int Elf_(r_bin_elf_get_static)(struct Elf_(r_bin_elf_obj_t) *bin)``` is and should always be (regardless of the 1000 changes that may happen in the static/private code) "Return true if this bin is static, false otherwise" so if you need to check whether a binary is static or not, which better function more than this one imo?

Anyway, it's just a minor thing ;) I said that just because at the moment i don't see the point of creating a new static function, since ```Elf_(r_bin_elf_get_static)``` and ```elf_get_static``` have exactly the same signature and exactly the same semantics.

**Comment by grandemk** [comment]
I think we are on the same page, if something break the API, then nothing works, it just that tying the API to its internal use in the module make it more difficult to change. Perhaps we want to return "static" instead of a boolean or whatever. But I agree that this is not important and this fcn shouldn't change as it is very simple. (But never say never...)

**Comment by radare** [comment]
Thanks!

**Pull request closed without merging**
