### PR TITLE
Decompiler default off for everything especially tabs working better …

### PR DESCRIPTION
**Pull request by Vane11ope**
…this way ##panels

### CODE REVIEW

**Comment by radare** [comment]
wat. the decompiler output is very useful. even more if you dont use pdc.

e cmd.pdc=pdd when r2dec is installed

**Comment by Vane11ope** [comment]
i know. i did not say it's not useful, i say it's wrong to open it as a default panel by asking users if they want open it or not, like severely annoying to get asked about that everytime especially when you open multiple tabs and move around them, even though it's only first time when you move to brand new tab.

the reason why im not opening pdc by default is it's sometimes severely slow. Users can choose to open them by * command or in menu. Im strongly sticking to not open it by default.

**Comment by radare** [comment]
Ok but its still there the option to have it ?

**Comment by Vane11ope** [comment]
i mean you can open decompiler easily with '*' command or in menu, I just disabled it to be open by default because it just slows down the users.

**Comment by radare** [comment]
Lgtm!

**Pull request merged**
