### PR TITLE
Revert to old coloring for asm.filter'd flags

### PR DESCRIPTION
**Pull request by kazarmy**
The old coloring for asm.filter'd flags makes them stand out:
old_filter_color
compared to the current coloring:
cur_filter_color

@SrimantaBarua This PR reverts a change in commit 2ce093b23dffd514a39f863979e7f3f0611a6405.

### CODE REVIEW

**Comment by kazarmy** [comment]
Fixed the XX tests in radare/radare2-regressions#784.

**Comment by kazarmy** [comment]
This PR fixes #7186 by accident.

**Comment by kazarmy** [comment]
Fixed #7186 by accident.

**Comment by SrimantaBarua** [comment]
@kazarmy Yeah, I'd done that because the color escape sequences was messing with `r_parse_filter`. It's a good thing you fixed that.

**Comment by kazarmy** [comment]
@SrimantaBarua Are there tests for what you were doing?

**Comment by SrimantaBarua** [comment]
You already changed the ones for color, I see. [This](https://github.com/radare/radare2-regressions/pull/770) is the relevant PR in r2r.

**Comment by kazarmy** [comment]
Yes, but the color-based tests I changed were old tests. Their color escape sequences can be processed by `r_parse_filter` without problems.

**Comment by kazarmy** [comment]
Oh I see. You want to transform:
```
lea eax, [ebx - 0x1b20]
```
into
```
lea eax, str.Hello_PIC_
```
but the color escape sequences are messing things up. Oh great, now I have to figure out how `filter` works.

**Comment by SrimantaBarua** [comment]
Probably :P
Or you might profit from looking at `colorize_asm_string` instead. And if there's a possible fix there, you could have the coloring happen after `r_parse_filter`. Just a suggestion

**Comment by kazarmy** [comment]
Ok done. Did think about `colorize_asm_string` but didn't want to modify the previous code too much (with possibly unintended consequences). There's also a test for it at commit radare/radare2-regressions@d49ce5538bc210981192a080777e2d0ff85d7c05.

**Comment by radare** [comment]
please resolve conflicts and squash

**Comment by radare** [comment]
solved the conflict, but must try before merge

**Pull request merged**
