### PR TITLE
libr/asm: Use memcmp instead of strcmp in r_asm_add

### PR DESCRIPTION
**Pull request by lzutao**

### CODE REVIEW

**Comment by lzutao** [comment]
Build failed ! Checking it !

**Comment by radare** [comment]
Thats wrong. What are you trying to do here?

**Comment by lzutao** [comment]
Sorry, I tried to reuse the `r_asm_is_valid` function in ` r_asm_add`, and use `memcmp` instead of `strcmp` but I forgot to +1 in result of `strlen`.

**Comment by radare** [comment]
there’s no point in using memcmp to compare strings, strcmp should be used

**Comment by lzutao** [comment]
There is a TODO in `asm.c` say that "use memcmp instead of strcmp". 

Btw, what about using `strncmp` instead?

**Comment by Maijin** [comment]
image

**Comment by Maijin** [comment]
Quite old commit though

**Comment by Maijin** [comment]
@lzutao if you're looking for contributions use the issue tracker ;)

**Pull request closed without merging**
