### PR TITLE
corrected rahash2 result for sha384 sha512

### PR DESCRIPTION
**Pull request by stanciuadrian**
corrected index of message length in SHA512/SHA384 preparation
#3274

### CODE REVIEW

**Comment by radare** [comment]
Can you add tests to confirm/verify this?

**Comment by stanciuadrian** [comment]
Currently the rahash2 test suite has 2 tests which now pass with [FX]. Will try to add more. If anybody can test this on a big-endian machine I would be grateful.

**Comment by radare** [comment]
Drop the BROKEN bit from those tests in a pr. Thx!

**Comment by radare** [comment]
Merged!

**Comment by radare** [comment]
i did the change in r2r

**Pull request closed without merging**
