### PR TITLE
Fix #14529 - 1 instruction on pi. pd. and pD.

### LINKED ISSUE #14529: Add pi. and pd., pD. ... as an aalias to show 1 instruction in current offset
so must be an alias for pd1

### PR DESCRIPTION
**Pull request by dvertx**

### CODE REVIEW

**Comment by radare** [comment]
33xx

**Comment by dvertx** [comment]
I could use a pointer why Travis CI error and did not pass the build. I don't understand the error messages spit out by Travis

**Comment by Maijin** [comment]
search for [XX] in the listing, those are the tests that are not passing due to the change you made e.g.

image


You can find the tests in radare2-regressions repository.

**Comment by dvertx** [comment]
If I'd like another go at trying to fix #14529, then I should close this PR and create a new PR right?

**Comment by radare** [comment]
No. Just git push

**Comment by dvertx** [comment]
Alas, my twitchy finger already killed the original fork. Noob :(

**Pull request closed without merging**
