### PR TITLE
Use HtUP to store canvas attributes instead of a sorted array

### LINKED ISSUE #14553: agf is slow
And that's because of the edges

Screenshot 2019-07-12 at 12 02 53

### PR DESCRIPTION
**Pull request by ret2libc**
This should improve performace as you don't need to shift elements of
the sorted array when you need to insert a new one.

Fixes #14553

Please do test the PR before merging. I've already tested on linux on my /bin/ls, but another run would not hurt :)

### CODE REVIEW

**Comment by radare** [comment]
Ill test tonight. But do you have some benchmarks? Like how much times faster or which % of time is spent in this function before the change?

**Comment by ret2libc** [comment]
Tested with:
```
$ time ./binr/radare2/radare2 -qc "s main;af;agf;q" ../../radare2-regressions/bins/elf/analysis/ls-linux64 2>/dev/null 1>&
```

On master:
```
./binr/radare2/radare2 -qc "s main;af;agf;q"  2> /dev/null >&2  6.48s user 0.04s system 99% cpu 6.532 total
```
With this PR:
```
./binr/radare2/radare2 -qc "s main;af;agf;q"  2> /dev/null >&2  0.89s user 0.03s system 99% cpu 0.919 total
```

**Comment by radare** [comment]
Beautiful. Ill try in few mins. Thanks!

**Comment by radare** [comment]
it also improves the performance in panels

**Pull request merged**
