### PR TITLE
Adding node testsuite to appveyor

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by XVilka** [comment]
What with this one?

**Comment by xarkes** [comment]
I'm working on it. I have to fix the mingw build and solve some node issues on Windows.

**Comment by xarkes** [comment]
I still cannot figure out why mingw is segfaulting.

**Comment by radare** [comment]
last time that happened it was because the mingw and w32 apis differ, so i had to do 1bfb5ffba2e6a6336fa32d80ad457e495cd3d71e

it is still happening?

**Comment by xarkes** [comment]
I can't find the issue. Someone familiar with MinGW should check it. Otherwise I can also remove the MinGW build from appveyor...

**Comment by XVilka** [comment]
We really need to make this one for running tests also on Windows.

**Comment by XVilka** [comment]
I think in the worst case, if Mingw32 cannot be fixed - I suggest to disable this build completely. Better to focus on purely native, MSVC-built version then.

**Comment by radare** [comment]
I will fix mingw because its the only way to build on mac/linux easily. And i would use that for wine. The problems inhave observed are more about runtime issues than compilation ones. Seems like some functions signatures are different. So having wrong abis between native windows and mingw dtuff for widechar strings and such. Whwres the crash exactly now?

**Comment by XVilka** [comment]
I suggest the fix can be made later, but mingw32 disabled right now, so we'll see what tests are broken on Windows and would be able to fix before the release.

**Comment by XVilka** [comment]
Moreover, in the long run it makes sense to kill the Mingw32, it was last updated in 2013 and focus on Mingw-w64, which is more updated and even more "native".

**Comment by xarkes** [comment]
So I disabled Mingw32 as suggested

**Pull request merged**
